### ISSUE TITLE
Word quantity in not annotated data

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#10]
Element `//extent/measure[@unit="word"]` does not make sense in raw text data. I am able to count the words `//w` in annotated(tokenized) data.

https://github.com/clarin-eric/ParlaMint/blob/main/ParlaMint-SI/ParlaMint-SI.xml#L28-L29

**Comment by TomazErjavec** [comment]
> Element //extent/measure[@unit="word"] does not make sense in raw text data.

Why not? It has just as many words as the annotated version. But, yes, they are more difficult to count. What we did in the first version of the corpora, is - when we were developing them - have a approximate number there, and, once we produced the lingistically annotated version, we copied the number of //w back into the unannotated one.
Do you see a problem with that?
(there is one: words in note, vocal etc. are not counted, but one could argue that those are not words on the same level as the ones that were spoken)

**Comment by matyaskopp** [comment]
OK, I did not correctly understand the purpose of the `extent` element. It describes text quantity features that are independent of used annotating tools. So the quantity of words is the guessing (We know a more precise number of `w` that we can use).
