### ISSUE TITLE
TR huge difference between number of utterances and number of speeches

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#104]
According to tables
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/Metadata/ParlaMint-overview.tsv#L18
and 
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/Metadata/ParlaMint-data.tsv#L18

The average word length of speech is 100 words, but TR corpus average speech length is 27 (half of the second smallest average speech length). This seems to be a bit strange.

The reason is that number of speeches is taken from the number of `<u>` elements (it is "almost" equal to the number in `ParlaMint-data.tsv`) which is not equal to the number of speeches for the TR corpus:
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/ParlaMint.ana.xml#L984
vs
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/ParlaMint.ana.xml#L423

I believe that number of speeches and utterances should not be necessarily equal due to interruptions, but the number of utterances is 5times bigger than the number of speeches.

@TomazErjavec, @coltekin 
Is not it a bug?
What is the correct number for statistics tables?

**Comment by coltekin** [comment]
This was a bug. Almost all segments (paragraphs in transcripts) were marked as individual speeches. I fixed this in my scripts. The new counts are as follows.

```
<tagUsage gi="u" occurs="692161"/>
<measure unit="speeches" quantity="289026" xml:lang="en">289,026 speeches</measure>
```
The way I count speeches is based on a heuristic, where short interrupts within a stream of utterances by the same speaker are ignored. And, it seems almost no one finishes their speech on time, so most speeches have at least a warning from the chair that they need to wrap up (interruptions from the audience are also common). The difference in the current numbers seem reasonable to me.

If we have a standard approach to count speeches, I'd be happy to follow it.

**Comment by TomazErjavec** [comment]
The standard approach is simply to count the number of `<u>` elements. This is in fact done automatically here:
https://github.com/clarin-eric/ParlaMint/blob/643f902481a47e942b713febe9613c9f5472ea82/Scripts/parlamint-add-common-content.xsl#L349-L356

I kind-of agree that your way might be better, but it would need to be applied to all corpora, and maybe a heuristic is not the best solution. Maybe a change of speaker? But let's leave this for another day, and probably under another dedicated issue. Closing this one now.
