### ISSUE TITLE
TR: bug in application description

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#106]
@coltekin, `czech-pdt-ud-2.6-200830` is not used in Tr corpus `//application/desc` (at the end of line)

https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/ParlaMint.ana.xml#L7087-L7090

**Comment by matyaskopp** [comment]
`UDPipe 1` and `turkish-imst-ud-2.5-191206` model is used

**Comment by TomazErjavec** [comment]
@coltekin, as you are working on your corpus, is this fixed? If yes, pls. close.

**Comment by coltekin** [comment]
Yes. I have just verified it. The current description of the tools is correct. I think this issue can be closed.
