### ISSUE TITLE
HU: Application description should contain only features that has been use

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#107]
I think that application description should contain only features that have been used - it is not a promotion of application capability - it  is more like documentation for what it has been used:

According to the paper, udpipe was used only for syntax:
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/ParlaMint-HU/ParlaMint-HU.ana.xml#L632-L635

**Comment by TomazErjavec** [comment]
HU appInfo has been changed to Spacy: https://github.com/clarin-eric/ParlaMint/blob/5fd0a6055579ded5b2b0b77f0988246fea2c6e0e/Data/ParlaMint-HU/ParlaMint-HU.ana.xml#L127

It still reads like an advert, but I guess all the mentioned levels of annotation have been used, so closing this.
