### ISSUE TITLE
HU: Wrong URL in bibl

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#108]
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/ParlaMint-HU/ParlaMint-HU_2014-06-19.xml#L58

**Comment by lnnoemi** [comment]
I am not sure whether I have to correct this. We agreed to build a whole new corpus which is an extension of this earlier Parlamint-HU corpus and starts from the beginning (May 2014). As we fully replace the content of the Parlamint-Hu corpus, is it still necessary to fix these bugs? If so, I will do that soon.

**Comment by matyaskopp** [comment]
well, there are two hidden issues:
- it is not a valid URL - `https://` at the beginning should be removed (I can fix this in v2 to v3 conversion)
- the URL should refer to the exact source, which is, in this case, https://www.parlament.hu/documents/10181/56618/ny150428.pdf I guess

If you are fully replacing the content, I prefer you to fix this - I think it is not a big issue, and your data will be more excellent if it contains precise URLs to the source.
