### ISSUE TITLE
CZ: wrong/missing @xml:lang

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#109]
The default language is set in root node `/*/@xml:lang = 'cs'`. There are a lot of elements that English text includes but `@xml:lang` is not specified:

- [ ] `/teiCorpus//prefixDef`
- [ ] `/teiCorpus//application`
- [ ] `//profileDesc//name[@type="country"]`  (or use Czech text?)

**Comment by TomazErjavec** [comment]
@matyaskopp, has this been fixed? If so, pls. close.

**Comment by matyaskopp** [comment]
No, it was not, leaving it opened.

**Comment by TomazErjavec** [comment]
OK, but then maybe also set the milestone, probably 3.1.

**Comment by matyaskopp** [comment]
fixed
