### ISSUE TITLE
Add new ParlaMint II parliaments folders

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#117]
@osenova, do we have the complete list of new participants?

**Comment by osenova** [comment]
Yes, we have a table here: https://docs.google.com/spreadsheets/d/1zHKN6a1GYF76veMflM9fWbVJVFtEGunZ70XrUNpihiE/edit?usp=sharing

Please ignore the lines in RED. The first part features the participants that continue in-kind from ParlaMint 1, and the second part - newcomers who reacted and confirmed.
