### ISSUE TITLE
Schema extension suggestion:  page breaks //pb

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#13]
Our (CZ) data are scrapped from a sequence of web pages. We want to store this pagination to be able to refer to an exact source of  data:
```
            <pb source="https://www.psp.cz/eknih/2013ps/stenprot/059schuz/s059231.htm"
                n="1"
                xml:id="ParlaMint-CZ_2017-07-13_ps2013-059-07-019-049.pb1"/>
```
Can you allow element `pb` in elements `div` and `u` (there can be page break within an utterance, see: https://www.psp.cz/eknih/2013ps/stenprot/059schuz/s059232.htm)

**Comment by TomazErjavec** [comment]
I can do it if you insist. But, IS already had a similar request, where we decided to extend the schema to allow `u/@corresp` and put the URL in this attribute. The situation with IS is a bit different, as they have each speech (u element) on a separate URL, still, I think it could be used for your case if:
- all the u elements that are from the same page are given the same URL (after all, you are interested from where an speech comes from, and this info is then readily available, if a bit redundantly specified)
- you give the URL where the speech starts, so if it's tail is on another URL, that is not specified (this is cheating a bit, but I imagine the main use for this info is that somebody clicks on the speech link to see the original, and there they can easily click Next page, if the speech ends there). Alternatively, and without cheating, both URLs can be given as the value of `u/@corresp`.

As for your suggestion, I prefer not to have various ways of encoding what is basically the same information and don't like to introduce more elements than needed. But, again, it is true that the situations are a bit different, so, if you insist I can do it. Let me know.

**Comment by matyaskopp** [comment]
I am storing urls to the beginning of speech only if a direct URL exists (URL with anchor):
```
            <note type="speaker" target="#VojtechFilip303">Místopředseda PSP Vojtěch Filip</note>
            <u who="#VojtechFilip303"
               ana="#chair"
               xml:id="ParlaMint-CZ_2017-07-13_ps2013-059-07-002-057.u6"
               source="https://www.psp.cz/eknih/2013ps/stenprot/059schuz/s059222.htm#r1">
```
I have used attribute **`source`**, I think that it is more fitting than `@corresp`

Page breaks are important for me for two reasons:

1. Our audio data corresponds to pages
2. We want to publish data in TEITOK and it is important to create some splitting of XML that is sent to the browser because the browser can be very slow in parsing large XML. Pages used in source data is the best option, see https://lindat.mff.cuni.cz/services/teitok/parczech-ps7-2.0/index.php?action=text&cid=ps2013-011/ps2013-011-01-001-001.tt.xml&pageid=ps2013-011-01-001-001.pb1&pbtype=pb

So for our purpose, I will use `pb` in files. I want to make all our future data compatible with ParlaMint. So I insist if you don't mind too much.

**Comment by TomazErjavec** [comment]
Not too much :)
I will also change `u/@corresp` to `u/@source` to store the source URL, you are quite right, it makes more sense.
Pls. check your pb data with the schema from the next commit, as I didn't actually test it. If it is ok you can close the issue.

**Comment by matyaskopp** [comment]
it is ok, closing
