### ISSUE TITLE
add Parla-CLARIN validation to workflow

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#132]
https://github.com/clarin-eric/parla-clarin/tree/master/Schema

**Comment by matyaskopp** [comment]
@TomazErjavec, I am not 100% sure that I understand you correctly. We have discussed both ParlaMint and ParlaCLARIN, so I am unsure if the issue is in the correct repository.  
Do we want to validate the ParlaMint corpus in the workflow against both schemas ParlaMint and ParlaCLARIN?

**Comment by TomazErjavec** [comment]
> Do we want to validate the ParlaMint corpus in the workflow against both schemas ParlaMint and ParlaCLARIN?

Yes, exactly - the ParlaMint schema is made from scratch, so there is no (at least theoretical) guarantee that a document validated against the ParlaMint schema will also validate against the TEI Parla-CLARIN (note spelling:) schema but it should, as we are saying we are TEI compliant.

So, to be 100% certain, every ParlaMint document should be validated by both.
And sorry for not being clear!
