### ISSUE TITLE
github pages deployement

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#134]
I have discovered that it is possible to use any branch for GitHub pages. 
So we can use [documentation](https://github.com/clarin-eric/ParlaMint/tree/documentation) branch.

The documentation branch is not protected, so I can write a workflow that will publish (render HTML) and commit it to this branch. We can use it for publishing the development version of documentation (`docs/devel.html`) and publish it when it is ready by replacing `index.html` with `devel.html`.

**Comment by TomazErjavec** [comment]
Thanks for this info & setting up the branch & the nice idea how to implement the development of documentation.
I am currently updating the [Parla-CLARIN documentation](https://clarin-eric.github.io/parla-clarin/), as soon as I finish that, I will first ask you (and Katja) to read it, and, once we have that finished, then I will move to the ParlaMint one.

**Comment by TomazErjavec** [comment]
I've been working on the github pages recently, and the workflow I have is:
- all the things related to the documentation (except docs/) are in the TEI/ folder
- I work on the documentation branch, and simply look at the docs/index.html on my local web server (there is the mount target in the TEI/Makefile, which rsynch it to the web server, which is , of course, a local thing, not useful for others)
- once done with a set of changes, and when everything validates, I just merge documentation into main

I'm not sure we need anything more complicated than this, but if there is a further reason to do it the somewhat more complicated way you suggest, then I can do it differently of course.

**Comment by matyaskopp** [comment]
I think it is good to split manual and generated changes into two commits. 
So probably the best solution is to add to make file `deploy` target, that will do something like:
```
deploy:	prepare val-schema xml-schemas val-samples html
	git commit -m "deploy" ./docs
	git push
```

But there is no need to create a workflow for it.

**Comment by TomazErjavec** [comment]
OK, good idea; added deploy in #19656dd.

**Comment by matyaskopp** [comment]
OK, so I am closing this issue
