### ISSUE TITLE
Schema extension suggestion: allow child nodes in //note 

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#14]
Currently, only text nodes are allowed in `<note>`

## audio
We are storing audio links in notes in this way :
```
               <note type="media">
                  <media mimeType="audio/mp3"
                         source="https://www.psp.cz/eknih/2013ps/audio/2017/07/13/2017071312581312.mp3"
                         url="2013ps/audio/2017/07/13/2017071312581312.mp3"/>
               </note>
```
It is related to page breaks because one audio file corresponds to one page (https://github.com/clarin-eric/ParlaMint/issues/13)

## time
We are parsing different formats of time, ie:
```
            <note type="time">
               <time from="2017-07-13T14:30:00">(Jednání pokračovalo ve 14.30 hodin.)</time>
            </note>
```

```
           <note type="time">
              <time to="2017-03-02T16:38:00">(Jednání skončilo v 16.38 hodin.)</time>
          </note>
```

**Comment by TomazErjavec** [comment]
> time

Yes, this makes sense, will add in next commit.

> audio

This one I will do diffierently, for two reasons: we already have in Parla-CLARIN the guidelines on how to encode audio (cf. https://clarin-eric.github.io/parla-clarin/#sec-speechvideo) and although that was so far meant for 1 recording (one media file) with fine-grained time alignment, it can easily be used also for your case and b) note is strictly meant for notes by the transcriber, not as a handy container for some extra information not present in the transcription. So, not only would we be ignoring existing guidelines, but abusing the elements we have.

So, pls. do it by adding a recordingStmt at the end of the sourceDesc in the component files, which looks like

```
<recordingStmt>
  <recording type="audio" dur="PT43M45S">
        <media xml:id="audio1" mimeType="audio/mp3"
           source="https://www.psp.cz/eknih/2013ps/audio/2017/07/13/...mp3"
           url="2013ps/audio/2017/07/13/...mp3"/>
        <media xml:id="audio2" mimeType="audio/mp3"
           source="https://www.psp.cz/eknih/2013ps/audio/2017/07/13/....mp3"
           url="2013ps/audio/2017/07/13/....mp3"/>
  </recording>
</recordingStmt>
````
and then you can just point to the appropriate media file from pb:

```
<pb corresp="#media1" source="http://..."/>
```

OK, you need to follow the pointer, but that needs to be done in various other contexts as well...
