### ISSUE TITLE
Schema extension suggestion: new org role values //org/@role

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#15]
## (CZ) list of new (or camelCased existing ones - with star) org roles with number of occurrences in corpus:
```
    299 interparliamentaryFriendshipGroup
    280 subcommittee
    114 committee
     77 commission
     44 politicalGroup
     31 delegation
     13 senate
*    11 politicalParty
      9 institution
      7 supervisoryBoard
      5 workingGroup
      3 czechNationalCouncil
      3 chamberOfThePeople
      3 chamberOfTheNations
      2 europeanParliament
      1 president
      1 internationalOrganizations
      1 boardOfDirectors
```

_Originally posted by @matyaskopp in https://github.com/clarin-eric/ParlaMint/issues/9#issuecomment-765179511_

**Comment by TomazErjavec** [comment]
As mentioned in #9, I added these values currently used by CZ in c99c006, also with some comments (ParlaMint/Schema/ParlaMint-teiCorpus.rng i.e.  https://github.com/clarin-eric/ParlaMint/blob/main/Schema/ParlaMint-teiCorpus.rng).

The only comment here is on "czechNationalCouncil", can this be "nationalCouncil"? Namely, nowhere else is the name of the country mentioned, so I don't see a reason it would be here. If you agree, pls. comment here, so I can change the value in the schema.

**Comment by matyaskopp** [comment]
Good point, lets rename it: `czechNationalCouncil` -> `nationalCouncil`

**Comment by TomazErjavec** [comment]
OK, this is sorted, closing.
