### ISSUE TITLE
Definition of a political group

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#155]
https://github.com/clarin-eric/ParlaMint/blob/f2f26176b551cb3a9b987ae1a9498f348379ef7c/TEI/ParlaMint.odd.xml#L1182-L1183

`politicalGroup` is more like a grouping of members of parliament that correspond to one political party. It is a representation of `politicalParty` in parliament. Not every member of `politicalGroup` should be a member of the corresponding `politicalParty`.

**Comment by TomazErjavec** [comment]
Yes, my formulation was rather sloppy because I don't quite understand this myself. But I have problems in turning your suggestion into a proper definition too, as I am now more confused than I thought I was...

Could you try to come up with a more or less proper definition? (Of course I can help, as long as I understand what you are trying to say). Or should we ask someone?

This is tricky one, always has been.

**Comment by matyaskopp** [comment]
as @attom wrote:
https://github.com/clarin-eric/ParlaMint/issues/38#issuecomment-808773593
the `politicalGroup` is formed in the parliament. I was influenced by the English translation on the Czech chamber of deputies web pages. 
Can we change it to the Italian suggestion `parliamentaryGroup`? Name changing can probably dispel doubts.
It sounds more general to me but it can be probably easier to understand the meaning.

Political Group characteristics:

- every MP should belong to zero or one `politicalGroup` at a given time (in CZ case I guess it is not possible to desert to another group officially, so MP can only be independent)
- `politicalGroup` is defined for a term
- `politicalGroup` represent `politicalParty` in parliament, members of `politicalGroup` are persons that have been nominated in election by `politicalParty`
- in case of coalitions that arise before the election, every political party in such coalition can have its own `politicalGroup` (it can happen, that they will work apart after the election) 

> Or should we ask someone?

It is probably a good idea to ask someone with better political knowledge background and better expression ability.

**Comment by TomazErjavec** [comment]
We have now discussed this, the conclusions are:

- the new name of a politicalGroup is a *parliamentaryGroup*
- this change must be implemented for all the corpora that currently use politicalGroup
- we would also change politicalParty to parliamentaryGroup for those that currently use politicalParty with the assumption that what is in fact meant by politicalParty is the parlimentary group that a party represents in the parliament. This change would affect BE, BG, DK, ES, GB, GR, HR, HU, IS, NL, PL, SI, TR. The authors of the corpora should probably be asked if this is ok.
- CZ is an exception, as it uses both politicalParty and (currently) politicalGroup.

**Comment by hpreki** [comment]
I am also very happy to associate MPs to _parliamentaryGroup_ instead to the politicalParty for AT. I think this the _only_ sound way to have meaningful values for the crucial information on membership-period!  (we _exactly_ know when a MP entered or left a "Klub" - as we call it - but there is no way to know when they joined a party -- typically decades before they became MP) 

But still I guess we still would collect information about the politicalParties to which the _parliamentaryGroups_ are tightly connected?  And    I  was not able to spot where the  
 association between Parties and their _parliamentaryGroup_  is encoded?

**Comment by vaidasmo** [comment]
The relations would also be relevant for Lithuanian data.

**Comment by TomazErjavec** [comment]
OK, lets add another value for `relation/@name`. @matyaskopp suggests:

`<relation name="represent" 
          active="#politicalGroup.CSSD.1107" 
          passive="#politicalParty.CSSD.153" 
          from="2013-10-29" 
          to="2017-10-26"/>`

I am more inclined towards a simple `member` value. What do you all think?

This will need to be added to the guidelines, as, indeed the whole issue of parliamentaryGroup vs. politicalParty. I have now at least somewhat improved the explanation of [relations](https://clarin-eric.github.io/ParlaMint/#sec-relation).

**Comment by matyaskopp** [comment]
> I am more inclined towards a simple member value. What do you all think?

I don't understand this. Are you suggesting to use `//relation/@name="member"` instead of `//relation/@name="represent"`?

**Comment by matyaskopp** [comment]
I agree with @hpreki. In CZ case I don't encode `member`ship, I use `representative` for affiliation with a political party. The only time when we can be sure who is a member of a political party is the period between 66 days before an election and the election date.

CZ needs a very very weak connexion between the political party and parliamentary group. There are membership overlaps in general but parliamentary groups are not subordinates of the political parties.
I believe that the `represent` relation characterizes the connection between political party and parliamentary group.

**Comment by matyaskopp** [comment]
> Btw. the @passive attribute can, in general contain a series of political parties, right?

Yes, it can contains a list of references. I think it can make sense in some parliaments that one parliamentary group can represent multiple parties.

**Comment by TomazErjavec** [comment]
OK, added "representing" in 6c7791a (as always, documentation branch), it is also visible in the [guidelines](https://clarin-eric.github.io/ParlaMint/#sec-relation).

**Comment by TomazErjavec** [comment]
This has been implement in https://github.com/clarin-eric/ParlaMint/issues/155#issuecomment-1181636278, so, closing
