### ISSUE TITLE
examples are not included on GitHub pages

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#156]
[copy.xsl ](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/copy.xsl)script do not copy examples, e.g.:
https://github.com/clarin-eric/ParlaMint/blob/aa5c25bc397e0596cea81587155247eff5accde1/TEI/ParlaMint.odd.xml#L417-L419

It is used here:
https://github.com/clarin-eric/ParlaMint/blob/aa5c25bc397e0596cea81587155247eff5accde1/TEI/Makefile#L38-L40

I tried to fix it but I was not successful. It seems to me that Saxon doesn't like changing the default namespace within the XML tree.

**Comment by TomazErjavec** [comment]
Thanks for noticing! Fixed now, it just needed the addition of the examples namespace. I also moved this script to the TEI folder, now it is called [copy-odd.xml](https://github.com/clarin-eric/ParlaMint/blob/documentation/TEI/copy-odd.xsl).
So maybe another merge to main?
