### ISSUE TITLE
Finalize ParlaMint script

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#157]
This issue collects ideas on what should (and probably shouldn't) do the finalization script.

- [x] count `tagUsage` numbers 
- [x] count cumulative numbers for `extent/measure`. (Numbers of speeches in component files should be provided by partners)
- [x] set release date
- [x] set version
- [x] set handle
- [x] add correct subcorpus flag `reference/covid`

**Comment by matyaskopp** [comment]
The finalization script can be split into two tasks:

1. To pass the validation (counting numbers, croak when affiliations or relations(coalition and opposition) overlap).
2. To make it ready for release (version, release date, handle), there wouldn't be any data propagation from component files to the root.

**Comment by matyaskopp** [comment]
The script currently contains country-specific(/ParlaMint I corpus) modifications
- fixing `_` lemma value:
https://github.com/clarin-eric/ParlaMint/blob/da1bf7381503ac3c3352c7958d56aacd006155a1/Scripts/parlamint-add-common-content.xsl#L443-L460
- adding `textCass` if missing
https://github.com/clarin-eric/ParlaMint/blob/da1bf7381503ac3c3352c7958d56aacd006155a1/Scripts/parlamint-add-common-content.xsl#L577-L591
- adding `parla.lower` or `parla.upper` if missing and is Bicameralism
https://github.com/clarin-eric/ParlaMint/blob/da1bf7381503ac3c3352c7958d56aacd006155a1/Scripts/parlamint-add-common-content.xsl#L649-L661
 

I think that all these changes can be moved to [fixings/v2tov3](https://github.com/clarin-eric/ParlaMint/tree/devel/Scripts/fixings/v2tov3) and [validate-parlamint.xsl](https://github.com/clarin-eric/ParlaMint/blob/devel/Scripts/validate-parlamint.xsl) validation should be extended to cover these known issues. The new partners should add this content themselves.
@TomazErjavec,  do you agree?

**Comment by TomazErjavec** [comment]
Now made new script [parlamint2release](https://github.com/clarin-eric/ParlaMint/blob/devel/Scripts/parlamint2release.xsl) in https://github.com/clarin-eric/ParlaMint/commit/084d3ecf9d2ab150cc165d0c820728bac4678995.
As suggested it only performes fixes for a release, but does not duplicate add-common content tasks.
In particular:
https://github.com/clarin-eric/ParlaMint/blob/084d3ecf9d2ab150cc165d0c820728bac4678995/Scripts/parlamint2release.xsl#L10-L29

**Comment by matyaskopp** [comment]
@TomazErjavec I am now checking old issues, and I discovered a suggestion about deleting and reintroducing brackets in notes: #195  
- the final suggestion was to add it to parlamint2final, which is now parlamint2release

Would you like me to do it?

**Comment by TomazErjavec** [comment]
We have to be a bit careful now, as the notes have already been transtated to English, and I match them to originals based of the form of the original note. But if the transformation is deterministic and commented, I guess I  can apply the same transformation in the matching process, so, yes, pls. do it. I guess parlamint2release is the right script for this.

**Comment by matyaskopp** [comment]
> We have to be a bit careful now, as the notes have already been transtated to English, and I match them to originals based of the form of the original note. But if the transformation is deterministic and commented, I guess I can apply the same transformation in the matching process, so, yes, pls. do it. I guess parlamint2release is the right script for this.

Understand. I will implement function `mk:normalize-note()` in parlamint-lib.xsl so that you can use this normalization instead of `normalize-space()`.

Giving it a second thought - do we want to normalize all notes with remove and reintroduce parentheses, as suggested here: https://github.com/clarin-eric/ParlaMint/issues/195#issuecomment-1139509051

At the time of discussing this, we did not have an experience with this kind of long-sequence of notes:

https://github.com/clarin-eric/ParlaMint/blob/53c4c1974152e7ff8e512af24f73460fa5fa055d/Data/ParlaMint-SE/ParlaMint-SE_2017-12-12-prot-201718--48.xml#L85-L116

I suggest normalizing spaces based on context:
- if `ancestor::tei:u` then `(text of note)` or `text of note` become `[[text of note]]`
- otherwise?? no change or remove parentheses and do not introduce new ones

**Comment by matyaskopp** [comment]
ok, then **removing pairing boundary brackets** is the best way. I will implement that. 
It was your very first suggestion (I should probably not challenge your opinion/wisdom so often :-) ) and TEI recommended solution.

**Comment by TomazErjavec** [comment]
> ok, then **removing pairing boundary brackets** is the best way. I will implement that.

OK, great, thanks.

> It was your very first suggestion (I should probably not challenge your opinion/wisdom so often :-) ) and TEI recommended solution.

Far from it that my suggestions are always right but nice of you to say so :)

**Comment by TomazErjavec** [comment]
I think we are done here ([37d6946](https://github.com/clarin-eric/ParlaMint/commit/37d69467b155df9c093774520733e7d966ac8471)) so, closing. 
If new issues crop up, we can open another issue :)
