### ISSUE TITLE
Schema extension suggestion: new affiliation role values //affiliation/@role

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#16]
I have unified `person/affiliation/@role` values:
```
chairman     ~ chairperson
minister     ~ minister of ...
viceChairman ~ viceChairperson 
```
so our final list of all affiliation roles is (I believe):
```
member
viceChairman
MP
candidate
chairman
verifier
minister
replacement
vicePresident
headOfDelegation
president
presidiumMember
observer
vicePublicDefenderOfRights
publicDefenderOfRights
alternateOfDelegation
```
## list of new (or camelCased existing ones - with star) roles with number of occurrences in corpus:
```
*   662 viceChairman
    604 candidate
    332 verifier
     62 replacement
*    22 vicePresident
     18 headOfDelegation
      2 presidiumMember
      2 observer
      1 vicePublicDefenderOfRights
      1 publicDefenderOfRights
      1 alternateOfDelegation
```
I don't insist on these exact words - I can replace them (ie `replacement ~ substitute`), or just remove.

_Originally posted by @matyaskopp in https://github.com/clarin-eric/ParlaMint/issues/8#issuecomment-765163711_

**Comment by TomazErjavec** [comment]
As mentioned in #9, I added these values currently used by CZ in c99c006, also with some comments (ParlaMint/Schema/ParlaMint-teiCorpus.rng i.e.  https://github.com/clarin-eric/ParlaMint/blob/main/Schema/ParlaMint-teiCorpus.rng).

The comments: 
- "replacement" is this the same as "substituteMP"? If so, can it be changed?
- "candidate" this is somewhat uninformative, candidate for what?
- "member" same here, member of what?

Pls. comment here, so I can change the value in the schema.

**Comment by matyaskopp** [comment]
- `replacement` is not used for members of parliament. It is used for organizations with these roles: `boardOfDirectors`, `supervisoryBoard`, `delegation`.
- `candidate` means that this person is a candidate for parliament for a given `politicalParty`.
- `member` of some organization: parliament, senate, government, politicalGroup, committee.... This is just a regular member with no voted position... Element `//affiliation` has mandatory attribute `@role` so `member` role is a sort of universal role.

**Comment by TomazErjavec** [comment]
> replacement is not used for members of parliament. It is used for organizations with these roles: boardOfDirectors, supervisoryBoard, delegation.

OK, lets leave it then.

> candidate means that this person is a candidate for parliament for a given politicalParty.

A candidate to become an MP? If so, maybe candidateMP?

> member of some organization: parliament, senate, government, politicalGroup, committee.... This is just a regular member with no voted position... Element //affiliation has mandatory attribute @role so member role is a sort of universal role.

If they can't be specificed more exactly, let's leave it then. Or maybe organizationMember is a bit more informative?

**Comment by matyaskopp** [comment]
`candidateMP` is ok for me. But I don't think that `@role` has to be informative. Informative is a combination of `@role` and `org`... 

Probably `institutionMember` can be more general. Our president is a member of the institution "president"

**Comment by TomazErjavec** [comment]
> candidateMP is ok for me.

OK, changing candidate to candidateMP.

> But I don't think that @role has to be informative. Informative is a combination of @role and org...

Well, to an extent it should be.

> Probably institutionMember can be more general. 

OK, changing member to institutionMember. 

> Our president is a member of the institution "president"

No idea what you mean by this. If he is a president, then, I hope, he is labeled as "president".

But I think it is ok now, closing, next commit will have these changes.

**Comment by TomazErjavec** [comment]
> OK, changing member to institutionMember.
>> Our president is a member of the institution "president"
> No idea what you mean by this. If he is a president, then, I hope, he is labeled as "president".

Having gotten tons of valdiation errors with this change, I do now know what you meant, sorry about that.
Will *not* change member to institutionMember.
