### ISSUE TITLE
File mode in archive

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#162]
I am not sure about these two lines and tar options:
https://github.com/clarin-eric/ParlaMint/blob/22caea04716aa7b47f368c0a4f8ce072fe2164cc/Scripts/pack-parlamint.pl#L65
https://github.com/clarin-eric/ParlaMint/blob/22caea04716aa7b47f368c0a4f8ce072fe2164cc/Scripts/pack-parlamint.pl#L74

When I first created and uploaded data to our repository, I was warned that I have to be absolutely sure that the archive I create is readable/unpackable. 
So I am always adding `--mode='a+rwX'` option to tar. I don't know whether it is essential, so I don't want to change these lines myself. 

@TomazErjavec please close this if it is irrelevant or reassign it to me, and I will change it.

**Comment by TomazErjavec** [comment]
I am no expert on tar, so completely trust what you write - so, yes, pls. change it.
