### ISSUE TITLE
ParlaMint title convention for translated versions

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#163]
Currently, we distinguish only text and annotated versions in the title:
https://github.com/clarin-eric/ParlaMint/blob/22caea04716aa7b47f368c0a4f8ce072fe2164cc/Scripts/validate-parlamint.xsl#L132-L139
(related to #144)

Are we planning to distinguish translated versions?

**Comment by TomazErjavec** [comment]
> Are we planning to distinguish translated versions?

I think not, except, of course, by the language code extensions on the name. I don't currently see the need to formally distinguish them in the validations script - and, if yes, I think it could be done on a lower level.

But we would need a sample file on which we would explore the encoding first. For now, I would leave this as it is.

**Comment by TomazErjavec** [comment]
I changed my mind, so, yes: the stamp would be
`ParlaMint[A-Z]{2}(-[A-Z]{2})?(-[a-z]{2,3)?(\.ana)?`, e.g. 
`ParlaMint-CZ-en.ana`.
And, to broaden the topic, could you (and maybe @katjameden) read and comment on https://clarin-eric.github.io/ParlaMint/#sec-mt?

**Comment by matyaskopp** [comment]
> I changed my mind, so, yes: the stamp would be
> `ParlaMint[A-Z]{2}(-[A-Z]{2})?(-[a-z]{2,3)?(\.ana)?`, e.g.
> `ParlaMint-CZ-en.ana`.

So you want to add language interfix '-xx' and country interfix `-XX` into the main titles?
Currently, only language interfix is allowed:
https://github.com/clarin-eric/ParlaMint/blob/4e04e3ac11a00624507f070d4fef4b97982d73de/Scripts/validate-parlamint.xsl#L163-L170

If so, then the `validate-parlamint.xsl` needs changes and `parlamint2release.xsl` too.

**Comment by TomazErjavec** [comment]
> So you want to add language interfix '-xx' and country interfix -XX into the main titles?

Oh dear, I was writing without checking how in fact it is now. Sorry. 
So, actually, no, I would not add the langauge interfix. So, the stamp would be simply `[ParlaMint-en.ana]`.
Sorry for the confusion.
But, I guess `-en`  should also be added in the main title proper, so that we get
```
<title type="main" xml:lang="bs">Bosanski parlamentarni korpus ParlaMint-BA-en, Mandat 2, Sjednica 01 [ParlaMint-en.ana]</title>
<title type="main" xml:lang="en">Bosnian parliamentary corpus ParlaMint-BA-en, Term 2, Session 01 [ParlaMint-en.ana]</title>
```
Does this make sense? If so, I will implement it.

**Comment by matyaskopp** [comment]
> Does this make sense? If so, I will implement it.

I can't say that I did not like your previous suggestion, but it will have considerable consequences in validation.

Agree with adding `-en` for the MT version

**Comment by TomazErjavec** [comment]
> Agree with adding -en for the MT version

Great, done!
