### ISSUE TITLE
Extend validation section

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#168]
Add note on make to [validation section](https://clarin-eric.github.io/ParlaMint/#sec-validate) after https://github.com/clarin-eric/ParlaMint/pull/161 pull request merge.

suggest `make help` after this paragraph:
https://github.com/clarin-eric/ParlaMint/blob/19656dd5870ca220bdedac7034e1242a1fd47969/TEI/ParlaMint.odd.xml#L2550-L2557
Validation details(make targets) are documented in the makefile.

**Comment by TomazErjavec** [comment]
This has been added in 60fc657
