### ISSUE TITLE
GB: multiple party affiliation

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#169]
Wrong party affiliation. E.g. `DavidPrior` is affiliated to the same party at the same time multiple times. 
The result on sample data:
```
ERROR: multiple party statuses for DavidPrior on 2017-01-24 - 2017-01-24: Opposition Opposition
ERROR: multiple party statuses for DavidPrior on 2017-01-24 - 2017-01-24: Opposition Opposition
ERROR: multiple party statuses for WilliamWiggin on 2015-01-06 - 2015-01-06: Coalition Opposition
ERROR: multiple party statuses for EdwardVaizey on 2015-01-06 - 2015-01-06: Coalition Opposition
```
**Note that this validates only speakers that appear in component files - It does not validate all persons in `<listPerson>` element!**

The error on sample data is reproducible with:
```
ls Data/ParlaMint-GB/*_*.xml | grep -v '.ana.' | parallel --gnu --halt 2 --jobs 10 \
> 'java -jar /usr/share/java/saxon.jar hdr=../Data/ParlaMint-GB/ParlaMint-GB.xml -xsl:Scripts/parlamint2meta.xsl \
> {} > Data/ParlaMint-GB/{/.}-meta.tsv-TEST'
```

**Comment by perayson** [comment]
Thanks, please can you assign UK items to Matt Coole as well?

**Comment by matyaskopp** [comment]
@matthewcoole, can you please accept ParlaMint GitHub invite? I am not able to assign you to this issue.

**Comment by matthewcoole** [comment]
@matyaskopp, accepted, you should now be able to assign the issue to me.
