### ISSUE TITLE
Schema extension suggestion: allow xsd:dateTime in temporal attributes

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#17]
Currently, it is possible to store a date. We are using time in our data. 

- time info within text
- `//person/affiliation`

Can you add `xsd:dateTime` to temporal attributes? https://github.com/clarin-eric/ParlaMint/blob/c99c006baf634adc9eb341ad10b66fcf7a06aa4a/Schema/ParlaMint-TEI.rnc#L291

**Comment by TomazErjavec** [comment]
Adding.
