### ISSUE TITLE
Validate affiliations and relations

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#170]
(a related issue that inspired me #169 )
[Scripts/parlamint2meta.xsl](https://github.com/clarin-eric/ParlaMint/blob/4c61c8d78c76929aac85140efce080ca86e39754/Scripts/parlamint2meta.xsl) validates speaker affiliations only at the time(date) of speaking.

This list of invariants should be extended:
- no one can be affiliated to multiple `politicalParty`s and `politicalGroup`'s at the same time (with `member` role)
- no one can be affiliated multiple times to one `//org` with the same `@role` at the same time with
- note that it is possible to be in `member` and (e.g.) `president` with one organization

**Comment by TomazErjavec** [comment]
> (a related issue that inspired me #169 ) 

This was, and still is, a cunundrum: it is nice to have a single value, but if the switchover is made in the middle of the day (at a specific session, maybe), a person or link can have two values in one day legitimately. I think GB gets this from a gov API. 

> [Scripts/parlamint2meta.xsl](https://github.com/clarin-eric/ParlaMint/blob/4c61c8d78c76929aac85140efce080ca86e39754/Scripts/parlamint2meta.xsl) validates speaker affiliations only at the time(date) of speaking.

Because this is the only case that would affect its output -  even this is a bit paranoid, as validate xslt should check (issue warnings), and maybe finalize fix such 1 day overlaps, e.g. by adding the timestamp (hm, do do you then have to have T23:59??).

And if a down-converter finds such cases, it could only issue a WARN and pick one (e.g. previous)  

> 
> This list of invariants should be extended:
>     * no one can be affiliated to multiple `politicalParty`s and `politicalGroup`'s at the same time (with `member` role)
>     * no one can be affiliated multiple times to one `//org` with the same `@role` at the same time with

yes, but they should be added here somewhere: https://github.com/clarin-eric/ParlaMint/blob/4c61c8d78c76929aac85140efce080ca86e39754/Scripts/validate-parlamint.xsl#L280 and https://github.com/clarin-eric/ParlaMint/blob/4c61c8d78c76929aac85140efce080ca86e39754/Scripts/parlamint2final.xsl#L809

> 
>     * note that it is possible to be in `member` and (e.g.) `president` with one organization

I vaguely remember that somebody already had problems with that, as somewhere the president isnt treated as a member...

**Comment by matyaskopp** [comment]
> This was, and still is, a cunundrum: it is nice to have a single value, but if the switchover is made in the middle of the day (at a specific session, maybe), a person or link can have two values in one day legitimately. 

OK, this situation can happen when members are chosen to some commissions but the situation of political membership with `politicalParty` does not make sense to me:
```mermaid
gantt
    title JOE DOE member affiliations
    dateFormat  YYYY-MM-DD
    section ORG1
    MEMBER affiliation 1         :a1, 2022-01-01, 5d
    MEMBER affiliation 2         :a1, 2022-01-05, 6d            
```
It makes sense to me when a different role is affiliated. i.e. `president`. Joe Doe regained president role in PARTY1:
```mermaid
gantt
    title JOE DOE president affiliations
    dateFormat  YYYY-MM-DD
    section PARTY1
    PRESIDENT affiliation 1         :a1, 2022-01-01, 5d
    PRESIDENT affiliation 2         :a1, 2022-01-05, 5d            
```

> I vaguely remember that somebody already had problems with that, as somewhere the president isnt treated as a member...

Ok, so the member can have multiple affiliations with the same organization but with different roles. The situation above can be shown in one chart:
```mermaid
gantt
    title JOE DOE affiliations
    dateFormat  YYYY-MM-DD
    section PARTY1
    MEMBER affiliation 1         :a1, 2022-01-01, 11d            
    PRESIDENT affiliation 1         :a1, 2022-01-01, 5d
    PRESIDENT affiliation 2         :a1, 2022-01-05, 5d            
```
In case the president is not treated as a member, Joe Doe wouldn't have member affiliation.
Generally, affiliation with role `ROLE` to the organization `ORG` does not imply the person is a member of the `ORG`.
This is the reason we introduced `candidateMP` role (discussed here: https://github.com/clarin-eric/ParlaMint/issues/16) which says that the person is listed on the ballot paper of political party, but says nothing about membership relation with this party.

**Comment by DimitrisGk-iel** [comment]
Hi @matyaskopp 
According to this table https://github.com/clarin-eric/ParlaMint/issues/245#issuecomment-1138402807 the deputyMinister role remains as is for the latest affiliation mappings.
Is it possible to add the deputyMinister role to the allowed ones for the Government organization? 
https://github.com/clarin-eric/ParlaMint/blob/b4ed546d50c3c86f098ab8ea3caccdc7a3389aa2/Scripts/validate-parlamint-particDesc.xsl#L513

Currently, we are getting a lot of warnings with the following message. Although they are just warnings they are quite a few of them.
> WARN[16] ParlaMint-GR: Invalid role 'deputyMinister' - unexpected affiliation role with government organization

**Comment by matyaskopp** [comment]
> Is it possible to add the deputyMinister role to the allowed ones for the Government organization?

Yes, it is.
I will remove the warning.

**Comment by TomazErjavec** [comment]
These are now pretty well validated, so, closing.
