### ISSUE TITLE
schemaSpecs: change availability/licence structure

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#174]
Current `<availability>` element structure documents three different times the URL related to licencing:

https://github.com/clarin-eric/ParlaMint/blob/4c61c8d78c76929aac85140efce080ca86e39754/Data/ParlaMint-SI/ParlaMint-SI.xml#L47-L51

 I think it can be done in cleaner way in TEI, there is no need to repeat URL three times:
```XML
<availability status="free">
   <licence target="http://creativecommons.org/licenses/by/4.0/">
      <p xml:lang="sl">To delo je ponujeno pod Creative Commons Priznanje avtorstva 4.0 mednarodna licenca.</p>
      <p xml:lang="en">This work is licensed under the Creative Commons Attribution 4.0 International License.</p>
   </licence>
</availability>
```

@TomazErjavec, Do we want to do this change?

**Comment by TomazErjavec** [comment]
As this is not only in SI but in all other corpora, I think it would be a lot of work for just making it a bit nicer looking, so, I'd say no, let's leave it.

**Comment by matyaskopp** [comment]
ok, closing
