### ISSUE TITLE
v2 to v3 fixings

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#183]
**both TEI and teiCorpus files:**

**teiCorpus files:**

- `idno/@type` -> URI #173 
- affiliations #177 
  - affiliation to organization (not event)
  - remove senseless affiliations `<affiliation role="member"/>`
  - convert text affiliations to `<org>`
 - remove text content from `<birth>` and `<death>` elements (https://github.com/clarin-eric/ParlaMint/pull/205#commitcomment-72067077) 

**TEI files:**

**Comment by TomazErjavec** [comment]
As we are now at V4, this is obsolete, i.e. won't be worked on anymore. Closing.
