### ISSUE TITLE
BG: Possibly wrong source URL

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#186]
element `sourceDesc` describes wherefrom has been data gained. Did you really use data from Bulgarian PARLAMETER?
If not then line 61 should be removed:
https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Data/ParlaMint-BG/ParlaMint-BG.xml#L58-L65

**Comment by osenova** [comment]
You are right. This line should be removed. Shall we do that? If yes, please instruct how. Thanks!
