### ISSUE TITLE
empty text in idno - missing handle url 

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#188]
An annotated version of LV corpus doesn't have a handle URL:
https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Data/ParlaMint-LV/ParlaMint-LV.ana.xml#L36
even in published data.

Every `<idno>` should contain non empty `text()` value.

**Comment by TomazErjavec** [comment]
Interesting. The content of idno was defined as https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Schema/ParlaMint-TEI.rng#L372
So it seems an empty string is a valid URL, which is rather weird.
I've now added a pattern to anyURI like https://github.com/clarin-eric/ParlaMint/blob/28f72556c03e879e61a3bc2fefc874795450012a/Schema/ParlaMint-TEI.rng#L373
With this the LV error is reported, but also IS and CZ errors, cf. https://github.com/clarin-eric/ParlaMint/blob/documentation/Schema/idno-errors.log

@matyaskopp, I propose to keep this updated schema, and for me to fix the errors in the samples, so they will validate. Once the partners submit the new data, it won't validate and they will be forced to fix it too. OK?

I would also remove the handles from the samples, as they don't correspond to V2.1 anymore, but this is probably another issue.

**Comment by matyaskopp** [comment]
> With this the LV error is reported, but also IS and CZ errors, cf. https://github.com/clarin-eric/ParlaMint/blob/documentation/Schema/idno-errors.log

Ok, but I think we can be more strict. The CZ case is really ugly (the bug is in the new MP - not in ParlaMint2.1 data):
```XML
<idno type="URI" subtype="facebook">www.facebook.com/starostove, www.stan.cz</idno>
```
There shouldn't be spaces in URL.

> @matyaskopp, I propose to keep this updated schema, and for me to fix the errors in the samples, so they will validate. Once the partners submit the new data, it won't validate and they will be forced to fix it too. OK?

OK, I will then fix `idno` (issue #173) with https://github.com/clarin-eric/ParlaMint/blob/v2tov3/Scripts/fixings/v2tov3/v2tov3.xsl so we can make the schema more strict.

**Comment by TomazErjavec** [comment]
> Ok, but I think we can be more strict. ... There shouldn't be spaces in URL.

I noticed this, but then also found https://stackoverflow.com/questions/33826104/can-xsd-type-of-anyuri-contain-spaces, Thinking that spaces will be certainly be errors, I now tried adding this constraint to the RE, but it turns out we do in fact have spaces in legitimate URLs in the corpus, cf. https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Data/ParlaMint-BG/ParlaMint-BG.xml#L8103

> OK, I will then fix idno (issue https://github.com/clarin-eric/ParlaMint/issues/173) with https://github.com/clarin-eric/ParlaMint/blob/v2tov3/Scripts/fixings/v2tov3/v2tov3.xsl so we can make the schema more strict.

OK, and I will fix the (non-CZ) samples.

**Comment by matyaskopp** [comment]
> I noticed this, but then also found https://stackoverflow.com/questions/33826104/can-xsd-type-of-anyuri-contain-spaces, Thinking that spaces will be certainly be errors, I now tried adding this constraint to the RE, but it turns out we do in fact have spaces in legitimate URLs in the corpus, cf.

OK, let's allow spaces. It is not recommended to use spaces, better is replacing them with `%20`.

**Comment by TomazErjavec** [comment]
> It is not recommended to use spaces, better is replacing them with %20.

Just for the record, I agree, but I don't think we want to insist, as then it would also be recommended that all nonASCII chars are MIME-encoded, and we would just be making lots of problems for everybody. And, anyway, URLs work even with spaces...

**Comment by TomazErjavec** [comment]
This has been fixed, closing.
