### ISSUE TITLE
Remove HU

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#189]
The Hungarian corpus won't be a part of ParlaMint II, so there is no one to update it in terms of time-span and extra data required in the project, so it won't be comparable to other corpora. Also, the HU corpus is already an outlier, as it contains only interpellations and urgent questions and is therefore by far the smallest of the ParlaMint I corpora with less than a million words, as compared to the 20 mil. average and 6.5 mil. for the next smallest.

So, I propose that we delete ParlaMint-HU from GitHub, also because otherwise we will have constant problems with non-validation (already #172, #108, #107, #95).
@maciej-ogrodniczuk, do you agree?
Of course, it will still remain on the repository, as well as in previous commits.

**Comment by maciej-ogrodniczuk** [comment]
OK, since no one responded, please delete ParlaMint-HU from GitHub.

**Comment by TomazErjavec** [comment]
This seems not to have been done yet - with new people taking over HU I guess it won't be either, so we can close this issue.
