### ISSUE TITLE
Taxonomy for ministry types

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#190]
related continue: #185

Make taxonomy for ministry. One ministry can be assigned to more "topics", compare:

- SI: Ministry of Health and Sports (topics: health, sport)
- CZ: Ministry of Education, Youth and Sports (topics: education, sport)

**Comment by coltekin** [comment]
Just a suggestion: for building a taxonomy, maybe looking at the ministries defined in Wikidata may be helpful. A bit unrefined, but here is a starter: <https://w.wiki/4yUg>.

**Comment by TomazErjavec** [comment]
> Just a suggestion: for building a taxonomy, maybe looking at the ministries defined in Wikidata may be helpful. A bit unrefined, but here is a starter: https://w.wiki/4yUg.

Thanks @coltekin, this could be quite useful. Esp. as I thought setting up such a taxonomy would be relatively simple task, but looking at the possible ministries there, I see that it isn't.

First, you have "weird" ministries, which would be difficult to map to a general ontology, such as "Ministry of the German-speaking Community", "Ministério das Colónias" and the already mentioned "State Ministry (Turkey)".

Then you have also very specific ministries, or at least different from the ones I'm used to, such as "Ministry of Works", "Ministry of Housing, Communities and Local Government" and "Ministry of Urban Development".

Some sort of staring point might be the Wikipedia entry for [Ministry](https://en.wikipedia.org/wiki/Ministry_(government_department)) esp. the Table on "Common types of government ministers and ministries". But it is confusing: if we have too few categories, there will be ministries that we won't be able to fit in the schema, if too many, it will be difficult to determine which ministries belong to which categories.

**Comment by TomazErjavec** [comment]
We have looked at this in more detail and decided it would be too complicated to implement because the scope of what a ministry does varies widely across countries. So, we will not implement a taxonomy of ministry types.
