### ISSUE TITLE
enforce parliament and government organizations in validation

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#191]
each corpus should have at least one organization with these types:
- parliament
- government

these organizations should have a list of events that reflect terms or government periods.

TODO list:
- [x] validation
- [x] documentation

**Comment by matyaskopp** [comment]
I have to correct myself. It seems that parliament(`role='parliament'`) shouldn't be enforced. It is quite a mess here, legislature can be bonded to multiple organizations with roles:
- parliament
- senate (CZ uses this - I now think that it is wrong)
- CZ from the era before parliament:
  - nationalCouncil 
  - chamberOfThePeople 
  - chamberOfTheNations

So we can probably force organization with `ana='parla.national'` or `ana='parla.regional'`

**Comment by TomazErjavec** [comment]
I'm not sure I follow this in all details, but at first glance it seem we could enforce having `org[@role='parliament']` because currently all 17 corpora use it anyway:
```
$ cat */ParlaMint-??.xml | grep -c 'role="parliament"'
17
```
incl. CZ:
```
               <org xml:id="parliament"
                    role="parliament"
                    ana="#parla.national #parla.lower">
                  <orgName full="yes" xml:lang="cs">Poslanecká sněmovna</orgName>
                  <orgName full="yes" xml:lang="en">Chamber of Deputies</orgName>
```
On the other hand, nobody actually uses this information:
```
$ cat */*.xml | grep -c '"#parliament"'
0
```
so, do we really need it anyway, much less want to enforce it? 

The encoding of houses, as you note, also differs. CZ has "senate" for the upper house but GB does not even distinguish the lower and upper house as separate organisations, they just have parliament:
```
<org xml:id="PoGB" role="parliament">
  <orgName full="yes">Parliament of the United Kingdom of Great Britain and Northern Ireland</orgName>
```
So, yes, it is rather a mess. I would be nice to have just one way of encoding this of course, but, as usual, I think we would need somebody more qualified in parliamentary systems to propose the best way to do it.

**Comment by matyaskopp** [comment]
> I'm not sure I follow this in all details, but at first glance it seem we could enforce having org[@role='parliament'] because currently all 17 corpora use it anyway:

I always have trouble with these attributes that do not correspond to any category and the value can be almost anything.
I think that the parliament organization's role should be `legislature` because the role of parliament is making laws. And to be complete - the government's role should be `executive` because it enforces the law.

Assuming my suggestion, attribute `@ana` just specifies the role:
- parliament is `legislature` that corresponds to `parla.national` geospatial unit
- government is `executive` that corresponds to national geospatial unit (but we can't use `parla.national` because it match legislature)

```XML
<org xml:id="parliament" role="legislature" ana="#parla.national #parla.lower">...</org>
<org xml:id="government" role="executive" ana="#parla.national">...</org>
```
> incl. CZ:

yes CZ uses it, but we had different organizations before parliament that I don't want to have `parliament` role


> ... but GB does not even distinguish the lower and upper house as separate organisations, they just have parliament:

I think if it is possible (and it should be) upper and lower houses should be separate organizations for many reasons:

- members of upper and lower houses are not sitting in one place and don't work together
- if we will add voting or attendance it will produce a big mess (will we, again and again, repeat that member of the upper house is absent in the lower house?)
- In CZ we have different terms in lower and upper houses - if one parliament organization will be used the terms in the event list will overlap
- I definitely have not thought of all consequences...

**Comment by matyaskopp** [comment]
I believe that this is fully implemented:
- **validation**
https://github.com/clarin-eric/ParlaMint/blob/7a795b79ed41cfdae6ca0093c4ff954f46ba27b3/Scripts/validate-parlamint-particDesc.xsl#L371-L392
- **documentation**
https://github.com/clarin-eric/ParlaMint/blob/0b14c37912520147cc7ba499be709607fb924eb2/TEI/ParlaMint.odd.xml#L1304-L1314
