### ISSUE TITLE
PL: missing parliament organizations

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#192]
Members of parliament are not affiliated with upper/lower-house parliament organizations:
https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Data/ParlaMint-PL/ParlaMint-PL.xml#L470

I am not able to automatically patch with #183 because there should be two parliament organizations in PL data and the person should be at one time affiliated with only one.

related to: #191 #177

**Comment by TomazErjavec** [comment]
This seems to be obsolete, closing.
