### ISSUE TITLE
Trascriber notes containing brackets

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#195]
Transcriber notes are in the source documents often indicated by being enclosed in brackets or similar, and these marks then also serve to identify the notes. The (admittedly implicit) assumption in [Parla-CLARIN](https://clarin-eric.github.io/parla-clarin/#sec-comments) as well as [ParlaMint](https://clarin-eric.github.io/ParlaMint/#sec-comments) recommendations is that these marks are not retained in the marked-up TEI document. This seem to make sense, as they are mark-up baggage from the source document, and only make the actualy content of the notes more opague.

However, many corpora, e.g. CZ have retained these markers: `<note type="comment">(otevřením?)</note>`. 
I propose that they are deleted. Rather than making an issue for every corpus that has them, this could be one of the v2tov3 script functions and recoded in #183.

@matyaskopp, would you agree?

**Comment by matyaskopp** [comment]
At the time of creating CZ data, I have been thinking about it. I did not care much about Parla-CLARIN recommendation in this issue. I decided to kept brackets for this reason:
- When you run the default XSLT transformation you expect to get a text that makes sense. But when you remove brackets from comments senseless text can be produced

so I am not sure if brackets should've removed (or added when they are missing?)

**Comment by TomazErjavec** [comment]
> When you run the default XSLT transformation you expect to get a text that makes sense. But when you remove brackets from comments senseless text can be produced

OK, so we have to conflicting requirements:
1. for those that would want to analyze or make use of the comments, it is better if they contain only text
2. for a straighforwad text dump, it is better if the brackets are kept

I had a look at the similar example of the [q](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COHQQ) element, and TEI is (of course!) agnostic on whether to keep the quotation marks, although it does advise if the quotation marks are not kept, they original form be kept in the `@rendition` attribute.

Note also that if 2. is taken, we have, as you note, further choices:
1. Leave the original brackets, whatever they are in the source: this has the disadvantage that, again, they can all be different, also that ParlaMint I partners mostly got rid of them, and now they would have to change their scripts to retain then, lots of work for a relativelly small gain
2. Delete the original marks, but insert unified ones, probably square brackets. This has the disadvantage that we are changing the source (but so are we if we delete them), but it is nice because then we do have uniform encoding and the partenrs don't need to do anything (v2tov3 can remove old ones and insert the standardised ones).

So, I would either delete them or delete them but reintroduce some common brackets. The second might indeed be preferable, but it does mean that maybe Parla-CLARIN and definitelly ParlaMint guidelines would need to be changed, and this implemented in v2tov3 and probably validation script.

**Comment by TomazErjavec** [comment]
@matyaskopp, as we are closing issues, maybe we should now also decide how to treat these brackets. My suggestions (delete + re-introduce) is above. What do you think?

**Comment by matyaskopp** [comment]
@TomazErjavec , I agree with delete+reintroduce but I am not sure where it should be implemented:
- v2tov3 #183, that affects only old partners
- in finalization #157 (together with tagDecl, measurements,...)

**Comment by TomazErjavec** [comment]
I would vote for finalization, as we can there also catch & correct errors of the new partners.

**Comment by matyaskopp** [comment]
>I would vote for finalization, as we can there also catch & correct errors of the new partners.


Ok, agree

**Comment by TomazErjavec** [comment]
Transcriber notes are now - after finalization - bracketless. so, closing.
