### ISSUE TITLE
[ParlaMint-GR] country and language code in parlamint2conllu.pl

### ISSUE THREAD

**Issue by DimitrisGk-iel** [clarin-eric/ParlaMint#196]
When the workflow executes the conllu script it fails because the language code is not present in the Scripts/parlamint2conllu.pl . 
$country2lang{'BG'} = 'bg';
$country2lang{'BE'} = 'fr, nl';
$country2lang{'CZ'} = 'cs';
$country2lang{'DK'} = 'da';
$country2lang{'ES'} = 'es';
$country2lang{'FR'} = 'fr';
$country2lang{'GB'} = 'en';
$country2lang{'HR'} = 'hr';
$country2lang{'HU'} = 'hu';
$country2lang{'IS'} = 'is';
$country2lang{'IT'} = 'it';
$country2lang{'LT'} = 'lt';
$country2lang{'LV'} = 'lv';
$country2lang{'NL'} = 'nl';
$country2lang{'PL'} = 'pl';
$country2lang{'RO'} = 'ro';
$country2lang{'SI'} = 'sl';
$country2lang{'TR'} = 'tr';

Should i include the GR/el  code myself?

![image](https://user-images.githubusercontent.com/30075838/160384362-e1bc52e1-04a4-40b8-97be-5d833eeeeb98.png)

**Comment by matyaskopp** [comment]
> Should i include the GR/el code myself?

My fault, I will solve it (add setting for the rest of the parliaments) together with #197

**Comment by matyaskopp** [comment]
@DimitrisGk-iel, it is now fixed I believe

**Comment by DimitrisGk-iel** [comment]
Thanks, this issue is resolved, but the workflow still fails because the ValidateCountries(GB) is failing. 

![image](https://user-images.githubusercontent.com/30075838/160779742-a9b77a85-4ea3-49f5-8405-4ffc5beb2f4e.png)

![image](https://user-images.githubusercontent.com/30075838/160780849-426eb4a7-ba68-497f-976e-fbafb8050d22.png)


I am not sure how to proceed. 
Should i open a new issue or do something myself?

**Comment by matyaskopp** [comment]
no GB fails validation, it is already reported here: #169 

GitHub runs all parliaments validation when the code is changed (you made a pull request on my code changes). Next time when you change only data in your folder, only the changed parliament data will be validated.
