### ISSUE TITLE
Congratulation to GR team 

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#201]
First of all, a big congratulation, you are the first who have delivered the new parliament sample! I am impressed. Great work.

An issue in workflow appeared: https://github.com/clarin-eric/ParlaMint/commit/baeeda65e50f96f8ece96e71b1e2ee8c94bfd3ff
I hadn't considered subfolders when implementing a workflow that creates sample data. I assumed a flat sample structure.

@TomazErjavec, do we insist on a flat sample structure, so @DimitrisGk-iel should fix sample data or do we admin subfolders in sample files, and @matyaskopp should fix the workflow?

I am loaning to flat structure - to make it consistent with other samples (but my laziness :-) can influence it)

**Comment by matyaskopp** [comment]
or I can make it flatten in workflow. Files new are generated but are not committed:
![image](https://user-images.githubusercontent.com/5867995/160805643-5e0d6260-82e9-4bd6-b691-34c106413fd7.png)

**Comment by TomazErjavec** [comment]
> @TomazErjavec, do we insist on a flat sample structure, so @DimitrisGk-iel should fix sample data or do we admin subfolders in sample files, and @matyaskopp should fix the workflow?

I would suggest that we do insist on a flat structure, as the idea is to have only a couple of sample files, so it is nice if they are all on the same level and that the structure is uniform, regardless of the corpus.

> or I can make it flatten in workflow

I think this is a needless complication, also, it might break any XIncludes from the corpus root.

**Comment by DimitrisGk-iel** [comment]
ok then i will remove the subdirectories and make a new pull request
