### ISSUE TITLE
Bug in schema: make u/@who obligatory

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#21]
Right now the ParlaMint-TEI schema has `u/@who` as optional, which is a mistake: make it obligatory. But wait for the new CZ samples from @matyaskopp , as otherwise (#19, #20) they won't validate.

**Comment by matyaskopp** [comment]
@TomazErjavec `u/@who` is fixed in https://github.com/clarin-eric/ParlaMint/pull/23

**Comment by TomazErjavec** [comment]
Thanks @matyaskopp, fixed, closing.
