### ISSUE TITLE
Inspect teiHeder elements that contain text content

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#215]
List of metadata elements that contain text content only. 
(related to #183 , https://github.com/clarin-eric/ParlaMint/pull/205#issuecomment-1109828598)

The final list is in this comment. The discussion is below in comments if necessary.

### remove text content from
* birth, death,
* sex, affiliation

Note that the `@xml:lang` attribute from the above elements should also be removed.

### preserve text content
* p
* ref
* title, idno, head, label, resp,
* language, 
* date, 
* name, orgName, persName, placeName, occupation, education, publisher, 
* measure (because it gives bi-lingual info, so we should probably  keep it)
* meeting (I think, because the text content cannot be regenerated from the attribtues for some corpora, can be discussed).

**Comment by matyaskopp** [comment]
Element `<sex>` contains text content that labels gender in the language of parliament:
https://github.com/clarin-eric/ParlaMint/blob/4a53f9b2d4b4bcc403ff6a23e1ec7ace1a0b8725/Schema/ParlaMint-teiCorpus.rng#L332-L341

By removing such cases, we lose information in parliament language. Do we want to have such info?

**Comment by TomazErjavec** [comment]
Well, if we are removing the text content in birth and death (which can be formatted as per object language), then we should also remove sex. So, yes, let us have a consistent policy: if metadata info is available in attribute value, then we do not have it in the text content.

**Comment by TomazErjavec** [comment]
I think we now have a complete list, it is actually shorter than I thought. Here are some further comments:
* we really need to remove pure text content from `birth` and `death` as they can have a subordinate element (i.e. the `place` where somebody was born or died)
* by analogy, we should also remove the text content of `date`
* `sex` could really stay with text content, although it is somewhat useless and repetitive, so I think we should delete it too
* `affiliation` was even now empty for most corpora, so we should remove its text as well.

@matyaskopp, do you agree? And can you implement fixes in processing, and I can do the schema + ODD.

**Comment by matyaskopp** [comment]
@TomazErjavec Agree. 
You can do it now, I think it would be easier to have invalid samples for fixings implementation.

**Comment by TomazErjavec** [comment]
> You can do it now, I think it would be easier to have invalid samples for fixings implementation.

Out of time now but will do it soon. Note that these are massive changes, so there will be lots of errors!

**Comment by TomazErjavec** [comment]
> by analogy, we should also remove the text content of date

Thinking about this some more, I think we should allow text content for `date` as it appears in some contexts where this makes sense, e.g. publicationStmt/date. So, not changing it, and editing the list in the first comment.
