### ISSUE TITLE
remove/preserve pubPlace element in schema

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#217]
I am suggesting removing `<pubPlace>` element from `<publicationStmt>` the schema (and also the ODD schema). I have not found it in the released data and only the CZ sample has it now.

https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Schema/ParlaMint-TEI.rng#L134-L139

@TomazErjavec, Agree?

**Comment by TomazErjavec** [comment]
Yes, I completely agree. Should I just remove it from the ODD & schema, or wait?

**Comment by matyaskopp** [comment]
You can remove it and make CZ sample invalid. I will fix CZ sample later

**Comment by TomazErjavec** [comment]
OK, I removed it from the Schema in the devel branch, and from the ODD in documentation branch. I don't dare merge into main, maybe you can do it if ok.

**Comment by matyaskopp** [comment]
closing, I have CZ issue reported here: https://github.com/ufal/ParCzech/issues/159
