### ISSUE TITLE
Git: fetch upstream

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#225]
I have followed the instruction to set up, fork and clone the repository, but I get stuck with this command:

**git fetch upstream**

I get:
----
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
----

Any ideas on what could be the problem? It's probably connected to access rights since the repository does exist. I am quite new to git so any help would be appreciated.

**Comment by matyaskopp** [comment]
It seems that I skipped some configuration in the [CONTRIBUTING.md](https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md) file

@starkadur, can you run the command `git remote -v` in the repository folder? 

The expected output should be something like:
```
origin	git@github.com:matyaskopp/ParlaMint.git (fetch)
origin	git@github.com:matyaskopp/ParlaMint.git (push)
upstream	https://github.com/clarin-eric/ParlaMint.git (fetch)
upstream	https://github.com/clarin-eric/ParlaMint.git (push)
```

where `origin` is your forked repository and `upstream` should be clarin-eric/ParlaMint repository

**Comment by matyaskopp** [comment]
now I believe that tutorial is fixed:
https://github.com/clarin-eric/ParlaMint/blob/34055a76e839cbb8182a0e5174541f1bd915be4e/CONTRIBUTING.md?plain=1#L24

@starkadur can you test it for me please?

**Comment by starkadur** [comment]
This works fine now. Thanks!
