### ISSUE TITLE
add generating ParlaMint root file to GitHub Actions

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#226]
Currently, the ParlaMint root files ([ParlaMint.xml](https://github.com/clarin-eric/ParlaMint/blob/main/Data/ParlaMint.xml) and [ParlaMint.ana.xml](https://github.com/clarin-eric/ParlaMint/blob/main/Data/ParlaMint.ana.xml) ) is not updated when sample data are generated.

**Comment by TomazErjavec** [comment]
@matyaskopp, are you still considering this?

**Comment by matyaskopp** [comment]
Yes, but it is not as straightforward as I expected. I have to refactorize the script bit because

1) it currently does not check the existence of the included root file. It shouldn't fail when a file is missing.

The question is how new corpora should be added... Should they be added to `Scripts/ParlaMint-template*.xml` when new corpora are initialized with: 
```bash
make setup-parliament PARLIAMENT-NAME='COUNTRY_NAME' PARLIAMENT-CODE='COUNTRY_CODE' LANG-LIST='LANG-CODE (LANG-NAME)'
```

2) Furthermore, I want to add comments similar to missing translations in taxonomies:
https://github.com/clarin-eric/ParlaMint/blob/cb93f7eb5002b6bd608600a6c800accfdce9c72b/Corpora/Taxonomies/ParlaMint-taxonomy-NER.ana.xml#L55-L62
so it is easily visible, what is missing some corpora.

**Comment by TomazErjavec** [comment]
> Yes, but it is not as straightforward as I expected. I have to refactorize the script bit because
>     1. it currently does not check the existence of the included root file. It shouldn't fail when a file is missing.

Yes.

> The question is how new corpora should be added... 
> Should they be added to `Scripts/ParlaMint-template*.xml` when new corpora are initialized 

Hm, dangerous, the corpus might not (yet) exists in .ana or MTed version. 
Anyway, maybe the whole question of initialising new corpora is bigger than just this and should be postponed...

>     2. Furthermore, I want to add comments similar to missing translations in taxonomies:
>        https://github.com/clarin-eric/ParlaMint/blob/cb93f7eb5002b6bd608600a6c800accfdce9c72b/Corpora/Taxonomies/ParlaMint-taxonomy-NER.ana.xml#L55-L62

Well, people will add their language via their local taxonomy, right? In which case noting that a translation is missing is maye redundant. But it doesn't hurt.
