### ISSUE TITLE
Mandatory affiliations and organizations roles

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#227]
updated with #245

- if a person is affiliated with some position such as prime minister - the person is affiliated two times: 
  - regular membership **member**
  - special position **head**, **deputyHead**
- position accumulation is allowed - eg a minister is a member of the government and can be also a member of the lower house
- mandatory organization roles
  - **parliament**
    - each house has a separate organization (with `role=parliament`)
    - in the case of national councils (or other names non-parliamentary sound names) use also `role=parliament`
  - **government**
  - **parliamentaryGroup**

```mermaid
graph LR
    person[person] -.can be a.-> PrimeMinister & Minister & overconfidentMinister & MG & LPG & MPG & MP & uaf & GM & GL
    PrimeMinister[Prime Minister] --head--> Gov(Government / role=government)
    Minister[Minister of ...] --minister--> Gov
    overconfidentMinister[Minister of two ministries] & overconfidentMinister--minister--> Gov
    LPG[Leader of Parliamentary Group] --head--> Par.G
    PrimeMinister & Minister & overconfidentMinister & MG[Member of government] --member--> Gov
    MPG[Member of Parliamentary Group] & LPG --member--> Par.G(Parliamentary Group  / role=parliamentaryGroup)
    MP[Member of Parliament] & LPG & MPG & uaf[unaffiliated Member of Parliament] --member--> Par.L(Lower House / role=parliament)
    GM[Member of optional organization] & GL --member--> GO(optional organization / role=...)
    GL[Leader/president/head of optional organization] --head-->GO
    style GM fill:#dff,stroke-width:0px
    style GL fill:#dff,stroke-width:0px
    style GO fill:#dff,stroke-width:0px
```

**Comment by TomazErjavec** [comment]
@matyaskopp, as we now changed "president" to "head", I'm afraid the figure will have to be re-drawn.
And here are some other small comments to make a perfect figure:
* Instead of "a person" maybe just "person" (as it is then exactly the xml element)
* "parliamentary group " maybe capitalise, so it is the same as other orgs, i.e. "Parliamentary group"

**Comment by TomazErjavec** [comment]
@matyaskopp, I now added an explanation of the obligatory and other affiliations roles to organisations at the end of the Section on [Speaker affiliations](https://clarin-eric.github.io/ParlaMint/#sec-affiliation). Could you pls. have a look and report any problems? Once it is ok, I think we can close this issue.

**Comment by matyaskopp** [comment]
@TomazErjavec, only one suggestion:

> Affiliation can also have the classification `ana` attribute, which here points to the definition of the legislative period in which the person was affiliated with the specified organisation.

In CZ corpus, I am pointing to events in organizations because originally, there were many organizations with the same/similar name defined for each term - eg parliamentaryGroups are newly established on every term.

Furthermore, the previous government is still working after the election - until a new government is nominated. And we can also have multiple governments in one legislative period.

So here I suggest adding:   
Affiliation can also have the classification `ana` attribute, which here **can** points to the definition of the legislative period in which the person was affiliated with the specified organisation **or event in the organisation which is usually established for the legislative period.**

**Comment by TomazErjavec** [comment]
I added the explanation about `@ana` as the third paragraph [Speaker affiliations](https://clarin-eric.github.io/ParlaMint/#sec-affiliation). Formulated a bit differently from your suggestion, as I didn't really understand it - if not ok, pls. complain, otherwise close.
