### ISSUE TITLE
Validation - check-links

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#228]
When I run make check-links-IS I get the following output:

for root in `find Data -type f -path "Data/ParlaMint-IS/ParlaMint-*.xml" | grep -v '_'`;	do \
  echo "checking links in root:" ${root}; \
  java -jar /usr/share/java/saxon.jar -xsl:Scripts/check-links.xsl ${root}; \
  for component in `echo ${root}| xargs -I % xmllint --xpath '//*[local-name()="include"]/@href' % |sed 's/^ *href="//;s/"//'`; do \
    echo "checking links in component:" Data/ParlaMint-IS/${component}; \
    java -jar /usr/share/java/saxon.jar meta=/home/starkadur/parlamint2/ParlaMint/${root} -xsl:Scripts/check-links.xsl Data/ParlaMint-IS/${component}; \
  done; \
done
checking links in root: Data/ParlaMint-IS/ParlaMint-IS.ana.xml
xargs: xmllint: No such file or directory
checking links in root: Data/ParlaMint-IS/ParlaMint-IS.xml
xargs: xmllint: No such file or directory

It doesn't matter if I use IS, SI or GB, it's always the same error.

**Comment by matyaskopp** [comment]
You don't have installed `xmllint` on your system. If you use an ubuntu-based system, you can install it with:

```bash
sudo apt-get -y install libxml2-utils
```

**Comment by starkadur** [comment]
Thank you!

**Comment by TomazErjavec** [comment]
@matyaskopp, maybe the presence of xmllint should then be checked in prerequisites? 

Btw. we mustn't forget the idea that all prerequsits are installed inside the ParlaMint repo in a gitignored directory - this would allow installing them without sudo and escape conflicts where people already have installed the tools but in a different place than the one assumed by ParlaMint.

And sorry if this is the wrong issue for this, feel free to continue in the approprite one!
