### ISSUE TITLE
remove xmllint dependency

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#229]
#228 

the only place where `xmllint` is used is Makefila:
https://github.com/clarin-eric/ParlaMint/blob/34055a76e839cbb8182a0e5174541f1bd915be4e/Makefile#L290
 and its installation needs sudo, so it is better not to use it.

**Comment by TomazErjavec** [comment]
If it is just used to process XIncludes, you could use Saxon + copy.xsl.

**Comment by matyaskopp** [comment]
No, I just wanted a list of included files. I have found a saxon way how to do this:
https://github.com/clarin-eric/ParlaMint/blob/26a991b178d5333b2061672bcbf8b099092a9b77/Makefile#L381
