### ISSUE TITLE
SI: Unrelated members of parliament vs. Parliamentary group of unrelated members of parliament

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#243]
This issue is to make sure that I understand the SI situation correctly and to refer to the changes in v2tov3.

SI has two organizations, but only `party.NP` is a parliamentary group.  `party.NeP` is a virtual organization.
https://github.com/clarin-eric/ParlaMint/blob/2a09e616722f6d360831f5549aa0c4eadb904b21/Data/ParlaMint-SI/ParlaMint-SI.xml#L535-L544

and here is the migration of one MP: 
1. becoming independent
2. becoming a member of  "Parliamentary group of unrelated members of parliament"

https://github.com/clarin-eric/ParlaMint/blob/2a09e616722f6d360831f5549aa0c4eadb904b21/Data/ParlaMint-SI/ParlaMint-SI.xml#L1415-L1424

---
I will make this changes in v2tov3 script:
 - remove  `party.NeP` with all affiliations
 - change `party.NP` role to `parliamentaryGroup`

@TomazErjavec Do I understand it correctly?

**Comment by TomazErjavec** [comment]
> I will make this changes in v2tov3 script:
>  remove party.NeP with all affiliations
> change party.NP role to parliamentaryGroup
> @TomazErjavec Do I understand it correctly?

Yes, exactly. Additionally, remove partyNeP affiliation from the persons that have it.
And, of course, all other politicalParty roles must be changed to parliamentaryGroup.
