### ISSUE TITLE
uniform affiliation role confusion

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#245]
I have been thinking about @perayson confusion (https://github.com/clarin-eric/ParlaMint/pull/239#issuecomment-1136118432).

I think that idea of having uniform affiliation role values for the most common roles is good, but as @perayson remarked we lose some information.

The idea is to add a optional subelement [`roleName` ](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-roleName.html) (note that the example in documentation is wrong and it seems to be fixed in next TEI release: https://github.com/TEIC/TEI/commit/75b47ee8d95b05afa1a9b14acedc9583f9e1c174)
```xml
<affiliation ref="#GOV" role="head"> 
  <roleName>Prime Minister</roleName>
</affiliation>
<!-- ... -->
<affiliation ref="#GOV" role="minister">
  <roleName>Minister for Higher and Further Education</roleName>
  <!-- info taken from: https://www.gov.uk/government/people/michelle-donelan -->
</affiliation>
```
Note also that there can be several roleNames for the names of the roles in different languages (local language(s) and English).
This idea has been discussed with @TomazErjavec and he agrees.

**Comment by TomazErjavec** [comment]
OK, I hope we now have a solution with embedding roleName inside affiliation, which means we still retain "abstract" roles, while at the same time not losing information about the exact role that the person plays in an parliamentary body in a specific country. This solution also has the advantage that the name can be given both in the local language and in English.
@perayson, I hope you are fine with this?

We do have another question though: "president" (and "vicePresident") is indeed an unhappy term, as it already means something very specific in parliamentary discourse, so we would prefer a more neutral label, preferably one that is not otherwise directly used in parliaments. We thought about:
* leader (and deputyLeader): however, this one is used for party leaders
* head (and deputyHead): sounds better, and does not seem to be used for a specific function in parliament
* boss (not serious about this one)
@perayson, and thoughts on this? In not, we go with "head".

**Comment by TomazErjavec** [comment]
I would move forward with this change, and have a suggestion for the v2 to v3 fixings (@matyaskopp, if you accept this, pls move or refer to the conversation there): as we now have affiliation/roleName and we are renaming existing roles to less specific ones, why not put existing roles, when different from new ones, in roleName? Maybe not literally, but closest human readable version, for example role, 'cadidateMP' goes to role 'represetative', roleName 'Candidate MP'. 
What do you think @matyaskopp?

Note also that we still have lots of idiosycratic affiliation roles (e.g. director, headOfDepartment, leader), which could (or should!) also be mapped to our "head" etc.

**Comment by TomazErjavec** [comment]
And here is a draft of  `affiliation/@role` mappings as suggested above:

Current | New | roleDesc
--------|-----|---------
member| member| Member
MP|     member| MP
presidiumMember|        member| Presidium Member
associateMember|        ?leave alone?
nonAttachedMember|      ?leave alone?
president|      head|   President
chairman|       head|   Chair Person
chairperson|    head|   Chair Person
speaker|        head|   Speaker
headOfDelegation|       head|   Head of Delegation
leader|         head|   Leader
presidentEP|    head|   President of EP
primeMinister|  head|   Prime Minister
director|       head|   Director
headOfDepartment|       head|   Head of Department
chiefInspector| head|   Chief Inspector
commander|      head|   Commander
vicePresident|  deputyHead|     Vice President
viceChairman|   deputyHead|     Vice Chairman
viceDirector|   deputyHead|     Vice Director
deputyChief|    deputyHead|     Deputy Chief
deputyPrimeMinister|    deputyHead|     Deputy Prime Minister
substituteMP|   representative| Substitute MP
minister|       minister|       Minister
ministerOfState|        minister|       Minister of State
deputyMinister
ministerDelegate
secretary|      secretary|      Secretary
secretaryGeneral
secretaryOfState
academician
alternateOfDelegation
candidateChairman
candidateMP
constitutionalJudge
observer
ombudsman
prosecutorGeneral
publicDefenderOfRights
replacement
verifier
vicePublicDefenderOfRights

**Comment by matyaskopp** [comment]
@TomazErjavec, I have been too rush with agreeing with you.
- `deputyMinister` should stay `deputyMinister` in affiliation with `government` organization
- `deputyMinister` can be changed to `deputyHead` in affiliation with optional `ministry` organization

and similarly to the `minister` role case

**Comment by TomazErjavec** [comment]
OK, I edited the table to reflect you comment. This makes sense, even though it does make the renaming context-dependent.

**Comment by TomazErjavec** [comment]
> head (and deputyHead)
As no comment from @perayson, I will now change "president" and "vicePresident" roles to "head" and "deputyHead". @matyaskopp, feel free to implement this in v2 to v3 as well.

**Comment by TomazErjavec** [comment]
I think we did what we wanted to here, so, closing.
