### ISSUE TITLE
wrong (or confusing) parliament example

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#247]
There is used an example from BE parliament in the documentation. This is wrong because BE uses a different `parla.legislature` taxonomy:
https://github.com/clarin-eric/ParlaMint/blob/2a09e616722f6d360831f5549aa0c4eadb904b21/Data/ParlaMint-BE/ParlaMint-BE.xml#L162-L168
There is no `parla.federal` category in the SI corpora

So this list:
https://github.com/clarin-eric/ParlaMint/blob/b9f2d3b1d54687812d06f4c454ac9c7714f72826/TEI/ParlaMint.odd.xml#L1357-L1364
and this example: 
https://github.com/clarin-eric/ParlaMint/blob/b9f2d3b1d54687812d06f4c454ac9c7714f72826/TEI/ParlaMint.odd.xml#L1370-L1393

are is wrong or confusing. 

---

I think that `parliament` organization should be categorized from two perspectives:
1. **spatial**, so it should be a subcategory of https://github.com/clarin-eric/ParlaMint/blob/2a09e616722f6d360831f5549aa0c4eadb904b21/Data/ParlaMint-SI/ParlaMint-SI.xml#L112
    - `parla.national` for most parliaments
    - `parla.regional` for all ES regions 
2.  **chamber** perspective: https://github.com/clarin-eric/ParlaMint/blob/2a09e616722f6d360831f5549aa0c4eadb904b21/Data/ParlaMint-SI/ParlaMint-SI.xml#L159
    - `parla.uni`
    - `parla.upper`
    - `parla.lower`

**Comment by TomazErjavec** [comment]
You are, of course, right. I've corrected this now, closing.
