### ISSUE TITLE
SI: error in metadata

### ISSUE THREAD

**Issue by kristinapdm** [clarin-eric/ParlaMint#259]
Corpus: [ParlaMint-SI 2.1 (Slovenian parliament)](https://www.clarin.si/noske/parlamint21.cgi/corp_info?corpname=parlamint21_si&struct_attr_stats=1&subcorpora=1)

Wrong gender assigned to the following MP:

<html>
<body>

speech.speaker_name | Furman, Karmen
-- | --
speech.speaker_gender | M

</body>
</html>

**Comment by TomazErjavec** [comment]
@katjameden , pls. check and fix this in the new version (i.e. of siParl).
Pls. close when fixed.

**Comment by katjameden** [comment]
Error fixed, closing the issue
