### ISSUE TITLE
funder: no ref-element. Bug or feature?

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#260]
unlike in `<publisher>` the `<funder>` element does not allow to add a `<ref>` for the funder-organisation 
Is this a bug or a feature?

**Comment by matyaskopp** [comment]
You can add a `<ref>` inside `publisher/funder/orgName`:
https://github.com/clarin-eric/ParlaMint/blob/54aa2d81885862302da38f74e6dcf2f2ffe248d8/Schema/ParlaMint-TEI.rng#L337-L346

But I think there should be a possibility to add `ref` outside `orgName`. The same way as it is implemented in `publicationStmt/publisher`:
https://github.com/clarin-eric/ParlaMint/blob/54aa2d81885862302da38f74e6dcf2f2ffe248d8/Schema/ParlaMint-TEI.rng#L318-L334

Good spot! @TomazErjavec, do you agree, and if so, can you fix the schema?

**Comment by TomazErjavec** [comment]
Yes, this makes sense, thanks both for the suggestion. I've added an optional `ref` to the end of `funder` in [9e54f8b](https://github.com/clarin-eric/ParlaMint/commit/9e54f8b10778655bfa81a37708afa3e847f31ac9). Note that this is in documentation branch.
