### ISSUE TITLE
Common taxonomies unification

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#264]
This issue describes the basic idea of taxonomy storing and unification:

- We will store all common taxonomies in [Data/Taxonomies](https://github.com/clarin-eric/ParlaMint/tree/main/Data/Taxonomies)
- Every corpus will `xi:include` all used taxonomies from the same folder as the root of the corpus file
- In GitHub there will be symbolic links from `Data/ParlaMint-XX/TAXONOMY.XML`  to `../Taxonomies/TAXONOMY.XML`
- Partners should translate all taxonomies (excepting `UD-SYN`) to the corpus language, and use ParlaMint-SI taxonomies as sources (`NER`, `subcorpus`, #322 , `parla.legislature`)
- No id changes are allowed
- `UD-SYN` taxonomy will be scrapped from UD webpages or GitHub (@matyaskopp #321 )
- and other translated taxonomies will be merged into  common multilingual taxonomies (@TomazErjavec)

@TomazErjavec, I hope I have not forgotten something. This records what we have discussed a month ago on Zoom...

**Comment by TomazErjavec** [comment]
Yes, I think this about covers it, thanks for summarizing. 
I don't rememeber the conclusion about symbolic links, rather than directly Xincluding ../Taxonomies/TAXONOMY.XML in each corpus root, what is the advantage? Is it that corpora can (for a while) still have their own taxonomies, rather than a common one? If so, this makes sense.

Next question is how to implement all this of course...

**Comment by TomazErjavec** [comment]
> The reason for this decision was that we don't want to introduce another difference between GitHub sample files and root files in the final release. I think that country-specific taxonomies should be also in the custom ParlaMint-XX folder as the partners are not supposed to change files outside their folder.

OK, understood.

> I think the partners should be asked to place translated taxonomies in their folders.
Yes, for the new ones anyway - maybe for the old ones this could be done in the v2tov3 script?

**Comment by TomazErjavec** [comment]
In [8df7d47](https://github.com/clarin-eric/ParlaMint/commit/8df7d471e27cb1d890a963f899148d10342dad28) there is now a new script [parlamint-merge-taxonomy.xsl](https://github.com/clarin-eric/ParlaMint/blob/devel/Scripts/parlamint-merge-taxonomy.xsl) for merging the translations of a corpus-specific taxonomy into a "master" ParlaMint-wide taxonomy. The script is careful in the sense that it reports mismatches or overwriting already existing translations. Also added is a testing environment in the [Data/Taxonomies](https://github.com/clarin-eric/ParlaMint/tree/devel/Data/Taxonomies) folder currently on the case of the (most complicated) "parla.legislature" taxonomy.

There is a number of open issues here, in particular:
 
1. The current test run was done on the already sumbmitted data for CZ, GR, IS, and on V2 data for the (other) corpora there. The [log](https://github.com/clarin-eric/ParlaMint/blob/devel/Data/Taxonomies/ParlaMint-taxonomy-parla.legislature.log.xml) shows a number of issues:
 * most of the corpora do not have all the categories and hence they lack their translations
 * some corpora introduced new categories
 * and the interesting case of nl, where BE and NL have different translations of the same categories
2. We need to set up a system of issues for reporting the above problems, and also deciding which ones to address and how
3. We need to come up with a controlled way of adding translations to taxonomies, incl. notifying partners.

@matyaskopp, ideas welcome!

**Comment by matyaskopp** [comment]
@TomazErjavec this is my idea:

## validation

First of all - if `ParlaMint-XX` does not provide correct common taxonomies with all `xx` translations, it shouldn't pass the validation.
- validation is needed 

The question is how we can help current and possibly new partners in future with the taxonomies.

## new future partners
I used https://github.com/clarin-eric/ParlaMint/blob/f253e93b9182b8ce283d67720e0e520ebf63f53c/Makefile#L37 

for initializing new partners' folders. I think this folder `ParlaMint-XX` should, after initialization, contains common taxonomies.
 - if there exists a translation: common taxonomies with `en` and `xx` translations
 - if there is no translation, it should contain files like this:
```XML
<?xml version="1.0" encoding="utf-8"?>
<taxonomy xmlns="http://www.tei-c.org/ns/1.0" xml:id="speaker_types">
  <desc xml:lang="xx"><term><!-- MISSING TRANSLATION --></term></desc>
  <desc xml:lang="en"><term>Types of speakers</term></desc>
  <category xml:id="chair">
    <catDesc xml:lang="xx"><term><!-- MISSING TRANSLATION --></term></catDesc>
    <catDesc xml:lang="en"><term>Chairperson</term>: chairman of a sitting</catDesc>
  </category>
  <category xml:id="regular">
    <catDesc xml:lang="xx"><term><!-- MISSING TRANSLATION --></term></catDesc>
    <catDesc xml:lang="en"><term>Regular</term>: a regular speaker at a sitting</catDesc>
  </category>
  <category xml:id="guest">
    <catDesc xml:lang="xx"><term><!-- MISSING TRANSLATION --></term></catDesc>
    <catDesc xml:lang="en"><term>Guest</term>: a guest speaker at a sitting</catDesc>
  </category>
</taxonomy>
```

## current partners
- we can adapt a new partner's solution, just use `<!-- MISSING TRANSLATION -->` when the translation is missing:
```XML
<?xml version="1.0" encoding="utf-8"?>
<taxonomy xmlns="http://www.tei-c.org/ns/1.0" xml:id="speaker_types">
  <desc xml:lang="xx"><term>Druhy řečníků</term></desc>
  <desc xml:lang="en"><term>Types of speakers</term>
  </desc>
  <category xml:id="chair">
    <catDesc xml:lang="xx"><term>Předsedající</term>: předsedá zasedání</catDesc>
    <catDesc xml:lang="en"><term>Chairperson</term>: chairman of a sitting</catDesc>
  </category>
  <category xml:id="regular">
    <catDesc xml:lang="xx"><term><!-- MISSING TRANSLATION --></term></catDesc>
    <catDesc xml:lang="en"><term>Regular</term>: a regular speaker at a sitting</catDesc>
  </category>
  <category xml:id="guest">
    <catDesc xml:lang="xx"><term><!-- MISSING TRANSLATION --></term></catDesc>
    <catDesc xml:lang="en"><term>Guest</term>: a guest speaker at a sitting</catDesc>
  </category>
</taxonomy>
```

**Comment by TomazErjavec** [comment]
I think everything to do with common taxonomies has been done, so, closing. @matyaskopp, if you disagree, pls. re-open.
