### ISSUE TITLE
AT: keeping "textual characteristics" of the original: how to deal with front-matter and quoted text?

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#265]
The data for the Austrian ParlaMint contribution is derived from the parliament's official "stenographic protocols".
I wonder how (and if!) the "textual characteristics" of these protocols are to be retained in the ParlaMint-representation. 

Protocols typically contain extensive "Front matter" - i.e. a table of content and the list of applications, motions etc. etc. 

You can just have a look at a typical example: 
https://www.parlament.gv.at/PAKT/VHG/XXVII/NRSITZ/NRSITZ_00124/fnameorig_1432643.html

The actual transcription only starts at page 36! ( search for the string: _"Beginn der Sitzung"_). 
 
In my understanding ParlaMint's current schema is quite restricted in that the `TEI/text/body` only is to contain just `<div type="debateSection"/>`. 
So what is the stance towards this additional information? Is it simply to be scraped? 

What's bothering me even more: the actual `debateSection` often contain quotes of written matter. 
Typically the chair announces the discussion about a motion with something like 

"... ver­weise ich ... auf die im Sitzungssaal verteilte Mitteilung. Die schriftliche Mitteilung hat folgenden Wortlaut:"
_(... I point to the announcement which has been distributed in the assembly hall. The written announcement has the following wording: )_

If you just search for the string _"Wortlaut"_  you can see _how_ prominently this pattern is used. (You can spot the quoted text as it  is type-set in _italics_).  

In my current "parla-clarin-inspired" representation these occurrences are marked as `<quote>` with internal `<p>` and even occasional `<table>`s. 

So what is ParlaMint's stance towards the representation of this kind of information? 
I am willing to accept that ParlaMint is intended to represent plain speeches only. 
On the other hand I am spotting the occasional `<pb>` in the examples, so there seem to exist some tributes to the textual origin of the data?  
I  find it hard/impossible to stay true to the original with the current ParlaMint schema. So again: are internal quotes just scraped? 
(The only alternative I see right now would be to add it as `<note>` -- but then these would be quite extensive and I think there is no way to structure them internally e.g. with `<p>`?)

**Comment by TomazErjavec** [comment]
In short: yes, I would scrap front matter and quoted material for ParlaMint, as it is really focused (only) on speeches. Also:

- I think you would get into lots of problems with the linguistic annotation of heavily annotated text
- It is not clear where then to stop, once you go down that road; you already mention tables, there will be bulleted list and enumerations, maybe bold, I see you also have graphics,...

You mention pb: yes, this is the "exception that proves the rule", but (@matyaskopp, correct me if I am wrong) only CZ uses them, and the main reason is that they have associated the URL which leads you to exactly the page on the parliamentary web site, so you can have a nice connection to the source of the text.

So, I would suggest you keep the full and fully annotated version in Parla-CLARIN, which should have all the required elements, but for ParlaMint make a trimmed-down version, i.e. ommiting the front, and having [gap](https://clarin-eric.github.io/ParlaMint/#sec-gaps) where the quote used to be.

**Comment by matyaskopp** [comment]
>In short: yes, I would scrap front matter and quoted material for ParlaMint,

@TomazErjavec I am not sure that I agree with you.
The front matter should be removed. if I correctly understand the quotation matter should be preserved. I think it is a part of speech if someone is reading a text from the paper.

> You mention pb: yes, this is the "exception that proves the rule", but (@matyaskopp, correct me if I am wrong) only CZ uses them, and the main reason is that they have associated the URL which leads you to exactly the page on the parliamentary web site, so you can have a nice connection to the source of the text.

@hpreki I think preserving `pb`s make perfect sense in your case:
```XML
<pb source="https://www.parlament.gv.at/PAKT/VHG/XXVII/NRSITZ/NRSITZ_00124/fnameorig_1432643.html#Seite_0036.html" />
```
My conviction is to use `@source` attribute whenever it is possible. It is nice proof that the data are based on real ground and it makes debugging anomalies in data easier.

**Comment by TomazErjavec** [comment]
>  if I correctly understand the quotation matter should be preserved. I think it is a part of speech if someone is reading a text from the paper.

I don't think they are actually reading these extensive texts (@hpreki correct me if I am wrong)  but that this is background material that is passed around beforehand. So, I would argue that if such quotes are included, you will get a skewed picture of what is actually being said in parliament. 

And, as said, not to mention the problems of annotating mixed content and which elements to allow in quote - the list might be quite large, inlc. tables, which is scary from the perspective of ParlaMint.

**Comment by hpreki** [comment]
Thanks you for your clarifications. 
@TomazErjavec is right: the `<quoted>` matter is not actually read. (In some places the chair  explicitly says something along the lines ... _the written proposal has been distributed in the hall and will therefore not be read to you_ )
Having your confirmation that ParlaMint focus on the speech-parts I will not hesitate to simplify/ scrape my current Parla-CLARIN-_ish_ representation in order to _home in_ to a 1st ParlaMint-conforming version.
