### ISSUE TITLE
Bugs in CZ

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#28]
In latest CZ data:
- the main title of the component files should be uniq in the corpus, so you should add a suffix that distinguishes it from the rest, e.g. "Czech parliamentary corpus ParlaMint-CZ, 2020-11-19 ps2017/070/01 [ParlaMint]"
- on the assumptiom that you are pushing actual files from the corpus, and not samples, the publicationStmt/idno should not be to GitHub but `<idno type="handle">http://hdl.handle.net/11356/1388</idno>`

**Comment by matyaskopp** [comment]
> the main title of the component files should be uniq in the corpus, so you should add a suffix that distinguishes it from the rest, e.g. "Czech parliamentary corpus ParlaMint-CZ, 2020-11-19 ps2017/070/01 [ParlaMint]"

OK, I will fix it in the next sample

> on the assumptiom that you are pushing actual files from the corpus, and not samples, the publicationStmt/idno should not be to GitHub but <idno type="handle">http://hdl.handle.net/11356/1388</idno>

NO, the sample is generated only for GitHub purposes. The number of elements corresponds to sample, `person`s and `org`s appears in sample data.
https://github.com/clarin-eric/ParlaMint/blob/c666fab596a151dcc89d22cd8ca088356c4b0817/ParlaMint-CZ/ParlaMint-CZ.xml#L85-L94

**Comment by TomazErjavec** [comment]
> OK, I will fix it in the next sample

ok, great.

> NO, the sample is generated only for GitHub purposes. 

So, invalid assumption. But note that I will be generating the samples anyway once I have the complete corpus, so no need to be very exact here.
