### ISSUE TITLE
Anonymous speaker?

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#29]
It might happen that for a certain speech (i.e. `<u>`) it is not known who the speaker was. Of the V1 corpora, this is only the case in BG, where this speaker was specified as: 
https://github.com/clarin-eric/ParlaMint/blob/c666fab596a151dcc89d22cd8ca088356c4b0817/ParlaMint-BG/ParlaMint-BG.xml#L7231

However, it is not clear that this is the best way to do it, it would be more XMLish if such speeches simply did not have the `@who` attribute. This would mean fixing BG, undoing #21 and esp. being aware in any user-facing applications that the attribute can be missing, and that such cases must be processed appropriatelly (probably by showing "Anonymous").

Comments?

**Comment by matyaskopp** [comment]
From application and statistics perspectives: Using `Anonymous` looks like it is one single (chatty) person.

If we don't fill `@who`, we are saying that we don't know the speaker.

**Comment by KirilSimov** [comment]
I agree and we will change in the new versions.

**Comment by TomazErjavec** [comment]
OK, I will make `u/@who` optional, as this also seems to solve the problem in #33.
Of course, now all utterances can be without their speaker, so the validation is weaker now. So I will change the conversion to vertical, to output a warning in such cases though.
