### ISSUE TITLE
gap-element: allow more than 1 desc

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#291]
Following the advice in #265 I omit  written matter in the protocols and replace it by `<gap>`s + 
Is is possible to allow more than 1 `<desc>` for `<gap>` so I can have descriptions in more than 1 language?

```xml
               <gap reason="editorial">
                  <desc xml:lang="en">Quoted printed matter omited</desc>
                  <desc xml:lang="de">Zitierte Druckfassung entfernt</desc>
               </gap>```

**Comment by TomazErjavec** [comment]
Yes, this is a very sensible suggestions - I've now implemented it (so, that we can have 1 or more desc) in gap, but also in the incident elements (vocal, kinesic, incident) in the documentation branch:

- implemented in the RNG schema
- in the ODD schemaSpecs
- in the ODD prose

The docu change is at https://clarin-eric.github.io/ParlaMint/#sec-incidents, https://clarin-eric.github.io/ParlaMint/#sec-gaps.
Feel free to close if ok.

**Comment by hpreki** [comment]
Thanks a lot for the super-fast reaction!
