### ISSUE TITLE
allow page-brakes within notes?

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#295]
Because our `<notes>` are derived from text in the original protocols occasionally `<pb/>` can appear within `<notes/>` which is ruled out by the current Schema. 
Could we allow `<pb/>` inside notes? 

( other options i.m.o would be 
* leave out `<pb/>` completely 
* leave out `<pb/>` (only) when they occur within `<note/>`
* shift `<pb/>` before or after the `<note/>`)

**Comment by matyaskopp** [comment]
I am not sure if I want to allow `<pb/>` inside notes - it would then contain mixed content (text + element)

**Comment by TomazErjavec** [comment]
> I am not sure if I want to allow <pb/> inside notes - it would then contain mixed content (text + element)

Well, our motivation for disallowing mixed content is that it then becomes difficult to linguistically annotate the text - and even here we do allow mixed content (like having note, vocal etc., just not elements that would then again contain text to be analysed, such as hi. Because notes are not ling. analysed, I don't see a problem here.

So, @hpreki, if you wish, we can add note/pb, although moving pb before or after note is also a possiblity of course. So, pls. let me know.

**Comment by vaidasmo** [comment]
To my mind, as long as PB is inside notes (metadata) and not inside texts (data), it is no problem.

**Comment by TomazErjavec** [comment]
OK then, I can add it to note (but I will not add it to incident elements (like vocal, kinesic), or, rather to their desc, as pb is not allowed there in TEI, to my mind with good reason.

**Comment by TomazErjavec** [comment]
OK, added pb to note in [908d51a](https://github.com/clarin-eric/ParlaMint/commit/908d51a8bd4bd502b0d0a79a727629143f433b4f). This is documentation branch, will appear in main when @matyaskopp merges (of course (the current soft link to Data) is gitingored in documentation!)

**Comment by hpreki** [comment]
@TomazErjavec.  I evaluated the situation in _our_ `<notes>`: typically the `<pb>` are already situated at the "edges" of the note - i.e. they are the 1st or the last child. So I the `<pb>` _can_ very well be moved without deviating from the original content, but if you allow them inside `<note>` I am not _obliged_ to move them.

**Comment by TomazErjavec** [comment]
I see! Well, so this fix was a bit useless, as the general guide is to move such elements as far up the tree as possible anyway, cf. second paragraph in [Transcriber comment](https://clarin-eric.github.io/ParlaMint/#sec-comments). But I will let it stand, there is not harm done if pb appears in a note..
