### ISSUE TITLE
members of other parliaments as speakers

### ISSUE THREAD

**Issue by lnnoemi** [clarin-eric/ParlaMint#296]
Hi All!
We could not find the right solution in the guidelines, but we might have just missed it, sorry: if we have a speaker who is a member of another country's parliament, and we have to list that parliament in the organisation's list, the role of that organisation has to be "parliament" - as it is for our own Hungarian parliament? Wouldn't it be a conflict later?
Sorry, if the question has been discussed earlier somewhere.

**Comment by matyaskopp** [comment]
Currently, we are not linking persons among different parliaments. The same human is stored multiple times in `<person>` element and different `xml:id`. If we decide to link these `person` elements in the future it will be possible.

The difficult question is how to handle organizations. I can see there are multiple problems:
- We have decided to encode two parliament organizations in bicameral systems. Do you have you have always the right information about the correct chamber affiliation?
- We claim, that if there are no `from` and `to` attributes the affiliation covers the same period as the corpus. So if you don`t fill in affiliation dates you can be in conflict with "country corpus data" (that are expected to be more precise). I can imagine that it can be solved by using the date of speech in `from` and `to` so you will fill the period of a smaller size than in "country corpus data".

I have a crazy idea of how to hack this but I will need @TomazErjavec independent opinion.
- don't add parliament  organization
- add a new element that will contain the country code, I am not sure which is better:
  - `<residence key="CZ"/>`  (this can cover regional)
  -  `<nationality key="CZ"/>` (MP should have country nationality - at least in CZ)

**Comment by matyaskopp** [comment]
> Sorry, if the question has been discussed earlier somewhere.

The question was not discussed, if I correctly remember. @hpreki  mentioned that it is a high possibility that president Zelenskyj will appear in multiple countries: https://github.com/clarin-eric/ParlaMint/issues/267#issuecomment-1172461795

So my suggestion of adding a person's residence or nationality seems relevant.

**Comment by hpreki** [comment]
I myself am notorious for making my life as developer harder than necessary, but I pray that we should not go over the top here. When I mentioned Zelenskyi in  #267 I did not mean that we need to make provisions for multi-parliament cross-linking. It only was to make a point that in my opinion "guest" does not automatically mean that a person is "unknown". 

If there was a speaker from another parliament in your protocols I just would mark it as `guest`.  That this person is a PM somewhere is a curious fact, but I do not think we should worry too much about it. 
As an example: _our_ most prominent guest-speaker is UN-secretary general Ban Ki Moon. I finally will tie his person-ID in ParlaMint-AT to some wikidata-URI but I _never_ would start putting the UN as organization into my taxonomy. Or South Korea (or New York? ) as  residence. The same of Zelenskyi: _if_ he would give a talk I would not start modelling the Ukraine-as-residence nor the Ukrainian Parliament nor the Ukrainian Government ... I would somewhere add  a reference to https://www.wikidata.org/wiki/Q3874799 and let it rest.

**Comment by matyaskopp** [comment]
> I would somewhere add a reference to https://www.wikidata.org/wiki/Q3874799 and let it rest.

Agree that linking persons with wikidata is probably the cleanest solution, but not everyone has wikidata link in the data. But this can be the motivation to add it.

With adding residence/nationality I wanted to avoid modelling of organizations outside the country.

**Comment by TomazErjavec** [comment]
> if there was a speaker from another parliament in your protocols I just would mark it as guest. That this person is a PM somewhere is a curious fact, but I do not think we should worry too much about it.

I couldn't agree more! I think we have a difficult enough job as it is, without worrying about encoding such edge cases. If we are really keen, we could see which names appear in more than one corpus towards the end of the project and maybe do something about it then - but probably not. 

> add a new element that will contain the country code, I am not sure which is better:
> `<residence key="CZ"/>` (this can cover regional)
> `<nationality key="CZ"/>` (MP should have country nationality - at least in CZ)

On the other hand, I have nothing against adding optional (and simple to encode!) metadata about speakers, so, @matyaskopp, if you would like to do this, pls. let me know and we add new elements to person. The above two options encode different info, so which one to use depends on the information one has - even if implicit, as is the case for CZ MPs. So, we could have both of them.

**Comment by matyaskopp** [comment]
> On the other hand, I have nothing against adding optional (and simple to encode!) metadata about speakers, so, @matyaskopp, if you would like to do this, pls. let me know and we add new elements to person. The above two options encode different info, so which one to use depends on the information one has - even if implicit, as is the case for CZ MPs. So, we could have both of them.

`residence` (and `nationality` probably too) are other elements that need `from` and `to` attribute as they can be changed over time. So I will not add in CZ data. 
On the other hand, I like the idea of having a link to wikidata for every person - I will at least try to add it in CZ data (I have to investigate how it works and how to avoid adding incorrect links).

I guess this issue can be closed now... @TomazErjavec , @hpreki
