### ISSUE TITLE
Possible typo in ParlaMint-TEI.ana.rng schema file

### ISSUE THREAD

**Issue by DimitrisGk-iel** [clarin-eric/ParlaMint#298]
Any chance that there is a missing end tag at this element?
https://github.com/clarin-eric/ParlaMint/blob/582a1922358a7f539777a326a3087a5ec5c2181a/Schema/ParlaMint-TEI.ana.rng#L53

**Comment by TomazErjavec** [comment]
Indeed yes! Thanks for noticing & sorry that I didn't, it doesn't do to be too much in a hurry...
Fixed in [4f6f6bc](https://github.com/clarin-eric/ParlaMint/commit/4f6f6bc2c248bd645a5e8612cb64affbd13fb773) (documentation branch)
