### ISSUE TITLE
Missing action for schema validation

### ISSUE THREAD

**Issue by RePierre** [clarin-eric/ParlaMint#3]
To make sure that the sample files are compliant with the schema we need to create and configure a GitHub action that will validate the files against the schema automatically.

**Comment by TomazErjavec** [comment]
Yes, that would be good. The current command how to validate the files is in the root Makefile, under "val", I hope this or something similar can be used also for the Git validation. 

I do not really know how the validations works and what options there are (could you point me to some simple documentation on when things are validated and what the consequences are?), but I guess some options will be better than others, so, another thing to decide.

**Comment by RePierre** [comment]
First I will setup an action that will run the commands from the `Makefile` afterwards we will see what can/needs to be improved.
