### ISSUE TITLE
<affiliation> to <org>: how to encode "president of republic"; "EU-commissioner" etc. ?

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#305]
I am compiling the affiliations of speakers and I am stumbling over cases like the President of the Republic and EU-commissioners. 

I am unsure on how to encode the respective `<org>`s which are required as `affiliation/@ref`

* **president of the republic:**
According to #245 we got rid of the `affiliation/@role="president"`  - so I would use  `affiliation/@role="head"` of the "Republic" instead. 
But  how would I encode  the "Republic of Austria"  in a `<org>`?
 Or more specifically what what kind of `org/@role` would you suggest for the/a republic/nation? 
I cannot spot any satisfying candidate in:
In https://clarin-eric.github.io/ParlaMint/#TEI.org 
(btw. there is `president` as possible `org/@role` - I suppose this should be removed?  ) 

 * **EU commissioner:**
 I would use  `affiliation/@role="member"` of the  EU-Commission. But same question here again: what's your suggestion on how to encode the `<org>`-entry for the EU-Commission?
 There is a possible `role`-value  `europeanParliament`. 
Would you consider adding another role `europeanCommission` ? Or  supply a more generic role `europeanInstitution` instead? 
(For the United Nations I am using `internationalOrganisations` (sic! Shouldn't it be singular?) which seems fair enough, but it seems awkward as role for  the EU Commission).

* **others ...**
We also have a talk by the president of the _Parliamentary Assembly of the Council of Europe (PACE)_, i.e. another `europeanInstitution` 
I would be happy to simply use `affiliation@role="head"` and dump the information about the  "president of PACE" into `affiliation/RoleName` but as far as I understand you want to enforce the use of `affiliation/@ref` which means I _do_ as well need a `<org>`-entry for PACE :-( 

As you can  see, I am very prone to going over the top when it comes to the level of details :-( 
So also any suggestion on how and when just _drop_ some information is  highly appreciated as well.

**Comment by TomazErjavec** [comment]
Thanks for these notes @hpreki. As regards `affiliation/@role`:
- I removed `president`, it was an oversight not to have done so before
- I changed `internationalOrganisations` to `internationalOrganisation`; @matyaskopp note that this change probably has to be included in v2tov3-affiliation.xsl (I tried to include this change there myself, but the code is too scary!)
- I added `europeanCommission` and `europeanInstitution`, I see no problem in having both, and you can have PACE so encoded.

The above changes are in 01afe03 (documentation branch) & are visible on https://clarin-eric.github.io/ParlaMint/#TEI.org.

What remains is how to encode "Republic of Austria" i.e. what `@role` to give it. I don't have any great idea here, will think on it, but if @matyaskopp has any ideas, and is not currently having a great time on holidays, I'd be glad to hear them!

**Comment by matyaskopp** [comment]
> What remains is how to encode "Republic of Austria" i.e. what @role to give it. I don't have any great idea here, will think on it, but if @matyaskopp has any ideas, and is not currently having a great time on holidays, I'd be glad to hear them!

**How it is encoded in ParlaMint-CZ 2.1 - `president`-role organization:**
```XML
               <org xml:id="president.PR" role="president">
                  <orgName full="yes" xml:lang="cs">Prezident republiky</orgName>
                  <orgName full="yes" xml:lang="en">The President of the Republic</orgName>
                  <orgName full="init">PR</orgName>
                  <event from="1998-01-20">
                     <label xml:lang="en">existence</label>
                  </event>
               </org>
```

```XML
                  <affiliation ref="#president.PR" role="president" from="2013-03-08T10:00:00"/>
                  <affiliation ref="#president.PR" role="member" from="2013-03-08T10:00:00"/>
```
I have encoded president as an organization because it can contain various members such as:
- head of the president's office
- various consultants
- the members of the 
  - press branch
  - protocol branch
  - ...

I think the `president` role can be changed into the `head` role in a `president`-role organization.


**`republic/nation`-role organization**
- Is it generally possible to say that the president/king/queen/emperor/... the head of the state? We can say that the president represents a republic...
- Do we want to use a general role for the state or the role that characterizes the state's constitution (republic, monarchy, ...)?

---

I do not have any final opinion on this. I have to think about it. I will get back to it later.

**Comment by matyaskopp** [comment]
> I changed internationalOrganisations to internationalOrganisation; @matyaskopp note that this change probably has to be included in v2tov3-affiliation.xsl (I tried to include this change there myself, but the code is too scary!)

@TomazErjavec, do we want to use British spelling? There is  internationalOrgani**z**ation in https://github.com/clarin-eric/ParlaMint/commit/01afe03789c60456a43d16923776bfb5c65edc72

It is only in CZ data - I will fix it on my side:
```XML
               <org xml:id="internationalOrganizations.CPSOBSE.1278"
                    role="internationalOrganizations">
                  <orgName full="yes" xml:lang="cs">Hlavní výbor pro demokracii, lidská práva a humanitární otázky PS OBSE</orgName>
                  <orgName full="init">CPSOBSE</orgName>
                  <event from="1993-01-01">
                     <label xml:lang="en">existence</label>
                  </event>
               </org>
```

**Comment by hpreki** [comment]
@matyaskopp : so your `president` in  `org/@role` is a feature not a bug? It still looks really strange to me!  I _always_ would view the president of the republic as a _natural person_ and not as an organisiation. 
My suggestion for encoding your special case -- the affiliations of persons from the president's working environment --  would be: 
define an organisation,  e.g. `presidential cabinet`, with `org@role="institution"`. 
E.g.  in AT we _do_ have an explitcit _Präsidentschaftskanzlei_ ( cf. https://en.wikipedia.org/wiki/Presidential_Chancellery ). 
(but we do not have any need to add any of this to our ParlaMint-data) 
i.e. 
```xml
               <org xml:id="institution.PresidentalOffice" role="institution">
                  <orgName full="yes" xml:lang="de">Präsidentschaftskanzlei</orgName>
                  <orgName full="yes" xml:lang="en">Presidential Chancellery</orgName>
                  <orgName full="init">PRO</orgName>
                  ... 
               </org>
               ... 
                 <!-- here we can argue whether the "head"-role for the Chancellery should be taken by the  "President of the Republic" or whether the head function is assigned to some "boss of the office"  --> 
                  <affiliation ref="#institution.PresidentalOffice" role="head" from="2013-03-08T10:00:00"/>
                  <affiliation ref="#institution.PresidentalOffice" role="member" from="2013-03-08T10:00:00"/>
```

**Comment by hpreki** [comment]
> **republic/nation-role organization**
>* Is it generally possible to say that the president/king/queen/emperor/... the head of the state? We can say that the president represents a republic...

I would guess it is fair to use the `head` as by all means the president in our constitution ( and I guess in many others ) is the _Staatsoberhaupt_  (`head of state` ). 
But using `@role=representative` is quite o.k for me as well, I do not really care. 

But what I think _is_ important, is an `org@role` for the state/republic/ :    
>* Do we want to use a general role for the state or the role that characterizes the state's constitution (republic, monarchy, ...)?

In my opinion _one_ general role for encoding a `state` would be sufficient, but again, I do not really care, as long as we do have _any_ means to somehow introduce  _States_ to our collection `<org>`s.

**Comment by TomazErjavec** [comment]
> @TomazErjavec, do we want to use British spelling? There is internationalOrganization in https://github.com/clarin-eric/ParlaMint/commit/01afe03789c60456a43d16923776bfb5c65edc72

Uh, yes, I guess we do. I have changed all "[Oo]rganization to "isation" in the schema and ODD in 5668d3e.

However, only after doing this, I thought to look at other occurnces of "organization", and it turns out we have quite a few in the root (plain + ana) files for all the corpora. One example is the legislative taxonomy:
https://github.com/clarin-eric/ParlaMint/blob/e98e335d1ccce52784d13b72759ddbb79adcb764/Data/ParlaMint-SI/ParlaMint-SI.xml#L152-L158

Another is the NER categories:
https://github.com/clarin-eric/ParlaMint/blob/e98e335d1ccce52784d13b72759ddbb79adcb764/Data/ParlaMint-SI/ParlaMint-SI.ana.xml#L444-L451

and there is lots of IDs (esp. in CZ) that also have "organization". So, maybe we should use "organization" after all, and revert to the previous commit @matyaskopp? Or, of course, add these cases to the fixings xlst...

**Comment by hpreki** [comment]
The issue on how to encode "Predient of the Republic" still is open. 

My proposal was  

> use `affiliation/@role="head"` of the "Republic" ...

Which leaves us with just the following question: 
> But how would I encode the "Republic of Austria" in a `<org>`?
Or more specifically what what kind of `org/@role` would you suggest for the/a republic/nation/country?

**Comment by TomazErjavec** [comment]
I ąbsolutely agree with `affiliation/@role="head"` and `org`. I am not sure if a republic = a nation = a country, so I would just concentrate on "republic", i.e. the president is the head of the republic, and we just add "republic" to the values of [org](https://clarin-eric.github.io/ParlaMint/#TEI.org). Does that sound ok?

**Comment by hpreki** [comment]
@TomazErjavec   "republic" as `org/@role` is perfectly o.k. for my purposes. 
( not sure what `org@role` democratic monarchies GB, DK, NL, BE ... would like prefer for representing  their kings/queens  :-) )

**Comment by TomazErjavec** [comment]
> @TomazErjavec "republic" as `org/@role` is perfectly o.k. for my purposes.

OK, added it in the latest commit to documentation branch, [32f168d](https://github.com/clarin-eric/ParlaMint/commit/32f168d1374180c038fad9937e574b495acbd67b). @matyaskopp, I guess this means you will have to change the `org/@role='president'` to `org/@role='republic'`.

> ( not sure what `org@role` democratic monarchies like GB, DK, NL, BE ... would prefer for representing their kings/queens :-) )

Well, just to be on the safe side, I also added "country" to the list of `org/@role` values. So the king/queen would be `person/affiliation[@role='head']` of `org[@role='country']` which, I think , makes sense.

Not sure what we will do with the presidents of autonomous regions such as Catalonia, as they are probably not a republic. Let us hope they don't have presidents, but only (the equivalent of) primer ministers.

Shall we close this issue, and make another one if necessary, or leave it open for e.g. possible problems with Catalonia and Basque country? Or others...

**Comment by hpreki** [comment]
I think we can close the issue for now.
