### ISSUE TITLE
Bugs in CZ + validaton with converion to vertical

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#31]
I have now modified my script that converts ParlaMint XML files to vertical files so that it can be used as further (semantic) validation of the corpora. It now produces some error messsages, and inspecting the structural attributes (there are as yet no tokens in the vertical files) can also reveal errors.

I ran it on the latest CZ data, problems:
```
ERROR: cannot find speaker for ParlaMint-CZ_2014-09-10_ps2013-016-01-001-001:AndrejBabis6150
ERROR: cannot find speaker for ParlaMint-CZ_2020-11-19_ps2017-070-01-001-001:JanBlatny6683
ERROR: cannot find speaker for ParlaMint-CZ_2020-11-19_ps2017-070-01-001-001:JanHamacek5462
...
```
15 such in sample; it's because the "#" is missing in the `u/@who`.
(link checker does not catch them, as AndrejBabis6150 is a legal reference to a local file named AndrejBabis6150).

The `<text>` element in the vertical looks like this:
```
<text id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000" subcorpus="Reference" term="ps2013" session="?" sitti\
ng="ps2013/016" from="2014-09-10" to="2014-09-10" title="Parliament of the Czech Republic, Chamber of Deputies">
```
Does this makes sense to you? Note that these attributes are the ones we had in V1, it might make sense to change them now, esp. session and sitting, depending also on what the other corpora will have.

And this is how a speech looked like before I modified the script:
```<speech id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000.u1" speaker_id="JanBartosek6178" speaker_name="Barto\
šek, Jan" speaker_role="chair" speaker_type="notMP" speaker_party="parliament.PSP7;ORGV;RRPNM;PNPUSV;SK;XNS;US\
;DE;HR;GB" speaker_party_name="Organizační výbor;Stálá komise pro rodinu, rovné příležitosti a národnostní men\
šiny;Podvýbor pro přípravu návrhů na propůjčení nebo udělení státních vyznamenání;Slovenská republika;Severské\
 státy (Švédsko, Finsko, Norsko, Dánsko, Island);Spojené státy americké;Spolková republika Německo;Chorvatská \
republika;Spojené království Velké Británie a Severního Irska" speaker_gender="M" speaker_birth="?">
```
Most attributes seem ok, except for speaker_party(_name), which is a complete mess:

In V1 we had a simple situation: 
https://github.com/clarin-eric/ParlaMint/blob/75fbf124c79a1826fc48a8d867b1c46a9661f8ff/ParlaMint-SI/ParlaMint-SI.xml#L530
and
https://github.com/clarin-eric/ParlaMint/blob/75fbf124c79a1826fc48a8d867b1c46a9661f8ff/ParlaMint-SI/ParlaMint-SI.xml#L412
So, a person could be a member of an organisation, and all the organisations were political parties. It was enough to check that they were a member on the date when they made their speech, and that is how the vertical file `text/@speaker_party` was computed.

In CZ you have many more organisations than just political parties. So I now check that a person has an affiliation with an `org[@role="politicalParty"]`, but in the first run this resulted in all speaker_party being empty.

The reason was that persons in CZ are also not "member"s of their political parties, like in V1 corpora, but "candidateMP"s, which I'm not sure what it means really (despite discussion in #16). Maybe you change back to member unless there are good reasons for keeping it so?

I then changed the script again, to just ignore the person's affiaition role. So, if somebody is affiliated to an organisation that is a political party, they are ipso facto their member. So, with this change, it now looks ok I think:
```
<speech id="ParlaMint-CZ_2020-11-19_ps2017-070-01-001-001.u23" speaker_id="PetrFiala6074" speaker_name="Fiala"\
 speaker_role="chair" speaker_type="MP" speaker_party="ODS" speaker_party_name="Občanská demokratická strana" \
speaker_gender="M" speaker_birth="?">
</speech>
```
And, just for fun, here are the stats on your speaker parties per speech:
```
     24 _       _
     36 ANO2011 ANO2011
     95 CSSD    Česká strana sociálně demokratická
     12 KSCM    Komunistická strana Čech a Moravy
     24 ODS     Občanská demokratická strana
     18 Piráti  Česká pirátská strana
     21 SPD     Svoboda a prima demokracie - Tomio Okamura
     28 TOP09   TOP 09
      1 Usvit   Úsvit přímé demokracie Tomia Okamury
`˙˙

The new script is coming along in the next commit.

**Comment by matyaskopp** [comment]
> 15 such in sample; it's because the "#" is missing in the `u/@who`.

fixed with https://github.com/ufal/ParCzech/commit/fe84b5614c86cba8311e4d44b73a23eb961fe3fb

> ` 
<text id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000" subcorpus="Reference" term="ps2013" session="?" sitti\
ng="ps2013/016" from="2014-09-10" to="2014-09-10" title="Parliament of the Czech Republic, Chamber of Deputies">
`
Does this makes sense to you? Note that these attributes are the ones we had in V1, it might make sense to change them now, esp. session and sitting, depending also on what the other corpora will have.

No, it does not. We don't use `session` -  we are using ` meeting` (`ps2013/016` is 16th meeting in term starting in 2013 https://www.psp.cz/eknih/2013ps/stenprot/016schuz/index.htm). This meeting consists of one sitting day `@sitting=ps2013/016/01`.

But there are meetings that consist of multiple sitting days: https://www.psp.cz/eknih/2013ps/stenprot/index.htm 
ie meeting `ps2013/26` consists of 10 sittings:
![image](https://user-images.githubusercontent.com/5867995/106591433-906f4d80-654e-11eb-813d-de8303dcfed9.png)

Furthermore, we added agenda items splitting - each topic is in a separate file... It makes sense because a single meeting topic can be discussed in multiple sittings(of the same meeting) and even multiple times in one sitting (Chairmen starts an agenda item but it appears that important person is not present. So he moved this topic to later hours of the same day)

> The reason was that persons in CZ are also not "member"s of their political parties, like in V1 corpora, but "candidateMP"s, which I'm not sure what it means really (despite discussion in #16). Maybe you change back to member unless there are good reasons for keeping it so?

`candidateMP` means that this person is listed in the election candidate list and is a member of parliament (has a seat there). It does not mean that he is a member of that political party. 

> ` <speech id="ParlaMint-CZ_2020-11-19_ps2017-070-01-001-001.u23" speaker_id="PetrFiala6074" speaker_name="Fiala"\
 speaker_role="chair" speaker_type="MP" speaker_party="ODS" speaker_party_name="Občanská demokratická strana" \
speaker_gender="M" speaker_birth="?">
</speech> `

I don't understand what is `speaker_type="MP"` means in speech -> you have replaced `regular` with `MP` ?

**Comment by TomazErjavec** [comment]
> No, it does not. We don't use session - we are using meeting ... that consist of multiple sitting days ... added agenda item.

Sorry, the "session" for a meeting was some weird remnant of V1, not sure why it was the way it was. Which of the above we should put in the vertical (ie. the concordancer) is a matter of discussion, but I would wait for the final decision till all samples are present, as here conventions in different countries differ considerably. For now I included all your divisions of meetings. 

Rather than pasting hard to read examples, I just added the verticals into your directory in 1c72c0e (and you can delete them anytime), pls. have a look if things look better now.

> I don't understand what speaker_type="MP" means in speech -> you have replaced regular with MP ?

speaker_type is either MP or notMP, while speaker_role is chair or regular (or, with some corpora, can also be also guest).

> candidateMP means that this person is listed in the election candidate list and is a member of parliament (has a seat there). It does not mean that he is a member of that political party.

This one is a killer. With other corpora (well, V1 anyway, and, as far as I understand with DK, IS as well) the idea was to have the information which party a speaker belongs to, as you can do interesting analyses, esp. if you group them into left/right.
I'm afraid I still don't understand how somebody can be listed in the election candidate list (of a party) but not be a member of that party, but that is probably just my ignorance in matters political.

For now, I will leave everything (in particular, the conversion to vertical as regards speaker_party) as it is, and would leave it up to you to decide how to solve this cunundrum. If you are otherwise happy with the verticals, pls. close this issue (= I didn't find any bugs in the new push), and can start the member vs. candidateMP in a new one.

**Comment by matyaskopp** [comment]
> Rather than pasting hard to read examples, I just added the verticals into your directory in 1c72c0e (and you can delete them anytime), pls. have a look if things look better now.

Yes...


> This one is a killer. ...

I have an example of Václav Klaus (the son of our former president), only relevant affiliations included:
```
          <person xml:id="VaclavKlaus6498">
            <persName>
              <surname>Klaus</surname>
              <forename>Václav</forename>
            </persName>
            <idno type="URI">https://www.psp.cz/sqw/detail.sqw?id=6498</idno>
            <sex value="M">mužské</sex>
            <affiliation ref="#parliament.PSP8" role="MP" from="2017-10-21"/>
            <affiliation ref="#politicalParty.ODS.155" role="candidateMP" from="2017-10-21"/>
            <affiliation ref="#politicalGroup.ODS.1295" role="member" from="2017-10-24T00:00:00" to="2019-03-17T00:00:00"/>
            <affiliation ref="#politicalGroup.Nezaraz.1500" role="member" from="2019-03-17T00:00:00"/>
          </person>
```
**Related parties and political groups:**
He was elected as a candidate of political party ODS
```
          <org xml:id="politicalParty.ODS.155" role="politicalParty">
            <orgName full="yes" xml:lang="cs">Občanská demokratická strana</orgName>
            <orgName full="yes" xml:lang="en">Civic Democratic Party</orgName>
            <orgName full="init">ODS</orgName>
            <event from="1900-01-01"><label xml:lang="en">existence</label></event>
          </org>
```
He joined to political group ODS in parliament
```
          <org xml:id="politicalGroup.ODS.1295" role="politicalGroup">
            <orgName full="yes" xml:lang="cs">Poslanecký klub Občanské demokratické strany</orgName>
            <orgName full="yes" xml:lang="en">Political group Civic Democratic Party</orgName>
            <orgName full="init">ODS</orgName>
            <event from="2017-10-24"><label xml:lang="en">existence</label></event>
          </org>
```
then he joined an independent MP group
```
          <org xml:id="politicalGroup.Nezaraz.1500" role="politicalGroup">
            <orgName full="yes" xml:lang="cs">Nezařazení</orgName>
            <orgName full="init">Nezařaz</orgName>
            <event from="2019-03-15"><label xml:lang="en">existence</label></event>
          </org>
```
Then he created a new political party "Trikolóra hnutí občanů" (2019-06-25), but there is no data of this event in the source data...

So the question is: What organization is relevant?
a **political party** or **political group** ( https://public.psp.cz/en/sqw/hp.sqw?k=193 )...

**Comment by matyaskopp** [comment]
just note:
> I'm afraid I still don't understand how somebody can be listed in the election candidate list (of a party) but not be a member of that party, but that is probably just my ignorance in matters political.

![image](https://user-images.githubusercontent.com/5867995/106643913-a995ef80-658a-11eb-9cdf-49ecc1720b31.png)

If all these candidates will be in parliament - they all would be affiliated with the same political party.

**Comment by TomazErjavec** [comment]
This was a fast close! I wanted to a) thank you for explaining this "for dummies" and b) maybe continue the discussion on

> So the question is: What organization is relevant? a political party or political group ( https://public.psp.cz/en/sqw/hp.sqw?k=193 )...

Although, it is true that what with so many corpora having a simplistic view of this, I'm not sure where we could move from where we are (so, maybe better for this issue to remain closed)!.

**Comment by TomazErjavec** [comment]
On second (or third) thoughts, I am reopening this issue, as we really haven't solved the underlying problem, so it is good it stays to remind us - for "further work" if nothing else.
But the title of this issue is not really informative, it would be ideal if it were called like "Problems with party affiliation" and the content had only parts that relate to this. @matyaskopp do you know any way how to achive this (short of opening a new issue and copying by hand the relevant parts)? Although maybe that would be worth doing to, as other issues address this, hm, issue.

**Comment by matyaskopp** [comment]
I have created an issue from the relevant comment...

Closing issue and let's move our discussion to #38
