### ISSUE TITLE
Bicameralism with two equal chambers

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#311]
I want to preserve a whole affiliation history of speakers (and members of parliament in corpus timespan). So I want to encode various `parliament` organizations when we were in the federation with Slovakia.

The main parliament organization that covered the whole federation was Federal Assembly (cs: Federální shromáždění, sk: Federálne zhromaždenie). It consisted of two houses: 

- Chamber of People (cs: Sněmovna lidu, sk:Snemovňa ľudu)
- Chamber of Nations (cs: Sněmovna národů, sk: Snemovňa národov)

The issue is that these chambers were equal. The passing of the law started in one of the chambers, and if accepted, it was processed by the second chamber then. There was no way of outvoting the second chamber (if I correctly understand this fundamental law: https://www.psp.cz/docs/texts/constitution_1968.html)

I am thinking about these three solutions:

1. Using `#parla.uni` for both organizations because it is somehow one organization split into two (there is not allowed member overlap). It suggest unicameralism even there are two chambers.
2. Using `#parla.bi` and set both chambers `#parla.lower`
3. Using `#parla.multi` and set both chambers `#parla.chamber`

I think the best solution is the 1st one, but I would like to know the second opinion(@hladkab, @TomazErjavec , @katjameden) before implementing this.

**Comment by matyaskopp** [comment]
currently(76e454e376c8a143bb3bf0d4e30d888fa8aa97a7) use (1) for encoding 

```XML
<org xml:id="chamberOfTheNations.FSSN" role="parliament" ana="#parla.national #parla.uni">...</org>
<org xml:id="chamberOfThePeople.FSSL" role="parliament" ana="#parla.national #parla.uni">...</org>
<org xml:id="nationalCouncil.CNR" role="parliament" ana="#parla.regional #parla.uni">...</org>
<org xml:id="parliament.PSP" role="parliament" ana="#parla.national #parla.lower">...</org>
<org xml:id="senate.SE" role="parliament" ana="#parla.national #parla.upper">...</org>
```

**Comment by TomazErjavec** [comment]
Um, it seems nobody had any comments here. I guess you did it the way you did it, and, in fact, this question might be beyond the scope of ParlaMint, so I will close it. Feel free to reopen, if you disagree!
