### ISSUE TITLE
check-content-XX : unexpected affiliation role

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#312]
When running "make check-content-IS" I get a lot of warnings of this kind:

WARN[15] ParlaMint-IS:16795 Invalid role 'substituteMP' - unexpected affiliation role with parliament organization in LenyaKarim affiliation [affiliation role="substituteMP" ref="#LV" from="2021-12-27" to="2022-06-06" ana="#LV.24 #const.Reyknesinga" /]

I don't see the reason for those warnings. Isn't "substituteMP" a valid role (it is according to the schema)?

**Comment by starkadur** [comment]
Thank you. I will then replace "substitueMP" with "replacement" and ignore those errors.

**Comment by TomazErjavec** [comment]
> oops, it shouldn't valid (https://github.com/clarin-eric/ParlaMint/issues/245#issuecomment-1138402807), but we (@TomazErjavec and @matyaskopp) haven't implemented it in schema.

My fault, I did not remove all old values in the previous fix. I did it now in https://github.com/clarin-eric/ParlaMint/commit/366862e6151824d489991edfea1866e6834410f4 (documentation branch), both in the RNG schema and in the ODD.

@matyaskopp, note that now the data in the data-v2tov3-fixings is not valid anymore - some CZ and IT `affiliation/@role` values need to be changed as per  https://github.com/clarin-eric/ParlaMint/issues/245#issuecomment-1138402807. Will you do this? I'd rather not mess with this branch, but if you want me to, pls. shout!

**Comment by matyaskopp** [comment]
@TomazErjavec, yes data-v2tov3-fixings branch is really out of date, I am now using data-XX branches in order to separate corpus-specific discussions with partners.
Do you want to use the data-v2tov3-fixings branch for validating schema? I don't need this branch anymore.

**Comment by TomazErjavec** [comment]
> Do you want to use the data-v2tov3-fixings branch for validating schema? I don't need this branch anymore.

Well, I do need some branch with V3 compatible data. But I am all in favour in having less branches. So, maybe the data branch would be appropriate. If, for some reason, not, then, yes, it would be nice to keep  data-v2tov3-fixings.
