### ISSUE TITLE
Event element in affiliation - error?

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#313]
I get an error when I include an event in an affiliation like:

`<affiliation role="minister" ref="#GOV_LV.44" from="2017-01-11" to="2017-11-30" ana="#mstr.landbunadur #mstr.sjavarutvegur"></affiliation>`

I want to express the fact that this person was a minister of agriculture (#mstr.landbunadur ) and fisheries (#mstr.sjavarutvegur)  in the **government referred to with the ID "#GOV_LV.44",** during the given period.

I this not the right way to do it?

**Comment by matyaskopp** [comment]
**event error**:
The person should be affiliated with organization(`GOV_LV`). If you want to add a term(`GOV_LV.44`) you can add it in `@ana`, so the correct encoding is (from data-IS branch):
https://github.com/clarin-eric/ParlaMint/blob/070759495b5349be0fd05eeaf27be08f69dedf8f/Data/ParlaMint-IS/ParlaMint-IS.xml#L11633-L11639

**`roleName`** is optional content - you have encoded ministers in categories which is cleaner.

**Comment by starkadur** [comment]
Thanks. I would actually have to have both "minister" and "member" as a role since I will get a new error if the role doesn't include a member since there is a reference to #GOV_LV.

**Comment by TomazErjavec** [comment]
>  I would actually have to have both "minister" and "member"
In this case & if I understand correct, the deal is that you have two affiliations, one for each role and with their appropriate attributes, cf. last paragraph of https://clarin-eric.github.io/ParlaMint/#sec-affiliation

**Comment by starkadur** [comment]
Yes, I will have to have two affiliations. I thought I might be able to have only one (with role = "member minister) since ministers are almost always also members of the parliament - but having two affiliations is cleaner and probably more correct.

**Comment by matyaskopp** [comment]
@starkadur,

> I thought I might be able to have only one (with role = "member minister)

We do not allow a list of roles as a value of `role` attribute in ParlaMint

> since ministers are almost always also members of the parliament

we are talking about affiliation with **government**, so the person with the minister role should be affiliated two times with the government (`minister` and  `member` role).

If the minister is also a member of parliament then affiliation with parliament organization should be included too.
