### ISSUE TITLE
Converting greek alphabet names into latin

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#320]
@TomazErjavec , you have encoded the Cyrillic alphabet names also in Latin in BG case:
https://github.com/clarin-eric/ParlaMint/blob/5e4fdd6d638bd22bbf121ffcb605cd76ebf952b4/Data/ParlaMint-BG/ParlaMint-BG.xml#L13-L14
https://github.com/clarin-eric/ParlaMint/blob/5e4fdd6d638bd22bbf121ffcb605cd76ebf952b4/Data/ParlaMint-BG/ParlaMint-BG.xml#L579-L589
with this script:
https://github.com/clarin-eric/ParlaMint/blob/5e4fdd6d638bd22bbf121ffcb605cd76ebf952b4/Scripts/fixings/v1tov2/v1tov2.xsl#L518-L562

Do we want to do this similarly in the GR case?

**Comment by TomazErjavec** [comment]
> Do we want to do this similarly in the GR case?
It would be nice of course! I have to admit I don't remember where I got the transliterations for bg from, so gr would have to be investigated.

**Comment by TomazErjavec** [comment]
Transliteration has been in the meantime implemented differently (#732) covering also Greek, so, closing this issue.
