### ISSUE TITLE
UD-SYN taxonomy

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#321]
The idea of common taxonomies is described in #264 
This issue is about implementing a script for creating UD syntactic relations.

### nesting relations
The current taxonomy is more like a list of relations:
https://github.com/clarin-eric/ParlaMint/blob/5e4fdd6d638bd22bbf121ffcb605cd76ebf952b4/Data/ParlaMint-SI/ParlaMint-SI.ana.xml#L537-L548
I think that relations can be nested. E.g. `flat:foreign` can be nested in `flat`. 
So the proper encoding of `flat` is:
```XML
<category xml:id="flat">
    <catDesc xml:lang="en"><term>flat</term>: Flat multiword expression</catDesc>
    <category xml:id="flat_foreign">
        <catDesc xml:lang="en"><term>flat:foreign</term>: Flat multiword expression: foreign</catDesc>
    </category>
    <category xml:id="flat_name">
        <catDesc xml:lang="en"><term>flat:name</term>: Flat name</catDesc>
    </category>
</category>
```
Does this make sense for all relations?

### What is the best source for creating taxonomy?

**all** relations: https://universaldependencies.org/u/dep/all.html
does not seem to be a complete list of all possible relations

For **extended** relation, I have found this page with links: https://universaldependencies.org/ext-dep-index.html
It contains two types of links:
1. universal: https://universaldependencies.org/u/dep/flat-foreign.html has `/u/` in the URL
2. language-specific: https://universaldependencies.org/hy/dep/flat-dist.html, which contains `/<LANGCODE>/` of alphabetically first language

### Are URLs to relation documentation persistent?
I have an idea for extending the schema with `category/@source` but I want to be sure that the URLs do not change.
```XML
    <category xml:id="flat_foreign" @source="https://universaldependencies.org/u/dep/flat-foreign.html">
        <catDesc xml:lang="en"><term>flat:foreign</term>: Flat multiword expression: foreign</catDesc>
    </category>
```
### Do every relation have a separate web page?
It seems that they have got (except the red ones).

### Documentation versioning
The TEI schema can also be extended with the `taxonomy/bibl` element. 
The question is how to handle versioning. 
- How often does documentation change?
-  Should I care about versioning, or can I use just version 2?

### xml:id
preserve the existing idea of translating terms into IDs with `tr/:/_/` (due to technical issues with `:`).

@TomazErjavec and  @dan-zeman, can you please review this issue and give me feedback?

**Comment by dan-zeman** [comment]
> I think that relations can be nested. E.g. `flat:foreign` can be nested in `flat`.

True. Do you want to cover both basic and enhanced UD representation, or only basic? For basic, there is at most one level of nesting, i.e., one colon delimiting the main type and subtype. For enhanced UD it is more complex.

The subtypes are technically language specific, although some of them, such as `flat:foreign`, are used in many languages and have a global documentation page. But the list of subtypes is not fixed and any language can define a subtype that is not used anywhere else — as long as it is a subtype of a universal relation.

> Are URLs to relation documentation persistent?

They are not guaranteed to be persistent, although we try to keep them relatively stable. Also, some of the UD infrastructure now depends on where the doc pages are and how they are named, which is a further factor against changes (but here we are talking about paths within the `docs` repository on Github, which is not necessarily the same thing as the URL on the final rendering of the UD website).

> Do every relation have a separate web page?

Every main relation type (without a colon) of the basic UD representation has its own page in the universal guidelines, plus optionally a separate page in some language-specific documentation sets.

Every subtype (with a colon) used in the basic UD representation must have either a global documentation page, or a language-specific page for the language where the subtype is used, or both.

Relation labels that are used in enhanced UD but not in basic UD generally do not have their pages. Except for `ref`, they are always subtypes of a relation defined in basic UD. They can contain up to three colons. The enhanced guidelines are less stable, so this may change in the future.

> * How often does documentation change?
> * Should I care about versioning, or can I use just version 2?

Documentation can change. Small clarifications can be added at any time. Significant changes of how the relations are used are announced roughly at the time when a new UD release gets out, so the release numbering could be used (see [here](https://universaldependencies.org/changes.html)). The list of the 37 main types will not change (i.e. the labels themselves, not the details about their usage) as long as we have UD v2 guidelines. Adding, removing or renaming a main relation type would require UD v3.

**Comment by matyaskopp** [comment]
@dan-zeman, thanks for your response.

>  Do you want to cover both basic and enhanced UD representation, or only basic?

I want to encode all relations, even those relations that are not used in the languages of ParlaMint corpora.

| They are not guaranteed to be persistent, although we try to keep them relatively stable.

OK, I will not embed backlinks in the taxonomy.

> ## What is the best source for creating taxonomy?

Does it make sense to convert  https://universaldependencies.org web into the taxonomy?

or is this harvesting procedure better?
1. add to taxonomy all relations listed in this folder: https://github.com/UniversalDependencies/docs/tree/pages-source/_u-dep
2. add language-specific relations listed in these folders (if not in "the universal folder"):
    - https://github.com/UniversalDependencies/docs/tree/pages-source/_[a-z]{2,3}/dep
    - ie for Czech: https://github.com/UniversalDependencies/docs/tree/pages-source/_cs/dep

**Comment by dan-zeman** [comment]
> > Do you want to cover both basic and enhanced UD representation, or only basic?
> 
> I want to encode all relations, even those relations that are not used in the languages of ParlaMint corpora.

The enhanced UD representation currently allows up to three subtypes for some relations, e.g. `obl:arg:na:acc`. The third segment in this example is a preposition lemma, so it may contain e.g. Chinese characters. Some relevant documentation is [here](https://universaldependencies.org/u/overview/enhanced-syntax.html#case-information). Valid prepositional labels should be documented (but they aren't for all languages yet), examples can be seen [here](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_edeprel.pl?lcode=cs).

> Does it make sense to convert https://universaldependencies.org web into the taxonomy?

If it is supposed to mean something else than the procedure below, then I don't know what it is supposed to mean.
 
> or is this harvesting procedure better?
> 
> 1. add to taxonomy all relations listed in this folder: https://github.com/UniversalDependencies/docs/tree/pages-source/_u-dep
> 2. add language-specific relations listed in these folders (if not in "the universal folder"):
>    
>    * [https://github.com/UniversalDependencies/docs/tree/pages-source/_[a-z]{2,3}/dep](https://github.com/UniversalDependencies/docs/tree/pages-source/_%5Ba-z%5D%7B2,3%7D/dep)
>    * ie for Czech: https://github.com/UniversalDependencies/docs/tree/pages-source/_cs/dep

Sounds reasonable. As I said before, this will only give you relations that can occur in the basic UD trees (the DEPREL column). Additional relations can occur in the enhanced UD graphs (the DEPS column) and you will not learn about them this way. You should be prepared to re-run the procedure after every UD release.

As you probably already know, if a relation label contains a colon, its corresponding file will contain a hyphen instead. Also, the `aux` relation's file cannot be `aux.md` because of stupid Microsoft limitations, so it is `aux_.md` instead.

Having a correspondingly named file in either .../_u-dep or .../$LANGCODE/dep is a necessary condition for the label to be valid and thus accepted in the released data, but it's not a sufficient condition. For example, the Vietnamese team recently documented `acomp` and used it in their (dev branch) data but the data is not valid and will not be released in this state because `acomp` is neither a universally defined relation nor a subtype of a universally defined relation. Also, a language-specific doc folder may contain outdated files that document relations that are no longer used in the treebanks of the language.

**Comment by matyaskopp** [comment]
@TomazErjavec, the common UD-SYN taxonomy is here: 
https://github.com/clarin-eric/ParlaMint/blob/devel/Data/Taxonomies/ParlaMint-taxonomy-UD-SYN.xml

I have added to the comments lists of languages where the taxonomy is used, but I can remove it.
The taxonomy contains all relations described in https://github.com/UniversalDependencies/docs

**Comment by TomazErjavec** [comment]
I had a look, and it looks very nice indeed! The only thing I would change is give some more info on the taxonomy, e.g.
```
 <desc xml:lang="en"><term>UD syntactic relations</term>: All defined syntactic relations of the <ref target="https://universaldependencies.org/">Universal Dependendencies</ref> project</desc>
```
I would leave in the comments, they don't hurt but give nice additional info.

**Comment by matyaskopp** [comment]
@TomazErjavec, I have added the info. 
There appeared one more issue. Various languages contain a different descriptions of the same relation. 
 - when common relation exists, I always use a common description
 - when the relation is language specific - a random description is chosen. (we prefer the best description...)
   - Should I implement some sort of statistics on which description is the most common, and if the number is equal, then use a longer one?

**Comment by TomazErjavec** [comment]
> Various languages contain a different descriptions of the same relation.

Wow. Scary.

> Should I implement some sort of statistics on which description is the most common, and if the number is equal, then use a longer one?

I guess. At least I can't think of a better heuristic. 
This is a bit similar to our problem with different translations into nl by BE nad NL...

**Comment by matyaskopp** [comment]
@TomazErjavec, the taxonomy now contains _the best_ description, and some relations are pruned (when the filename does not correspond the title)
The errors are not in ParlaMint languages, so the taxonomy should work for our case.

---
@dan-zeman, just for your info, the script's log output shows some inconsistencies/bugs in the documentation:
```
ERROR: title 'acl:relcl' does not match filename _urj/dep/acl.md
ERROR: title 'obl:lmp' does not match filename _myv/dep/advmod-lmp.md
ERROR: title 'appos:' does not match filename _tt/dep/appos.md
WARN: strange characters in title 'aux:ex'='<0x61><0x75><0x78><0x3A><0x435><0x445> in _hyw/dep/aux-ex.md'
WARN: strange characters in title 'aux:ex'='<0x61><0x75><0x78><0x3A><0x435><0x445> in _hy/dep/aux-ex.md'
INFO: replacing characters in title 'case affix' to make term 'case:affix' _bej/dep/case-aff.md
ERROR: title 'case:affix' does not match filename _bej/dep/case-aff.md
ERROR: title 'compound:pron' does not match filename _vi/dep/compound-redup.md
ERROR: title 'compound:redup' does not match filename _bej/dep/dep-redup.md
INFO: replacing characters in title 'discourse-emo' to make term 'discourse:emo' _pl/dep/discourse-emo.md
ERROR: title 'expl' does not match filename _it/dep/expl-poss.md
INFO: replacing characters in title 'flat-foreign' to make term 'flat:foreign' _kpv/dep/flat-foreign.md
ERROR: title 'flat:range' does not match filename _hyw/dep/flat-frac.md
ERROR: title 'nmod' does not match filename _hu/dep/nmod-obl.md
ERROR: title 'nmod:dup' does not match filename _cy/dep/nmod-redup.md
ERROR: title 'nsubj' does not match filename _vi/dep/nsubj-pass.md
ERROR: title 'dobj' does not match filename _gsw/dep/obj.md
ERROR: title 'dobj' does not match filename _de/dep/obj.md
ERROR: title 'dobj' does not match filename _vi/dep/obj.md
ERROR: title 'dobj' does not match filename _el/dep/obj.md
ERROR: title 'dobj' does not match filename _et/dep/obj.md
ERROR: title 'obl:comp' does not match filename _vi/dep/obl-about.md
ERROR: title 'obl:comp' does not match filename _kpv/dep/obl-cmp.md
ERROR: title 'nmod:lmod' does not match filename _sms/dep/obl-lmod.md
INFO: replacing characters in title 'NP-related object' to make term 'NP:related:object' _tpn/dep/obl-obj.md
ERROR: title 'NP:related:object' does not match filename _tpn/dep/obl-obj.md
INFO: replacing characters in title 'NP-related object' to make term 'NP:related:object' _gn/dep/obl-obj.md
ERROR: title 'NP:related:object' does not match filename _gn/dep/obl-obj.md
ERROR: title 'oblique' does not match filename _gd/dep/obl.md
ERROR: title 'oblique' does not match filename _no/dep/obl.md
ERROR: title 'oblique' does not match filename _ga/dep/obl.md
ERROR: title 'parataxis:coord' does not match filename _bej/dep/parataxis-mod.md
```

**Comment by TomazErjavec** [comment]
> @TomazErjavec, the taxonomy now contains the best description, and some relations are pruned (when the filename does not correspond the title)

Great, thank you. So I guess we can close this, unless there are further things to do here (but I don't think so).
