### ISSUE TITLE
Transcriber's comments (pause tag)

### ISSUE THREAD

**Issue by marilinapisani** [clarin-eric/ParlaMint#323]
I noticed that the "pause" label is not included in the schema (maybe I'm missing something)

It would be useful in our corpus since the participants make pauses and this phenomenon has been transcribed. We are encoding now with the "note" element, but ["pause" ](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/TS.html#TSBAPA) would be more accurate. Has anyone encountered the same issue?

Example:
```
<seg xml:id="ParlaMint-ES-CT_2018-01-17-0101.16.5" xml:lang="ca">Gràcies.</seg>
<note>(Pausa.)</note>
<seg xml:id="ParlaMint-ES-CT_2018-01-17-0101.16.6" xml:lang="ca">Som-hi; endavant, senyora Ribas.</seg>               
```

**Comment by matyaskopp** [comment]
At the first sight it sounds reasonable to add `<pause>` element, but there is one important difference between `<pause>` and the phenomena that we currently encode: 5.3.2. Incidents: [`<vocal>`, `<kinesic>`, `<incident>`](https://clarin-eric.github.io/ParlaMint/#sec-incident)
All of these elements can contain `<desc>` element with a description in the language of the corpus but `<pause>` element does not allow any content in TEI. So it will cause this pause will not appear in the concordancers (unless @TomazErjavec implement it in conversion).  

There is an example in ParlaMint documentation which encodes **active silence**, which is not this situation:
```XML
<incident type="action">
 <desc>minute of silence</desc>
</incident>
```

But I guess we can add a new `type` attribute value:
```XML
<incident type="pause">
 <desc>Pausa.</desc>
</incident>
```

**Comment by marilinapisani** [comment]
Thanks @matyaskopp. Your alternative seems good to me, since the `<incindent>` tag seems broad enough to include this type of phenomena.

**Comment by matyaskopp** [comment]
@TomazErjavec 
Can you please add `pause` as a new `incident/@type` value in the schema and documentation?

Current values in the schema are:
https://github.com/clarin-eric/ParlaMint/blob/560609d3ee9bb463a125281811e21b1b8d73cd9b/Schema/ParlaMint-TEI.rng#L552-L572

I believe that `pause` is a different phenomenon from `break`. The `break` is somehow organized for all MPs, but `pause` means that a particular speaker stops speaking for a while.

**Comment by TomazErjavec** [comment]
> @TomazErjavec Can you please add pause as a new incident/@type value in the schema and documentation?

Done!
