### ISSUE TITLE
Failed pull request validation

### ISSUE THREAD

**Issue by cluljoseaires** [clarin-eric/ParlaMint#331]
#330 

I fail to see which file has more than 100MB, as pointed out in the failed verification log. According to my local copies, the largest one has 20MB of size.

Trying to solve this issue becomes even more difficult as all the tests where successful, both locally and on github, to the point where I was allowed to make the pull request.

Perhaps it could be possible to update Java and/or increase the memory available on your side to run the tests.

Any tips are welcome to fix my failed verification test.

**Comment by matyaskopp** [comment]
the total size of your corpus is 5306 MB: https://github.com/clarin-eric/ParlaMint/runs/8178813844?check_suite_focus=true#step:4:33

You are allowed to upload only 100 MB. Please remove some files (to reduce the sample to approximately 80MB to be sure that it passes the limit) from git and xincludes from root XML files.

**Comment by matyaskopp** [comment]
clossing - discussion continue here: #330
