### ISSUE TITLE
PT: feedback

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#332]
This issue tries to summarize changes that are needed to be done to have better metadata in PT corpus. (commit 94489ada469c2ea1f548c911f65fcca85c680ec4)

Firstly I want to note that if the corpus is valid, then it should pass all validations (if there is not a bug in the validation script). But the opposite implication is not true! So **passing validation doesn't necessarily mean that the corpus is valid.**

### person name
- [x] `persName/term`

You use `term` element in `persName`:
```bash
java -cp /usr/share/java/saxon.jar net.sf.saxon.Query -xi:off \!method=adaptive \
            -qs:'//*[local-name()="persName"]/*/local-name()' \
            -s:Data/ParlaMint-PT/ParlaMint-PT.xml \
            | sort | uniq -c
    723 "term"
```

The `term` is meant to be used if every other option fails: https://clarin-eric.github.io/ParlaMint/#TEI.persName
> **Note**	Special persons (like 'anonymous', 'group' etc.) have their name in `<term>`.

So the correct encoding of person's name is to use `forename` and `surname` in `listPerson/person` context

### affiliation roles

```bash
java -cp /usr/share/java/saxon.jar net.sf.saxon.Query -xi:off \!method=adaptive \
            -qs:'//*[local-name()="affiliation"]/@role' \
            -s:Data/ParlaMint-PT/ParlaMint-PT.xml \
            | sort | uniq -c
   2386 role="member"

```

You use only `member` role in affiliations. there is no `minister` or `head` role. I guess you have at least `minister` role information because there are affiliations with government. Remember that if someone is affiliated with `minister` role one should be also affiliated with `member` role for same period as well: https://clarin-eric.github.io/ParlaMint/#sec-affiliation
> An important point to note is that ParlaMint makes no assumptions on the interconnection between various roles, e.g. we do not assume that if somebody has a minister role in the government that they are also a member of the government. Therefore it is necessary to specify all the desired affiliations with their particular roles, e.g. both as minister and as member.

- [x] `affiliation/@role`

### taxonomies

- [x] `taxonomy`

There are taxonomies that I don't understand, ie:
https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L127-L145
```XML
                <taxonomy xml:id="parla.legislature">
                    <desc xml:lang="en">
                        <term>Legislature</term>
                    </desc>
                    <category xml:id="XII">
                        <catDesc>
                            <term />
                        </catDesc>
                    </category>
                    <category xml:id="XIII">
                        <catDesc>
                            <term />
                        </catDesc>
                    </category>
                    <category xml:id="XIV">
                        <catDesc>
                            <term />
                        </catDesc>
                    </category>
```

You are supposed to take common taxonomies and translate them into the corpus language. You can start with taxonomies from SI corpus:https://github.com/clarin-eric/ParlaMint/blob/5e4fdd6d638bd22bbf121ffcb605cd76ebf952b4/Data/ParlaMint-SI/ParlaMint-SI.ana.xml#L117-L125

We will then merge (on `@xml:id` attribute) these translations into one common taxonomy (https://github.com/clarin-eric/ParlaMint/issues/264)

### meeting element
- [x] `meeting`
https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L8
```XML
                <meeting ana="#parla" />
```

`meeting` elements do not provide enough information. See examples: https://clarin-eric.github.io/ParlaMint/#TEI.meeting
Also component files need fixings

### `setting` (and also `bibl` )in component files
- [x] `setting`

`setting` in a component file should describe the content of the component file, not the whole corpus: https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT_darl12sl04n034-07-01-2015.xml#L68

for this file `ParlaMint-PT_darl12sl04n034-07-01-2015.xml` it should be
```XML
				<setting>
					<name type="address">Alameda da Universidade, 1600-214 Lisboa, Portugal</name>
					<name type="city">Lisboa</name>
					<name type="country" key="PT">Portugal</name>
					<!--BUG: <date from="2015-11-06" to="2020-08-18">06.11.2015 - 18.08.2020</date> -->
					<date when="2015-01-07">07.01.2015</date>
				</setting>
```

### corpus timespan (end)

- `settingDesc`: https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L386
```XML
                    <date from="2015-11-06" to="2020-08-18">06.11.2015 - 18.08.2020</date>
```

- last parliament event: https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L408-L410
```XML
                            <event xml:id="L.XIV" from="2019-10-25" to="2022-03-28">
                                <label xml:lang="pt">XIV Legislatura</label>
                            </event>
```

- last government: https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L426-L428
 ```XML
                            <event xml:id="Gov.XXII" from="2019-10-26" to="2022-03-29">
                                <label xml:lang="pt">XXII Governo Constitucional de Portugal</label>
                            </event>
 ```

- `sourceDesc/bibl`: https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L49
```XML
                    <date from="2015-01-07" to="2022-01-06">07.01.2015 - 06.01.2022</date>
```

- last file in your full data
```XML
<ns:include xmlns:ns="http://www.w3.org/2001/XInclude" href="ParlaMint-PT_darl14sl03n038-22-03-2022.xml" />
```

- `title`: https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L7
```XML
                <title xml:lang="en" type="sub">Minutes of the Assembleia da República Portuguesa (2015-2020)</title>
```

I believe that at least `settingDesc` should correspond to the corpus timespan: (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-settingDesc.html)
> `<settingDesc>` (setting description) describes the setting or settings within which a language interaction takes place, or other places otherwise referred to in a text, edition, or metadata. [[15.2 Contextual Information](https://tei-c.org/release/doc/tei-p5-doc/en/html/CC.html#CCAH) [2.4 The Profile Description](https://tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD4)]

### affiliation of dead person
https://github.com/cluljoseaires/ParlaMint/blob/94489ada469c2ea1f548c911f65fcca85c680ec4/Data/ParlaMint-PT/ParlaMint-PT.ana.xml#L1109-L1120
```XML
                    <person xml:id="AntónioAndrédaSilvaTopa">
                        <persName>
                            <term>António André da Silva Topa</term>
                        </persName>
                        <sex value="M" />
                        <birth when="1954-09-02" />
                        <death when="2021-10-31" />
                        <affiliation role="member" ref="#PSD" />
                        <affiliation role="member" ref="#GrupoParlamentardoPsd" />
                        <affiliation role="member" ref="#AR" from="2015-10-23" to="2019-10-24" />
                        <affiliation role="member" ref="#AR" from="2019-10-25" to="2022-03-28" />
                    </person>
```

**Comment by amamendes** [comment]
Thanks Matyás, we're going to look into it.

**Comment by cluljoseaires** [comment]
Thank you so much for your tips. I already suspected the validation process would not be enough to have a finished product, but at least we have that out of the way.

Considering your observations, I believe I can fix the issues relatively easily since I already have the data in the cases where it is missing. I did not include it simply because I forgot after so many iterations to make the tests iteratively pass in this overwhelming task.

Once I have taken care of the issues, I will do another pull request.

**Comment by matyaskopp** [comment]
> Considering your observations, I believe I can fix the issues relatively easily since I already have the data in the cases where it is missing. I did not include it simply because I forgot after so many iterations to make the tests iteratively pass in this overwhelming task.

I am glad to hear that it wouldn't be a big issue.

I have one more observation:
### `bibl` link
- [ ] link in bibl in component files

It would be great to have a direct link to transcription in component files. You have one common link for all files, but it is better to use the real source of data. 

You can check CZ data, where I am preserving a lot of link types 
- `bibl/idno`
- `pb/@source`
- `u/@source`

**Comment by amamendes** [comment]
Thanks for the feedback.

We have another question about the Portuguese data.
During the tokenization, we decided to keep the frequent contractions in Portuguese and not to expand them. This is the same decision we took for the Reference Corpus of Contemporary Portuguese, and the reason is that expanding the contractions makes it difficult for users to read the text. 
To deal with this, we use composite POS tags. For instance, the contraction of a preposition+determiner (e.g, "no") is kept as such and is  labelled with the tag "ADP+DET". We see that this is not accepted during validation. Could composite tags be integrated in ParlaMint?

**Comment by cluljoseaires** [comment]
Neither 'republic' nor 'president' are allowed as 'presidency org role', which is why I chose 'institution', before your observation.

`error: value of attribute "role" is invalid; must be equal to "boardOfDirectors", "boardOfParliament", "chamberOfTheNations", "chamberOfThePeople", "coalition", "commission", "committee", "conferenceOfChairs", "delegation", "ethnicCommunity", "europeanCommission", "europeanInstitution", "europeanParliament", "government", "institution", "internationalOrganisation", "interparliamentaryFriendshipGroup", "nationalCouncil", "ngo", "parliament", "parliamentaryGroup", "politicalParty", "senate", "subcommittee", "supervisoryBoard" or "workingGroup"`

By the way, I did a pull just to make sure there were no missing updates on my side.

**Comment by matyaskopp** [comment]
> By the way, I did a pull just to make sure there were no missing updates on my side.

My fault, it was in the documentation branch, which is now synced with the data branch: https://github.com/clarin-eric/ParlaMint/pull/356

**Comment by cluljoseaires** [comment]
About the political orientation:

`<org xml:id="PSD" role="politicalParty">
    <orgName xml:lang="pt" full="yes">Partido Social Democrata</orgName>
    <orgName xml:lang="pt" full="abb">PSD</orgName>
    <event from="1974-04-25">
        <label xml:lang="en">existence</label>
    </event>
    <state type="politicalOrientation" subtype="unknown" ana="#orientation.CR">
        <note xml:lang="en">Orientation determined by encoder, using own knowledge of the parliamentary group.</note>
    </state>
</org>`

I get the following:

`error: element "state" not allowed anywhere; expected the element end-tag or element "desc", "event", "idno" or "listEvent"`

Perhaps I am missing something...

**Comment by matyaskopp** [comment]
@TomazErjavec, can you please clarify this https://github.com/clarin-eric/ParlaMint/issues/332#issuecomment-1271491379 ?

**Comment by cluljoseaires** [comment]
I was trying to include the party political orientation using the first case of [https://clarin-eric.github.io/ParlaMint/#sec-parties](https://clarin-eric.github.io/ParlaMint/#sec-parties)
````
<org xml:id="PSD" role="politicalParty">
    <orgName xml:lang="pt" full="yes">Partido Social Democrata</orgName>
    <orgName xml:lang="pt" full="abb">PSD</orgName>
    <event from="1974-04-25"><label xml:lang="en">existence</label></event>
    <state type="politicalOrientation" subtype="unknown" ana="#orientation.CR">
        <note xml:lang="en">Orientation determined by encoder, using own knowledge of the parliamentary group.</note>
    </state>
</org>
````
but I get the «element "state" not allowed anywhere» error mentioned in my previous post.

**Comment by matyaskopp** [comment]
your branch is not up to date: https://github.com/cluljoseaires/ParlaMint/pull/1

**Comment by cluljoseaires** [comment]
Indeed, I needed to merge the main branch into the data branch... Sorry. I now need a taxonomy for the political orientations. Any tips would be welcome. ;)

**Comment by TomazErjavec** [comment]
@cluljoseaires, it is actually a bit premature that you would start adding political orientation. Cf. [this comment](https://github.com/clarin-eric/ParlaMint/issues/184#issuecomment-1267265564), esp. the G'doc mentioned there. We are doing it via TSV files, which we first produce automatically, and then they need to be edtied, so we get the CHES orientations for free. So, let's wait untill the corpora are submitted, and they we can generate the TSVs, and these edited, and then we can automatically add their content to the TEI.

**Comment by matyaskopp** [comment]
- [ ] application descriptions and labels are nice but they misses a `@xml:lang="en"` attribute
- [ ] there is still a big issue in taxonomies. You are supposed to use common taxonomies (`NER`, `speaker_types`, `subcorpus`, `parla.legislature`) and add to them a pt translation. #264 
as for the `ud-syn` taxonomy, I am planning to create one common taxonomy (#321) for all possible languages in universal dependencies, so if you did not make changes in ids (= id corresponds to a term and the colon is replaced with an underscore), there shouldn't be a problem with embedding this complete taxonomy in your corpus - you don't need to care about it.
- [ ] `langUsage` element - documented here: https://clarin-eric.github.io/ParlaMint/#sec-langUsage

**Comment by matyaskopp** [comment]
ok, closing issue

**Comment by matyaskopp** [comment]
I am sorry I have been too rush with closing this issue...

### Wrong meeting annotations in component files
- [ ] `meeting` -> `session`,`meeting`, `sitting`

https://github.com/cluljoseaires/ParlaMint/blob/5e8a2d87fb8a02db9d01da513942234aa226690f/Data/ParlaMint-PT/ParlaMint-PT_2015-01-07.xml#L7
```XML
 <meeting ana="#parla.term #L.XII" n="s.4/n.34">Série I - XII Legislatura - Sessão 4 - Número 34</meeting>
```
@TomazErjavec's suggestion:
```XML
<meeting ana="#parla.term #L.XII" #parla.uni" n="I/XII>Série I - XII Legislatura</meeting>
<meeting ana="#parla.session #parla.uni" n="4">Sessão 4</meeting>
<meeting ana="#parla.meeting #parla.uni" n="34">Número 34</meeting>
```
and add please `#parla.sitting` if it makes sense (I believe it does). You can use date for `text()` and `@n`

### Component file `/TEI/@ana`
- [ ] `/TEI/@ana`

Please use the correct classification that specifies the content of the file `#parla.meeting` or `#parla.sitting`. Greek sample:
https://github.com/clarin-eric/ParlaMint/blob/a7c867f644b84269a30a818363fb4ec650ed3fff/Data/ParlaMint-GR/ParlaMint-GR_2015-02-06-S1-commons.xml#L1-L6

### component file title 
- [ ] unique title
- [ ] missing pt translation

https://clarin-eric.github.io/ParlaMint/#sec-titleStmt
> The title statement starts with two titles (one main, the other subordinate), both in English and the local language, with the appropriate language code possibly inherited from a superordinate element. ...
> ... Both titles must be unique in the complete corpus.
 
Your title is not unique because you have 111 titles and 702 component files.

**Comment by cluljoseaires** [comment]
Thank you for the notes. I am just intrigued by the 702 files because they were supposed to be 704, but above all I am really confused by the 111 titles. Obviously, I need to do some checking...

**Comment by cluljoseaires** [comment]
As I suspected, the issue with the number of files had to do with the fact that some files had incorrectly repeated dates, which was masked by the remainder elements present in the filename.

**Comment by cluljoseaires** [comment]
I have addressed all of your notes and I believe the documents are substantially better but tell me if you need improvements.

**Comment by matyaskopp** [comment]
There is one issue left:
> ### component file title
> * [ ]  unique title

@TomazErjavec, can support my interpretation that both titles (`title[@type='main']` and `title[@type='sub']`) must be unique?
Both titles mean (`main` and `sub`) in both/all languages (`lang=en` and `lang=xx`)
> In the example it can be seen that the main title of a corpus component is simply an extension of the corpus root title, as it also gives the name of the particular meeting that the component contains, while the subordinate title is, again, free text. Both titles must be unique in the complete corpus.

I believe that this example is misleading: (https://clarin-eric.github.io/ParlaMint/#sec-titleStmt)
```XML
<titleStmt>
 <title type="main">Slovenski parlamentarni korpus ParlaMint-SI, izredna seja 59 [ParlaMint]</title>
 <title type="main" xml:lang="en">Slovenian parliamentary corpus ParlaMint-SI, Extraordinary Session 59 [ParlaMint]</title>
 <title type="sub">Zapisi sej Državnega zbora Republike Slovenije, 7. mandat, 59. izredna seja, 13.4.2018</title>
 <title type="sub" xml:lang="en">Minutes of the National Assembly of the Republic of Slovenia, Term 7, Extraordinary Session 59, 13.4.2018</title>
```
because `Slovenski parlamentarni korpus ParlaMint-SI, izredna seja 59 [ParlaMint]` doesn't look like a unique title.

**Comment by cluljoseaires** [comment]
Given that @TomazErjavec has sent me a message saying everything was fine except for some notes having trailing spaces, I assume the example is acceptable.

**Comment by TomazErjavec** [comment]
@cluljoseaires, I just rebuilt your corpus and it turns out it is no longer valid. Namely (cf. #472) after you submitted your corpus we decided on a change to the schema (and Guidelines) so that div elements that do not contain utterances (but only headings, notes) should get the type "commentSection" rather than "debateSection", and your corpus has a number of such divs.

My finalization script corrects this, you don't actually have to do anything if you can't be bothered and don't care if your copy of the corpus is different from the one that goes into the repository. But if you would like to keep them in synch, then please correct the types of these divs. The list of the files to be corrected can be found in https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-PT.log (grep for "no utterances in div"). 

Note also that there are two reported errors as regars bad chars (again, this is new check):
```
ERROR: File ParlaMint-PT_2019-12-20.ana.xml contains bad chars: U+F0B7 (4x)
ERROR: File ParlaMint-PT_2020-04-16.ana.xml contains bad chars: U+F020 (2x)
```
This I don't fix as it might be non-trivial, then again, we can live with 6 bad characters in the corpus.

And sorry about this late change & pls. let me know if you will (not) fix this, so I can re-close this issue.
