### ISSUE TITLE
ParlaMint-TEI.ana.rng: allow <pb> ? 

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#334]
Currently pagebreaks `<pb>` are legal in `ParlaMint-TEI.rng` but not in `ParlaMint-TEI.ana.rng`. 
Is this a _bug_ or a _feature_? (I myself would consider it a _buggy feature_ :-) )
Or to be more concrete: would you consider to unifiy the two schemas so `<pg>` can be used in both?

**Comment by matyaskopp** [comment]
In annotated version `ParlaMint-TEI.ana.rng`, `<pb>` is allowed only outside `<seg>` because the `ParlaMint-TEI.rng` is included.

Do you need `<pb>` inside `<seg>`? CZ case doesn't have `pb` inside paragraph (I believe). I am not sure about the ES case.

**Comment by TomazErjavec** [comment]
As @matyaskopp notes, so far we didn't have cases, where this was required. But given that we do alow interruptions inside `seg` and `s`, I see no good reason not to also allow `pb` there, so I just added it (documentation branch). I hope this doesn't cause problems, but I hope not!

**Comment by hpreki** [comment]
Thank you @TomazErjavec  and @matyaskopp

**Comment by hpreki** [comment]
@TomazErjavec could you also allow `<pb>` within `<name>`?  After the last bug-fix it is only allowed as _direct_ child of `<s>`

**Comment by TomazErjavec** [comment]
Sorry about this, added it now (documentation branch), I hope it is ok - if so, pls. reclose, otherwise, of course, complain!

**Comment by hpreki** [comment]
Looks fine - thanks a lot!

**Comment by matyaskopp** [comment]
@hpreki. Now merged with data branch
