### ISSUE TITLE
Relation between parties: should split-offs be encoded?

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#335]
We have occasions where new political parties come into existence as (unfriendly) "split offs" from their original "parent"-party. 
Should these cases be captured as `<relation>` ? 
_Iff_ the answer is yes, I guess we do need an additional relation name - e.g. `split-off`? I think `successor` could not be applied for these cases:
> successor: an organisation (again, typically a political party), or several of them, ceased to exist, but a successor was created

The "originator" of the "split-off" definitely does not cease to exist, and I do not think (unfriendly) split-offs would consider themselves as "successors".
(from what I understand, `successor` could be applied to encode the opposite case: a merger/fusion  of several parties into a new one, right?)

Given the restricted time we have for finishing our corpora I personally can live _very_ well with just _ignoring_ these split offs in the `<relations>` for now, I only wanted to raise awareness on that issue and make sure we come to a common agreement.

**Comment by matyaskopp** [comment]
I definitely vote for ignoring this information.
I guess you will have encoded this information in affiliations with political party -> one affiliation ends, and another starts. 

yes, the `successor` is more likely for renaming parties and "permanent coalitions" creation (new party appears and the old ones disappear).

In case, just a few members decide to be independent, it is not the opposite case because the old party stands as is (without rebel members).

The question is how you are planning to implement it concerning parliamentary groups... Do the members become independent (no parliamentary group affiliation) or stay in their current parliamentary group?

**Comment by hpreki** [comment]
so we all agree that ignoring this kind of relation between parties is o.k.? That's just fine for me. 

To  @matyaskopp 's  question
> The question is how you are planning to implement it concerning parliamentary groups... Do the members become independent (no parliamentary group affiliation) or stay in their current parliamentary group?

* we stopped modelling parliamentary groups in our corpus: instead we stick to political parties and MP are tied to a party via the relation `<affiliation role="representative" ref="#politicalParty...." from=... to=..../>`  
* as for "rebels": they never stay in their current parliamentary group (otherwise they are no rebels in a technical sense :-) ). This leaves us with 2 possibilities: 
    1) they join another, possibly newly founded party -> this is modeled with a new `affiliation`.
    2) they are so called "wild MP" - i.e. do not have any relation to a party or organisation. 
    
For case (2) ("wild _unaffiliated_ MP) I actually wonder what's the best practice to encode this? 

I think the solution to express _non_-affiliation by affiliating the a MP to a virtual entitity which expresses "NonMembership" was dumped some time ago? (on the basis, that the "NonMembers" are politically so diverse, that it doesn't make sense to group them in one "organisation")

So my proposal would be to encode "no affiliation with  a party" by just that: do not specify any relation! I.e. if a MP turns "wild" he/she just has no `<affiliation>` for this period of time! 
 
But I suppose you _always_ want/require  an `affiliation` ?

So what's the best practice for these "unaffilated" wild MP? Maybe @TomazErjavec can contribute?

**Comment by matyaskopp** [comment]
> - we stopped modelling parliamentary groups in our corpus: instead we stick to political parties and MP are tied to a party via the relation `<affiliation role="representative" ref="#politicalParty...." from=... to=..../>`

So if someone has affiliation:
```XML
<affiliation role="representative" ref="#politicalParty.XXX" from=... to=..../>
```
then the person is a member of the parliamentary group for this period:
```XML
<affiliation role="member" ref="#parliamentaryGroup.XXX" from=... to=..../>
```
but you don't want to have this line in your corpus. Do I understand correctly?

---

> For case (2) ("wild unaffiliated MP) I actually wonder what's the best practice to encode this?

In short: "wild unaffiliated MP" should stay (parliamentaryGroup-)unaffiliated, discussed here #246So my proposal would be to 

> encode "no affiliation with a party" by just that: do not specify any relation! I.e. if a MP turns "wild" he/she just has no <affiliation> for this period of time!

Agree

> But I suppose you always want/require an `affiliation`?

No, I require parliament organization `affiliation` if he/she is a member of parliament.

**Comment by hpreki** [comment]
> but you don't want to have this line in your corpus. Do I understand correctly?

Yes, because I thought parliamentaryGroups are superfluous.
 I _was_ a big fan of paliamentaryGroups in the beginning, when I saw party affiliations encoded via `<affiliation role="member" ref="#politicalParty...." from=... to=..../>`. This "felt" quite wrong, because we do not know about the `from` and  `to` of party-memberships (membership usually starts _way_ before a person becomes a MP and  typically lasts for a lifetime) . 
This  problem was resolved by using `role="represents"` instead of `role="member"`.
So I thought, I could get completely rid of parliamentaryGroups - we call them "Klubs" . And that's what I did!  I.e. currently "Klubs" do not exist in our encoding at all. I hope that's o.k.
 

> But I suppose you always want/require an affiliation?
>>No, I require parliament organization affiliation if he/she is a member of parliament.

And just for clarification: the requirement  _must be affiliated to parliament organization_ can be met with 
  `<affiliation from="..." to="..." role="member" ref="#NR">` 
  
  where NR is just the Parliament 

```xml
   <org xml:id="NR" role="parliament" ana="#parla.national #parla.lower">
                  <orgName xml:lang="de" full="yes">Nationalrat der Republik Österreich</orgName>
                  <orgName xml:lang="en" full="yes">National Council of the Republic of Austria</orgName>
                  <idno type="URI" subtype="wikimedia" xml:lang="de">https://de.wikipedia.org/wiki/Nationalrat_(%C3%96sterreich</idno>
                
   ...
   </org>
```
Is that right?

**Comment by TomazErjavec** [comment]
I think this debate moved on to #368, and the questions above are now dated, so, closing. If @hpreki or @matyaskopp disagrees, pls. reopen!
