### ISSUE TITLE
Some tagging issues

### ISSUE THREAD

**Issue by cluljoseaires** [clarin-eric/ParlaMint#339]
I have information about parliament 'secretary' but validation does not allow such role to be associated with parliament. I tried with government just to see if it worked and had the same error.

Also, I have information about government 'secretaryOfState' and validation does not allow them to be associated with government as well.

So, I guess those roles are supposed to mean something else, but I wanted to confirm.

Additionally, I would like to know how the center/left/right party leanings should be enconded so that I can included them.

**Comment by TomazErjavec** [comment]
> I have information about parliament 'secretary' but validation does not allow such role to be associated with parliament. I tried with government just to see if it worked and had the same error.

I'm not sure I understand this: do you mean that you want to insert a `<affiliation role="secretary" ...>` into a `<person>` element?
I think this should work - if this is what you mean and it in fact doesn't work, can you please give the exact snippet of data that fails? But maybe I misunderstand.

> Additionally, I would like to know how the center/left/right party leanings should be enconded so that I can included them.

As I said today at the meeting, we don't quite have it yet but hopefully we will soon!

**Comment by cluljoseaires** [comment]
First of all, sorry about my 'party leaning' misunderstanding. I though your comment applied for the tsv option for people who would prefer to use it...

Now, about the affiliations, with the following person xml:

<person xml:id="AbelLimaBaptista">
    <persName>
        <forename>Abel</forename>
        <surname>Lima</surname>
        <surname>Baptista</surname>
    </persName>
    <sex value="M"/>
    <birth when="1963-10-13"/>
    <affiliation role="member" ref="#CDS-PP"/>
    <affiliation role="member" ref="#GrupoParlamentardoCds-Pp"/>
    <affiliation role="member" ref="#Parliament" from="2011-06-20" to="2015-10-22">
        <roleName>Secretário de Mesa</roleName>
    </affiliation>
    <affiliation role="secretary" ref="#Parliament" from="2011-06-20" to="2015-10-22">
        <roleName>Secretário de Mesa</roleName>
    </affiliation>
    <affiliation role="member" ref="#Parliament" from="2015-10-23" to="2019-10-24">
        <roleName>Secretário de Mesa</roleName>
    </affiliation>
    <affiliation role="secretary" ref="#Parliament" from="2015-10-23" to="2019-10-24">
        <roleName>Secretário de Mesa</roleName>
    </affiliation>
</person>

I get the following warning in check-content-PT:

WARN[15] ParlaMint-PT.ana:563 Invalid role 'secretary' - unexpected affiliation role with parliament organization in AbelLimaBaptista affiliation [affiliation role="secretary" ref="#Parliament" from="2011-06-20" to="2015-10-22"]
                            [roleName]Secretário de Mesa[/roleName]
                        [/affiliation]

And with the following:

<person xml:id="AdolfoMiguelBaptistaMesquitaNunes">
    <persName>
        <forename>Adolfo</forename>
        <surname>Miguel</surname>
        <surname>Baptista</surname>
        <surname>Mesquita</surname>
        <surname>Nunes</surname>
    </persName>
    <sex value="M"/>
    <birth when="1977-11-29"/>
    <affiliation role="member" ref="#CDS-PP"/>
    <affiliation role="member" ref="#GrupoParlamentardoCds-Pp"/>
    <affiliation role="member" ref="#Parliament" from="2011-06-20" to="2013-01-31">
        <roleName>MP</roleName>
    </affiliation>
    <affiliation role="member" ref="#Government" from="2013-02-01" to="2015-10-29">
        <roleName>Secretário de Estado do Turismo</roleName>
    </affiliation>
    <affiliation role="secretaryOfState" ref="#Government" from="2013-02-01" to="2015-10-29">
        <roleName>Secretário de Estado do Turismo</roleName>
    </affiliation>
    <affiliation role="member" ref="#Government" from="2015-10-30" to="2015-11-25">
        <roleName>Secretário de Estado do Turismo</roleName>
    </affiliation>
    <affiliation role="secretaryOfState" ref="#Government" from="2015-10-30" to="2015-11-25">
        <roleName>Secretário de Estado do Turismo</roleName>
    </affiliation>
</person>

I get:

WARN[16] ParlaMint-PT.ana:644 Invalid role 'secretaryOfState' - unexpected affiliation role with government organization in AdolfoMiguelBaptistaMesquitaNunes affiliation [affiliation role="secretaryOfState" ref="#Government" from="2013-02-01" to="2015-10-29"]
                            [roleName]Secretário de Estado do Turismo[/roleName]
                        [/affiliation]

It is becoming very hard to keep track, but if I remember correctly, validation enforces to include the member association, as with 'ministry', for instance.

I now realize it is just a warning, but it could still be not a good sign... What I did to overcome this was skip the conflicting role and just keep the 'member' affiliation.

Actually, you can check in my last commit how things look after I managed to avoid the warnings.

**Comment by matyaskopp** [comment]
It is just a warning, I can change it to INFO to avoid confusion.
These roles are not in all corpora but they seams to me valid

**Comment by cluljoseaires** [comment]
In that case I will include them later in my next commit, possibly when I receive your observations, for which there is no hurry.

**Comment by TomazErjavec** [comment]
> WARN[15] ParlaMint-PT.ana:563 Invalid role 'secretary' - unexpected affiliation role with ...
> It is just a warning, I can change it to INFO to avoid confusion.

@matyaskopp, I think it is ok that it is a warning, but the text could be less scary, as it not explictily says that the role is invalid but in fact it isn't. Also, this is not the first time that people consider these warnings as failures of validation.

So, maybe somethink like (for this and other similar WARNs):

Non-standard role 'secretary' - consider changing affiliation with ...

**Comment by matyaskopp** [comment]
> Non-standard role 'secretary' - consider changing affiliation with ...

ok, I will change it. Thanks for suggesting a less scary formulation
