### ISSUE TITLE
factorize particDesc and classDecl elements

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#344]
Write a script that takes a root file and factories `particDesc` and `classDecl` elements:
- factorized content is replaced with `<xi:include ...>`
- create a `ParlaMint-XX-listPerson.xml` file for the list of persons (make sure that there are not multiple lists)
- create a `ParlaMint-XX-listOrg.xml` file for the list of organisations (make sure that there are not multiple lists)
- create a separate file for every taxonomy
  - `ParlaMint-XX-taxonomy-${TAXONOMY_ID}.xml` for parliament specific taxonomies
  - `ParlaMint-taxonomy-${TAXONOMY_ID}.xml` for common taxonomies
- do nothing if there is no new candidate for factorization is present

@TomazErjavec, this issue needs to be extended:
 - what will be broken by including content in the header?
 - what are the proper names for these files? (we usually use `ls` or `find` in our scripts and then filter files...)

related to #264

**Comment by matyaskopp** [comment]
the current implementation creates files with these names: 
- if element does not have id: `ParlaMint-{XX}-{elementName}.xml`
- if element has id: `ParlaMint-{XX}-{elementName}-{elementId}.xml`

and extracts these elements:
- `listPerson`
- `listOrg`
- `taxonomy`

**Comment by TomazErjavec** [comment]
@matyaskopp, `make` gives wrong explanation for `factorize-teiHeader`: `calculate and add common content (tagUsage,)`. Note also that this explanation (for `add-common-content`) should also be fixed, e.g. `(tagUsage etc.)` or actually list all the common content that is added.

**Comment by TomazErjavec** [comment]
> Here are the things that will be broken and need to be fixed:
> ParlaMint-teiCorpus.rng schema
> ParlaMint ODD: Schema + Guidelines

This has now been done (includes major refactoring the the RNG schemas) in the documentation and devel branches. Also taken into account are (the possiblity of) factorized taxonomies (i.e. the RNG and ODD schema support them, and Guidelines mention them), cf. #264.

**Comment by TomazErjavec** [comment]
Introduced [parlamint-lib.xsl](https://github.com/clarin-eric/ParlaMint/blob/devel/Scripts/parlamint-lib.xsl) and changes most scripts to use it and take into account possible XIncludes in root teiHeader.

@matyaskopp, I also changed some of your XSLT scripts, but did not test them (or mine) extensivelly, as it is difficult with missing V3 samples. Pls. report if it turns out your scripts do not work anymore (I hope not, but...)

**Comment by matyaskopp** [comment]
@TomazErjavec I believe it is working now. Do you think that I can merge it with the main and data?
I have prepared two pull requests (factorized https://github.com/clarin-eric/ParlaMint/pull/375  and not factories https://github.com/clarin-eric/ParlaMint/pull/374 ), so I am ready to test GitHub workflows ,

**Comment by matyaskopp** [comment]
I am taking back my last comment - I do not need to merge it to test validation:
https://github.com/clarin-eric/ParlaMint/actions/runs/3300175288/jobs/5444386852#step:4:1793

**Comment by matyaskopp** [comment]
workflow validation seems to work on non-factorized files.
Ready to merge?

**Comment by TomazErjavec** [comment]
> Ready to merge?

Go for it! Sorry about overlooking the hdr vs. meta pramateter - as you now noticed, I unified this to meta everywhere.

**Comment by matyaskopp** [comment]
@TomazErjavec It seems to work!
https://github.com/clarin-eric/ParlaMint/tree/data/Data/ParlaMint-CZ

**Comment by TomazErjavec** [comment]
Great! But [your listPerson](https://github.com/clarin-eric/ParlaMint/blob/data/Data/ParlaMint-CZ/ParlaMint-CZ-listPerson.xml) still too large to be viewed. Oh well...

So, who will do this now for the other languages?

**Comment by TomazErjavec** [comment]
Processing works even without this, but I think it would be nice if elements factored out into separate files also had `@xml:lang` defined - it should be the same as `ancestor-or-self::tei:*[@xml:lang][1]/@xml:lang`. 
So, e.g. if somebody just takes the file ParlaMint-CZ-listOrg.xml they will still know what language `<orgName full="abb">FSSN</orgName>` is in. Because everything has to be in some language.

It would also be nice to have `@xml:id` on the root element, ideally the same as the filename, although this might be more tricky. But maybe not, as nothing in the corpora actually refers to the IDs. So, we would then have something like
```<taxonomy xmlns="http://www.tei-c.org/ns/1.0" xml:lang="cs" xml:id="ParlaMint-CZ-taxonomy-meeting.parts">```
```<listOrg xmlns="http://www.tei-c.org/ns/1.0" xml:lang="cs" xml:id="ParlaMint-CZ-listOrg">```

**Comment by matyaskopp** [comment]
> Processing works even without this, but I think it would be nice if elements factored out into separate files also had `@xml:lang` defined - it should be the same as `ancestor-or-self::tei:*[@xml:lang][1]/@xml:lang`.
> So, e.g. if somebody just takes the file ParlaMint-CZ-listOrg.xml they will still know what language `<orgName full="abb">FSSN</orgName>` is in. Because everything has to be in some language.

That is a good point, I can imagine that someone takes just these two list files and processes only them.

This can also be done with taxonomies, but merging common taxonomies should be done with more care.


> It would also be nice to have `@xml:id` on the root element, ideally the same as the filename, although this might be more tricky. But maybe not, as nothing in the corpora actually refers to the IDs. So, we would then have something like
> `<taxonomy xmlns="http://www.tei-c.org/ns/1.0" xml:lang="cs" xml:id="ParlaMint-CZ-taxonomy-meeting.parts">`
> `<listOrg xmlns="http://www.tei-c.org/ns/1.0" xml:lang="cs" xml:id="ParlaMint-CZ-listOrg">`

Yes, I guess it is possible


@TomazErjavec, should I implement this?

**Comment by TomazErjavec** [comment]
> That is a good point, I can imagine that someone takes just these two list files and processes only them.

Yes, excatly.

> This can also be done with taxonomies, but merging common taxonomies should be done with more care.

Here, I think there are two sensible solutions, either give "en" as the root element language, as the "default", or to give it "mul", which is more "correct". Even though in practice it won't matter, as every element containing text should be marked for language. 

> Yes, I guess it is possible

Great.

> @TomazErjavec, should I implement this?

Yes please.

**Comment by matyaskopp** [comment]
> > @TomazErjavec, should I implement this?
> 
> Yes please.

done.

Now I have to change validation scripts

**Comment by matyaskopp** [comment]
@TomazErjavec,
I am adding the correct id into taxonomies eg:
- `UD-SYN` -> `ParlaMint-taxonomy-UD-SYN.ana`
- `parla.legislature` -> `ParlaMint-taxonomy-parla.legislature`
- `NER.cnec2.0` -> `ParlaMint-CZ-taxonomy-NER.cnec2.0.ana`

And I have found one place where an id is used:
https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ.xml#L122
I will implement this change in the factorization script. But now I think we will need #358 to composite factorized headers and then factorize them again with fixings (change id, add lang, change filename - .ana suffix)

I will implement this in devel and then we have to synchronize another big bang in recommendations.

**Comment by TomazErjavec** [comment]
https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ.xml#L122

1. schema is an optional attribute, and in this case it is redundant anyway, as it is implied by targets. 
2. is your corpus the only one using this?

**Comment by matyaskopp** [comment]
> 2\. is your corpus the only one using this?

no new partners are using it too:
```
Data/ParlaMint-CZ/ParlaMint-CZ.ana.xml:            <catRef scheme="#parla.legislature" target="#parla.bi #parla.lower"/>
Data/ParlaMint-CZ/ParlaMint-CZ.xml:            <catRef scheme="#parla.legislature" target="#parla.bi #parla.lower"/>
Data/ParlaMint-GR/ParlaMint-GR.ana.xml:            <catRef scheme="#parla.legislature" target="#parla.uni"/>
Data/ParlaMint-GR/ParlaMint-GR.xml:            <catRef scheme="#parla.legislature" target="#parla.uni"/>
Data/ParlaMint-PT/ParlaMint-PT.ana.xml:            <catRef scheme="#Parliament" target="#parla.uni"/>
Data/ParlaMint-PT/ParlaMint-PT.xml:            <catRef scheme="#Parliament" target="#parla.uni"/>
```

**Comment by TomazErjavec** [comment]
I see. OK, then I would suggest either changing the value of `catRef/@scheme` - or simply removing the attribute - as part of factorize.

**Comment by matyaskopp** [comment]
> I see. OK, then I would suggest either changing the value of `catRef/@scheme` - or simply removing the attribute - as part of factorize.

the change is already implemented:
https://github.com/clarin-eric/ParlaMint/commit/47e2d43d27b6a3bf2f0b2d28657ae179a64426c0#diff-e690444a4eb785216017be5bea18947381b386963513997e0973d311d51e5510R96-R98

**Comment by TomazErjavec** [comment]
Well, that is great. So, does anything remain to be done here?

**Comment by matyaskopp** [comment]
no
