### ISSUE TITLE
Affiliation for non-affiliated speakers and misc 

### ISSUE THREAD

**Issue by adina-v** [clarin-eric/ParlaMint#346]
Hi all! Quick question about how to encode non-affiliated speakers - that is, persons who are neither members of the Parliament nor of recognizable organizations. They normally intervene once or a couple of times in all the corpus. Would it work to use an affiliation role such as "speaker", just for the day they intervene in the Parliament? 
Something like this:
` affiliation role="Speaker" ref="#PG" from="2015-10-01" to="2015-10-01" ana="#PG.9"/`

**Comment by matyaskopp** [comment]
Not every person should be affiliated with an organization. You can encode it this way:
https://github.com/clarin-eric/ParlaMint/blob/0c5c0cbc7f3c17636ee407c57dbcd296833f23c0/Data/ParlaMint-SI/ParlaMint-SI.xml#L703-L709

Just make sure if a person occurs multiple times in the corpus, `u/@who` always points to the same `person` in `personList`, and use `u/@ana="#guest"`
```XML
<u who="#AccettoMatej" ana="#guest"  ...>
...
</u>
```

**Comment by adina-v** [comment]
All right, thank you!
