### ISSUE TITLE
BG: use of "coalition" as role of org/@role

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#350]
BG currently uses `org/@role = 'coalition'` in some cases, e.g. https://github.com/clarin-eric/ParlaMint/blob/655d37393c30b413b478eb57abe5fc13ce043b10/Data/ParlaMint-BG/ParlaMint-BG.xml#L352

With 93abb1b the `org/@role = 'coalition'`  has been removed, so these organisations should be encoded differenty:
* if they are truly coalitions, then in `relation/@name="coalition"` elements
* if they are in fact political parties or parliamentary groups, then as `org/@role = 'politicalParty'`  or `org/@role = 'parliamentaryGroup'`

@osenova, I am assigning this to you, as Kirili has not reported his GitHib nick - could you remind him pls.?

**Comment by osenova** [comment]
Thanks, Tomaz - where can I edit this? Should I make a branch and edit there?

**Comment by TomazErjavec** [comment]
> Thanks, Tomaz - where can I edit this? Should I make a branch and edit there?

@osenova, the [CONTRIBUTING](https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md) file explains how to make changes to data. But maybe @KirilSimov can do it now he has been added as a contributer to this repo.

**Comment by matyaskopp** [comment]
this seems to be fixed, closing
