### ISSUE TITLE
PT: contractions and composite tags 

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#353]
During the tokenization, we decided to keep the frequent contractions in Portuguese and not to expand them. This is the same decision we took for the Reference Corpus of Contemporary Portuguese, and the reason is that expanding the contractions makes it difficult for users to read the text. 
To deal with this, we use composite POS tags. For instance, the contraction of a preposition+determiner (e.g, "no") is kept as such and is  labelled with the tag "ADP+DET". We see that this is not accepted during validation. Could composite tags be integrated in ParlaMint?

_Originally posted by @amamendes in https://github.com/clarin-eric/ParlaMint/issues/332#issuecomment-1270440212_

**Comment by matyaskopp** [comment]
@amamendes 

The correct solution, according to ParlaMint's recommendation and UD annotation style, is expanding all contractions and encoding them this way: https://clarin-eric.github.io/ParlaMint/#sec-ana-norm

So if I show it on Portuguese sentence: "_Porque é que os senhores não agendam debates de atualidade sobre estas melhorias no Serviço Nacional de Saúde?_"
![image](https://user-images.githubusercontent.com/5867995/194476540-d4cd4719-675b-4456-8995-0f2a9ba37644.png)
the violet part of sentence should be encoded this way:
```XML
...
<w xml:id="w14w15">no
  <w xml:id="w14" norm="em" lemma="em" msd="UPosTag=ADP"/>
  <w xml:id="w15" norm="o"  lemma="o"  msd="UPosTag=DET|Definite=Def|Gender=Masc|Number=Sing|PronType=Ar"/>
</w>
...
```
> This is the same decision we took for the Reference Corpus of Contemporary Portuguese, and the reason is that expanding the contractions makes it difficult for users to read the text.

There is no reason to worry about the readability of the text:
- user will see only the "orthographical" entry of a word because it is in the text content (`w/text()`) of word(`w`) element
- the syntactic words  stay hidden because they are stored in `w/@norm` attribute

related issue: #61

**Comment by matyaskopp** [comment]
@cluljoseaires, are you planning to split the contracted word 'no' into two syntactic words?

**Comment by cluljoseaires** [comment]
Yes I am, but I found out it requires updating the UD relations. I already have an idea on how to address that, but for now I will keep what we already have. I am running the validation again on the full corpus just to be sure, and if I have no errors I will produce the delivery following the "contributing.md" requirements.

**Comment by TomazErjavec** [comment]
@cluljoseaires, are we then ok with this issue, i.e. can it be closed?

**Comment by cluljoseaires** [comment]
I would say you can close it because I already know what to do. The question now is for me to check if I can do it, which I am confident I can... ;)

**Comment by TomazErjavec** [comment]
OK, great. Re-open or make another one if there will be problems!
