### ISSUE TITLE
Composite teiHeader content

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#358]
an opposite operation to #344 

the intent of writing this script is to avoid rewriting a lot of scripts and Relax NG schemas.

**Comment by TomazErjavec** [comment]
I think this is a couple of templates like https://github.com/clarin-eric/ParlaMint/blob/a7c867f644b84269a30a818363fb4ec650ed3fff/Scripts/parlamint-lib.xsl#L133
Or maybe I could even change that to just XInclude the files inside the teiHeader, but copy over XInclusion of components.
