### ISSUE TITLE
definition of  u/@ana='regular' vs. 'guest': adding `government` ?

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#359]
Is there a common understanding of what kind of speakers would  trigger  `u@ana=regular` and which would be `u@ana=guest` ?
(I am afraid I will need to re-assign these values -- currently I only used `u@ana=chair` for chairpersons, and `regular` for _all_ the rest -- and I would like to do it correctly this time) 

My initial heuristic for reassigning the  speaker-type would have been: apart from the `chair`s I would  assign `regular` only to utterances by current members of the parliament, and `guest` to all the rest. 

Which leaves us with the problem of members of the government - who in Austria never are _members_ of the parliament (the legislative).  On the other hand, ministers usually take part in the parliamentary sittings...
What do you think of adding `u/@ana=government` to solve this dilemma and have a clear distinction? 
(somewhere @matyaskopp mentioned, that for CZ it cannot be determined whether a person speaks as a member  of the national assembly or as a member of a government, but should that completely rule out the usage of such a possibly useful classification for all parliaments?)

@TomazErjavec do I interprete your discussion with @gclux  in #66  correctly, that I am free to add such a category to my 
` <taxonomy xml:id="speaker_types">` ?  I am hesitant to do so, because I would prefer to have a "common agreement" for that kind of distinction. 

**Plan B ?**
But of course another possibility is: to give `regular` the broadest possible scope: basically _everybody_ would be `regular` unless he/she has no `id`  in the parliament's list of  _Austria's political functionaries since 1945_  
This leaves us with exactly _one_ `guest` in our whole corpus - namely UN-secretary general Ban Ki-moon. 
If that's o.k. with you (is it?): fine for me, because it would allow me to quick-fix my `u/@ana` without any real programming.  Considering the looming deadline this would be great as well.

**Comment by matyaskopp** [comment]
@hpreki, I think that plan B is ok.
The `regular` speakers are members of parliament/house and members of government at the time of the speech, but plan B will be close to the truth enough.
And `guest` speakers are all rest.

**Comment by TomazErjavec** [comment]
@hpreki, I agree with @matyaskopp - we should try and keep this simple. To be honest, we currently (so, in V2.1) have quite a mess with these roles - I did a grep through the vertical files of the corpora, and give the result below (with the number of speeches that have the speaker with the given role): some have missing data, some don't use guest at all, and some have rather idiosycratic roles, esp. BE. I hope we can get to a more uniform situation in V3!

```
     10 ParlaMint-HR
  16013 ParlaMint-FR
  22107 ParlaMint-ES
   2393 ParlaMint-GB
    485 ParlaMint-BE
     56 ParlaMint-BG
      1 ParlaMint-BE    Chair of Senate
 104998 ParlaMint-PL    Chairperson
 118347 ParlaMint-LT    Chairperson
 123172 ParlaMint-NL    Chairperson
  14175 ParlaMint-GB    Chairperson
 149934 ParlaMint-DK    Chairperson
  28638 ParlaMint-IT    Chairperson
  31903 ParlaMint-BE    Chairperson
  37906 ParlaMint-SI    Chairperson
   5105 ParlaMint-IS    Chairperson
  60362 ParlaMint-FR    Chairperson
  61473 ParlaMint-LV    Chairperson
  62368 ParlaMint-HR    Chairperson
   6398 ParlaMint-ES    Chairperson
  72370 ParlaMint-BG    Chairperson
  82159 ParlaMint-CZ    Chairperson
      1 ParlaMint-BE    European Commissioner
  30205 ParlaMint-FR    Government
  12055 ParlaMint-LT    Guest
      1 ParlaMint-IS    Guest
  22569 ParlaMint-PL    Guest
   3424 ParlaMint-IT    Guest
   3900 ParlaMint-CZ    Guest
   5177 ParlaMint-LV    Guest
   9186 ParlaMint-FR    Guest
  27470 ParlaMint-BE    Minister
   2291 ParlaMint-BE    Other type of speaker
      3 ParlaMint-BE    President Of the European Commission
   1061 ParlaMint-BE    Prime Minister
 114433 ParlaMint-LT    Regular
 137210 ParlaMint-DK    Regular
 203477 ParlaMint-PL    Regular
  21414 ParlaMint-ES    Regular
   3086 ParlaMint-HU    Regular
 351772 ParlaMint-NL    Regular
 365837 ParlaMint-FR    Regular
  37216 ParlaMint-SI    Regular
  47311 ParlaMint-IT    Regular
 535535 ParlaMint-GB    Regular
  55486 ParlaMint-LV    Regular
  62118 ParlaMint-HR    Regular
  68401 ParlaMint-CZ    Regular
  69026 ParlaMint-IS    Regular
  73925 ParlaMint-BG    Regular
  82098 ParlaMint-BE    Regular
    614 ParlaMint-BE    Reporting
      4 ParlaMint-BE    Secretary
   2493 ParlaMint-BE    Secretary Of State
      1 ParlaMint-BE    Staff Member of Minister
```

**Comment by hpreki** [comment]
@matyaskopp  and @TomazErjavec  thank you for the clarification - and the "licence to be sloppy". 
I nevertheless could not resist and implemented a mechanism that properly assigns "regular" to (current) MPs and Government-members and "guest" to the rest.

**Comment by gclux** [comment]
Sorry if my reply is late.

I would add that I consider it useful to distinguish if a 'regular' speaker
is member of parliament or member of government. This is the reason we have
***@***.***=government in the French corpus (I am surprised it is the only one).
I think we would keep it simple with just: chairperson, government, guest,
regular.

In the French current version however, it is not always determined. The
source metadata records as members of government those who were previously
elected in the parliament (i.e. who already had a mandate). As a result,
members of government who were not known at the time of their appointment
in the government are identified in ParlaMint-FR as 'guest'. I think this
should be improved in the next version...

Of course, we can comply with what is decided in the other countries. Not
sure if we need to reopen the issue.

**Comment by TomazErjavec** [comment]
> I would add that I consider it useful to distinguish if a 'regular' speaker is member of parliament or member of government. 

I agree, but we now distinguish this not via `u/@ana` but through the [affiliation of the speaker](https://clarin-eric.github.io/ParlaMint/#sec-affiliation). So, I would leave the distinctions made on the speech level as they are, i.e. `#chair`, `#regular`, and `#guest`.

@gclux, note that GitHub anonymises things that it considers email addresses, so `***@***.***=government ` becomes undredable (or, rather, not understandable). Maybe try Preview before you post an issue, to see if it looks ok.
