### ISSUE TITLE
Schema: @lemma and @msd has to be optional

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#36]
@TomazErjavec , please make `@lemma` and `@msd` optional
https://github.com/clarin-eric/ParlaMint/blob/809c1537d7692b10c91c925808b1de63a79af5a8/Schema/ParlaMint-TEI.ana.rnc#L55-L63

it is not possible to represent some multi-token words (out email discussion from the beginning of december, subj ParlaMint - TEI encoding - multi-word tokens). 

ParlaClarin example: https://clarin-eric.github.io/parla-clarin/#sec-ananorm

example:
![image](https://user-images.githubusercontent.com/5867995/106778157-f2f74500-6645-11eb-8ea6-969c93d9bc3c.png)

**Comment by TomazErjavec** [comment]
You mean to support cases as in https://clarin-eric.github.io/parla-clarin/#sec-ananorm?

This I did, but only in the context of multiword units, cf. https://github.com/clarin-eric/ParlaMint/blob/809c1537d7692b10c91c925808b1de63a79af5a8/Schema/ParlaMint-TEI.ana.rnc#L33

Does this not work for you?

**Comment by matyaskopp** [comment]
Oh, sorry. I misunderstand the validator output!
Problem is that outer `<w>` doesn't have an attribute `@id` in the schema.

My data:
```
                     <w xml:id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000.u1.p1.s2.w10">
                        aby
                        <w xml:id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000.u1.p1.s2.w11"
                           lemma="aby"
                           msd="UposTag=SCONJ"
                           ana="pdt:J,-------------"
                           norm="aby"/>
                        <w xml:id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000.u1.p1.s2.w12"
                           lemma="být"
                           msd="UposTag=AUX|Mood=Cnd|Person=3|VerbForm=Fin"
                           ana="pdt:Vc-------------"
                           norm="by"/>
                     </w>
```

Valid data:
```
                     <w>
                        aby
                        <w xml:id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000.u1.p1.s2.w11"
                           lemma="aby"
                           msd="UposTag=SCONJ"
                           ana="pdt:J,-------------"
                           norm="aby"/>
                        <w xml:id="ParlaMint-CZ_2014-09-10_ps2013-016-01-000-000.u1.p1.s2.w12"
                           lemma="být"
                           msd="UposTag=AUX|Mood=Cnd|Person=3|VerbForm=Fin"
                           ana="pdt:Vc-------------"
                           norm="by"/>
                     </w>
```

**Comment by matyaskopp** [comment]
an invalid issue, closing...
