### ISSUE TITLE
CONTRIBUTING.md hard to find, README.md outdated

### ISSUE THREAD

**Issue by nljubesi** [clarin-eric/ParlaMint#365]
@matyaskopp, we had some trouble finding CONTRIBUTING.md given that it is not referenced in the README.md. On the other hand, in the README.md, reference is made to the Scripts folder and its validation, so some contributing users might miss the proper way of validating their contributions.

I guess it might be easiest just to put a very visible disclaimer of a sort on top of README.md that for users contributing to Parlamint 3.x, they should follow through to CONTRIBUTING.md.

**Comment by TomazErjavec** [comment]
>  in the README.md, reference is made to the Scripts folder and its validation

I now noticed that the Scripts/README.md is quite obsolete - my bad, and I will fix the README there, @matyaskopp, if you could fix the main README, that would be great.

**Comment by TomazErjavec** [comment]
@nljubesi, if you think it is ok now, pls. close the issue - or complain if not!
