### ISSUE TITLE
are "parliamentaryGroup"s mandatory? 

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#368]
Validation with  
`make validate-parlamint-AT` 
complains:
```
ERROR[12] ParlaMint-AT: Total number of organizations with parliamentaryGroup role: 0
```

As a matter of fact, we only use `politicalParty`s .
Are `parliamentaryGroup`s mandatory? Or can this "ERROR" be ignored? 

We currently do not have any need for  `parliamentaryGroup`s 
Persons are directly linked  to parties via `@role="representative`
e.g.
```xml 
<affiliation from="1983-05-19" to="1999-10-28"   role="representative"  ref="#politicalParty.ÖVP"/>
```

**Comment by TomazErjavec** [comment]
I think this is too strict validation of @matyaskopp, at least my understanding is that a corpus can choose to have either politicalParty, of parliamentayGroup, or both, and, in fact, this is what is wirrten in the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-parties). So I think even a WARNING would be too much, but it would be nice to see an INFO about the numbers.

However, @hpreki, I am surprised that you use `@role="representative`, as this is contrary to the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-affiliation), where it is assumed that `@role="member` is used. Do you have good arguments why member is not ok, and we should switch to representative? This would be a big change, esp. as I guess other corpora are using member, so I would be disinclined to implement it, except if the arguemnts were really convincing.

**Comment by matyaskopp** [comment]
> I think this is too strict validation of @matyaskopp, at least my understanding is that a corpus can choose to have either politicalParty, of parliamentayGroup, or both, and, in fact, this is what is wirrten in the Guidelines. So I think even a WARNING would be too much, but it would be nice to see an INFO about the numbers.

there is inconsistency in guidelines and this issue #155. I thought we made `parliamentaryGroup` mandatory(we decided to change the politicalParty into parliamentaryGroup in v2tov3 transformation) and `politicalParty` optional.

> However, @hpreki, I am surprised that you use `@role="representative"`, as this is contrary to the Guidelines, where it is assumed that `@role="member"` is used. Do you have good arguments why member is not ok, and we should switch to representative? This would be a big change, esp. as I guess other corpora are using member, so I would be disinclined to implement it, except if the arguemnts were really convincing.

in CZ case, I use `representative` too, but I have `parliamentaryGroup`s and persons are affiliated with them with `member` role.
And I have also `<relation name="representing" active="#parliamentaryGroup...."  passive="#politicalParty..." from=... to=... />` (#335).
I believe this is the most precise solution.

**Comment by hpreki** [comment]
> However, @hpreki, I am surprised that you use @role="representative"

In #155  I fiercely advocated against using  a _timed_  `<affiliation from=... to=...  role_"member" ref="#politicalParty">` . This felt entirely wrong because we do not have any clue on the real temporal extension of party memberships: they start much before a person becomes a politician and usually last a life-time. 

So I was happy when it was decided to switch to `parliamentaryGroup`s instead, because the temporal extension of _these_ affiliations is clear. I.e. perceived  the `parliamanentaryGroup`s as a construct to avoid the `role="member" ref="#party"`

So when I found out about the `representative` role - I interpreted it as the one elegant way to directly affiliate persons with a party, without using the`parliamentaryGroup` as intermediate.
 Also this works  uniformly for _all_ kind of persons, not only for MPs! E.g. members of the government are (at least in Austria) _never_ members of any `parliamentaryGroup` but still are typically members of a party. 

Using the `role="representative" ref="#party..."` thus seemed like a perfect solution. 


And yes there's some "chaos"  in the Guidelines: 

In the text a role "representing" is mentioned, which is not part of the formal description? 
https://clarin-eric.github.io/ParlaMint/#TEI.affiliation
 
 And in #155 you use "representing" as role to connect parliamentaryGroups with politicalPartys, 
But in the Guidelines there also is an example, for the way  _I_ am using the relation . i.e. for connecting a `<person>` to a party: 

```xml
 <affiliation ref="#politicalParty.ANO2011.1104"
  role="representative" from="2017-10-21" to="2021-10-21">
  <roleName xml:lang="en">Candidate MP</roleName>
 </affiliation>
```

*Executive summary:* @TomazErjavec , yes I thought I had good reasons and was not breaching regulations when entirely skipping parliamentaryGroups, Of course I can recode my affiliations if  you think encoding of party-affiliation via to be via membership to parliamentaryGroups is mandatory, but would only do so right now if you think it's a _must_.

**Comment by TomazErjavec** [comment]
Thank you both for the very sensible comments! I guess I do need to change things after all, will do so in the next few days, and continue here when I have something to report.

**Comment by TomazErjavec** [comment]
OK, I now read this issue, #38, and #155, which refreshed my memory, and made me appreciate @hpreki's and @matyaskopp's arguments. 

So, yes, I now agree that parliamentaryGroups are obligatory (not something that can be checked by the schema of course), and say as much in the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-parties). I also fixed an error with `relation/@name` value definitions in the ODD.

I am less sure what to do now with "representative" vs. "member" role for affiliation of person with a politicalParty or parliamentaryOrganisation. I'd still prefer to leave things simple and just use "member", but if both of you agree that "representative" should be used for politicalParty (and/or parlimanetaryGroup?) that is ok with me, and I can change the text of the Guidelines and fix the (CZ) [example of affiliation](https://clarin-eric.github.io/ParlaMint/#TEI.affiliation) (which has to be changed anyway).

**Comment by coltekin** [comment]
I also like making the `parlimanetaryGroup` the main object the MPs are related to since the `to`/`from` becomes easier to determine. And, we can easily determine the party memberships of the MPs through the relation between the party and the parliamentary group. However, I have two somewhat related questions:

- In Turkish parliament (I guess like many others) there is a well defined "parliamentary group", the members of the same party in the parliament form the parliamentary group of this party. However, there is also the rule that parties with less than 20 MPs do cannot form a group. So, even though they are not independent, they do not have an official `parlimanetaryGroup`. One way to work around this is to assume that there is an unofficial `parlimanetaryGroup`. The other option is to directly indicate the party memberships. The drawback of the first option is mismatch with the reality, while the second one has the issues of undefined `from`/`to` dates. Any suggestions which way to go?
- When/if we indicate party memberships, it is often that we know the end of the party affiliation (e.g., because of switch to another party), but we do not have the information about joining the party. This is mostly related to above case with MPs, but it may also be the case for non-MP frequent speakers (like ministers). It seems it is not allowed to specify `to` while leaving `from` unspecified. Is this intentional? Again, suggestions and earlier experiences are most welcome.

**Comment by hpreki** [comment]
The issue brought up by @coltekin is very similar to mine. 

Iff @TomazErjavec  insists, I can switch from MP as `representative` of a `politicalParty` to `member` of a `parliamentaryGroup`, but I think we still need `politicalParty` and `representative` as well: 

* out (AT) members of the GOV are _never_ members of a `parliamentaryGroup` ("Klub") but (usually) are affilitated to a  `politicalParty` 
* corrrect time-spans for   `politicalParty`-membership cannot be determined. 

Therefore I would opt for:  
MP is `member` of a `parliamentaryGroup` with exact `from` + `to`
 Everybody else is possibly a `representative` of a `politicalParty` with an exact `from`+ `to` (which relates to the time-span a specific political role such as `minister` has been filled by that person.
 
 On the other hand this means: there is not _one_ but _two_ ways to relate a person to a  politicalParty, which have to be taken into account by any user of the corpus. 
 This could aleviated by always using the more general `representative` :-) Which brings us full circle to the start of our discussion.

**Comment by hpreki** [comment]
Addendum: I am against making `politicalParty` optional. I think they are a central "entitiy" in each encoding. E.g. I think political orientation should be encoded as a property of a `politicalParty` and not of a `parliamentaryOrganisation`. Cf.  #386

**Comment by matyaskopp** [comment]
> Therefore I would opt for:
MP is `member` of a `parliamentaryGroup` with exact from + to
Everybody else is possibly a `representative` of a `politicalParty` with an exact `from`+ `to` (which relates to the time-span a specific political role such as `minister` has been filled by that person.

Yes, that is the way how it is done in CZ corpus.

> On the other hand this means: there is not one but two ways to relate a person to a politicalParty, which have to be taken into account by any user of the corpus.

yes, it's true, but we can say that if a person is a `member` of a `politicalParty` and is also a `member` of `parliament`, then he/she is a `representative` of `politicalParty` (at the same time) - so corpora can be automatically extended with this information iff there is correctly set an affiliation timespan with `parliament`.

**Comment by hpreki** [comment]
@matyaskopp @TomazErjavec @coltekin maybe the re-iteration of our discussion is due to the fact that we never agreed  whether the affiliation-information is to be interpreted using  the  _closed world_  or the _open world_ assumption. 

I always assumed it to be interpreted in a _closed world_ scenario. 

Given the following: 
  
```xml
<affiliaton ref="#politicalParty.X" role="member" from="xxx" to="yyy"/>```

The  _closed world_ interpretation means: we state that somebody was  a party member _exactly_ from date `xxx` to date `yyy` i.e.  was _not_ a member before `xxx` or after `yyy`. 

It was with this interpretation in mind that let me and e.g. @coltekin protest against the usage of "member" - because there just is _no way_ to retrieve a person's actual time-span for party-membership. 

In a _open world_  scenario the above example only states that we know for sure that a person was a party member between  `xxx` to ` yyy` - but we do not make _any_ statement / have no further knowledge about his/her party-membership before or after.  

Switching to a "open world"-interpretation  would probably get rid of the necessity to use the "representive" role in _one_ case (affiliation to a party) and "member" in another (affiliation to parliamentaryGroup) and could uniformly use "member". 
I do _not_ know how the interpretation actually is defined in TEI  and whether it could (or must) be freely defined in the schema.

**Comment by vaidasmo** [comment]
> Addendum: I am against making `politicalParty` optional. I think they are a central "entitiy" in each encoding. E.g. I think political orientation should be encoded as a property of a `politicalParty` and not of a `parliamentaryOrganisation`. Cf. #386

I would argue that in less established democracies (such as, Lithuania) party affiliation is rather transitory and sometimes actively avoided. In addition, there are parliamentary group (faction) coalitions, with some groups not representing any existing party. Therefore, even declaration of ministers as representatives of parties becomes complicated. Thus, I think that we should avoid too strict references to "outside parliament" institutions, as they may vary considerably among countries.

**Comment by TomazErjavec** [comment]
There quite some discussion here, also on varios topic. To try and take them one by one:
>   In Turkish parliament (I guess like many others) there is a well defined "parliamentary group", the members of the same party in the parliament form the parliamentary group of this party. However, there is also the rule that parties with less than 20 MPs do cannot form a group. So, even though they are not independent, they do not have an official `parlimanetaryGroup`. One way to work around this is to assume that there is an unofficial `parlimanetaryGroup`. The other option is to directly indicate the party memberships. The drawback of the first option is mismatch with the reality, while the second one has the issues of undefined `from`/`to` dates. Any suggestions which way to go?

I would go for the second, as corresponds to reality. The affiliation element does not require temporal attribues, so, if you do not know, you just leave them out, possibly both.

>     * When/if we indicate party memberships, it is often that we know the end of the party affiliation (e.g., because of switch to another party), but we do not have the information about joining the party. This is mostly related to above case with MPs, but it may also be the case for non-MP frequent speakers (like ministers). It seems it is not allowed to specify `to` while leaving `from` unspecified. Is this intentional? Again, suggestions and earlier experiences are most welcome.

This seemed to be the sensible thing to do at the time, as a classical situation is that we know the "from", but not the "to" (as they are e.g. still a member of the party when ParlaMint ends.) But I see your point, so let's also allow `@to` without `@from`, as is now in 3103b07 (documentation branch for now). I haven't extensivelly tested it, I hope it works!

**Comment by TomazErjavec** [comment]
> maybe the re-iteration of our discussion is due to the fact that we never agreed whether the affiliation-information is to be interpreted using the _closed world_ or the _open world_ assumption.
> 
> I always assumed it to be interpreted in a _closed world_ scenario.
> 
> Given the following:
> 
> ```
> <affiliaton ref="#politicalParty.X" role="member" from="xxx" to="yyy"/>
> ```
> 
> The _closed world_ interpretation means: we state that somebody was a party member _exactly_ from date `xxx` to date `yyy` i.e. was _not_ a member before `xxx` or after `yyy`.
> 
> It was with this interpretation in mind that let me and e.g. @coltekin protest against the usage of "member" - because there just is _no way_ to retrieve a person's actual time-span for party-membership.
> 
> In a _open world_ scenario the above example only states that we know for sure that a person was a party member between `xxx` to ` yyy` - but we do not make _any_ statement / have no further knowledge about his/her party-membership before or after.
> 
> Switching to a "open world"-interpretation would probably get rid of the necessity to use the "representive" role in _one_ case (affiliation to a party) and "member" in another (affiliation to parliamentaryGroup) and could uniformly use "member". I do _not_ know how the interpretation actually is defined in TEI and whether it could (or must) be freely defined in the schema.

I am a bit confused by this, as my assumption was that if we don't know when somebody became (or stopped) being e.g. a member of a party (or whatever) that we simply do not give the `@from` or `@to` attribute. Is there anything wrong with this?

But, if you think there is, then I would defnitelly go for the _open world_ semantics. 

I've now added a new section on [Temporal attributes](https://clarin-eric.github.io/ParlaMint/#sec-temporal), in the hope of making the whole thing clearer. Let me know if it isn't.

**Comment by hpreki** [comment]
@TomazErjavec I consulted with some of our "TEI experts". According to them, the TEI guidelines do not decide on the open/closed interpretation. I consider this _good news_:  it  means we are free to chose what we want. 
And I fully agree with you that we should go for the  _open world_ interpretation! 
This will spare us a _lot_ of troubles.
It immediately  voids the whole discussion on _"We cannot use the "from" and "to" from a political period as values in the `<affiliation role="member" ref="politicalParty.X"/> because they are not the correct values for a person's (close to lifetime-period) _true_ membership period"_  

My colleague's proposal was, to document the fact that we are using   _open world_-semantics  in the `<encodingDesc>` for  affiliation. 
I will close _this_ issue.
