### ISSUE TITLE
validation - parliamentaryGroups?

### ISSUE THREAD

**Issue by lnnoemi** [clarin-eric/ParlaMint#385]
@matyaskopp (or anyone else): during validation, all my parliamentaryGroups are marked as errors, and the script says:
`value of attribute "role" is invalid; must be equal to "boardOfDirectors", "boardOfParliament", "chamberOfTheNations", "chamberOfThePeople", "coalition", "commission", "committee", "conferenceOfChairs", "delegation", "ethnicCommunity", "europeanParliament", "government", "independent", "institution", "internationalOrganizations", "interparliamentaryFriendshipGroup", "nationalCouncil", "ngo", "parliament", "politicalGroup", "politicalParty", "president", "senate", "subcommittee", "supervisoryBoard" or "workingGroup"`
Was there a change in the list of valid roles? Which one should I use for parliamentary groups?
And `"full": "abb"` is again an error, and the script requires `"init"` as a valid value - but earlier somewhere you agreed on using "abb". Is it possible that I use the wrong validation script, or what?

**Comment by lnnoemi** [comment]
And the same goes for my ministries.

**Comment by TomazErjavec** [comment]
It sounds to me like you are using some old version of the schemas. If you forked a long time ago, you should sync with upstream.
I hope this is the correct diagnosis, if not, I hope @matyaskopp will correct me!

**Comment by matyaskopp** [comment]
yes, @TomazErjavec is right. I have made a pull request into your repo to sync your data branch with the current state of this repo:
https://github.com/lnnoemi/ParlaMint/pull/1

**Comment by matyaskopp** [comment]
closing, as it seems to be solved
