### ISSUE TITLE
political orientation: shouldn't it be a property a politicalParty?  

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#386]
According to the example in
https://clarin-eric.github.io/ParlaMint/#sec-parties

political orientation is encoded as info on a  `parliamentaryOrganisation`  
I consider this a bug, not a feature. 
In both our sources of information - Wikipedia and [Chapel Hill Expert Surveys for Europe](https://www.chesdata.eu/ches-europe) (CHES) orientation is a property of a `politicalParty` and not of a  `parliamentaryOrganisation`. 

I deem `politicalParty` as one  of _the_   most important entities in any political corpus. It this seems strange to make them _optional_

**Comment by TomazErjavec** [comment]
> According to the example in https://clarin-eric.github.io/ParlaMint/#sec-parties 
> political orientation is encoded as info on a `parliamentaryOrganisation` I consider this a bug, not a feature. In both our sources of information - Wikipedia and [Chapel Hill Expert Surveys for Europe](https://www.chesdata.eu/ches-europe) (CHES) orientation is a property of a `politicalParty` and not of a `parliamentaryOrganisation`.

Yes, this is a complication. Strange how it never cropped up in #184. 

We (i.e. @jureskubic, @katjameden & me) try to address it in the Sec. "Dealing with parliamentary groups" in the [G'doc](https://docs.google.com/document/d/1dqEhWPUGugy-uYbgOvyMdbbUmioIUEIUXyY8zQAklZ0/edit?usp=sharing). It seemed the best we can do, but maybe others have a better suggestion.

> I deem `politicalParty` as one of _the_ most important entities in any political corpus. It this seems strange to make them _optional_

It's because ParlaMint centers around transcriptions, hence their speakers. And, as mentioned in some issues, you don't necessarily know which political party somebody belongs to, but you do know about their parliamentaryGroup membership. Or so I understand... And also very few corpora have both party + group membership recorded for their speakers.

Something to discuss at the meeting?

**Comment by hpreki** [comment]
> Something to discuss at the meeting?
Could be a good idea. I myself will not be able to attend. 

But it seems, that in the 
[G'doc](https://docs.google.com/document/d/1dqEhWPUGugy-uYbgOvyMdbbUmioIUEIUXyY8zQAklZ0/edit?usp=sharing) you  already were aware of that issue and proposed that orientation is encoded _both_ on the `politicalParty` and on the `parliamentaryOrganisation`. 
In the case of a 1:1 relationship between  `politicalParty` and  `parliamentaryOrganisation` (which in AT always is the case) this just means that we have some redundant information, but I do not really care.

**Comment by TomazErjavec** [comment]
> But it seems, that in the [G'doc](https://docs.google.com/document/d/1dqEhWPUGugy-uYbgOvyMdbbUmioIUEIUXyY8zQAklZ0/edit?usp=sharing) you already were aware of that issue and proposed that orientation is encoded _both_ on the `politicalParty` and on the `parliamentaryOrganisation`. 

To be honest, we weren't really at first, things used to be simpler in ParlaMint I, we just had "parties" (although @matyaskopp was never happy with this, cf. #38). But yes, orientation should be given to both PPs and POs.

> In the case of a 1:1 relationship between `politicalParty` and `parliamentaryOrganisation` (which in AT always is the case) this just means that we have some redundant information, but I do not really care.

Yes, we are counting bit on the fact that many pOs will 1:1 with pPs. I wonder what the end statistics will be.

This whole orientation business is more trouble than it is probably worth.

Shall we close this issue, as there are so many others?

**Comment by hpreki** [comment]
> This whole orientation business is more trouble than it is probably worth.

Probably true. 

> Shall we close this issue, as there are so many others?

Yes we can close it.
 
**Resolution:** political orientation will be encoded on both the `politicalParty` and the `parliamentaryOrganisation` as pointed out in [G'doc](https://docs.google.com/document/d/1dqEhWPUGugy-uYbgOvyMdbbUmioIUEIUXyY8zQAklZ0/edit?usp=sharing)
