### ISSUE TITLE
sample of bicameral system encoding

### ISSUE THREAD

**Issue by atomm** [clarin-eric/ParlaMint#387]
Hi, 
could anyone point me to a sample of a bicameral system encoded ? (preferably with lower/upper chambers?)

I am considering the possibility to extend IT corpus with data from the Chamber of Deputies (currently only covers Senate) or at least leave open the possibility for the future without the need to affect current Senate only encoding. 

Thanks, 
Tommaso

**Comment by matyaskopp** [comment]
You can see it in the CZ sample. We have proceedings from only the lower house, but there are guests from the upper house, so I have encoded their house too.

https://github.com/clarin-eric/ParlaMint/blob/757c1f8c0d5b3ae9dd299f369c462af8ef09da65/Data/ParlaMint-CZ/ParlaMint-CZ-listOrg.xml#L209-L253

https://github.com/clarin-eric/ParlaMint/blob/757c1f8c0d5b3ae9dd299f369c462af8ef09da65/Data/ParlaMint-CZ/ParlaMint-CZ-listOrg.xml#L254-L314
