### ISSUE TITLE
My validation failed

### ISSUE THREAD

**Issue by rjzevallos** [clarin-eric/ParlaMint#396]
Hello, 

I am working with Catalan and I have some problems when I validate my files. For example, we have a sentence of this form "se'n", which we split it into 2 tokens ["se","'n"] but when we annotate it in an ana.xml file, we try to put that token ["'n"]  is joined with the previous token using the tag "join". You can see this below.

`<w xml:id="ParlaMint-ES-CT_2018-01-17-0101.2.10.3.7" lemma="se" msd="UPosTag=PRON|Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes">se
</w>`

`<w xml:id="ParlaMint-ES-CT_2018-01-17-0101.2.10.3.8" join="left" lemma="ne" msd="UPosTag=PRON|Case=Gen|Person=3|PronType=Prs">'n</w>`

`

When validating, I get the error: "you can't add join tag". My question is, what label do I put to know that this token is joined with the previous one and I can validate correctly?

**Comment by matyaskopp** [comment]
You should use `@join="right"` in `#ParlaMint-ES-CT_2018-01-17-0101.2.10.3.7` not `@join="left"` on the following token. We are allowing only `@join="right"`.

In sample you provided I see one more issue... there shouldn't be spaces within token:
```XML
<w xml:id="ParlaMint-ES-CT_2018-01-17-0101.2.10.3.7" 
   lemma="se" msd="UPosTag=PRON|Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes">se<!--NO SPACE--></w>
```

**Comment by TomazErjavec** [comment]
To simplify processing, we just allow `@join="right"` (cf. the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-ana-words), so you should encode this as
```
<w xml:id="ParlaMint-ES-CT_2018-01-17-0101.2.10.3.7" join="right" lemma="se" msd="UPosTag=PRON|Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes">se</w>

<w xml:id="ParlaMint-ES-CT_2018-01-17-0101.2.10.3.8" lemma="ne" msd="UPosTag=PRON|Case=Gen|Person=3|PronType=Prs">'n</w>
```
(also note the delition of space after "se").

I am a bit worried about `Case="Acc,Dat"` but ConLL-U validation will screem if this is wrong.

**Comment by TomazErjavec** [comment]
Hehe, not only do @matyaskopp and me write exactly the same things, we even do it at the same time :)

**Comment by rjzevallos** [comment]
Thank you so much, I will try it.
