### ISSUE TITLE
document choice of "open-world"-semantics in  <encodingDesc>

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#397]
The fact, that `<affiliation>`-annotations are to be interpreted using the _open world_-assumption  should be made explicit in the `<encodingDesc>`  

Cf. #368

**Comment by hpreki** [comment]
@TomazErjavec and @matyaskopp  my initial enthusiasm, that our troubles just would _"disappear"_ if we just interpret the `affiliation/@from` and `@to`  under an _open world_-assumption came to an abrupt halt after giving the situation a second thought :-( 
Yes, the `open-world` scenario is perfect for the case of _party-membership_ where we lack exact temporal information. 
 But what's about all the other affiliations (the majority, I guess) where we _do_ have exact knowledge and want to convey that information: affiliations to `parliamentaryOrg` and affiliations as `minister` or `head` to `#GOV`. 
 Specifying that `from` and `to` follow the _open world_-interpretation would mean, that even for ministers the affiliation would just state a positive assertion that a person fulfilled that function in the specified period - but it does not make any claim about the _complete_ temporal extension of that period. 
 
 So we lean towards a `open-world`-interpretation for _one_ type of affiliation and  a `closed-world`-interpretation for all the others? 
 The only solution my colleagues came up with, was to add an _explicit_ tag to `affiliation` which specifies the intemded interpreation: - e.g.  have something like `affiliation @ana="(#openworld|#closedworld)"/>` 

Given the fact that it is somehow _5 minutes to 12_  and up to now none of the 30 partners in ParlaMint seemed to see any problem ... I am not sure whether this is practical.

So the probable choice would be  to  :see_no_evil:   for now :-(

**Comment by TomazErjavec** [comment]
Sorry if I am stupid, but I still don't understand why not just leave out `@from` and/or `@to` when we dont know a date?

**Comment by hpreki** [comment]
o.k. @TomazErjavec - maybe you are _not_ stupid at all... 

Let's check: 
I was under the impression, that the validation of membership periods was quite strict - @matyaskopp  ( I assume that you are writing the code for validation? ) could you confirm that validation would not fail when `<affiliation role="member"/>` come without any `from` and `to` ? 
When you validate temporal extensions you  _do_ make some assumptions on how to interpret undefined values. 
(e.g. I think you internally treat a missing `to`  as `to=<DATE_of_most_current_protocol>`).
 So are you o.k. with left-out `to` and `from` ?

**Comment by matyaskopp** [comment]
> @matyaskopp -- I assume that you are writing the code for validation? -- could you confirm that validation would not fail when <affiliation role="member"/> come without any from and to ?
I understand, that when you check temporal extensions you do make some assumptions on how to interpret undefined values.
(e.g. I think you internally treat a missing to as to=<DATE_of_most_current_protocol>).
So are you o.k. with left-out to and from ?

If there are no dates `@from` and  `@to`, I am making an assumption that the affiliation covers a full period of corpus
So yes, there is an issue if you skip these dates:
- the first reason could be that you don't have these dates
- the second can be that you are covering the full corpus period

so if you left out `@from` and  `@to`, you have to be sure that there is no collision in the time period of the corpus.

**Comment by hpreki** [comment]
Thanks for the confirmation @matyaskopp 

I  think/hope that in the AT corpus I can properly deal with that. 

> so if you left out @from and @to, you have to be sure that there is no collision in the time period of the corpus

Several persons will have died before the end of the corpus-coverage and maybe some are not yet born. But I guess your _"assumption that the affiliation covers a full period of corpus"_ is only used for checking conflicting affiliations and is not checked against a person's biological life period.

So altogether: I think the option to just leave out `from` and `to` for all the party-membership where we do not know any dates - will work for me and I will pursue that way.

**Comment by TomazErjavec** [comment]
> But I guess your "assumption that the affiliation covers a full period of corpus" is only used for checking conflicting affiliations and is not checked against a person's biological life period.

Exactly - we are interested in organisations only to the extent that they affect the status (inlc. affiliation with organisations) when they are speaking. Hopefully this won't happen with those not alive then :) 

> So altogether: I think the option to just leave out from and to for all the party-membership where we do not know any dates - will work for me and I will pursue that way.

Great. So, closing this.
