### ISSUE TITLE
PT: wrong values of note/@type

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#407]
@cluljoseaires, I just noticed that you use `note/@type="voting"`; could you pls. change it to `note/@type="vote"`, as suggested in the [definition](https://clarin-eric.github.io/ParlaMint/#TEI.note)?

You also use `note/@type="note"`:
```
<note type="note">Submetida à votação, foi aprovada, com votos a favor do PSD, do PS, do CDS-PP, do PCP e de Os Verdes e a abstenção do BE.</note>
```
I presume this is an error?

The validation does not catch this, as the values are only suggested, still, no reason to have slightly different or nonsensical values than the suggested ones. Also, we might change the values (after fixing them) to required.

**Comment by cluljoseaires** [comment]
Such tags are now fixed. Once I have fixed some other issues from your message I will do another pull request. I will send you the full set only when I have all the issues you pointed out in the mentioned message.
