### ISSUE TITLE
make text not working

### ISSUE THREAD

**Issue by lnnoemi** [clarin-eric/ParlaMint#411]
It's me, again, I'm sorry. :)

The validation scripts run without errors on all my files (I am now only testing the plain text format).
But make text-HU comes back with this: `/bin/sh: 1: parallel: not found`

Could you tell me what exactly this means?
Thanks!

**Comment by TomazErjavec** [comment]
@lnnoemi, first, you do not need to run text-HU: this target generates the plain-text files from the XML corpus, and is something that is run automatically on the samples, and that we will run on the complete corpus, once submitted.

That said, "[parallel](https://www.gnu.org/software/parallel/)" is a Unix commad that allows parallel execution of processes. So, if you want to run this command, you need to install it on your machine

**Comment by matyaskopp** [comment]
you don't have the command `parallel` in your system. If you have ubuntu-based system, you can install it with:
```bash
sudo apt-get install parallel
```
---
I will add checking into:
```bash
make check-prereq
```
and extend CONTRIBUTING file

**Comment by lnnoemi** [comment]
Ok, thanks. But `make-conllu` has to be tested on the linguistically annotated files before submitting, am I right?

**Comment by TomazErjavec** [comment]
> Ok, thanks. But `make-conllu` has to be tested on the linguistically annotated files before submitting, am I right?
You are. But this is independent of making the plain-text.
