### ISSUE TITLE
Obsolete projectDesc

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#415]
We forgot about the `<projectDesc>` element in the corpus root file (.ana included), and people now submitting their corpora still use the one from ParlaMint I, which goes like this:
```
<projectDesc>
<p xml:lang="en"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that
 aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded 
according to the <ref target="https://github.com/clarin-eric/parla-clarin">Parla-CLARIN recommendations</ref>
and covering the COVID-19 pandemic from November 2019 as well as the earlier period from 2015 to serve as 
a reference corpus; (2) process the corpora linguistically to add Universal Dependencies syntactic structures and 
Named Entity annotation; (3) make the corpora available through concordancers and Parlameter; and (4) build 
use cases in Political Sciences and Digital Humanities based on the corpus  data.</p>
</projectDesc>
```

Somewhat fortuitously, all this still holds for ParlaMint II, except "and Parlameter". Note also that the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-projectDesc) do in fact ommit this although leaving the text otherwise as it is. Nevertheless, more things could be written now. 

So, the question is @matyaskopp, shall we ask the partners to change the projectDesc? I would vote "yes", but maybe for 3.1.
The minimal change would be to delete "and Parlameter" (the change being supported by the current Guidelines), a more comprehensive one could be the suggested text as below:
```
<projectDesc>
<p xml:lang="en"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that
aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded
according to the <ref target="https://clarin-eric.github.io/ParlaMint/">ParlaMint encoding guidelines</ref>
and covering the period from 2015 to mid-2022; (2) add linguistic annotations to the corpora and
machine-translate them to English; (3) make the corpora available through concordancers; and (4) build
use cases in Political Sciences and Digital Humanities based on the corpus data.</p>
</projectDesc>
```

**Comment by matyaskopp** [comment]
Good spot!
Someone did not care about translating the description:
https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ.xml#L59-L62

Couldn't we add this "fixture" in the `parlamint-add-common-content.xsl` script?
once you will finalize the corpora, the English description can be changed (and other languages removed) in `projectDesc`.

**Comment by TomazErjavec** [comment]
> Someone did not care about translating the description

I know :) But you are not the only one. I would not insist on it in any case.

> Couldn't we add this "fixture" in the parlamint-add-common-content.xsl script?

Yes, very good idea.

> once you will finalize the corpora, the English description can be changed (and other languages removed) in projectDesc.

OK. I am still having problems with what it means for me to finalize the corpora and how this ties in with make, but that is another topic.

**Comment by TomazErjavec** [comment]
> Couldn't we add this "fixture" in the parlamint-add-common-content.xsl script?

I now put changing the projectDesc in parlamint2finalxsl:
https://github.com/clarin-eric/ParlaMint/blob/cd6df7f48df59c6caf1c35779d37f349de344341/Scripts/parlamint2final.xsl#L52-L62
https://github.com/clarin-eric/ParlaMint/blob/cd6df7f48df59c6caf1c35779d37f349de344341/Scripts/parlamint2final.xsl#L245-L247
https://github.com/clarin-eric/ParlaMint/blob/cd6df7f48df59c6caf1c35779d37f349de344341/Scripts/parlamint2final.xsl#L390-L392

This was because I forgot that we said it should go into add common-content.xsl. As people have already sumbitted data, I think it would be best if it were (for now) in both scripts?
