### ISSUE TITLE
Bugs in CZ.ana

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#43]
Some details:
- for the .ana documents the top level title stamp is "[ParlaMint.ana]" (in all files)
- as mentioned, you also need the standard NER taxonomy

I see you are committed to your ud-syn prefixDef: https://github.com/clarin-eric/ParlaMint/blob/ba0b5015c6755ff67d9477938a63069083d0fe54/ParlaMint-CZ/ParlaMint-CZ.ana.xml#L865

Are you sure? Your corpus will be different from all the others, and conversions to other formats (like for the concordancer) won't work. 

The pdt prefixDef is also of the same ilk: https://github.com/clarin-eric/ParlaMint/blob/ba0b5015c6755ff67d9477938a63069083d0fe54/ParlaMint-CZ/ParlaMint-CZ.ana.xml#L870

First, the `../pdt-fslib.xml` certaily wont work for others. If you do want to include it with your corpus, then, sure, do, but have the file then just `pdt-fslib.xml` as it will be in the same dir as the rest (you could even XInclude it in the root). In both cases, I don't think you need xpath, just have `pdt-fslib.xml#1` (or if you XInclude, just `#1`).

And the component files look really nice.

**Comment by matyaskopp** [comment]
Closing issue. The only unsolved task is named entities: #46 and #41
