### ISSUE TITLE
CZ: missing party status info + xi namespace on relation

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#433]
In CZ data the speeches go back to 2013-11-2, but coalition/opposition info is only available from 2014-01-29 onwards. Is this an oversight?

Another thing I noticed is that relation elements have suprious XInclude namespace:
https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ-listOrg.xml#L8027
can you get rid of this?

**Comment by matyaskopp** [comment]
> In CZ data the speeches go back to 2013-11-2, but coalition/opposition info is only available from 2014-01-29 onwards. Is this an oversight?

No, it is not a bug. It is possible to have coalition and opposition when you have government and a signed coalition agreement. We usually have a new government 1-2 months after the election (or first meeting  2013-11-02):

https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ-listOrg.xml#L52-L55

Till then, an old government is working with limited power.

> Another thing I noticed is that relation elements have suprious XInclude namespace:
> 
> https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ-listOrg.xml#L8027
> 
> 
> can you get rid of this?

I will take a look.

**Comment by TomazErjavec** [comment]
>No, it is not a bug.

OK, great, thanks for the explanation and sorry for doubting you! 

> I will take a look.

Not really urgent, it does not harm, it's just ugly to look at.
