### ISSUE TITLE
date format in teiHeader//date elements

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#434]
There are multiple date formats in the `teiHeader` context. Some of them are "language safe", but some of them are language specific where an `xml:lang` attribute should be added.

this produces English format (or system language format?? not sure):
https://github.com/clarin-eric/ParlaMint/blob/49c3aef87a4010a30f50bd58764168a5130a718d/Scripts/parlamint-add-common-content.xsl#L677-L683
https://github.com/clarin-eric/ParlaMint/blob/49c3aef87a4010a30f50bd58764168a5130a718d/Scripts/parlamint2final.xsl#L371-L377 

Possible solutions:
1. do not care
2. care about `xml:lang` when we(finalizing scripts) modify dates
3. unify all dates in the header to an English format (the similar way how the numbers are treated)

**Comment by TomazErjavec** [comment]
@matyaskopp, you are right that this is sloppy. I don't know how to convince XSLT and esp. Saxon to output localised strings, on the other hand, why bombard people with English at all costs. So I would actually suggest:

4. change content of date to be the ISO date string, so, e.g. `<date when="2022-11-07">2022-11-07</date>`.  

This is languge neutral, and everybody can understand it. Do you agree? 
If so, I can change the cases where this occurs in dev.

**Comment by matyaskopp** [comment]
> This is languge neutral, and everybody can understand it. Do you agree?
> If so, I can change the cases where this occurs in dev.

Yes, agree - it is the safest option

Summary of task:
remove and replace all text values `//teiHeader//date/text()` with this format:
  - when `date/@when`: `YYYY-MM-DD`
  - when `date/@from`: `YYYY-MM-DD -`
  - when `date/@to`: `- YYYY-MM-DD`
  - when `date/@from` and `date/@to`: `YYYY-MM-DD - YYYY-MM-DD`

in `parlamint2final.xsl`

**Comment by TomazErjavec** [comment]
> remove and replace all text values //teiHeader//date/text() with this format

Not sure I agree here, I wouldn't change the date format for the dates that the partners have already inserted themselves, as they seem to be (like in CZ! and DK) already formatted according to national rules, so why destroy it?
I thought we were talking about the format for the release date that I insert in parlamint2final and you in parlamint-add-common-content.
