### ISSUE TITLE
HU feedback

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#435]
@lnnoemi nice work, this is a huge improvement of the ParlaMint-HU corpus! 
I have a few observations that can help you make your corpus better and more comparable with other ParlaMint corpora.

 ## GitHub sample is missing the un-annotated version
- [x] un-annotated version

## English content in `resp` element in the Hungarian context
- [x] root file - wrong content in `resp` element
https://github.com/lnnoemi/ParlaMint/blob/86e0935d9f1aaa54ede9c09e655c1bd4f002a89b/Data/ParlaMint-HU/ParlaMint-HU.ana.xml#L15-L19 
```XML
            <respStmt>
               <persName>Noémi Ligeti-Nagy</persName>
               <resp>ParlaMint TEI XML corpus encoding</resp>
               <resp xml:lang="en">ParlaMint TEI XML corpus encoding</resp>
            </respStmt>
```
the next `resp` element is in the right context but it does not contain `xml:lang` element:
```XML
            <respStmt>
               <persName>Réka Dodé</persName>
               <persName>Kinga Jelencsik-Mátyus</persName>
               <persName>Zsófia Varga</persName>
               <resp>Metaadatok gyűjtése és rendszerezése</resp>
               <resp xml:lang="en">Metadata collection and organization</resp>
            </respStmt>
```

## wrong url in bibl
- [x] wrong `//bibl/idno/text()` in corpus root file
- [x] wrong `//bibl/idno/text()` in component files

there is repeated `https://`
https://github.com/lnnoemi/ParlaMint/blob/86e0935d9f1aaa54ede9c09e655c1bd4f002a89b/Data/ParlaMint-HU/ParlaMint-HU.ana.xml#L66-L71
```XML
            <bibl>
               <title type="main" xml:lang="hu">A Magyar Országgyűlés ülései</title>
               <title type="main" xml:lang="en">Minutes of the National Assembly of Hungary</title>
               <idno type="URI">https://https://www.parlament.hu/</idno>
               <date from="2014-05-06" to="2022-06-14">2014.05.06 - 2022.06.14.</date>
            </bibl>
```
it was mentioned here  #108, where I suggested that I could fix this in v2 to v3 conversion, but now you have nicely processed data without running additional scripts so I suggest fixing this in your pipeline to avoid propagation of this error in the future ParlaMint releases.

## missing subtype 'parliament' in `//bibl/idno`
- [x] missing `//bibl/idno/@subtype` in corpus root file
- [x] missing `//bibl/idno/@subtype` in component files

```XML
<bibl>
  ...
  <idno type="URI" subtype="parliament">...</idno>
  ...
</bibl>
```

## speaker notes are inside `u` element
- [x] move `//note[@type="speaker"]` before utterance `u`
documentation (https://clarin-eric.github.io/ParlaMint/#sec-notes) says:
> The first note simply gives the speaker of the utterance that would follow it

so
```XML
         <div type="debateSection">
            <u xml:id="u2014.05.06-0" who="#AderJanos" ana="#guest">
               <note type="speaker">DR. ÁDER JÁNOS köztársasági elnök</note>
               <seg xml:id="u2014.05.06-0.1">
               ...
               </seg>
           ...
           </u>
         ...
         </div>
```
should be
```XML
         <div type="debateSection">
            <note type="speaker">DR. ÁDER JÁNOS köztársasági elnök</note>
            <u xml:id="u2014.05.06-0" who="#AderJanos" ana="#guest">
               <seg xml:id="u2014.05.06-0.1">
               ...
               </seg>
           ...
           </u>
         ...
         </div>
```

## `relation/passive` should refer to the organization, not the event
- [x] relation/passive

https://github.com/lnnoemi/ParlaMint/blob/86e0935d9f1aaa54ede9c09e655c1bd4f002a89b/Data/ParlaMint-HU/ParlaMint-HU-listOrg.xml#L671-L676
```XML
      <relation name="opposition"
                from="2014-06-06"
                to="2018-05-07"
                ana="#OGY.7"
                passive="#GOV.10"
                active="#parliamentaryGroup.JOBBIK.7 #parliamentaryGroup.LMP.7 #parliamentaryGroup.MSZP.7"/>
```
 `GOV.10` is an event in the organization:
https://github.com/lnnoemi/ParlaMint/blob/86e0935d9f1aaa54ede9c09e655c1bd4f002a89b/Data/ParlaMint-HU/ParlaMint-HU-listOrg.xml#L11-L14
```XML
         <event xml:id="GOV.10" from="2014-06-06" to="2018-05-17">
            <label xml:lang="hu">Harmadik Orbán-kormány (2014. június 6 - 2018. május 17.)</label>
            <label xml:lang="en">3rd Orbán-government (6 June 2014 - 17 May 2018)</label>
         </event>
```

## merging similar parliamentary organizations into one with multiple events
- [x] merge parliamentary organizations

This was originally suggested for CZ corpus by @TomazErjavec, but unfortunately, I am not able to find proof of this in issues or in email. 

The situation is that you have multiple organizations with the same name that are reestablished in every legislative period, eg:
```XML
   <org xml:id="parliamentaryGroup.Fidesz.7" role="parliamentaryGroup">
      <orgName full="yes" xml:lang="hu">A Fidesz – Magyar Polgári Szövetség parlamenti frakciója a 7. parlamenti ciklusban</orgName>
      <orgName full="yes" xml:lang="en">Parliamentary group of the Fidesz – Hungarian Civic Alliance in the 7th parliamentary term</orgName>
      <orgName full="abb">Fidesz-frakció</orgName>
      <event from="2014-05-06" to="2018-05-07">
         <label xml:lang="en">existence</label>
      </event>
   </org>
   <org xml:id="parliamentaryGroup.Fidesz.8" role="parliamentaryGroup">
      <orgName full="yes" xml:lang="hu">A Fidesz – Magyar Polgári Szövetség parlamenti frakciója a 8. parlamenti ciklusban</orgName>
      <orgName full="yes" xml:lang="en">Parliamentary group of the Fidesz – Hungarian Civic Alliance in the 8th parliamentary term</orgName>
      <orgName full="abb">Fidesz-frakció</orgName>
      <event from="2018-05-08" to="2022-05-01">
         <label xml:lang="en">existence</label>
      </event>
   </org>
   <org xml:id="parliamentaryGroup.Fidesz.9" role="parliamentaryGroup">
     ...
      <event from="2022-05-02">...</event>
   </org>
```
these organizations can be merged into one, and every current organization can be transformed into an event. See CZ sample:
https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Data/ParlaMint-CZ/ParlaMint-CZ-listOrg.xml#L5407-L5429

note that this also has consequences for 
1. affiliations:
 - appending current `@ref` into `@ana` attribute
 - and `@ref` should contain a reference to an organization
2. relations - relations should be among organizations, not events

@TomazErjavec, do you still insist on this? (CZ has already implemented that)

**Comment by TomazErjavec** [comment]
> @TomazErjavec, do you still insist on this?

Yes, the various converson won't work otherwise. And, anyway, it is then consistent internally and between corpora.

**Comment by lnnoemi** [comment]
Thanks, @matyaskopp, I updated the files and managed to update the sample as well.
By non-annotated version, you meant the txt-s? I created them with `make text-HU`, I hope it's fine.

**Comment by matyaskopp** [comment]
> By non-annotated version, you meant the txt-s? I created them with make text-HU, I hope it's fine

no I meant `ParlaMint-HU.xml` and component files that was not in revision I have been reviewing:
https://github.com/lnnoemi/ParlaMint/tree/86e0935d9f1aaa54ede9c09e655c1bd4f002a89b/Data/ParlaMint-HU

In the current revision, you have these files: https://github.com/lnnoemi/ParlaMint/tree/de7c93937436c91b25d459437981e260f2bb83ca/Data/ParlaMint-HU

**Comment by matyaskopp** [comment]
> @matyaskopp , does the missing ticks ('missing subtype') mean that I still have to do sg with that? I think I fixed that, but probably not.

You haven't solved it in annotated version of files

> I had to update the `listPerson` with some missing roles, but now I am unable to push the data, could you please help me? I get `remote: Permission to clarin-eric/ParlaMint.git denied to lnnoemi`. I may mess up something with the authentication.

You are not allowed to push data into clarin-eric repository, you have to push it into your repository.
Firstly, please sync your fork: https://github.com/lnnoemi/ParlaMint/pull/6
