### ISSUE TITLE
Validating presence of join attribute

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#442]
We now already have a case where an .ana corpus does not contain any `//tei:*[self::tei:w or self::tei:pc]/@join`, and it might happen again. @matyaskopp, do you think you could add this check to your validation?

**Comment by matyaskopp** [comment]
Ok, seeing this issue, two possible types of validation cross my mind.

### statistical validation

use some expected amount in corpus/file and show a warning or error:
- `//@join` 
  - error if `0.8 * count(//s) > count(//tei:*[self::tei:w or self::tei:pc]/@join)`
  - warning if `1.2 * count(//s) > count(//tei:*[self::tei:w or self::tei:pc]/@join)`

and in this way, we can count other stats:
- name/@type
- number of adjected speeches of the same speaker
- compare `count(distinct-values(meeting[contains(@ana,'#parla.sitting)']/text()))` and `count(distinct-values(setting/date/@when))` (see #438 )
  


### unannotated version reconstruction

The idea is to take annotated TEI.ana version and transform it into an unannotated version and compare it with the original TEI. There should be a defined normalization for comparison. Only `/TEI/text` content is possible to compare this way, and it also expects that there are no elements in the TEI version that are added during annotation (or normalization should handle it).

It is probably too crazy...

**Comment by TomazErjavec** [comment]
I would not mix stats with this validation (but we definitelly should have scripts for lots of fancy stats, and I think we already have some, but they could be improved), and your solutions are more complex than I was thinking of. My reasoning was that it would be enough to check that `//@join` exists in each .ana file, and be done with it. The logic being, either they will have them (and they will presumably be correct), or they will forget them, and we should throw an error.
There could in theory be a problem that the text is so short and even without punctuation that it legitimatelly has no `@join`. But I would argue that such a degenerate text should not be a corpus component.

**Comment by TomazErjavec** [comment]
This has been implemented as above, closing.
