### ISSUE TITLE
Bugs in RO samples

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#45]
Great first sample, the only error I see is `w/@who`, this must be a reference to an ID, and IDs cannot contain spaces, colons etc. so e.g. "#Florin-Claudiu Roman:"  won't work. But I guess you will fix this once you have the root file with proper person descriptions. 

Also, if you could (redundantly) specify the type of corpus on the text element as well like `<text ana="#covid">`.

**Comment by TomazErjavec** [comment]
@RePierre, about 2b44bd80d68dcf0a3698f2f7c6cc66c4b0d757e6: 
- where is the root file?
- I don't understand the structure, some files are in top folder, some in year folders
-  you don't have >1000 files, so actually no need to put them in year folders
- some funny chars (admitedly with low frequency) in chars-RO.tbl, maybe  have a look and get rid of them
- is this supposed to be the complete corpus? Because this repo is really meant for small samples only

**Comment by RePierre** [comment]
I'm terribly sorry, this Pull Request should have been initiated on a fork of this repository, not the main one. I messed up the names of the remotes.

The intent of the Pull Request was to validate that the application we created outputs proper XML files. I will create another Pull Request to keep only a small sample of files in the repository.

**Comment by TomazErjavec** [comment]
> I will create another Pull Request to keep only a small sample of files in the repository.

OK, great, looking forward to it!
