### ISSUE TITLE
fix filename validations

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#452]
only one `_` is allowed in component filenames: https://clarin-eric.github.io/ParlaMint/#sec-files
- `ParlaMint-XX_YYYY-MM-DD(-[-A-Za-z0-9]+)?.xml`
- `.` is not allowed too !!!

**Comment by hpreki** [comment]
@matyaskopp  I will modify my filenames accordingly. 

Of course that means that  internal `xml:id` of subordinate elements need to be adapted as well.

This brings me to 2 questions concerning the nomenclature of `xml:id` :
 
1) According [3.3. Attributes of top-level elements](https://clarin-eric.github.io/ParlaMint/#sec-roottags)

> subordinate elements in the transcription that have an ID (...) should have the top level xml:id as a prefix

In `ParlaMint-CZ` I see that for `*.ana.xml`-files the top-level id of the file is `xyz.ana` but the subordinate elements use the id _without_ the  `.ana` part. Is this the proper way to go? 
 
2) `@xml:id`  of subordinate elements _should_ reflect the hierarchical structure + numbering: i.e. something like `<top-level-id>.u1.p1.s1.w1`. 
Does _"should"_ mean this is _mandatory_  ?  My `<u>` and `<seg>` do  have randomly generated ids: I.e. my ids are like `<top-level-id>.<random-id-for-p>.s1.w1`.  Can I get away with this or do I need to fix all existing `xml:id`  _a posteriory_ ? (no rocket science -- but I rather would only do if it's actually _required_)

**Comment by TomazErjavec** [comment]
> This brings me to 2 questions concerning the nomenclature of xml:id

The two points your bring up are nice in theory but in practice most corpora don't follow them (and we don't really do any validaton on this). So, I think I should really change "should" to "are recommended".

**Comment by TomazErjavec** [comment]
OK, did this. Close?

**Comment by matyaskopp** [comment]
no, I will improve validation of **filenames**, and then I will close it
