### ISSUE TITLE
AT feedback

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#453]
You have provided sampled pull request, so I can't give better feedback. E.g., it seems that you have only `chair` speeches from these samples.

### linguistic annotations mentioned in TEI version
- [x] fix `<resp>` content in TEI version (root+component)

no lingv. annotation has been done in TEI version (only in TEI.ana), so it shouldn't be mentioned here
https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT.xml#L25-L29
```XML
        <respStmt>
          <persName>Hannes Pirker</persName>
          <resp xml:lang="de">Datenbeschaffung, Korpuskodierung in TEI und automatische linguistische Annotation</resp>
          <resp xml:lang="en">Data retrieval, TEI corpus encoding and automatic linguistic annotation</resp>
        </respStmt>
```
### missing ')' in funder
- [x] missing ')' (TEI and TEI.ana) x (root and component files)

https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT.xml#L47
```XML
          <orgName xml:lang="en">CLARIN-ERIC (Common Language Resources and Technology Infrastructure—European Research Infrastructure Consortium</orgName>
```

### only one '_' should be in the component filename
- [x] rename component files

https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT.xml#L179-L181

```XML
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-AT_1996-01-15-020_XX_NRSITZ_00001.xml"/>
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-AT_2010-03-24-024_XXIV_NRSITZ_00057.xml"/>
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-AT_2022-04-27-027_XXVII_NRSITZ_00153.xml"/>
```
I will improve the validation soon: https://github.com/clarin-eric/ParlaMint/issues/452

### description of nametag
- [x] application description

I guess you have used nametag script from the ParCzech pipeline. It does the conversion of nested named entities into four (PER,...). But model you have used does not recognize nested entities, so this comment is senseless: 
>  Posprocessing: nested named entities has been merged to four categories (PER, LOC, ORG, MISC).

https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT.ana.xml#L169-L172
```XML
        <application ident="NameTag" version="2">
          <label>NameTag 2 (german-conll-200831 model)</label>
          <desc>Name entity recognition done with NameTag 2 (<ref target="http://ufal.mff.cuni.cz/nametag/2">http://ufal.mff.cuni.cz/nametag/2</ref>) with german-conll-200831 model (<ref target="http://hdl.handle.net/11234/1-3443">http://hdl.handle.net/11234/1-3443</ref>). Posprocessing: nested named entities has been merged to four categories (PER, LOC, ORG, MISC).</desc>
        </application>
```

### missing `<meeting>` sitting in component files
- [x] `//meeting[contains(@ana,"#parla.sitting")]` 

you can use a date or replace `parla.session` with `parla.sitting`, I don't know what makes more sense.

### moving tailing `note` outside utterance
- [x] tailing notes

Tailing notes can be moved outside utterance:
https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT_2010-03-24-024_XXIV_NRSITZ_00057.xml#L154-L157

```XML
        <u who="#PAD_04476" xml:id="ParlaMint-AT_2010-03-24-024_XXIV_NRSITZ_00057_d7e8321" ana="#chair">
          <seg xml:id="ParlaMint-AT_2010-03-24-024_XXIV_NRSITZ_00057_d2e206">Für diese Sitzung hat das Bundeskanzleramt über Vertretung von Mitgliedern der Bundesregierung folgende Mitteilung gemacht: Der Bundesminister für Land- und Forstwirtschaft, Umwelt- und Wasserwirtschaft Dipl.-Ing. Nikolaus Berlakovich wird durch den Bundesminister für europäische und internationale Angelegenheiten Dr. Michael Spindelegger vertreten.</seg>
          <note type="time"><time when="2010-03-24T10:02:01+01:00">10:02:01</time></note>
        </u>
```

### `relation/@passive` should refer to organization
- [x]  `relation/@passive`
https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT-listOrg.xml#L500-L503
```XML
	     <relation name="opposition" from="1983-05-24" to="1986-06-16"
                active="#politicalParty.ÖVP"
                passive="#GV.42.Sinowatz"
                ana="#NR.XVI"/>
```
you can move event references into `@ana` and for `@passive` use government
```XML
	     <relation name="opposition" from="1983-05-24" to="1986-06-16"
                active="#politicalParty.ÖVP"
                passive="#GOV"
                ana="#NR.XVI #GV.42.Sinowatz"/>
```

### namespace not needed
- [x] remove namespace from org
https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT-listOrg.xml#L217
```XML
            <org xmlns:tei="http://www.tei-c.org/ns/1.0" xml:id="GOV" role="government">
```

### follow recommended order of organizations
- [ ] org order

government - parliament - the rest of organizations
I can't find it in the documentation now, but it is/was definitely there. @katjameden, please help

### invalid idno type and missing subtype
- [x] idno  `type="parlament.gv.at"`
- [x] idno `type="wikidata.org"`

https://github.com/hpreki/ParlaMint/blob/e962a6232d90da77e5a6927deb6615e232958c8c/Data/ParlaMint-AT/ParlaMint-AT-listPerson.xml#L27
```XML
    <idno type="parlament.gv.at">https://www.parlament.gv.at/WWER/PAD_00024/index.shtml</idno>
```
should be
```XML
 <idno type="URI" subtype="parliament">https://www.parlament.gv.at/WWER/PAD_00024/index.shtml</idno>
```

https://github.com/hpreki/ParlaMint/blob/data/Data/ParlaMint-AT/ParlaMint-AT-listPerson.xml#L15573
```XML
    <idno type="wikidata.org">https://www.wikidata.org/wiki/Q1253</idno>
```
should be
```XML
 <idno type="URI" subtype="wikimedia">https://www.wikidata.org/wiki/Q1253</idno>
```
sorry for this all should be in the documentation, but there is only issue: 
- https://github.com/clarin-eric/ParlaMint/issues/173#issuecomment-1122276595

**Comment by katjameden** [comment]
> ### follow recommended order of organizations
> * [ ]  org order
> 
> government - parliament - the rest of organizations I can't find it in the documentation now, but it is/was definitely there. @katjameden, please help
> 
I've checked the Guidelines and the corpora from the ParlaMint 2.1 - there is some confusion when it comes to the order of the organisations:
The Chapter on organisations in the [Guidelines ](https://clarin-eric.github.io/ParlaMint/#sec-orgs) describes organisations in the following order: "Information on the the government, parliament, political parties or parliamentary groups of political parties, as well as other optional parliamentary structures". The subchapters are also structured in that order (so government, parliament and then parliamentary groups/political parties). 

But:

-  for some of the corpora in ParlaMint 2.1 (SI, NL, GB etc), the parliament is at the top of the the <listOrg> list; while some followed the government, parliament, political parties order
- some listOrg.xml files, that are already in the master/Data folders, (e.g., PT), Presidency is at the top of the list, followed by parliament and then government, while GR starts with parliament and then government
- CZ follows the order, stated in the current Guidelines of government, parliament and then parliamentaryGroups/politicalParties

 so we should probably decide for a specific order, and stick to it (as well as stating the decision clearly in the Guidelines).

**Comment by hpreki** [comment]
> You have provided sampled pull request, so I can't give better feedback
@matyaskopp  I thought that only sampled data is allowed in the pull-request. What is your preferred way to receive more / unsampled data? Can I simply push a few full-files?

**Comment by matyaskopp** [comment]
> @matyaskopp I thought that only sampled data is allowed in the pull-request. What is your preferred way to receive more / unsampled data? Can I simply push a few full-files?

the best is to push full XML files (without conllu, tsv, txt,...), but be careful about 100MB limit.
The samples are made when the pull request is merged.

**Comment by matyaskopp** [comment]
> But can they just be "original-original"? Or is it still required to add `SAMPLE` to the main title? :

original, 'SAMPLE' is added automatically when data pull request is merged

**Comment by TomazErjavec** [comment]
> follow recommended order of organizations

@matyaskopp, I agree it would be aesthetically pleasing to have the (types of) organisations in the same order for all corpora but in practice it doesn't really matter in which order they come. Still, given the nice analysis by @katjameden, I have now modified the [text](https://clarin-eric.github.io/ParlaMint/#sec-orgs) (last paragraph/list) to recommend a specific order, also indicating which ones are obligatory. Let me know if you spot errors or if it could be written better.

I would not now try to force partners to rearrange their orgs, but would do that for 3.1, either that they do it, or via add-common-content. Which makes me think that we should have a list of ToDos for 3.1, so we don't forget. I will open another issue about this.

**Comment by matyaskopp** [comment]
> I would not now try to force partners to rearrange their orgs, but would do that for 3.1, either that they do it, or via add-common-content. Which makes me think that we should have a list of ToDos for 3.1, so we don't forget. I will open another issue about this.

makes sense.

**Comment by hpreki** [comment]
@matyaskopp @TomazErjavec : 

> Tailing notes can be moved outside utterance

Is this a _can_   or a _must_ ?  I can see some aesthetic appeal in your recommendation :-)   But maybe you noticed, that I in fact we have quite a number of tailing notes in `<seg>` - so I suppose I also would need to  move  _these_ out  as well ?  And then there are things like `<kinetics>` which I view just as "special purpose-notes-in-disguise": would it be required to also move these? etc. etc. 
_Short_: do you _insist_ on the moving out? Otherwise  I probably will not touch the `<notes>` for now.

**Comment by matyaskopp** [comment]
> _Short_: do you _insist_ on the moving out? Otherwise I probably will not touch the `<notes>` for now.

You should first solve other issues/suggestions this should be the last to solve because I see it as the least important.
The documentation says (https://clarin-eric.github.io/ParlaMint/#sec-comments)

> Apart from head elements, transcriber comments are encoded using the [`<note>`](https://clarin-eric.github.io/ParlaMint/#TEI.note) element or one of several so called ‘incident’ elements, as explained below. These elements can be placed directly inside [`<div>`](https://clarin-eric.github.io/ParlaMint/#TEI.div), [`<u>`](https://clarin-eric.github.io/ParlaMint/#TEI.u) or [`<seg>`](https://clarin-eric.github.io/ParlaMint/#TEI.seg). **It is recommended to place them as far up the hierarchy as possible**, and, if possible, avoid having them inside [`<seg>`](https://clarin-eric.github.io/ParlaMint/#TEI.seg) (which contains text), as placing these elements there leads to mixed content, which is difficult to process further, in particular when linguistically annotating the corpus. However, if a transcriber comment is placed in the middle of the text, then it needs to be encoded inside the segment, except if the utterance is split, as is further explained in the Section on [Interrupted utterances](https://clarin-eric.github.io/ParlaMint/#sec-interruptions).

You saw that end notes and tailing spaces made troubles to my udpipe annotation script.

I don't insist on it significantly I am just pointing out that there is something contrary to the recommendation.

@TomazErjavec, I am leaving the last say in this up to you.

**Comment by TomazErjavec** [comment]
This is only recommended, not required, as it says in the Guidelines. I would require it, but it happens - at least with some corpora- that the notes are inside the segment (so, text before and after), so you can't necessarily avoid mixed content in any case.

**Comment by hpreki** [comment]
Thanks for your feedback. I think I will be able to supply an updated version of Parlat-AT tomorrow with all your currently proposed corrections in place -- with the exception of the `<note>`-moving. I am "optimistic" that you will be able to spot additional issues in the new data, so I will consider the `<note>`-moving for the next release-iteration.

**Comment by hpreki** [comment]
@matyaskopp : I pushed a new commit. It now also contains 1 file without any `<u>`  

`ParlaMint-AT_1999-10-28-020-XX-NRSITZ-00183.ana.xml:       <desc xml:lang="en">This protocol does not contain any debates</desc>`
This is a feature not a bug - there are protocols of "debate-less" sittings, and  therefore  I wanted to check, how your system deals with that special cases.

**Comment by TomazErjavec** [comment]
My feeling here is that some validation or processing will freak out, as ParlaMint is centred around transcriptions, and in this context having a component without any utterances does not make much sense. 

I guess we could e.g. relax content models to not require u, but I wonder if this is the right way to go, as this will by definition also mean less strict validation. Also, downstream format or applications will have problems, e.g. what is a CoNLL-U file wihtout any data, or a vertical file that has empty text elements - the indexing will freak out. 

So, hm, I am a bit sceptical about this excercise.

**Comment by matyaskopp** [comment]
@hpreki 
result of your experiment - createSample fails.
https://github.com/clarin-eric/ParlaMint/actions/runs/3531514011

I do not have now the capacity to check what is wrong, I would rather give feedback to other partners on their data. So @hpreki  please remove the file, create a new pull request and report this error in a separate issue.

**Comment by hpreki** [comment]
I created a fresh pull request, this time without the one sample that doesn't contain any <u>.

  I understand the status quo, that I will also completely leave out the "debate-less" TEI when providing the full data.

**Comment by matyaskopp** [comment]
> @matyaskopp @TomazErjavec any additional feedback from your side?
> If not, I will try to provide the "full-data-zip" tomorrow.

you still have missing ')' in component files but I am not insisting on fixing this, I leave it up to you.
https://github.com/clarin-eric/ParlaMint/blob/3ff634290fc5ace6665fe98489990d4985df97ef/Data/ParlaMint-AT/ParlaMint-AT_1996-01-15-020-XX-NRSITZ-00001.xml#L58

You can deliver full data.

**Comment by TomazErjavec** [comment]
Not from my side either, so, yes, go ahead pls. If possible, put the data on a http server, rather than cloud, and let me know where either by email or here. We can then keep the same 2 URLs for any subsequent corpus sending.

**Comment by hpreki** [comment]
@TomazErjavec :  I sent you the Download-link via email. Sorry, for today I have to use a cloud-share. 
@matyaskopp : I could not resist and also fixed that missing ")": do you want me to create a new pull-request for the sample data? Or do we let it rest for now, and see what problems are going to pop up when you inspect the full-data?

**Comment by matyaskopp** [comment]
> @matyaskopp : I could not resist and also fixed that missing ")": do you want me to create a new pull-request for the sample data? Or do we let it rest for now, and see what problems are going to pop up when you inspect the full-data?

No, need to upload a new sample. I think we (@TomazErjavec or @matyaskopp)  will push all new samples when the data are released to be sure that samples are derived from data in the v3.0 release.

**Comment by matyaskopp** [comment]
Closing as everything important has been done.
@hpreki, thanks for your punctilious work
