### ISSUE TITLE
validate-parlamint.pl works only with `xi:` prefix in include

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#457]
validation of component files is bypassed when a different prefix is used
https://github.com/clarin-eric/ParlaMint/blob/bdb2f597aaf1ce1204a5e88384b8d625ac989f09/Scripts/validate-parlamint.pl#L58

it seems that only HU (@lnnoemi) data used different prefixes:
https://github.com/clarin-eric/ParlaMint/blob/27a2e17b15896cb58938aae7a4130ba3dc85fd49/Data/ParlaMint-HU/ParlaMint-HU.xml#L184-L191

@lnnoemi, can you please change the prefix and rerun the validation of your corpus to be sure that it is valid?
You can use this taxonomy: https://github.com/clarin-eric/ParlaMint/blob/devel/Data/Taxonomies/ParlaMint-taxonomy-UD-SYN.ana.xml
to fix
```
ERROR ParlaMint-HU_2014-05-06.ana: ERROR: Can't find local id for link/@ana="ud-syn:obl"
```

**Comment by matyaskopp** [comment]
the error was discovered because script [Scripts/corpus2sample.xsl](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/corpus2sample.xsl) is changing the namespace to `xi` and the HU sample didn't pass the validation.

**Comment by lnnoemi** [comment]
Sure, I'm sorry, I'll fix that (first on the sample, then on the whole corpus).
But I don't know why to use that taxonomy, could you explain that?

**Comment by matyaskopp** [comment]
because your taxonomy does not contain `obl`. 
That taxonomy contains every documented relation in universal dependencies, eg missing `obl`:
https://github.com/clarin-eric/ParlaMint/blob/639f0c1baff04ea46b446677c8f6192922569f17/Data/Taxonomies/ParlaMint-taxonomy-UD-SYN.ana.xml#L1127

You can also add it to your taxonomy. But in ParlaMint v3.1, we plan to make taxonomy unification so that all corpus share common taxonomies. So in the next releases, this taxonomy will be appended to your corpus.

**Comment by matyaskopp** [comment]
@TomazErjavec, I think we should enforce (documentation+validation) a `xi` prefix because it is more foolproof for our future validations. Do you agree?

**Comment by TomazErjavec** [comment]
It would make our job easier, true, but strictly speaking, in the XML world the name of the namespace prefix is irrelevant, as long as it is bound to the correct URI. 
The proper way of dealing with this would be to write a new XSLT script that returns all the XIncluded filenames, call it in Perl, get the result, and then let Perl process the files It is a bit of work, but not too much.
What do you think?

**Comment by matyaskopp** [comment]
> It would make our job easier, true, but strictly speaking, in the XML world the name of the namespace prefix is irrelevant, as long as it is bound to the correct URI.

ok

> The proper way of dealing with this would be to write a new XSLT script that returns all the XIncluded filenames, call it in Perl, get the result, and then let Perl process the files It is a bit of work, but not too much.
What do you think?

For me is the proper way to create `libParlaMint.pm` package. Every script can use it just use it:
```Perl
use libParlaMint;
my $corpus = libParlaMint->new($filepath);
my $componentList = $corpus->getComponentFiles();
my $headerList = $corpus->getHeaderFiles();
```

**Comment by matyaskopp** [comment]
> For me is the proper way to create `libParlaMint.pm` package. Every script can use it just use it:
> 
> ```perl
> use libParlaMint;
> my $corpus = libParlaMint->new($filepath);
> my $componentList = $corpus->getComponentFiles();
> my $headerList = $corpus->getHeaderFiles();
> ```

it is probably better, but it needs more prerequisites installed `XML::LibXML`, so it is not an option for everyone...

So I will use your suggestion:

> The proper way of dealing with this would be to write a new XSLT script that returns all the XIncluded filenames, call it in Perl, get the result, and then let Perl process the files It is a bit of work, but not too much.

**Comment by TomazErjavec** [comment]
I agree that "most natural" would be to use LibXML, but we use XSLT so much that one more won't hurt. Btw, it is probably possible to catch STDOUT from XSLT in Perl, so a temporary file is not needed. If I understand correctly, you will write this (not complaining, but not insisting either, as I wrote [validate-parlamint.pl](https://github.com/clarin-eric/ParlaMint/blob/bdb2f597aaf1ce1204a5e88384b8d625ac989f09/Scripts/validate-parlamint.pl).

**Comment by matyaskopp** [comment]
@TomazErjavec done, closing
