### ISSUE TITLE
ToDo for 3.1

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#461]
Now that 3.0 is slowly taking shape, it would be good to start gathering things we know we (aready) need to do for 3.1, so we don't forget. I am not quite sure what the best place for this is, would it simlpy be this issue, or can there be a better way? E.g. we could make 3.0 and 3.1 milestones and start assinging issues to them. @matyaskopp, what do you think?

**Comment by matyaskopp** [comment]
I will setup all milestones: 3.0, 3.1, 3.2.
New data are great inspirations for new types of validations. We can implement it with a WARNING if they are expected in the following milestone and then change it to ERROR. So milestones are a good solution.

**Comment by matyaskopp** [comment]
done: https://github.com/clarin-eric/ParlaMint/milestones?direction=asc&sort=due_date&state=open

**Comment by TomazErjavec** [comment]
Lovely. I fiddled with dates and desc of 3.0 and assigned the "next" corpus specific issues to "3.0". We have now some "next" and a lot no-milestone issues. We can slowly add them to milestones. And come up with new ones of course!
