### ISSUE TITLE
Finding what lines are causing errors

### ISSUE THREAD

**Issue by amandanwadkwe** [clarin-eric/ParlaMint#462]
Hi,

When I run a validation script I get all these errors and have no way of telling what line are causing the error and why. How do you suggest I go about this please?

The errors:

`ERROR[03] : Wrong affiliation ref=#parla.lower`
 `Non-standard role 'minister' - invalid affiliation role with parliament organization in DeanRussell affiliation [affiliation from="2022-09-20" ref="#PoGB" role="minister" to="2022-10-27" /]`
 `INFO[01] : affiliation collision: (2018-01-09 --- 2018-07-19) has one day overlap with (1500-01-01 --- ) affiliation (line:) minister-#PoGB`
 `ERROR[15] : Non-standard role 'minister' - invalid affiliation role with parliament organization in StuartAndrew affiliation [affiliation from="2017-06-15" ref="#PoGB" role="minister" to="2018-07-19" /]`
 `WARN[08] : Affiliate from date (2003-06-13T00:00:00) is P2531D before PoGB organization beginning (2010-05-18T00:00:00)`
 `ERROR[12] : Total number of organizations with government role: 0`

**Comment by matyaskopp** [comment]
I have added back printing line numbers when running validation with:
```bash
make check-content-XX
```

It is not possible to add it easily into validate-parlamint.pl because it creates temporary files. Free Saxon does not provide information about line numbers, so I have created temporary files and added the additional attribute `LINE`

**Comment by amandanwadkwe** [comment]
Thank you very much
