### ISSUE TITLE
Element u with ill-formed @who

### ISSUE THREAD

**Issue by rjzevallos** [clarin-eric/ParlaMint#467]
Hello, when I run 

`make check-content-ES-CT`

I get this error

ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.1.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.2.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.3.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.4.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.5.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.6.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.7.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.8.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.9.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.10.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.11.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.12.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.13.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.14.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.15.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.16.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.17.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.18.0
ERROR ParlaMint-ES-CT_2018-01-17-0101.ana: Element u with ill-formed @who ParlaMint-ES-CT_2018-01-17-0101.19.0

My files are in https://github.com/IULATERM-TRL-UPF/ParlaMint/tree/main/Data/ParlaMint-ES-CT

**Comment by matyaskopp** [comment]
```XML
            <u xml:id="ParlaMint-ES-CT_2018-01-17-0101.1.0" who="MuroXavier" ana="member" xml:lang="ca">
```
Attribute `who` should be the reference (`#MuroXavier`), your TEI version is ok, but annotated version is wrong.


BTW `ana="member"` should be `ana="#regular"` (also reference)

**Comment by rjzevallos** [comment]
Great!! Thank you so much.
