### ISSUE TITLE
make conllu not working

### ISSUE THREAD

**Issue by rjzevallos** [clarin-eric/ParlaMint#468]
Error when I run 

`make conllu-ES-CT`

rm -f Data/ParlaMint-ES-CT/*.conllu
test -f Data/ParlaMint-ES-CT/ParlaMint-ES-CT.ana.xml \
  && Scripts/parlamint2conllu.pl Data/ParlaMint-ES-CT Data/ParlaMint-ES-CT \
  || echo "WARNING skipping/failing conllu-ES-CT"
/bin/sh: 2: Scripts/parlamint2conllu.pl: not found
WARNING skipping/failing conllu-ES-CT

**Comment by matyaskopp** [comment]
you can try to run this if you haven't removed the file:
```sh
ls -l Scripts/parlamint2conllu.pl
```
it is this file: https://github.com/IULATERM-TRL-UPF/ParlaMint/blob/data-ES-CT/Scripts/parlamint2conllu.pl

**Comment by rjzevallos** [comment]
I got this

-rwxrwxrwx 1 nyro22 nyro22 4224 Nov 16 19:26 Scripts/parlamint2conllu.pl

**Comment by TomazErjavec** [comment]
And this: https://github.com/clarin-eric/ParlaMint/blob/data/Scripts/parlamint2conllu.pl
So, weird.

**Comment by matyaskopp** [comment]
Try to switch from `sh` to `bash`

or run just
```
Scripts/parlamint2conllu.pl Data/ParlaMint-ES-CT Data/ParlaMint-ES-CT
```
without makefile
