### ISSUE TITLE
Allow @pos <w>

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#47]
We have a local tagset which does not have a decomposition into feature-structures. Could we use the pos-attribute in <w>?

**Comment by matyaskopp** [comment]
I use [Lingua::Interset](https://metacpan.org/release/Lingua-Interset) for transforming between tagsets. Is not your tagset listed in supported tagsets?

**Comment by TomazErjavec** [comment]
>  Could we use the pos-attribute

Added `w/@pos` and `pc/@pos.`

> I use Lingua::Interset for transforming between tagsets. Is not your tagset listed in supported tagsets?

Icelandic is ineed not supported. But even if it were, I don't see why Interset (and I'm not saying it is not a great tool) would solve anything here: they already have the UD features, the point is that they would like to retain the PoS tagging of their "native" tagset.

**Comment by matyaskopp** [comment]
> Icelandic is indeed not supported. But even if it were, I don't see why Interset (and I'm not saying it is not a great tool) would solve anything here: they already have the UD features, the point is that they would like to retain the PoS tagging of their "native" tagset.

I misunderstand the problem and was not able to connect GitHub name with language. So my point is wrong,

**Comment by TomazErjavec** [comment]
OK, now we know. Still, good that you pointed out Interset, I forgot about it, and it might come in handy as some point.
