### ISSUE TITLE
Local validation

### ISSUE THREAD

**Issue by nemeek** [clarin-eric/ParlaMint#470]
I would like to do local validation, but `make val-schema-EE`  says:
```
mkdir -p Data/TMP/ParlaMint-EE
test -f Data/ParlaMint-EE/ParlaMint-EE.xml \
  && java -jar /usr/share/java/saxon.jar -xi:on -xsl:Scripts/copy.xsl -s:Data/ParlaMint-EE/ParlaMint-EE.xml -o:Data/TMP/ParlaMint-EE/ParlaMint-EE.xml \
  && java -jar /usr/share/java/jing.jar Schema/parla-clarin.rng                 Data/TMP/ParlaMint-EE/ParlaMint-EE.xml \
  || echo "WARNING skipping/failing val-schema-tei-ParlaCLARIN-EE"
Unknown option -xi:on
```
Do I have wrong version of saxon?
```
SAXON 6.5.5 from Michael Kay
```

**Comment by matyaskopp** [comment]
The default system Saxon is very poor, you have to use Saxon-HE: https://saxon.sourceforge.net/

This should fail in your case:
```
make check-prereq
```

**Comment by nemeek** [comment]
Yes, `make check-prereq` failed in first place.
Now
```
Saxon: OK
Jing: OK
```
make fails on Scripts/tools/validate.py
There is no such file. Where should tools/validate.py come from?

**Comment by matyaskopp** [comment]
Everything is described in [CONTRIBUTING.md](https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md)

**Comment by TomazErjavec** [comment]
So, not so hidden after all :)

**Comment by nemeek** [comment]
Yes, thank you, now I can see that it comes from UniversalDependencies. I had done a fresh clone, thatswhy I was missing the file.

**Comment by TomazErjavec** [comment]
Great; if all ok, pls. close this issue.
