### ISSUE TITLE
NO feedback

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#473]
## missing root title translation
- [x] root title translation (TEI + TEI.ana)

https://github.com/tungland/ParlaMint/blob/1c385b6acce7a1459878c377a79dec4672af6d7d/Data/ParlaMint-NO/ParlaMint-NO.ana.xml#L8-L9
```XML
            <title type="main" xml:lang="en">Norwegian parliamentary corpus ParlaMint-NO [ParlaMint SAMPLE]</title>
            <title type="sub" xml:lang="en">Transcriptions of the Norwegian Parliament, Stortinget, 1997-2022</title>
```

## missing taxonomies translations
- [x] taxonomies translations

Please translate all taxonomies (except `ud-syn`) into `nob`.

## idno type and subtype
- [x] idno

Please use the correct encoding of URLs (https://clarin-eric.github.io/ParlaMint/#TEI.idno) 
eg:
https://github.com/tungland/ParlaMint/blob/1c385b6acce7a1459878c377a79dec4672af6d7d/Data/ParlaMint-NO/ParlaMint-NO.xml#L353
```XML
<idno type="wikimedia" xml:lang="nob">https://no.wikipedia.org/wiki/Stortinget</idno>
```
should be
```XML
<idno type="URI" subtype="wikimedia" xml:lang="nob">https://no.wikipedia.org/wiki/Stortinget</idno>
```

## term / session / meeting / sitting
- [x] root file

You are missing terms in your data, and you are encoding parliamentary years as a `session` which is correct (I believe), But your data miss terms (`parla.term`).

- [x] component file

Every component file contains one sitting day, so it should also contain a corresponding `meeting` element. Furthermore there should be also specified term and session and probably title should be fixed too, because it is saying something different from meeting element:

https://github.com/tungland/ParlaMint/blob/1c385b6acce7a1459878c377a79dec4672af6d7d/Data/ParlaMint-NO/ParlaMint-NO_1999-03-02-lower.xml#L11-L13
```XML
<title type="sub" xml:lang="nob">Referat fra møte i Stortinget, periode 1997-2001, sesjon 1998-1999</title>
<title type="sub" xml:lang="en">Hansard from meeting in the Norwegian Parliament, Session 1997-2001, Sitting 1998-1999</title>
<meeting ana="#parla.lower #parla.session #ST.1998-1999" corresp="#OT">Session 1998-1999</meeting>
```
Can be encoded this way (if it makes sense in the Norwegian domain):
```XML
<title type="sub" xml:lang="nob">Referat fra møte i Stortinget, <!--Term--> 1997-2001, sesjon 1998-1999, <!--Sitting day 1999-03-02--></title>
<title type="sub" xml:lang="en">Hansard from meeting in the Norwegian Parliament, Term 1997-2001, Session 1998-1999, Sitting day 1999-03-02</title>
<meeting ana="#parla.lower #parla.term" corresp="#OT" n="1997-2001">Term 1997-2001</meeting>
<meeting ana="#parla.lower #parla.session #ST.1998-1999" corresp="#OT" n="1998-1999">Session 1998-1999</meeting>
<meeting ana="#parla.lower #parla.sitting" corresp="#OT" n="1999-03-02">Sitting day 1999-03-02</meeting>
```

## note is splitting paragraph
- [x] insert note inside paragraph

https://github.com/tungland/ParlaMint/blob/1c385b6acce7a1459878c377a79dec4672af6d7d/Data/ParlaMint-NO/ParlaMint-NO_1999-03-02-lower.xml#L118-L120
```XML
<seg xml:id="ParlaMint-NO_1999-03-02-lower.segd164e45">Statsråd Anne Enger Lahnstein la fram 2 kgl. proposisjonar</seg>
<note>(sjå under Referat)</note>
<seg xml:id="ParlaMint-NO_1999-03-02-lower.segd164e45s1">.</seg>
```
Source:
```XML
<a type="minnrykk">
<uth type="sperret">Statsråd Anne Enger Lahnstein</uth>
la fram 2 kgl. proposisjonar (sjå under Referat).
</a>
```
Expected encoding:
```XML
<seg xml:id="ParlaMint-NO_1999-03-02-lower.segd164e45">Statsråd Anne Enger Lahnstein la fram 2 kgl. proposisjonar<note type="comment">(sjå under Referat)</note>.</seg>
```

## weird notes:
- [x] merge note with speakernote

I believe that this kind of notes can be merged with speaker note:
https://github.com/tungland/ParlaMint/blob/1c385b6acce7a1459878c377a79dec4672af6d7d/Data/ParlaMint-NO/ParlaMint-NO_1999-03-02-lower.xml#L193-L198
```XML
            <note type="speaker">Trond Helleland (H)</note>
            <u who="#person.TROH"
               ana="#regular"
               xml:id="ParlaMint-NO_1999-03-02-lower.ud164e135"
               xml:lang="nob">
               <note>(ordfører for saken):</note>
```
Source:
```XML
<navn>Trond Helleland (H)</navn>
<merknad> (ordfører for saken): </merknad>
```
Suggested encoding:
```XML
            <note type="speaker">Trond Helleland (H) (ordfører for saken):</note>
            <u who="#person.TROH"
               ana="#regular"
               xml:id="ParlaMint-NO_1999-03-02-lower.ud164e135"
               xml:lang="nob">
```

## weird note types
- [x] non-english note types

You have a huge amount of non-English note types (eg `type="ordennr`). Please use recomended values: https://clarin-eric.github.io/ParlaMint/#TEI.note

## debate section without utterances
- [x] debate section

I have opened an issue to discuss this #472

## element `name` is missing `type`
- [x] `name/@type`

https://clarin-eric.github.io/ParlaMint/#sec-ner
```XML
<name>
  <w lemma="Hedstrøm"
      xml:id="ParlaMint-NO_1999-03-02-lower.ana.segd164e71.2.6.1"
      msd="UPosTag=PROPN|Case=Gen">Hedstrøms</w>
</name>
```

**Comment by tungland** [comment]
Hi @matyaskopp 

note is splitting segment:
1. Is this a hard requirement? We would prefer to keep it like this.
2. In your expected encoding, where are the <u> tags? Are they parallel with the new note tag or is the note nested within the u tag as well?

**Comment by tungland** [comment]
Deleted a previous comment, as it was based on a misreading

**Comment by matyaskopp** [comment]
> 1) Is this a hard requirement? We would prefer to keep it like this.

Yes, you are breaking sentences when you split paragraphs with notes in the middle of sentences. I guess you don't have notes inside words, so there shouldn't be a problem.

> 2) In your expected encoding, where are the tags? Are they parallel with the new note tag or is the note nested within the u tag as well?

I am not sure what you mean by the word `tag`...
I hope an answer is here https://clarin-eric.github.io/ParlaMint/#sec-comments :
> It is recommended to place them as far up the hierarchy as possible, and, if possible, avoid having them inside `<seg>` (which contains text), as placing these elements there leads to mixed content, which is difficult to process further, in particular when linguistically annotating the corpus. However, if a transcriber comment is placed in the middle of the text, then it needs to be encoded inside the segment...

You should place the note outside most - so if it is on the sentence border, it should be outside `<s>` element, but if it is in the sentence, then it should be on the `<w>` level.

**Comment by tungland** [comment]
1: Your answer is a little ambiguous  - you are saying the correction is a hard requirement, yes?

2:  I meant to ask about the `<u>` tag, but forgot to mark it up as code, so the u became invisible. Anyway the question was based on that I had gotten `<u>` and `<seg>` mixed up, so please disregard it.

**Comment by TomazErjavec** [comment]
> 1: Your answer is a little ambiguous - you are saying the correction is a hard requirement, yes?

Let me answer: yes, correction is necessary, so that sentences are not split.

**Comment by matyaskopp** [comment]
section without utterances should be now typed `commentSection` (https://github.com/clarin-eric/ParlaMint/issues/472#issuecomment-1325414863) eg:
```XML
         <div type="commentSection">
            <note type="time">Møtet slutt kl. 13.20.</note>
         </div>
```

**Comment by tungland** [comment]
Thanks for the feedback @matyaskopp !

> strange segmentation

It seems the tokenizer interprets "kgl." as the end of the sentence. That would indeed be an issue with the model...

**Comment by matyaskopp** [comment]
@tungland Thanks for the changes it is much better now.

I have to admit that I still don't understand the Norwegian bicameral-unicameral situation
These are the numbers of affiliations:
```
  INFO[10]  Total number of affiliations with ST: 3537
  INFO[10]  Total number of affiliations with LT: 14
  INFO[10]  Total number of affiliations with OT: 12
```
The lower and upper house have only `head` and `deputyHead` members, and it seems that all these lower/upper house members are affiliated with ST(The Storting, the Norwegian Parliament)  as `member`s.
All parliament organizations have existed since 1814, and lower+upper house disappeared on 2009-10-01.

Is it what you want to encode? From the outside, without knowing Norwegian conditions, it looks weird. 

Are there any proceedings from meetings of the lower and upper house parliament organizations?

**Comment by tungland** [comment]
@matyaskopp the problem is that the system pre-2009 was odd. Before then, there was what I at least think of as a pseudo-bicameral system. Briefly put, the parliament was formally unicameral, but at the start of every parliament the MPs themselves would appoint some of from their own ranks to act as an upper house. This system was a compromise, and by the late 1990s seems to have been mostly a formality. So most meetings took place with the joint assembly, but we also have transcripts from the "lower house" and "upper house". These are usually sparser. 

The reason for the affiliations is that in the data we are working with, only the presidency of the "lower house" and "upper house" are recorded, while the regular MPs are just decscribed as being MPs.

**Comment by tungland** [comment]
This system was abandoned in 2009 in favour of a regular unicameral system

**Comment by tungland** [comment]
> regular MPs are just decscribed as being MPs.

I.e. for the regular MPs, it is not described what their affiliation is. This information was not digitized, and so we did not get it from the parliament in time to include it with this project. And most debates happens in the whole chamber, it did not seem super important to have these. On the contrary, it could make more sense to remove the extra "lower house" and "upper house" transcripts as from what I have seen they are not very valuable.

**Comment by tungland** [comment]
> I.e. for the regular MPs, it is not described what their affiliation is.

In terms of the "lower house" and "upper house". They are only attached to the full parliament.

**Comment by matyaskopp** [comment]
Thanks, now I understand it better. It is a pity that the information on members of the upper and lower houses is not reachable. You can mention it in the documentation to avoid confusion.

I believe that your sample is now valid, so I am merging it into data branch
