### ISSUE TITLE
IT: errors and failures in validation with make conllu-IT

### ISSUE THREAD

**Issue by valeq** [clarin-eric/ParlaMint#474]
The Italian corpus is now complete also in the linguistically annotated version. It passes all validations, except for make conllu-IT which returns a few errors ("FAILED"). Overall 74 segments (in 71/1388 sessions, about the 0,05% of the sentences) contain at least 1 error.  
In 209 cases we have error messages, as follows: 
 [L1 Format missing-empty-line] Missing empty line after the last sentence.   ==  56
 [L2 Metadata text-extra-chars] Extra characters at the end of....            ==   9
 [L2 Syntax unknown-head] Undefined HEAD ....                                 ==  14
 [L2 Syntax non-tree] Non-tree structure.                                     ==   3
 [L2 Format skipped-corrupt-tree]                                             ==   3
 [L2 Syntax root-is-not-0]                                                    ==  18
 [L1 Format reversed-word-interval] Spurious token interval                   ==  64
 [L1 Format number-of-columns] The line                                       ==  38
 [L1 Unicode unicode-normalization]                                           ==   2 
 [L1 Format empty-column]                                                     ==   2

At manual inspections it looks like two types of errors depend in fact on the Stanza parser and seems to occur in particularly long or unusual utterances/sentences. 
These are [L1 Format reversed-word-interval] Spurious token interval, due to Stanza erroneously creating a multiword token with only one subtoken. (e.g. id 24-24); and [L2 Syntax root-is-not-0], due to multiple main roots in the same sentence.  

In these two cases however the sentence is entirely converted to conllu.

In all other cases (except for one case of a greek char unrecognised as unicode), the errors are generated because the produced conllu is incomplete, but we are not able to understand what failed during conversion, since apparently the original xml.ana is correct. 

Any idea on how to deal with these?

**Comment by matyaskopp** [comment]
> [L2 Syntax root-is-not-0] == 18

This can be fixed easily (udpipe has the same bug) -> replace `root` relation inside tree with `dep` relation:
https://github.com/clarin-eric/ParlaMint/blob/c5fd7aaee29b18cf537a84850d41c4930250de51/Data/Taxonomies/ParlaMint-taxonomy-UD-SYN.ana.xml#L563-L564

For the rest of the issues, I need to see the data.
Can you add the samples of the wrong files to the repository?

**Comment by matyaskopp** [comment]
> It seems a bit harsh to require the partners to correct mistakes made by a thrid-party tool, esp. as the mistakes won't be really corrected, but fixed just enough to validation to pass.

Yes, it is. I am not insisting on fixing everything, but it would be great to fix two easy situations:
- `root` in the middle of tree -> `dep` 
- root node does not have `root` relation

> That said, I'm not sure what to do then. I could easly fix the parlamint2conllu.xsl script not to die when encountering such errors, but just issue a warning, but then the UD CoNLL-U validation would not pass afterwards.

I don't like that if one sentence is wrong, then the full file fails.
- sentence can be skipped if corrupted this way
- add a comment inside conllu file at the place where should be the sentence

> @matyaskopp, does a fail in CoNLL-U validation cause a fail in Actions? If not, I could modify the conversion to just warning, and we would live with less than perfect CoNLL-U. If yes, we have a problem.
> I guess your heuristic to fix the tree could be impemented (for everybody) in the parlamint2conllu.xsl script but that is a lot of work, and I don't have time for it now. And even if it were there, it would take care of just one of a number of possible errors...

Yes, the conversion does not fail the action(I believe but not tested). I just grep for the word `error` and fail it at the end. I think we can start with skipping sentences in conversion, and we will see if another issue arises.

**Comment by robertobartolini** [comment]
Hi, thanks for the reaction... first of all I didn't understand the log file well and I only checked the "FAILED" string and the lines starting with "[L1" and "[L2" seemed to me the descriptions of the errors.... actually not I had checked the "ERROR" errors (perhaps generated by java or python scripts) which blocked the production of the conllu file.... now seeing those lines it is clear where the error is. At this point I figured out how to fix almost all of the errors. In the specific case of element without head relation, I made an error: sometimes Stanza generates a <PAD> relation which made the XML validation fail: I fixed the error incompletely by removing the <PAD> relation and thus passing the validation.... now I can replace the <PAD> relation with the "dep" relation and it should work for both validation and make conllu.

**Comment by robertobartolini** [comment]
the relation generated by Stanza that didn't let me pass the validation is called PAD surrounded by angle brackets, I noticed that in my previous post it was deleted from the github editor perhaps due to the angled brackets....

**Comment by TomazErjavec** [comment]
> the relation generated by Stanza that didn't let me pass the validation is called PAD surrounded by angle brackets, I noticed that in my previous post it was deleted from the github editor perhaps due to the angled brackets....

I know this one well, and I replace `<PAD>` with `dep`, as I guess you do. (and, yes, you need to put angle brackets inside backticks). I'm glad you managed to resolved the problems.

@matyaskopp, will get back about your comments to my comments!

**Comment by matyaskopp** [comment]
> I know this one well, and I replace `<PAD>` with `dep`, as I guess you do. (and, yes, you need to put angle brackets inside backticks). I'm glad you managed to resolved the problems.

I thought it was a problem in udpipe https://github.com/ufal/udpipe/issues/143, but it seems that Stanza likes `<pad>` too.
