### ISSUE TITLE
HR: too large components 

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#475]
All corpora in ParlaMint should have the component files by, at least, individual dates, and their filenames like "ParlaMint-HR_2016-01-01.xml". Quite a few things depend on this, not the least that the file sizes are small enough so they can be processed in a reasonable amount of time, and that GitHub does not fail when running Actions on submitted files. 

But if I understand correctly, HR even in ParlaMint II does not have individual dates but rather complete sessions in one file, e.g. "ParlaMint-HR_T05_S01.xml"  which has a wrongly formatted filename, spans several months, with the (linguistically unannotated) files already have more than 10M, and the .ana version will be at least 10x bigger.

This will cause *lots* of problems all over the place. Is there really no way to distinguish individual dates, so that we can have like "ParlaMint-HR_2016-01-01.xml"?

**Comment by nljubesi** [comment]
All three corpora, Croatian, Serbian, Bosnian, do not have date information in the data obtained by the ERC project, our upstream. What we could do to make the files of more reasonable size is to include N+ segments in each file and then move over to the next file once an agenda point (we have those) is finished. WIth that we would not abruptly move between files inside a discussion, but would also probably not move between files between days neither.

If this is the way to go, I am interested in 1. a reasonable number of segments per file, I would say 500-1000, and 2. whether ParlaMint-HR_2016-01-01-p01.xml (if the session has started on 2016-01-01) is a good naming schema.

**Comment by TomazErjavec** [comment]
> All three corpora, Croatian, Serbian, Bosnian, do not have date information in the data obtained by the ERC project, our upstream. 

I thought as much, drat.

> What we could do to make the files of more reasonable size is to include N+ utterances in each file and then move over to 
the next file once an agenda point (we have those) is finished. WIth that we would not abruptly move between files inside a discussion, but would also probably not move between files between days neither.

That sounds like the best we can do, @matyaskopp, do you agree? Because a number of files will then have the same from - to dates in `<setting>` I am a bit worried that some processing will freak out, as the assumption was that each file covers a separate time span - but maybe it will be ok, we would have to try it out. Note that each file has to have a different title, but that is not hard, just end it with "part 2/10" (like 2 out of 10) or something similar.
 
> If this is the way to go, I am interested in 1. a reasonable number of utterances per file, I would say 500-1000, 

This seems a bit much, others seem to have 100 or less. It would help if I would see how many HR has now per file, but it seems each one has just one (probably the division into utterances has not be done yet or something).

> and 2. whether ParlaMint-HR_2016-01-01_p01.xml (if the session has started on 2016-01-01) is a good naming schema.

Almost, you don't want the second underscore. So, ParlaMint-HR_2016-01-01-p01.xml

**Comment by nljubesi** [comment]
Okay, there has been a development in between - I went to double-check (pretty sure we discussed this previously) with the data donor, and we might be able to obtain dates for the data, but it is very unclear (the main donor is moving to another country as we speak).

Let us wait for us to check, quite likely during the next week, whether we can really obtain dates for all the speeches, and we will reconvene if it shows that we will have to split files by other criteria than date.

**Comment by TomazErjavec** [comment]
Great, fingers crossed! It would really be wonderful if we had it by day.

**Comment by nljubesi** [comment]
@TomazErjavec @matyaskopp We have the dates for all three languages, and they are valid, except for some very future typoish ones that we corrected. However, there are still rather large days (more than thousand utterances) that, I guess, would still need splitting. Is splitting allowed? We would split simply on every N-th utterance (I was thinking 500) as these are lengthy outliers anyway.

**Comment by 5roop** [comment]
We estimate that if components were on day-basis, the biggest would be 11 Mb. The fourth largest file would be 6 Mb, by the seventh they are already < 1 Mb. Is this too big?

**Comment by TomazErjavec** [comment]
11 Mb does indeed sound large to me, esp. as the .ana variant is then 10-20 times larger. If this is the case, then, yes, we would need splits into, say, about 1M or, maybe even better, 500k.

I am a bit confused though, as I had a look at V2.1 HR files, which are grouped according to sessions:  here the largest is ParlaMint-HR_S16.xml with 19M, 14,532 utterances and spans 2020-01-17 - 2020-05-17, i.e. four months. So, how can a per-date split be more than half as large? And also larger than the files of any other country? Except if you are talking about linguistically annoated files?

**Comment by nljubesi** [comment]
After some additional inspections (we could not find anything wrong with the large files in the first round) we realised that the distribution of number of utterances per agenda has a ridiculously high number of identical values (different agendas having the exact same number of utterances), which are quite likely very nasty duplicates (the agenda titles differ only in codes of laws being discussed), so we will reconvene after a short break on tricky near-duplicate removal.

**Comment by TomazErjavec** [comment]
OK, great, I thought there was something fishy. Not that I am glad you have more work - good luck with dedup!
