### ISSUE TITLE
Do we insist on subtitle?

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#480]
@TomazErjavec, I have doubts if we insist on `//titleStmt/title[@type="sub"]`. I believe that we are insisting on that, but now I have doubts because it is a repeated error even in old-parters corpora.

The documentation is a bit fussy for me: https://clarin-eric.github.io/ParlaMint/#sec-titleStmt
because it is not clear if the text about the titles describes just a sample or describes a general rule for all corpora.

**Comment by matyaskopp** [comment]
> So, my suggestion would be to leave things as they are, and not require it. Do you agree?

ok, agree. So the only required is the main title (unique + country and en lang)

**Comment by TomazErjavec** [comment]
>ok, agree. So the only required is the main title (unique + country and en lang)

Unique yes, but not necessarily both languages:
* submitted DK has only en
* GB will obviously have only en
