### ISSUE TITLE
idno in publicationStmt

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#486]
In my current version of ParlaMint-IS the value of idno in publicationStmt is http://hdl.handle.net/11356/1388, which is the handle of ParlaMint 2.0. Have you already created a handle for ParlaMint 3.0? If not, does it matter what the value is since you will probably automatically update it later?

**Comment by TomazErjavec** [comment]
The handles are given in [Milestone 3.0](https://github.com/clarin-eric/ParlaMint/milestone/4), but you are right, they get inserted anywy in the finalization step. Still, if you want your copy to already have the correct handle (and version number 3.0) then best do it at your end.
