### ISSUE TITLE
NL feedback (TEI version)

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#501]
@RubenvanHeusden, nice work. I like you have been able to encode ministries fully.
Still, I have a few remarks:

## Surprisingly small amount of members of parliament
- [x] MPs amount
```
INFO[10]  Total number of affiliations with TK: 6
INFO[10]  Total number of affiliations with EK: 4
```

## annotation of notes
- [x] head
- [x] comment

I guess these types of notes, can be encoded as [`head`](https://clarin-eric.github.io/ParlaMint/#TEI.head):
https://github.com/RubenvanHeusden/ParlaMint/blob/8821a7bbcd479585197c99805a5e1c5138c93399/Data/ParlaMint-NL/ParlaMint-NL_2021-02-11-tweedekamer-5.xml#L84
```XML
<note>Wetsvoorstellen tot samenvoeging en herindeling van gemeenten</note>
```
can be:
```XML
<head>Wetsvoorstellen tot samenvoeging en herindeling van gemeenten</head>
```

and stenographers notes should be [`comment`](https://clarin-eric.github.io/ParlaMint/#TEI.note)
https://github.com/RubenvanHeusden/ParlaMint/blob/8821a7bbcd479585197c99805a5e1c5138c93399/Data/ParlaMint-NL/ParlaMint-NL_2021-02-11-tweedekamer-5.xml#L91
```XML
<note>De algemene beraadslaging wordt geopend.</note>
```
should be
```XML
<note type="comment">De algemene beraadslaging wordt geopend.</note>
```

## missing speaker notes
- [x] speaker notes
![image](https://user-images.githubusercontent.com/5867995/205580209-6166dd1a-e52c-4ce3-b104-c763f5c90593.png)
Arguments for not discarding them are here: https://github.com/clarin-eric/ParlaMint/issues/448#issuecomment-1315149199
> ... I think that speaker notes shouldn't be skipped:
> 
> * You made an assumption based on these notes that the referred person in `who` is the speaker. But it is still an assumption, so adding the source(the note) of this assumption makes complete sense.
>   
>   * why assumption? There can be name duplicity, or the note can be wrong, but if you include a note, you can at least prove that you did not fabricate the speaker attribution.
> * I am not aware of any other corpus that does not encode these notes = being consistent with others
 
## Session or sitting?
- [x] session/sitting fix/add
- [x] `/TEI/@ana`

I don't understand the NL conditions, can you check if the definition of session:
https://github.com/RubenvanHeusden/ParlaMint/blob/8821a7bbcd479585197c99805a5e1c5138c93399/Data/ParlaMint-NL/ParlaMint-NL_2021-02-11-tweedekamer-5.xml#L14
```XML
<meeting ana="#parla.session" corresp="#TK" n="5">Session 5</meeting>
```
corresponds to taxonomy? 

If it is correct, you are missing `#parla.sitting` that corresponds to one sitting day. And the lowest level of hierarchy should also be encoded in `TEI/@ana`, eg:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0"
     ana="#covid" <!-- #parla.sitting or #parla.meeting-->
     xml:lang="nl"
     xml:id="ParlaMint-NL_2021-02-11-tweedekamer-5">
```

## taxonomies translation
- [x] taxonomies

this will be needed in v3.1, but you can do it now

**Comment by matyaskopp** [comment]
@RubenvanHeusden 
I have found one more issue.
The `meeteng/@ana` in component files should contain information on which house's proceeding (`#parla.lower` or `#parla.upper`) is in a file.
- [ ] house in component files' meetings

In the same way, it is done in the root file:
```XML
            <meeting n="28-lower" ana="#parla.lower #parla.term">28ste Tweede Kamer</meeting>
            <meeting n="29-lower" ana="#parla.lower #parla.term">29ste Tweede Kamer</meeting>
            <meeting n="34-upper" ana="#parla.upper #parla.term">34ste Eerste Kamer</meeting>
            <meeting n="35-upper" ana="#parla.upper #parla.term">35ste Eerste Kamer</meeting>
            <meeting n="36-upper" ana="#parla.upper #parla.term">36ste Eerste Kamer</meeting>
```

**Comment by RubenvanHeusden** [comment]
@matyaskopp

Thanks for your feedback, I will change this in the component files. 

Just to clarify, I should change 
```xml
<meeting ana="#parla.term #TK.29" corresp="#TK" n="29-lower">Meeting of the 29th Tweede Kamer</meeting>
```

to 

```xml
<meeting ana="#parla.lower #parla.term #TK.29" corresp="#TK" n="29-lower">Meeting of the 29th Tweede Kamer</meeting>
```
right ?
(and upper for our upper house of course)

**Comment by matyaskopp** [comment]
> right ?

yes and every other meeting element in header (not only that describes the term). Documented in sample here: https://clarin-eric.github.io/ParlaMint/#sec-titleStmt (second sample)

so I expect:
```XML
            <meeting ana="#parla.lower #parla.meeting.regular" corresp="#TK" n="56">Meeting 56</meeting>
            <meeting ana="#parla.lower #parla.session" corresp="#TK" n="5">Session 5</meeting>
            <meeting ana="#parla.lower #parla.term #TK.29" corresp="#TK" n="29-lower">Meeting of the 29th Tweede Kamer</meeting>
```

and you should also add `meeting` element that describes sitting because the file contains one sitting
- [ ] sitting in `meeting`

```XML
            <meeting ana="#parla.lower #parla.sitting" corresp="#TK" n="2021-02-11">Sitting 2021-02-11</meeting>
```

probably add lang attribute because it is in English
- [ ] `meeting/@xml:lang="en"`

**Comment by RubenvanHeusden** [comment]
Thanks for clearing this up! I have now updated the files as you mentioned and made a commit with the updated files.

**Comment by matyaskopp** [comment]
@RubenvanHeusden, thanks. Closing this issue.
Let me know when your annotated version of the sample is ready.
