### ISSUE TITLE
GB: Validation Error

### ISSUE THREAD

**Issue by amandanwadkwe** [clarin-eric/ParlaMint#511]
Hello,

How do I fix these errors please?

`Error: ERROR[19]  Parliament organization without geo-political(#parla.national/#parla.regional) or chamber(#parla.uni/#parla.lower/#parla.upper) classification`

```Error: ERROR[10]  parliament-role organisation without affiliation: #PoGB```

**Comment by TomazErjavec** [comment]
First one means that you have the parliament org but don't specify what kind of parliament it is, cf. https://clarin-eric.github.io/ParlaMint/#sec-parliament

The second that no persons (like MPs) are affiliated with the parliament org, cf. https://clarin-eric.github.io/ParlaMint/#sec-affiliation

**Comment by amandanwadkwe** [comment]
Thank you very much
