### ISSUE TITLE
branches cleanup

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#514]
@TomazErjavec I have decided to remove all data-XX branches that were meant to show encoding changes in v2tov3 schema transition.

https://github.com/clarin-eric/ParlaMint/branches/all?query=data-

I think they are now a dead end, so they are no more useful. I just want your blessing because this operation is not reversible simply.

**Comment by TomazErjavec** [comment]
Yes please. They are all stale anyway. As is [documentation-desc](https://github.com/clarin-eric/ParlaMint/tree/documentation-desc), which we don't need anymore either.

**Comment by matyaskopp** [comment]
done
