### ISSUE TITLE
coalition / opposition validation

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#515]
> > It is not a mistake as such: it is like this in the source data. In Norway the status of MP is protected. ... But if this looks odd I could remove the "future" dates.
> 
> Well, it does look odd to me but if it is in the source data, migt as well leave it, it can make a nice footnote in a paper :)
> 
> Same for opposition - given that you don't have this concept. For AT, I think, they decided to mark with opposition only those that are clearly typically against the governemt agenda. In case @matyaskopp has an error, if it is missing, I guess it should be changed to warning...
> 
> As for time, (in both senses), there is still most of December left, again, up to you. Note types are somewhat a mess anyway.

no, it produces error only if there is no type of `coalition` or `opposition` relation.
https://github.com/clarin-eric/ParlaMint/blob/16812d4742d99b0387a7b779eb9ebae3f9cc45b7/Scripts/parlamint-lib.xsl#L353-L359
So NO sample is ok because it has a `coalition`.

I guess this can be done better (stricter):
- missing `coalition` -> ERROR
- missing `opposition` -> WARNING

@TomazErjavec should I change it?

_Originally posted by @matyaskopp in https://github.com/clarin-eric/ParlaMint/issues/513#issuecomment-1343905393_

**Comment by TomazErjavec** [comment]
OK, to repeat here from https://github.com/clarin-eric/ParlaMint/issues/513#issuecomment-1343905393, yes. pls. change it.
