### ISSUE TITLE
ParlatMint-AT: Validation WARN: political parties

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#526]
There a some  warnings left in the ParlaMint-AT validations. 
I am very tempted to simply ignore them all :-)  

But for 2 WARN-types I think I even can bring up some reasons to do so.

@TomazErjavec and @matyaskopp  you might remember the longish discussions we had about encoding party-affiliations and how to deal with the non-existing temporal information. I ended up with using the exactly timed member-relation between MP and  (party-related) `parliamentaryGroup` . 
And I use membership to `politicalParty`  when a person (throughout their political vita) also has a function other than MP: then, and only then,  I add a membership to a `politicalParty` - and these memberships never have any `from` or `to`. 

This triggers the following warnings:

```
WARN[08] ParlaMint-AT-listPerson Affiliate from date (1996-01-15T00:00:00) is P3380D before politicalParty.BZÖ organization beginning (2005-04-17T00:00:00) 
WARN[08] ParlaMint-AT-listPerson Affiliate from date (1996-01-15T00:00:00) is P6585D before politicalParty.NEOS organization beginning (2014-01-25T00:00:00) 
```

These 2 parties are younger than the "corpus-start"  (1996-01-15) - so obviously you interpret the "non-existing from-to" as `from=<CORPUS_START_DATE> to=<CORPUS_END_DATE>` and produce a  (unjustified) warning. 

The other WARN is:

``` 
WARN[10] ParlaMint-AT-listOrg politicalParty-role organisation without affiliation: #politicalParty.JETZT
WARN[10] ParlaMint-AT-listOrg politicalParty-role organisation without affiliation: #politicalParty.STRONACH
```
These 2 parties were  small and short-lived  - so none of their members made it into a political function outside the parliament. So yes:  no person has a _direct_ affiliation to either `politicalParty.JETZT` or `politicalParty.STRONACH` . But still I need these entities, because they are needed as "closest relatives" of their respective `parliamentaryGroup`: 

```xml
             <relation name="representing" active="#parliamentaryGroup.JETZT"
                passive="#politicalParty.JETZT"/>
             <relation name="representing" active="#parliamentaryGroup.STRONACH"
                passive="#politicalParty.STRONACH"/>
```

Summary:  unless you protest, I would ignore this WARNings - and maybe you even want to relax / modify your validation process to downgrade these WARN to INFO.

**Comment by matyaskopp** [comment]
> I am very tempted to simply ignore them all :-)

Yes, I agree with you.


> This triggers the following warnings:
> 
> ```
> WARN[08] ParlaMint-AT-listPerson Affiliate from date (1996-01-15T00:00:00) is P3380D before politicalParty.BZÖ organization beginning (2005-04-17T00:00:00) 
> WARN[08] ParlaMint-AT-listPerson Affiliate from date (1996-01-15T00:00:00) is P6585D before politicalParty.NEOS organization beginning (2014-01-25T00:00:00) 
> ```
> 
> These 2 parties are younger than the "corpus-start" (1996-01-15) - so obviously you interpret the "non-existing from-to" as `from=<CORPUS_START_DATE> to=<CORPUS_END_DATE>` and produce a (unjustified) warning.

You are right. In the beginning, there was an agreement that if a date is missing whole corpus period is used, but it can also happen that the date is missing because it is not possible to get it.



> Summary: unless you protest, I will ignore these WARNings - and maybe you even want to relax / modify your validation process to downgrade these WARN to INFO.

No protest, but I am unsure if I want to change these WARNings into INFO because no one reads INFO messages. The warnings try to highlight that there can be something odd and the corpus maker should think about it (As you did :-) )

I guess @TomazErjavec has no complaints, so you are free to close.
