### ISSUE TITLE
Potential indentation issue in instructions on how to "Synchronize your remote repository with the ParlaMint repository"

### ISSUE THREAD

**Issue by nljubesi** [clarin-eric/ParlaMint#529]
In file [https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md](CONTRIBUTING.md) it seems that you have a bullet point indentation issue.

"create a pull request: https://github.com/clarin-eric/ParlaMint/compare/data...USER-ORG:data" should be one level deeper, this is an instruction on how to "update ParlaMint repository with data in your repository:", right?

In general I had issues in understanding the whole section "Synchronize your remote repository with the ParlaMint repository", but this might be because (for me) too many details are set out ("git pull" described in three long bullet points), which might be needed for other users, so just mentioning this.

**Comment by matyaskopp** [comment]
> "create a pull request: [data...USER-ORG:data](https://github.com/clarin-eric/ParlaMint/compare/data...USER-ORG:data)" should be one level deeper, this is an instruction on how to "update ParlaMint repository with data in your repository:", right?

fixed with b4be2f4

> In general I had issues in understanding the whole section "Synchronize your remote repository with the ParlaMint repository", but this might be because (for me) too many details are set out ("git pull" described in three long bullet points), which might be needed for other users, so just mentioning this.

The three bullets do not describe just `git pull`, it describes synchronization with the ParlaMint repo
- pull
- check changes
- merge changes
