### ISSUE TITLE
feedback requested for HR, RS, BA

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#534]
@5roop,  I am planning to give you feedback for  HR, RS, BA.
Do you want to have separate feedback for each corpus or one join one?
- if you expect the same issues because you are using the same pipeline, it makes sense to me to create one issue
- if there can be totally different issues, then I am tending to separate issues

What do you prefer?

**Comment by 5roop** [comment]
Yes, I use the same pipeline for all three languages, so probably the bugs
in all three corpora are related and it makes sense to batch them together
as much as possible.
Thanks!
