### ISSUE TITLE
Bug in validation script

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#55]
https://github.com/clarin-eric/ParlaMint/blob/e54b9db258199c9377c78450e75aa01fe1ca7c2b/Scripts/validate-parlamint.xsl#L106

`]` is not escaped: `( SAMPLE)?` **HERE**`]$`

**Comment by TomazErjavec** [comment]
Thanks, but this has already been fixed in the meantime, cf.
https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/validate-parlamint.xsl#L86

**Comment by TomazErjavec** [comment]
Ups, sorry, I see now I fixed one check, but not the other. Fixing now.
