### ISSUE TITLE
Issue with add-common-content

### ISSUE THREAD

**Issue by tungland** [clarin-eric/ParlaMint#554]
I am having an issue with the add-common-content script. When trying to run on the full NO corpus, nothing happens. Process runs, but does not produce any output. It ran fine on the sample. Is this a known issue? How can I debug this?

**Comment by tungland** [comment]
![image](https://user-images.githubusercontent.com/58625228/208924205-1db0fb3d-0086-4ee8-8784-03fafb867cd1.png)

I get the above screen and then nothing happens. Just keeps spinning, but no output.

**Comment by tungland** [comment]
Ah, after a while it exited with the error `java.lang.OutOfMemoryError: Java heap space`

Maybe I could modify the script to run with more memory assigned or something? I am not familiar with java, so some guidance on this would be very much appreciated.

**Comment by tungland** [comment]
![image](https://user-images.githubusercontent.com/58625228/208929316-d5403e3c-5b9c-49cc-935f-3d9fa8480dc5.png)

**Comment by matyaskopp** [comment]
you can now increase a java heap size:
```bash
make add-common-content-NO JAVA-MEMORY=120
```
the number sets Giga Bytes
