### ISSUE TITLE
schema: allow notes and incidents in elements representing named entities

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#56]
Please can you add `<ref name="comment"/>`
inside named entity elements: 
https://github.com/clarin-eric/ParlaMint/blob/e54b9db258199c9377c78450e75aa01fe1ca7c2b/Schema/ParlaMint-TEI.ana.rng#L112

examples here: 

- transcriber corrected the wrong name:  https://github.com/ufal/ParCzech/issues/109
- another parliament member interrupts the speaker due to the wrong date: https://github.com/ufal/ParCzech/issues/111

**Comment by TomazErjavec** [comment]
Yes, very sensible, IS had requested the same - added.
