### ISSUE TITLE
NO: three-letter language codes

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#568]
NO corpus currently uses three letter codes for names of langauges on utterances, i.e "nno" and "nob". 
In ParlaMint we use two-char language codes when possible, so this should be changed to "nn" and "nb".

**Comment by tungland** [comment]
I have updated the sample and the corpus. The new corpus can be downloaded from the links here: https://github.com/clarin-eric/ParlaMint/issues/513#issuecomment-1380391275
