### ISSUE TITLE
BE language buglet in main title

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#57]
English title is in Dutch (and vice versa:), cf.
https://github.com/clarin-eric/ParlaMint/blob/f6f43b4f526864a7b9ca121291497104667087cc/ParlaMint-BE/ParlaMint-BE.xml#L5
and 
                <title type="main" xml:lang="en">Belgisch parlementair corpus ParlaMint-BE [ParlaMint]</title>

**Comment by JessedeDoes** [comment]
This has been fixed
