### ISSUE TITLE
tagUsage expected scope

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#58]
I am uncertain if I am counting correctly numbers in `tagUsage`. What is the expected scope of `tagUsage` element?

Now I am counting value in `@occurs` over the whole TEI file: `count(/TEI//element)`
But in TEI guidelines (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-tagUsage.html) is written: 

> specifies the number of occurrences of this element within the text.

This probably means: within the `<text>` element. 

So should I change the values to `count(/TEI/text//element)`?

**Comment by TomazErjavec** [comment]
> So should I change the values to count(/TEI/text//element)?

Yes, you should. Although I am confused, as it seems that even now your are counting exactly that, i.e. I don't see any teiHeader elements in your tagUsage:
https://github.com/clarin-eric/ParlaMint/blob/eb0a406fcceb985db56e02f7d3563058f7099a2e/ParlaMint-CZ/ParlaMint-CZ_2014-09-10-ps2013-016-01-000-000.xml#L83-L97

(ok, you do have counts on the text element, and so do I, which might be strictly speaking be a mistake, but it in the root file it tells you how many components there are, which makes sense)

**Comment by matyaskopp** [comment]
yes, but with CNEC, there appears an element that can be also in teiHeader: `ref`
And I have to remove `media` that has been moved into teiHeader...

**Comment by TomazErjavec** [comment]
Ah, I see. OK. Close this when you feel like it.
