### ISSUE TITLE
AT: personal names decomposition

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#580]
https://github.com/clarin-eric/ParlaMint/blob/5deaeed5ae792f3ba1726072298885b5b64a6d64/Data/ParlaMint-AT/ParlaMint-AT-listPerson.xml#L76
can be encoded this way:
```XML
<persName to="2000-09-27">
  <surname>Aumayr</surname>
  <forename>Anna</forename>
  <forename>Elisabeth</forename>
</persName>
```

**Comment by hpreki** [comment]
@matyaskopp  : I suppose the same holds true for `<surname>`s as well? 

i.e. "Liliane Maury Pasquier"  (  https://www.wikidata.org/wiki/Q116648 ) should become: 
 
 ```xml
 <persName>
  <surname>Maury</surname>
  <surname>Pasquier</surname>
  <forename>Liliane</forename>
</persName>
 ```
right?

**Comment by matyaskopp** [comment]
> @matyaskopp : I suppose the same holds true for `<surname>`s as well?
> 
> i.e. "Liliane Maury Pasquier" ( https://www.wikidata.org/wiki/Q116648 ) should become:
> 
> ```
> <persName>
>  <surname>Maury</surname>
>  <surname>Pasquier</surname>
>  <forename>Liliane</forename>
> </persName>
> ```
> 
> right?

yes

**Comment by hpreki** [comment]
@matyaskopp you probably can close this isssue now
