### ISSUE TITLE
Empty speech.house

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#584]
- even if you fill #parla.uni it would still leave speach.house empty
https://github.com/clarin-eric/ParlaMint/blob/5deaeed5ae792f3ba1726072298885b5b64a6d64/Scripts/parlamint-lib.xsl#L172-L202

Another question is how to treat with `parla.committee` meetings... 
replace  `speach.house` field with `speech.<organization type of target audience>`

**Comment by TomazErjavec** [comment]
OK, fixed this, I hope. It should now output whatever parliamentary body is referred to in meeting. Changed its name from "house" to "body", as it can be e.g. a committee. Still need to do a proper test, i.e. re-do verticals for all corpora and mount them. 
@matyaskopp, if you know of a corpus that has committee meetings included it would be helpful.

**Comment by matyaskopp** [comment]
> @matyaskopp, if you know of a corpus that has committee meetings included it would be helpful.

BE team has included committee meetings. But they don't categorize it with `parla.committee`:
https://github.com/clarin-eric/ParlaMint/issues/496#issuecomment-1372343737

They use the hybrid view (temporal+organizational) category `parla.meeting.committee`:
https://github.com/JessedeDoes/ParlaMint/blob/efd96af632531fb457aa4e38554f482a4f162f53/Data/ParlaMint-BE/ParlaMint-BE_2021-01-26-definitief-55-commissie-ic347x.xml#L7
```XML
<meeting corresp="#be_federal_parliament" ana="#parla.meeting.committee" n="ic347">Commissievergadering 347 van 26-01-2021</meeting>
```

**Comment by matyaskopp** [comment]
> Changed its name from "house" to "body", as it can be e.g. a committee.

I like it. Body sounds in this context well to me.

**Comment by TomazErjavec** [comment]
I think this has been solved, if you think otherwise @matyaskopp, pls. reopen and explain what needs to be done. 
And move it to Future...
