### ISSUE TITLE
xml2vert is not covering all cases in notes

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#585]
I think that 
https://github.com/clarin-eric/ParlaMint/blob/5deaeed5ae792f3ba1726072298885b5b64a6d64/Scripts/parlamint2xmlvert.xsl#L109-L123

should be extended with
```XML
<xsl:otherwise>
  <xsl:value-of select="concat(name(), ':-')"/> 
</xsl:otherwise>
```

because it does not cover this case:
```XML
<kinesic>
  <desc>Az elnök a csengő megkocogtatásával jelzi az időkeret leteltét.</desc>
</kinesic>
```

so in NoSketch it shows empty `note.type`: https://www.clarin.si/noske-beta/parlamint30.cgi/wordlist?corpname=parlamint30_hu;wlmaxitems=1000;wlattr=note.type;wlminfreq=1;include_nonwords=1;wlsort=f;wlnums=docf

**Comment by TomazErjavec** [comment]
Well spotted & fixed.
