### ISSUE TITLE
How to add links to photos?

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#59]
GB would like to add links to photos of persons, as this can then be used by ParlaMeter. The questions is how to encode photos?
The obvious solution would be to use `<idno>` as we do alredy for links to homepages of people, e.g. 
```
<person xml:id="AdamVojtech.1986">
   <persName>
      <surname>Vojtěch</surname>
      <forename>Adam</forename>
   </persName>
   <idno type="URI">https://www.psp.cz/sqw/detail.sqw?id=6491</idno>
```
But this is problematic, as the link to the photo is also an URI, so how do you distinguish the two?

The best I can come up with is to introduce the subtype attribute, and then have e.g.
```
   <idno type="URI" subtype="home">https://www.psp.cz/sqw/detail.sqw?id=6491</idno>
   <idno type="URI" subtype="photo">https://www.psp.cz/eknih/cdrom/2017ps/eknih/2017ps/poslanci/i6491.jpg</idno>
```
Any opinions on this?

**Comment by matyaskopp** [comment]
There is probably another place where can a photo be put in TEI: `<figure><graphics url="" /><figure>`.


But `idno` is shorter. Adding subtype makes sense to distinguish types of URL. I am not sure about subtype `home`. In our case we can have multiple URLs for different person roles: a member of parliament, member of government (each tenure has different url)
```
               <person xml:id="AndrejBabis.1954">
                  <persName>
                     <surname>Babiš</surname>
                     <forename>Andrej</forename>
                  </persName>
                  <sex value="M">mužské</sex>
                  <idno type="URI" subtype="home">https://www.psp.cz/sqw/detail.sqw?id=6150</idno>
                  <idno type="URI" subtype="home">https://www.vlada.cz/cz/clenove-vlady/andrej-babis-115388/</idno>
                  <idno type="URI" subtype="home">https://www.vlada.cz/cz/clenove-vlady/andrej-babis-162063/</idno>
```

furthermore, I can imagine a situation that a person has a personal web. Should it be `subtype="home"` or something different

**Comment by matyaskopp** [comment]
Another related problem. I've looked to parlameter: https://parla.me/Yp
And discover that MPs have links to their Facebook/Twitter, but in your data, there are no such records.

Should it be placed to:
```
<idno type="facebook">...</idno>
<idno type="twitter">...</idno>
<idno type="instagram">...</idno>
<idno type="tiktok">...</idno>
<!-- ... any other social media-->
```
if we will have time to manage that?

**Comment by TomazErjavec** [comment]
> There is probably another place where can a photo be put in TEI: <figure><graphics url="" /><figure>.

I think this is a very nice idea - didn't even know person/figure is legit, but it seems it is. So, I am adding figure (and figure graphics) to the schema for person (and, it can have a head at the top as well if you with to write "A revealing photo of the prime minister" there:).

>  [ParlaMeter] MPs have links to their Facebook/Twitter, but in your data, there are no such records.

No, we never did import from their data into our corpus. Not sure it will happen either. Still, you are right, that "home" is rather too broad. However, I would not want to mess with the `idno/@type` as the TEI guidelines suggest they should be URI, ISBN, and similar. Rather, I would that we all have `idno/@type="URI` but then put whatever we feel like into `idno/@subtype`, where you could have e.g. "handle", "wikipedia", "twitter", etc.

I would prefer to constrain `idno/@type` to "URI" and make `idno/@subtype` obligatory, but this would make all the corpora immediatelly invalid. So, if everybody would change their `person/idno` according to the suggestions above, I will do it, otherwise we will live in an somewhat imperfect universe.

**Comment by TomazErjavec** [comment]
This has been implemented in GB: https://github.com/clarin-eric/ParlaMint/blob/2d788c742be628f1c09004db8ff87ed5e1c9eb8c/ParlaMint-GB/ParlaMint-GB.xml#L309

Others don't seem to have such fancy metadata, so, closing the issue.
