### ISSUE TITLE
Merging organizations?

### ISSUE THREAD

**Issue by gclux** [clarin-eric/ParlaMint#591]
In France, with a new government there may slight changes in the title of a ministry, e.g.
```
          <org xml:id="PO766505" role="ministry">
            <orgName full="yes" xml:lang="fr">Ministère de la transition écologique et solidaire</orgName>
            <orgName full="abb">TRE</orgName>
            <event from="2019-07-17" to="2020-07-06">
              <label xml:lang="en">existence</label>
            </event>
          </org>

          <org xml:id="PO773376" role="ministry">
            <orgName full="yes" xml:lang="fr">Ministère de la transition écologique</orgName>
            <orgName full="abb">TRE</orgName>
            <event from="2020-07-07" to="2022-05-16">
              <label xml:lang="en">existence</label>
            </event>
          </org>
 
```
Sometimes, a portfolio may be split in two (or vice versa two portfolios are merged) with a government change.

Sometimes the name does not change with a government change.

```
          <org xml:id="PO730004" role="ministry">
            <orgName full="yes" xml:lang="fr">Ministère de l'intérieur</orgName>
            <orgName full="abb">INT</orgName>
            <event from="2017-06-22" to="2018-10-16">
              <label xml:lang="en">existence</label>
            </event>
          </org>
          <org xml:id="PO759777" role="ministry">
            <orgName full="yes" xml:lang="fr">Ministère de l'intérieur</orgName>
            <orgName full="abb">INT</orgName>
            <event from="2018-10-17" to="2020-07-06">
              <label xml:lang="en">existence</label>
            </event>
          </org>

```
In all these cases, we consider we deal with different organizations. 

Is it useful to try merging these organizations? Instead, should not we use consistent decisions in these different cases?

**Comment by matyaskopp** [comment]
@gclux, thanks for the question. Only FR and HU (@lnnoemi) are implementing ministry organizations (as far as I know).
I was not thinking about it in depth when I gave you feedback #574 . 
As for now, I think that you can leave it as it is
- new name usually means a different area of scope so that we can take it as a new organization. 
- if there is not a new name, it can be merged - but I am not insisting on that
