### ISSUE TITLE
HU: File ParlaMint-HU-listPerson.xml contains bad chars: U+AD (3x)

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#594]
U+AD is not a valid character:
https://github.com/clarin-eric/ParlaMint/actions/runs/4027956603/jobs/6924302983#step:4:435

https://clarin-eric.github.io/ParlaMint/#sec-chars

**Comment by TomazErjavec** [comment]
@lnnoemi , note that this error showed up beacause we now incorporated character validity checking in the validate-parlamint script. As you already finished 3.0, you can address this for 3.1 if you wish. But as we promised that there will be no requirements for changing the content of segments, it is not obligatory. Which doesn't meant we wouldn't be happy to see this corrected, even in 3.0!

**Comment by TomazErjavec** [comment]
This has been corrected, closing.
