### ISSUE TITLE
Validation details

### ISSUE THREAD

**Issue by JessedeDoes** [clarin-eric/ParlaMint#60]
Hi,

in the validation xsl (cf code below):

- The first rule `base-uri() = concat($id, '.xml')` should probably read `not (base-uri() = concat($id, '.xml'))` ?
- The rule `matches(base-uri(), '_.+_')` fires for me because of underscores in the path where my files live: `file:/mnt/Projecten/Corpora/0-Ruwmateriaal/FederaalParlement/annotatie_lopend/both_parlamint_v7_trankit/ParlaMint-BE_2019-11-05-55-commissie-ic045x.xml`
- I get warnings like `SnoyetdOppuersThérèse should be Snoyetd'OppuersThérèse `, but the suggested improvement is not a valid xml id.

```
  <xsl:template match="tei:TEI">
    <xsl:if test="base-uri() = concat($id, '.xml')">
      <xsl:call-template name="error">
        <xsl:with-param name="msg">TEI/@xml:id does not match filename</xsl:with-param>
      </xsl:call-template>
    </xsl:if>
    <xsl:if test="$level != 'component'">
      <xsl:call-template name="error">
        <xsl:with-param name="msg">Wrong filename for TEI component</xsl:with-param>
      </xsl:call-template>
    </xsl:if>
    <xsl:choose>
      <xsl:when test="not(matches(base-uri(), 'ParlaMint-.._'))">
        <xsl:call-template name="error">
          <xsl:with-param name="msg">
            <xsl:text>Component filenames should be ParlaMint-XX_...</xsl:text>
          </xsl:with-param>
        </xsl:call-template>
      </xsl:when>
      <xsl:when test="matches(base-uri(), '_.+_')">
        <xsl:call-template name="error">
          <xsl:with-param name="msg">
                  <xsl:text>Component filenames should have only one underscore</xsl:text>
          </xsl:with-param>
        </xsl:call-template>
      </xsl:when>
    </xsl:choose>

```

**Comment by TomazErjavec** [comment]
Thanks for the comments! I guess I should've done some more debuggging...
I now tried to fix the above errors (and also found some other things to make better), pls. check or let me know if you need another log. 

I now also take a bit more care with flagging messages as erorrs (must be fixed) or warnings (could be fixed to make the corpus more uniform).

**Comment by JessedeDoes** [comment]
Thanks!  I do not need another log, it is easier to run the script locally.

**Comment by TomazErjavec** [comment]
OK, great. So, closing this, but if anybody finds new problems, pls. feel free to reopen or make a new issue.
