### ISSUE TITLE
Is there an equivalent for EU governent websites?

### ISSUE THREAD

**Issue by sdspieg** [clarin-eric/ParlaMint#607]
[Sorry for asking a non-technical question here - maybe you may want to open a 'Discussions' feature here?]
What a fantastic resource! Thanks to all who have made this possible. I realize this falls outside of the scope of this project, but has any of you ever come across similar efforts for the executive or legislative branches of various government?

**Comment by TomazErjavec** [comment]
Dear @sdspieg, thanks for the nice words! For related work on executive or legislative branches of various government, unfortunatelly I have no idea...

**Comment by TomazErjavec** [comment]
We don't seem to have much else to say here, so, closing.
