### ISSUE TITLE
Tokenization for romance languages

### ISSUE THREAD

**Issue by JessedeDoes** [clarin-eric/ParlaMint#61]
Cf also https://universaldependencies.org/fr/tokenization.html 

We should agree on a common TEI convention for the encoding of clitic combinations like

- l'auto `<w join="right">l'</w> <w>auto</w>`? 
- dammelo
- `au` which should be  `à + le` according to the guidelines
```  sent_id = fr-ud-train_00019
# text = Créée au cours du troisième trimestre 1915 comme escadrille MF 93, elle a disparu en même temps que la 30e Escadre de Chasse à laquelle elle était intégrée.
1       Créée   créer   VERB    _       Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part 17      advcl   _       wordform=créée
2-3     au      _       _       _       _       _       _       _       _
2       à       à       ADP     _       _       4       case    _       _
3       le      le      DET     _       Definite=Def|Gender=Masc|Number=Sing|PronType=Art       4       det     _       _
4       cours   cours   NOUN    _       Gender=Masc|Number=Sing 1       obl:mod _       _
5-6     du      _       _       _       _       _       _       _       _
```

**Comment by matyaskopp** [comment]
> `au` which should be `à + le` according to the guidelines

is similar to our case `abyste` ->  `aby + byste`
https://github.com/clarin-eric/ParlaMint/blob/963e8aaf43d569b997242ccd11da7039e5d9f3fe/ParlaMint-CZ/ParlaMint-CZ_2014-09-10-ps2013-016-01-000-000.ana.xml#L541-L549

https://clarin-eric.github.io/parla-clarin/#sec-ananorm

**Comment by TomazErjavec** [comment]
I agree with @matyaskopp that the situation with Romance (and also other languages) is similar to the one already encountered for Czech, and I think their [solution](https://clarin-eric.github.io/parla-clarin/#sec-ananorm) is maybe not ideal (I prefer to avoid mixed content) but still the best under the circumstances. At least I cannot see a better way of annotating cases where the concatenation of the two syntactic words is not identical to the surface word, or, in fact, where the two parts are purely alphabetic (i.e. the tokeniser would have problems splitting them apart).

The case of _l'auto = `<w join="right">l'</w> <w>auto</w>`_ is a bit different, as I guess a tokeniser could easily always split off _l'_, so, I am agnostic here, it could be done as above, or as suggested here, it depends on the annotation tool chain.

Note that there are (even though, in my experience, much less frequent) also the opposite cases, where several surface words correspond to one syntactic one. Here, I think the Parla-Mint proposed solution is the only one possible.

**Comment by gclux** [comment]
I have now found this issue, related to what we discussed earlier today. I agree with the two examples given by Jesse: "dammelo" (it) and "au" (fr). However, about "l'auto", as Tomaz mentioned, this is normally handled by the usual tokenization options in French.
@TomazErjavec : what do you mean by "avoiding mixed content"?
I discussed with Sascha, who takes care of the CoNLL-U layer on our side, and he sees some disadvantages in applying the 6.2 solution in the previous cases. He was busy with teaching today, but I hope he will add a comment soon... Or Giulia for Italian?

**Comment by TomazErjavec** [comment]
>  what do you mean by "avoiding mixed content"?

The [solution](https://clarin-eric.github.io/parla-clarin/#sec-ananorm) is to have an outer `<w>` which contains the text of the surface word and the `<w>` elements that contain the annotation of the syntactic words as:
```
<w>abyste<w norm="aby" lemma="aby"/>
 <w norm="byste" lemma="být"/>
</w>
```
So, the outer `<w>` contains text and elements, what is in XML known as "mixed content". This can be problematic if the tools are not careful with processing, e.g. in the above we in fact do have "abyste" followed by a new line and two spaces, not something you would be happy to see as part of the word. The above is for expository purposes, but in fact it should be:
```
<w>abyste<w norm="aby" lemma="aby"/><w norm="byste" lemma="být"/></w>
```

**Comment by JessedeDoes** [comment]
We have many similar cases in our historical corpora. As we use feature structures anyway to encode all kinds of word properties, we use something like this (avoiding the mixed content with an extra `<seg>`, which would be out of place in ParlaMint):
```
<w>
  <seg>abyste</seg>
  <fs n="1">
     <f name="lemma">aby</f>
     <f name="pos">SCONJ</f>
  </fs>
  <fs n="2">
     <f name="lemma">být</f>
     <f name="pos">AUX</f>
 </fs>
</w>
```
The `<seg>` is not very satisfactory, I would prefer `<orth>`, but that is not allowed within `<w>`

**Comment by matyaskopp** [comment]
> The above is for expository purposes, but in fact it should be: `<w>abyste<w norm="aby" lemma="aby"/><w norm="byste" lemma="být"/></w>`

@TomazErjavec , good point, it is a matter of transformation from our format(I am keeping all spaces) to ParlaMint. This can be fixed.

> ... avoiding the mixed content with an extra <seg>, which would be out of place in ParlaMint):

@JessedeDoes, yes, it is a possibility, but I don't like putting features to text. If I will run the default XSLT transformation on your data I would expect the original text. But it will produce text with some mess `AUX`,... 

So that is why I have put values that do not appear in the text to attributes.

**Comment by TomazErjavec** [comment]
@JessedeDoes, thanks for sharing you solution. But in ParlaMint it would mean a redesign of the complete ling. annotation, as, presumably, you then use the same principle for "regular" words as well; additionaly, in ParlaMint we can have more than annotation (e.g UD + MULTEXT-East). And, yes, as @matyaskopp writes, it is also nice ot be able to dump just the text content of the XML and get just the transcription (although we do fail here as spaces are encoded as attributes; I had this differently in my old corpora, but am now following the standard (new-ish) TEI  practice with `@join`).

**Comment by JessedeDoes** [comment]
I agree that the feature structures should not be used in ParlaMint, (and i like the remove-all-tags-gives-plain text principle too).

**Comment by JessedeDoes** [comment]
From the the French GSD UD treebank training file, these would be the distinct tokens we would have to split:
```
au = à:ADP|_ +  le:DET|Definite=Def|Gender=Masc|Number=Sing|PronType=Art
Au = à:ADP|_ +  le:DET|Definite=Def|Gender=Masc|Number=Sing|PronType=Art
au = à:ADP|_ +  les:DET|Definite=Def|Number=Plur|PronType=Art
auquel = à:ADP|_ +  lequel:DET|Gender=Masc|Number=Sing
auquel = à:ADP|_ +  lequel:PRON|Gender=Masc|Number=Sing|PronType=Rel
aux = à:ADP|_ +  les:DET|Definite=Def|Number=Plur|PronType=Art
Aux = à:ADP|_ +  les:DET|Definite=Def|Number=Plur|PronType=Art
auxquelles = à:ADP|_ +  lesquelles:PRON|Gender=Fem|Number=Plur|PronType=Rel
auxquels = à:ADP|_ +  lesquels:PRON|Gender=Masc|Number=Plur|PronType=Rel
des = de:ADP|_ +  les:DET|Definite=Def|Number=Plur|PronType=Art
Des = de:ADP|_ +  les:DET|Definite=Def|Number=Plur|PronType=Art
desquelles = de:ADP|_ +  lesquelles:PRON|Gender=Fem|Number=Plur|PronType=Rel
du = de:ADP|_ +  le:DET|Definite=Def|Gender=Masc|Number=Sing|PronType=Art
Du = de:ADP|_ +  le:DET|Definite=Def|Gender=Masc|Number=Sing|PronType=Art
duquel = de:ADP|_ +  lequel:PRON|Gender=Masc|Number=Sing|PronType=Rel
```

**Comment by TomazErjavec** [comment]
Well, for what's it worth, these all seems cases of `<w>abyste<w norm="aby" lemma="aby"/><w norm="byste" lemma="být"/></w>` to me.

**Comment by JessedeDoes** [comment]
So it is probably easiest (at least for French) to expand the words before passing the sentence to the dependency parser (because it has presumably been trained on the split words), and join things together again at integration-into-TEI time. 
It feels a bit kludgy though. 
One might also run into the risk that the NER model has been trained on unsplit tokens...

**Comment by TomazErjavec** [comment]
> So it is probably easiest (at least for French) to expand the words before passing the sentence to the dependency parser (because it has presumably been trained on the split words), and join things together again at integration-into-TEI time.

Yes, that is how we did it (with e.g. Tweets, where we standardised the words). But it will depend on the tool - as far as I know, UD-pipe does all the steps in one seamless process.

> It feels a bit kludgy though.

Well, but what is the alternative? The only one I see is to have a system that does not fiddle with the orthographic words and just annotates them, clitics or not..

> One might also run into the risk that the NER model has been trained on unsplit tokens...

In which case you might run NER directly on those? The two annotations are pretty distinct. But, yes, I agree it is pretty fiddly...

**Comment by JessedeDoes** [comment]
Yes, the dependency parser we use now can do it all seamlessly.

But the bothersome thing that we run into is in general
- You want to add linguistic annotation to already tokenized material
- The tool you use has its own ideas about tokenization and will probably give better results if you allow it to tokenize in its own way  (this would also apply to Alpino for Dutch)
- So the best solution is probably to re-align the two different tokenizations after processing

**Comment by JessedeDoes** [comment]
We get wildly inconsistent results from the parser we use for the -ci and -la clitics.

-la is mostly tagged as an adverb
![image](https://user-images.githubusercontent.com/1109972/110351652-599cc380-8035-11eb-87e9-175adca1cc35.png)
-ci is mostly tagged as particle
![image](https://user-images.githubusercontent.com/1109972/110351978-a6809a00-8035-11eb-905e-fb89883cd4d3.png)

**Comment by TomazErjavec** [comment]
It might be that such clitics appear seldom (at least judging from your example), so even if wrongly analysed, it does't really show up in the scores. Anyway, if there isn't a better pipeline, there is probably not much you can do...

**Comment by valeq** [comment]
> I have now found this issue, related to what we discussed earlier today. I agree with the two examples given by Jesse: "dammelo" (it) and "au" (fr). However, about "l'auto", as Tomaz mentioned, this is normally handled by the usual tokenization options in French.
> I discussed with Sascha, who takes care of the CoNLL-U layer on our side, and he sees some disadvantages in applying the 6.2 solution in the previous cases. He was busy with teaching today, but I hope he will add a comment soon... Or Giulia for Italian?

After some reflections and the help of a TEI expert Italian colleague (Angelo Mario Del Grosso, ), we would like to propose the following option for the representation of subtokenisation of clitics and complex prepositions as represented in the Italian UD corpora.  Eg: 
ConllU:
3-4 della _ _ _ _
3 di di ADP E _
4 la il DET RD Definite=Def|Gender=Fem|Number=Sing|PronType=Art  
-->
TEI
 <w xml:id="ID-ZZZ-x-y" orig="della" type="complex" >
   <w xml:id="ID-ZZZ-x" join="right" part="Y"  lemma="di" pos="E" msd="UposTag=ADP">
      <reg type="automaticAnnotation" resp="#UD_parser">di</reg>
   </w>
   <w xml:id="D-ZZZ-y" join="left" part="Y" lemma="il" pos="RD" msd="UposTag=DET|Definite=Def|Gender=Fem|Number=Sing|PronType=Art" >
     <reg type="nlp" resp="#UD">la</reg>
   </w>
</w>

This should avoid mixed content and be general enough for back-conversion to ConllU.  @join and <reg> are not necessary but perhaps useful. For the values of @type we are open to suggestions for existing vocabularies we might draw from.

**Comment by TomazErjavec** [comment]
Thanks for the suggestion, if I write it indented and without `@msd`, so it is shorter:
```
<w xml:id="ID-ZZZ-x-y" orig="della" type="complex">
  <w xml:id="ID-ZZZ-x" join="right" part="Y" lemma="di" pos="E">
     <reg type="automaticAnnotation" resp="#UD_parser">di</reg>
  </w>
  <w xml:id="D-ZZZ-y" join="left" part="Y" lemma="il" pos="RD">
    <reg type="nlp" resp="#UD">la</reg>
  </w>
</w>
```
while the original suggestion would be (again, indented, even though you would not want that in practice):
```
<w xml:id="ID-ZZZ-x-y">della
  <w xml:id="ID-ZZZ-x" lemma="di" pos="E" norm="di">
  <w xml:id="D-ZZZ-y" lemma="il" pos="RD" norm="la">
</w>
```
I have to admit I like the original, i.e. second suggestion, better. It has one downside, mixed content, but, on the plus side:
* the main one is that if you just dump the text, the second one gets you the original text, so, "della" but the first one the syntactic words "dila", which is surely not what you want
* because the first one stores the synt. words as text nodes, you then need to complicate with all sorts of attributes like `@join` and it is, in general,  a lot more baroque
* and, I'm afraid to say, it might be a bit late in the day to change things now - [Parla-CLARIN](https://clarin-eric.github.io/parla-clarin/#sec-ananorm) has had the current recommendation since Dec 8, 2020, and CZ and IS have already finished their .ana corpora...

**Comment by JessedeDoes** [comment]
In order to implement the token splitting of the "du/au" etc case and tokens like "pense-t-il", we follow a simple rule-based approach, based on inspecting the French UD training files.
What we lack is a more or less systematic description of the cases where the whitespace-delimited token should be split in to several. 
Is this documented anywhere?

**Comment by TomazErjavec** [comment]
> What we lack is a more or less systematic description of the cases where the whitespace-delimited token should be split in to several. Is this documented anywhere?

I guess in the individual language descriptions of UD and, implicitly, in the UD treebanks. For ParlaMint there are no rules for this, as it depends excusivelly on what the toolchain does, and our project certainly does not have capacities to start fiddling with the annotation toolchain (well, unless the output does not pass UD validation at Level 2).

Note also that, to an small extent, this point has already been addressed above, in https://github.com/clarin-eric/ParlaMint/issues/61#issuecomment-785168768

**Comment by TomazErjavec** [comment]
I would just like to add to this debate, esp. to https://github.com/clarin-eric/ParlaMint/issues/61#issuecomment-785168768 that I used to encode these 1-n, n-1 (this is the case of modernising a historical text, but the principle would be the same for syntactic words) as:
```
<choice>
   <orig>
      <w>nar</w>
      <w>vezh</w>
   </orig>
   <reg>
      <w lemma="veliko" ana="#Rgs">največ</w>
   </reg>
</choice>
```
which does have some advantages, but is pretty bulky; I like the w/w better.

**Comment by JessedeDoes** [comment]
We also considered the choice/reg/orig encoding, but it feels a bit weird to encode "de le" (incorrect French) as a "regularization" of the correct "du".

**Comment by TomazErjavec** [comment]
> We also considered the choice/reg/orig encoding, but it feels a bit weird to encode "de le" (incorrect French) as a "regularization" of the correct "du".

I agree - we used it for regularisation of historical texts (so, modernisation) and of user-generated content (so, standardisation), which it might make a bit more sense...

**Comment by TomazErjavec** [comment]
I guess all has been said on this topic, and, given that we now have already many finalised corpora that do use https://clarin-eric.github.io/parla-clarin/#sec-ananorm I am closing this issue.
