### ISSUE TITLE
Coalition relation in ES-GA

### ISSUE THREAD

**Issue by adina-v** [clarin-eric/ParlaMint#612]
Hi all,
Quick question about the "coalition" relation, as it appears that when converting to .vert, we get the following message: .vert, "ERROR: no coalition info found in corpus". 
I have been reading the previous discussions on this issue with respect to the Spanish Parliament. In the Galician Parliament we have the same issue: one single party in government, and all others forming the opposition. We understand that the correct way to encode this situation would be something like this, then, even if the "mutual" relation is between one party and, basically, itself?

		<relation name="coalition" 
				  mutual="#party.PPdeG" 
				  from="2012-11-16" 
				  to="2016-08-01" 
				  ana="#PG.9"/>
		<relation name="opposition" 
				  active="#party.AGE #party.PSdeG-PSOE #party.BNG" 
				  passive="#party.PPdeG" 
				  from="2012-11-16" 
				  to="2016-08-01" 
				  ana="#PG.9"/>
				  
Thank you!

**Comment by matyaskopp** [comment]
Exactly.
TEI does not allow mixing `mutual` and `active`+`passive`. So we have decided to use one participant relation when only a single party cooperates with the government.

**Comment by adina-v** [comment]
Thank you! We will modify our ListOrg accordingly.
