### ISSUE TITLE
Nested date validation problem

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#62]
In our nested named entities can this happen (formated and removed elements(`w`, `pc`) for better orientation):
```
<s> Návrh zákona, kterým se mění  
  <name ana="ne:or" type="MISC">
     zákon č. 
    <num ana="ne:n_">353</num>
    /
    <date ana="ne:ty">2003</date>
     ..... 
  </name> 
  .... 
</s>
```

so `s` is not a parent of `date` and this validation fails:
https://github.com/clarin-eric/ParlaMint/blob/3695a7a2746d0fa4954e5c646bdfa26a626d6bca/Scripts/validate-parlamint.xsl#L218-L222

@TomazErjavec, can you change `parent` axis to `ancestor` please?

Or you can change the condition to: `not(@when or @from or @to or @ana)` as can occur only in named entities and there should be some annotation (in CZ).

**Comment by matyaskopp** [comment]
And `time` should have a similar check...

**Comment by TomazErjavec** [comment]
Fixed, now
```
  <xsl:template match="tei:date | tei:time">
    <xsl:if test="not(@when or @from or @to or @ana)">
      <xsl:call-template name="error">
...
```
