### ISSUE TITLE
ES-GA Feedback

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#621]
### corpus timespan
- [x] corpus timespan in title

https://github.com/adina-v/ParlaMint/blob/308040600d3003048864710cd326255da0a415d5/Data/ParlaMint-ES-GA/ParlaMint-ES-GA.xml#L8-L9
```XML
<title type="sub" xml:lang="gl">Actas do Parlamento de Galicia, Lexislaturas IX-XI (2015 - 2021)</title>
<title type="sub" xml:lang="en">Minutes of the Galician Parliament, Terms 9-11 (2015 - 2021)</title>
```

versus:

```XML
			<bibl>
				<title type="main" xml:lang="gl">Actas do Parlamento de Galicia</title>
				<title type="main" xml:lang="en">Minutes of the Galician Parliament</title>
				<idno type="URI">https://www.parlamentodegalicia.gal/</idno>
				<date from="2015-01-27" to="2022-05-25">27.01.2015 - 25.05.2022</date>
			</bibl>
```
```XML
			<setting>
				<name type="address">Rúa do Hórreo, 63, 15702 Santiago de Compostela, A Coruña, Galicia, España</name>
				<name type="city">Santiago de Compostela</name>
				<name type="country" key="ES-GA">Galicia</name>
				<date from="2015-01-25" to="2022-05-25">25.01.2015 - 25.05.2022</date>
			</setting>
```

### funder
- [x] CLARIN expected in funder list

https://github.com/adina-v/ParlaMint/blob/308040600d3003048864710cd326255da0a415d5/Data/ParlaMint-ES-GA/ParlaMint-ES-GA.xml#L63
see:
https://github.com/clarin-eric/ParlaMint/blob/031ec3009386a4bfec60bf0e22f653a813ddf98c/Data/ParlaMint-CZ/ParlaMint-CZ.xml#L17-L20

### missing speaker notes
- [x] speaker notes

https://github.com/adina-v/ParlaMint/blob/308040600d3003048864710cd326255da0a415d5/Data/ParlaMint-ES-GA/ParlaMint-ES-GA_2022-04-04-DSPG076.xml#L84-L90
```XML
<u who="#SantalicesMiguelÁngel" ana="#chair" xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.u1">
  <seg xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.seg1">Bos días. </seg>
```
speaker note is missing:
```XML
<note type="speaker">O señor PRESIDENTE:</note>
<u who="#SantalicesMiguelÁngel" ana="#chair" xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.u1">
  <seg xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.seg1">Bos días. </seg>
```
source: https://www.parlamentodegalicia.es/sitios/web/BibliotecaDiarioSesions/D110076.pdf
![image](https://user-images.githubusercontent.com/5867995/225307674-b118b725-44ea-446e-8095-4776e78dc5c3.png)

### notes inside sentences
- [x] notes inside utterance / paragraph / sentences

this note should not split sentence/paragraph/utterance:
https://github.com/adina-v/ParlaMint/blob/308040600d3003048864710cd326255da0a415d5/Data/ParlaMint-ES-GA/ParlaMint-ES-GA_2022-04-04-DSPG076.xml#L109-L113
```XML
	<seg xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.seg21">Miren, en termos globais, Galicia é das comunidades autónomas de España que está na metade inferior no seu gasto en investimento por habitante en sanidade. O investimento por persoa que temos en Galicia está na franxa inferior. Podemos reinterpretar este dato como cada un queira, pero esta é a realidade, hai máis comunidades, algunhas, bastantes máis, por riba que por debaixo. Permítanme que llelo ensine nun gráfico</seg>
</u>
<note>(O señor Torrado amosa un gráfico.)</note>
<u who="#TorradoJulio" ana="#regular" xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.u4">
	<seg xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.seg22">e, ademais, permítanme que o faga porque hai un detalle aí que me parece moi interesante. Este é o gráfico de investimento por habitante para os orzamentos de 2022 en España. Vostedes poden ver as máis altas, están aquí sinaladas en verde: Euskadi, Asturias e Navarra; e poden ver Galicia na metade inferior, e poden ver as últimas tres.</seg>
```
should be in one `seg`
![image](https://user-images.githubusercontent.com/5867995/225311905-f0e874c0-1fe7-46d8-8a8e-da7d8baaa437.png)

If there is a note inside utterance, you automatically split this utterance into two

### strange speech content
- [x] invalid speech content

https://github.com/adina-v/ParlaMint/blob/308040600d3003048864710cd326255da0a415d5/Data/ParlaMint-ES-GA/ParlaMint-ES-GA_2015-12-23-DSPG136.xml#L121-L122
```XML
<seg xml:id="ParlaMint-ES-GA_2015-12-23-DSPG136.seg23">PAGE    </seg>
<seg xml:id="ParlaMint-ES-GA_2015-12-23-DSPG136.seg24">PAGE   2</seg>
```

### passive should be government in opposition relation
- [x] government in opposition relation

https://github.com/adina-v/ParlaMint/blob/308040600d3003048864710cd326255da0a415d5/Data/ParlaMint-ES-GA/ParlaMint-ES-GA-listOrg.xml#L558-L563
```XML
		<relation name="opposition" 
				  active="#party.AGE #party.PSdeG-PSOE #party.BNG" 
				  passive="#party.PPdeG" 
				  from="2012-11-16" 
				  to="2016-08-01" 
				  ana="#PG.9"/>
```
should be:
```XML
		<relation name="opposition" 
				  active="#party.AGE #party.PSdeG-PSOE #party.BNG" 
				  passive="GOV" 
				  from="2012-11-16" 
				  to="2016-08-01" 
				  ana="#PG.9"/>
```

**Comment by adina-v** [comment]
Thank you for the feedback and the keen eye, @matyaskopp! 
One question: We were trying to avoid having notes inside segments and utterances as per (our understanding of) the TEI schema. So, for the note to be non-splitting, then it should be something like this? 
```
<seg xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.seg21">Miren, en termos globais, Galicia é das comunidades autónomas de España que está na metade inferior no seu gasto en investimento por habitante en sanidade. O investimento por persoa que temos en Galicia está na franxa inferior. Podemos reinterpretar este dato como cada un queira, pero esta é a realidade, hai máis comunidades, algunhas, bastantes máis, por riba que por debaixo. Permítanme que llelo ensine nun gráfico
<note>(O señor Torrado amosa un gráfico.)</note>
e, ademais, permítanme que o faga porque hai un detalle aí que me parece moi interesante. Este é o gráfico de investimento por habitante para os orzamentos de 2022 en España. Vostedes poden ver as máis altas, están aquí sinaladas en verde: Euskadi, Asturias e Navarra; e poden ver Galicia na metade inferior, e poden ver as últimas tres.</seg>
```

**Comment by matyaskopp** [comment]
> One question: We were trying to avoid having notes inside segments and utterances as per (our understanding of) the TEI schema. So, for the note to be non-splitting, then it should be something like this?
> 
> ```
> <seg xml:id="ParlaMint-ES-GA_2022-04-04-DSPG076.seg21">Miren, en termos globais, Galicia é das comunidades autónomas de España que está na metade inferior no seu gasto en investimento por habitante en sanidade. O investimento por persoa que temos en Galicia está na franxa inferior. Podemos reinterpretar este dato como cada un queira, pero esta é a realidade, hai máis comunidades, algunhas, bastantes máis, por riba que por debaixo. Permítanme que llelo ensine nun gráfico
> <note>(O señor Torrado amosa un gráfico.)</note>
> e, ademais, permítanme que o faga porque hai un detalle aí que me parece moi interesante. Este é o gráfico de investimento por habitante para os orzamentos de 2022 en España. Vostedes poden ver as máis altas, están aquí sinaladas en verde: Euskadi, Asturias e Navarra; e poden ver Galicia na metade inferior, e poden ver as últimas tres.</seg>
> ```
> 
> Or can the note only be inside the "u" but dividing the "seg" like [here](https://github.com/clarin-eric/ParlaMint/blob/main/Data/ParlaMint-ES-CT/ParlaMint-ES-CT_2018-01-17-0101.xml#:~:text=europea.%3C/seg%3E-,%3Cseg%20xml%3Aid%3D%22ParlaMint%2DES%2DCT_2018%2D01,tamb%C3%A9%20un%20bon%20mapa%20de%20la%20societat%20catalana%20d%E2%80%99avui%2C%20diversa%2C%20complexa%2C,-una%20societat%20que)?

If the note (short note) is in the middle of a paragraph, then you should keep it there. (but end and beginning notes should be outside of paragraph)
```XML
<seg>If the note <note>(short note)</note> is in the middle of a paragraph, then you should keep it there.</seg>
<note>(but end and beginning notes should be outside of paragraph)</note>
```
and if the note is first/last in the utterance, then it should be outside too.

Your sample is almost correct. It is better to use space around the note - it is safer for further linguistic annotation - better to have double space, then double new lines for sentence segmentation.

```XML
<seg>Miren, <!--...--> gráfico <note>(O señor Torrado amosa un gráfico.)</note> e, ademais, <!--...--> tres.</seg>
```

**Comment by matyaskopp** [comment]
@adina-v one more improvement idea:

### proper link to source file
- [ ] `bibl/idno`

Currently, you have a similar URL in all component `bibl/idno` elements. If it is possible it would be great to refer to each component file's proper source. It is a kind of proof that the data are real
Check CZ corpus, I am even adding links to `u` and `pb` elements:
https://github.com/clarin-eric/ParlaMint/blob/031ec3009386a4bfec60bf0e22f653a813ddf98c/Data/ParlaMint-CZ/ParlaMint-CZ_2016-04-13-ps2013-044-02-013-114.xml#L54-L59
https://github.com/clarin-eric/ParlaMint/blob/031ec3009386a4bfec60bf0e22f653a813ddf98c/Data/ParlaMint-CZ/ParlaMint-CZ_2016-04-13-ps2013-044-02-013-114.xml#L161-L164
https://github.com/clarin-eric/ParlaMint/blob/031ec3009386a4bfec60bf0e22f653a813ddf98c/Data/ParlaMint-CZ/ParlaMint-CZ_2016-04-13-ps2013-044-02-013-114.xml#L174-L177

**Comment by adina-v** [comment]
Thank you! We´ll do what we can :)

**Comment by matyaskopp** [comment]
I hope this summarizes the idea:
- `<note>`, `<incident>`,`<vocal>`, `<kinesic>` should be handled in similar way 
- you should preserve paragraphs as they are in the text - so if there is a note/incident in the middle of a paragraph, then you should place it in the very same place
- if there is a note/incident at the beginning/end of paragraph(`<seg>`) - then it is better to place it outside `<seg>` (or even outside utterance `<u>`) documented here: https://clarin-eric.github.io/ParlaMint/#para-hierarchy-comments
- the only unclear question is whether note/incident should break/split utterance `<u>`  - it is not very strict - every partner does it as they want:
   - it should split `<u>` if it is a long interruption such as break/signing hymn/...
   - otherwise, it should be inside utterance (between segments - unless it is a leading/trailing note/incident)

**Comment by adina-v** [comment]
Thank you!

**Comment by adina-v** [comment]
> * you should preserve paragraphs as they are in the text - so if there is a note/incident in the middle of a paragraph, then you should place it in the very same place

Sorry, @matyaskopp, we are still debating on note placement and could really use your expertise. Could you please shed some light once and for all on this issue?
Would it be acceptable to separate notes in the middle of paragraphs by new lines, like so, 
```
	<u who="#IglesiasCarmen" ana="#regular" xml:id="ParlaMint-ES-GA_2015-01-27-DSPG095.u67">
		<seg xml:id="ParlaMint-ES-GA_2015-01-27-DSPG095.seg494">
			...e das poucas disimuladas intencións de culpabilizar as pacientes 
			<vocal type="murmuring">
				<desc>(Murmurios.)</desc>
			</vocal>
			pois parece que enfermamos por riba das nosas posibilidades...</seg>
		</u>
```
Or must such notes be placed in the same line as all the test of the `<seg>` they belong to, like so
			
```
<note type="speaker">A señora IGLESIAS SUEIRO:</note>
	<u who="#IglesiasCarmen" ana="#regular" xml:id="ParlaMint-ES-GA_2015-01-27-DSPG095.u67">
	       <seg xml:id="ParlaMint-ES-GA_2015-01-27-DSPG095.seg494">
		...e das poucas disimuladas intencións de culpabilizar as pacientes  <vocal type="murmuring"> <desc>(Murmurios.)</desc> </vocal>  , pois parece que enfermamos por riba das nosas posibilidades...</seg>
	</u>
```

**Comment by adina-v** [comment]
Thank you, @matyaskopp! We have updated the sample fixing the issues in the XML files. The .ana files are still in progress, so we´ll be updating those when we have them.

**Comment by matyaskopp** [comment]
> Thank you, @matyaskopp! We have updated the sample fixing the issues in the XML files. The .ana files are still in progress, so we´ll be updating those when we have them.

@adina-v, great thanks.
You still have newlines around notes - I am not insisting on fixing this, but you should be careful in linguistic annotations - sentence segmentation and tokenization can be broken by it.

**Comment by adina-v** [comment]
Sorry - we are aware of that. We looked into it, but with the way we had our scripts set up and the limited time available, it was very complicated to implement - so we decided to leave the newlines in place and be ready to fix this issue at the level of linguistic annotation.

**Comment by adina-v** [comment]
Hi! We just updated the sample with the ana files - hope all is correct!

**Comment by matyaskopp** [comment]
> Hi! We just updated the sample with the ana files - hope all is correct!

@adina-v, great, thanks. Reported issues are fixed. 
There is always space for improvement, but it is time to stop :-). 
But I have spotted one final issue that affects only root files and can cause confusion in the concordancer.

## language usage
- [ ] `langUsage` in TEI root
- [ ] `langUsage` in TEI.ana root

should look like this: https://clarin-eric.github.io/ParlaMint/#exa-langUsage

But you are missing a Galician translation, and an English translation is wrongly set as Galician: 
https://github.com/adina-v/ParlaMint/blob/1e4ebbe388f362d2ce002c7bef95b34fb6810204/Data/ParlaMint-ES-GA/ParlaMint-ES-GA.xml#L192-L193
```XML
<langUsage>
    <language ident="gl" xml:lang="gl">Galician</language>
    <language ident="en" xml:lang="en">English</language>
</langUsage>
```
should be
```XML
<langUsage>
    <language ident="gl" xml:lang="gl"><!-- ??? --></language>
    <language ident="en" xml:lang="gl"><!-- ??? --></language>
    <language ident="gl" xml:lang="en">Galician</language>
    <language ident="en" xml:lang="en">English</language>
</langUsage>


```

**Comment by adina-v** [comment]
Thank you for the observation and all the help so far! We have updated the TEI root and TEI ana root.

**Comment by matyaskopp** [comment]
@adina-v, thanks for the fast fixings.

The Galician sample works for me, so if you agree, I can merge it into the data branch and close this issue, and you can jump into processing the whole corpus.

**Comment by adina-v** [comment]
Great, thank you!
