### ISSUE TITLE
AT: addition of new protocols still welcome? 

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#622]
@TomazErjavec  @matyaskopp the publication of stenografic protocols by the Austrian Parliament is quite delayed, therefore our submission to ParlaMint only included data until 2023-05-19. 

In the meantime some more protocols have been published - so I could  offer  10 new protocols until 2023-09-21. Or -- if we want to have a less "random" cut, and we stop with the  beginning of the summer break -- it would be 9 more protocols up to 2023-07-08.  

Executive summary: what's your stance towards additions right now? Would you welcome the submission of these new protocols, or would they just add confusion (and work!) for you? (the _one_ issue that comes to my mind immediately: these 9 or 10 protocols would require automatic translation) 

(processing of these new protocols is already finished, so it's not the question whether _I_ should go for the effort, it's only just whether I submit the results right now)

**Comment by TomazErjavec** [comment]
Thanks for the offer but let's leave this till 3.1; the situation now is messy enough that it wouldn't be a good idea to introduce furhter complications.

**Comment by TomazErjavec** [comment]
Great. But let's leave the issue open, I put it on milestone 3.1, so we remember then.

**Comment by TomazErjavec** [comment]
> @TomazErjavec do you prefer an incremental submission of only the new protocols and the updated corpus- and metadata-files or do you want to receive the whole bulk of existing + new?

We have only 5 corpora that have expressed their intention to deliver changed or new files, so it won't be a lot of work for me, i.e. whichever you prefer is ok with me.

**Comment by matyaskopp** [comment]
> * @matyaskopp  should I still add the new "youngest"  protocol and the updated metadata-files  to the AT-Fork (branch `data`) and issue a pull request, as before?

Yes please, create a new pull request, just to be sure the new metadata is ok.

**Comment by hpreki** [comment]
@matyaskopp I created a new pull-request but it had to fail,  because the `Schema` in branch `data` does not yet contain the new `@role federatedState`

**Comment by TomazErjavec** [comment]
Has this been sorted, or is there something more to do?

**Comment by TomazErjavec** [comment]
Doesn't seem so, closing.
