### ISSUE TITLE
New definitions for subcorpora

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#629]
As the UA corpus will also be part of ParlaMint 3.0, there were suggestions that we should introduce a new subcorpus corresponding to the war in Ukraine. While we are changing the scope of subcorpora, this also seems a good opportunity to change the start date of the COVID subcorpus to something more sensible than the current rather arbitrary date of 2019-11-01.

With this, the following suggestions:
* The COVID subcorpus start date changes to 2020-01-31, when WHO made their PHEIC, i.e. "Public Health Emergency of International Concern", cf. https://www.who.int/publications/m/item/covid-19-public-health-emergency-of-international-concern-(pheic)-global-research-and-innovation-forum.
* The Reference subcorpus end-date therefore changes to 2020-01-30.
* We introduce a new "War" subcropus, which starts on 2022-02-24, when Russia invaded Ukraine, cf. https://en.wikipedia.org/wiki/Russian_invasion_of_Ukraine.
* A corpus component would be marked either as Reference; as COVID; or as COVID + War (because COVID didn't really end yet).
* In the concordancers, to simplify the usage, a corpus component would be marked as Reference, COVID or War (i.e. COVID + War is changed to simple "War").

I would be interested in comments to the above plan. 
If none, or if all in favour, I would try to introduce this already for 3.0. This could be done with the finalisaiotn script, while the GitHub samples would also need to be changed (or just wait for samples derived from 3.0).

**Comment by osenova** [comment]
Hi Tomaz, I totally agree with the three subcorpora suggestion: Reference, COVID and WAR. I am also OK with the dates. Just please check this also with Darja.

**Comment by AnnaParla** [comment]
I believe we need to think about naming the "war" corpus a bit more carefully, since Russia invaded and annexed parts of Ukraine back in 2014. It did the same in 2022 but on a much larger scale. And war related themes were introduced into the Ukrainian corpus back in 2014. In fact, it might be interesting to compare the exact wordings and frequencies of mentions of Russia's aggression against Ukraine across the national parliaments... 
As for the sub-corpus name, maybe "large-scale war" or something along these lines will be better, if we need to refer to the period from 2022 onward? To indicate that the war started in 2022 would be inaccurate and it could create unnecessary confusions (and potentially even manipulations).

**Comment by TomazErjavec** [comment]
I am not against renaming (although I think 2014 is more like "invasion", not really "war", which 2022 surely is) but I would need a single-word term. As for confusion / manipulation, I think this potentially holds for any distinction, e.g. "COVID" subcorpus could have any number of start points, from the first reported instance of the virus, to first known case in Europe, to first mention in a parliament etc etc. So, I wouldn't worry about this, as long as we are clear what the reasoning is.

**Comment by TomazErjavec** [comment]
Thanks for the explanation, so, if I understand correctly "War" would then still be the appropriate name for the subcorpus starting in 2022-02-24.

**Comment by AnnaParla** [comment]
Yes, but it might need to be explained. What about placing an information icon right next to War with a short explanation like "starting from Russia's full-scale invasion of Ukraine" or something similar?

**Comment by AnnaParla** [comment]
On a different note, 2020-01-31 is a landmark not only for COVID but also for Brexit, which will be convenient for searches in the ParlaMint-GB!

**Comment by TomazErjavec** [comment]
> Yes, but it might need to be explained. What about placing an information icon right next to War with a short explanation like "starting from Russia's full-scale invasion of Ukraine" or something similar?

I can place this info in the taxonomy, yes. Can't do an icon in the concordancer I think, but will have a look if it is possible to give glosses with values.

As for Brexit, well spotted! :)

**Comment by TomazErjavec** [comment]
> I can place this info in the taxonomy

Did it now, in [fdb8dce](https://github.com/clarin-eric/ParlaMint/commit/fdb8dce0cd38fbe2fd9fc46578457097a251aef0).
@matyaskopp, can you merge devel into main, so that it is available there too pls.? 
I will modify the finalization step to correctly label the components, and (somehow) insert the new taxonomy into the corpora.

**Comment by TomazErjavec** [comment]
This has now been implemented (https://github.com/clarin-eric/ParlaMint/blob/main/Data/Taxonomies/ParlaMint-taxonomy-subcorpus.xml) also so that corpora that are finalized now include this taxonomy and that the derived files make the distinction. Am just re-processing all the corpora that have been submitted so far.
