### ISSUE TITLE
make vertana

### ISSUE THREAD

**Issue by nemeek** [clarin-eric/ParlaMint#638]
Should `make vertana-XX` work (with full data)? I tried `vertana-EE` and got
```
Can't find href in xi:include!
WARNING skipping/failing vertana-EE
´´´

**Comment by matyaskopp** [comment]
my guess is that you don't have attribute `href` or empty `href=""` because it is failing on this line:
https://github.com/clarin-eric/ParlaMint/blob/937681cf012cc7330025a8052c60cb05b1bc25ae/Scripts/parlamint-tei2vert.pl#L30-L31

**Comment by nemeek** [comment]
Thank you. It was some commented out includes that broke the script.
