### ISSUE TITLE
script for initializing taxonomies for new languages

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#650]
Implement script for creating common taxonomies without translations:
- input: common taxonomy with English terms
- param: list of languages
- output: taxonomy with prepared elements for every language from list

This script needs to be integrated into Makefile:
```bash
make initTaxonomies-XX LANGS="xx yy"
```
it takes taxonomies from `Data/Taxonomies` folder

**Comment by matyaskopp** [comment]
@RePierre @TomazErjavec ,
taxonomy initialization is implemented. Sample results are in PArlaMint-RO: 
https://github.com/clarin-eric/ParlaMint/tree/d685b4df32d81bf35133c896d93a85027af58ddf/Data/ParlaMint-RO

**Comment by RePierre** [comment]
Thank you, @matyaskopp!
