### ISSUE TITLE
insert new sample data 

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#651]
Insert sample data created from release-ready files into the data branch.
Source: 
```bash
/project/corpora/Parla/ParlaMint/ParlaMint-full/Data/Corpora/Sample-ParlaMint-XX
```

**Comment by matyaskopp** [comment]
@TomazErjavec, I have inserted new sample data into [data](https://github.com/clarin-eric/ParlaMint/tree/data) branch.
Everything validates (I haven't done a manual inspection - I will do it later or not at all...).

ParlaMint-ES-GA data is missing, @adina-v provided (7th April, subj: ParlaMint-ES-GA corpus
) us full data, but it seems that you haven't downloaded and processed them.

**Comment by TomazErjavec** [comment]
> ParlaMint-ES-GA data is missing

Now ready in the usual place.

**Comment by TomazErjavec** [comment]
Once all the corpora are processed for 3.0, this should be done again. Currently the samples are in (non GitHub directory) /Distro/Master/Sample-ParlaMint-*

Then again, I could just change script that generates the samples to put them in the Data directory, or symlink the Sample-ParlaMint-* to there.

**Comment by TomazErjavec** [comment]
OK, inserted samples generated from 3.0 full data. This is in the devel branch, sorry, but it works out that way easier in the current set up. If happy, @matyaskopp, pls. merge to main (and data I guess) and close this issue.

**Comment by TomazErjavec** [comment]
Merged, closing.
