### ISSUE TITLE
Utterance has obligatory @ana, for the role of the speaker.

### ISSUE THREAD

**Issue by gclux** [clarin-eric/ParlaMint#66]
We have cases, for which the speaker metadata is incomplete or inconsistent. Mostly for invited speakers, who should be 'guest' or 'government'. We may fix these situations progressively. Meanwhile, how can we avoid validation errors? Is a default value OK, like "#NIL"? Is there a generic rule also for other attributes?

**Comment by matyaskopp** [comment]
> speaker metadata is incomplete or inconsistent.

Do you mean `<person>` static metadata (stored in teiCorpus)? If so, it does not affect TEI files validation, so it does not make sense to add to TEI files values that shouldn't be there...

Or is it the matter that you are not able to determine the speaker's role (speaker dynamic metadata)?

**Comment by gclux** [comment]
The problem is that @ana is mandatory with <u> and we cannot always determine it.

**Comment by TomazErjavec** [comment]
I would not remove `u/@ana`, but, yes, this is merely a pointer, so I would suggest that you add to your "speaker_types" taxonomy in the root teiHeader a new category (where the "???" should of course be the translation to French):
```
<category xml:id="unknown">
   <catDesc xml:lang="fr">
      <term>???</term>: ???</catDesc>
   <catDesc xml:lang="en">
      <term>Unknown</term>: unknown type of speaker</catDesc>
</category>
```
and then just use `<u ... ana="#unknown">`. Would this be ok?

**Comment by TomazErjavec** [comment]
Sorry, forgot to answer this:

>  Is there a generic rule also for other attributes?

I guess it depends on the attribute, so, not as such. If we find that there is a pervasive case where the value of some attribute is unknown, then, indeed, it is best defined as optional (as we did with `u/@who`). If it is an edge case, then I think introducing a new "unknown" category into the appropriate taxonomy is better.

**Comment by TomazErjavec** [comment]
I think this has been settled, so, closing.
