### ISSUE TITLE
new org/@role: state?  

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#670]
@TomazErjavec I am just re-fetching officially issued metadata for persons, and realised, that some new political afiliations have been added in that data. 
Namely the role of "Landeshauptmann"  https://en.wikipedia.org/wiki/Landeshauptmann or state governor.

In Austria, these are the head of one of the 9 states (like e.g. Tyrol, Styria, Carinthia, Vienna, Salzburg...) that constitute our federal republic. In our political landscape these are quite "big fish" - they are usually called "state emperors" due to their almost feudal power, therefore I think it would be fair to encode this kind of affiliation in our TEI. 

The most straightforward way that comes into my mind is to encode this as `head`  of some `state`. 
But up to now, I think there is no `org/@role`  called `state`? 

With `state` in place my TEI could look like:  
```
<affiliation  role="head" ref="#state.Carinthia">
     <roleName xml:lang="de">Landeshauptmann von Kärnten</roleName>
      <roleName xml:lang="en">governor of Carinthia</roleName>
  </affiliation>
  ```
  ...
  ```
             <org xml:id="state.Carinthia" role="state">
                  <orgName xml:lang="de" full="yes">Bundesland Kärnten</orgName>
                  <orgName xml:lang="en" full="yes">Carinthia</orgName>
                  <idno type="URI" subtype="wikimedia" xml:lang="de">
                     https://de.wikipedia.org/wiki/K%C3%A4rnten
                  </idno>
                  <idno type="URI" subtype="wikimedia" xml:lang="en">
                    https://en.wikipedia.org/wiki/Carinthia
                  </idno>
               </org>
```

Or do I go over the top? What do you think?  

(another option would be to remove/ignore that kind of affiliation entirely: state governors are not expected to show up in the parliament of the republic. Usually a former minister or member of parliament could later on take this significant career up-step and become a governor.  Therefore the head-of-state-role would not be used for expressing an "current affiliation" for any speaker in the parliament, but usually only a former or future affiliation.)

**Comment by hpreki** [comment]
@TomazErjavec : waiting for 3.1 is completely fine for me - I only ask for `state` being added as possible value to `org@role` until then. 

As for the "top level"-status: I was not aware that there was any hierarchical ordering in `listOrg`. 
In the documentation I spot a recommendation for a certain order of `org`s to be emplyed : country - republic - parliament ... e 
Do you mean, that  `org[@role="state"]` should go to the top of the list - e.g. between `republic` and `parliament`? 
I really do not care much, but if pressed hard I would rather opt against it, because this `@role="state"`-orgs are just a means to express some _very_ specific role of a _very_ restricted number of persons ( 2-3!) in _one_ parliament... 
We e.g. also have the United Nations or the European Parliament or EU-commission in our `orgList` - for the same purpose: allowing us to express "extra-parliamentary-affiliations" in the curriculum vitae of some members of parliament. And though these entities also could be viewed as 
 being hierarchically "top level"  -  we do not put them on top of the list.  
 I would treat `org[@role="state"]` the  the same way: an obscure org that can live somewhere on the bottom :-)

**Comment by matyaskopp** [comment]
> I presume the definition of org[@role="state"] would go on the top level of the listOrg?

The TEI allows sub-organizations which @TomazErjavec indirectly permitted (https://github.com/clarin-eric/ParlaMint/issues/11)

I think the role `state` is ok, or we can choose a less deterministic label `region`.
ES-GA, ES-CA, and BE do not have this kind of organization, so your newly added role will not collide with their idea of encoding.

> express some very specific role of a very restricted number of persons ( 2-3!) in one parliament...

If someone adds Germany into ParlaMint, there will be many persons of this kind. So it is probably good to start thinking about it when only one highly cooperative country is affected :-)

In ParlaMint, there is no prescribed way for geospatial labelling non-parliament organizations:
- Europe > Austria > Tyrol > Insbruck

So no hierarchy is stored in the data.

**Comment by TomazErjavec** [comment]
> I think the role state is ok, or we can choose a less deterministic label region.

Yes, I was a bit doubtful about "state" myself, as it might be confusng, on the other hand, "region" is also problematic. I guess whatever is chosen, conventions and meanings differ between countries and never can everybody be happy..

As for the rest, as @matyaskopp says!

**Comment by hpreki** [comment]
@TomazErjavec @matyaskopp : so I would suggest to use `federatedState` as the name for the new `@role`. 
Unless you object against it soon, I will use that name in my submissions for ParlaMint 3.1 for now. Iff you decide for another name it's an easy find-and-replace in listOrg and listPerson.

**Comment by matyaskopp** [comment]
I have nothing against `federatedState`. It is safer to be more specific when we are not sure about the exact term - it can be later easier changed.

**Comment by TomazErjavec** [comment]
Yes, this sounds fine to me! 
Added `org/@role="federatedState"` to schema in latest commit (in documentation branch).

**Comment by TomazErjavec** [comment]
I think we sorted this, so, closing.
