### ISSUE TITLE
Refactorise parlamint-add-common-content and parlamint2final

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#675]
We now have to somewhat similar scripts [parlamint-add-common-content](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/parlamint-add-common-content.xsl) and [parlamint2final](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/parlamint2final.xsl), i.e. they both:
* fix some known and fixable bugs
* add common content for a release

It is not good practice anyway to have simiar code in two places, but parlamint2final also has the bug (cf. https://github.com/clarin-eric/ParlaMint/issues/662#issuecomment-1550352079)) that it calculates tagUsages on the original data, but then changes various tags in the bodies of components, leading to incorrect final tagUsages.

I propose that we change this so that:
* parlamin2final does all the fixes to the corpus
* parlamint-add-common-content does exactly what it's name says: sets the hande, date, extents and tagUsage, maybe fixes the title
* (this will also mean that I will have to change [parlamint2distro](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/parlamint2distro.pl) so that it first runs 2final, stores the corpus in a tmp folder, and then runs add-common-content on that and outputs the final corpus)

@matyaskopp, do you agree with this change? I can start implementing it, if so.

**Comment by matyaskopp** [comment]
My suggestions:
- parlamin2final should be renamed to something like `parlamint-fix-known-bugs` to avoid temptations for adding features that should be in a different script
- as a part of the fixing process can be done factorization 
  - in near future, we will not support embedded taxonomies,listPerson and listOrg - only xinclude will be supported
- `parlamint-add-common-content` can be extended with 
  - langUsage, the idea/implementation can be adopted from [ufal/ParlaMint-UA/Scripts/ParlaMint-UA-finalize.xsl](https://github.com/ufal/ParlaMint-UA/blob/74db5ef0602b8ef9419feca889306cf5772f8de0/Scripts/ParlaMint-UA-finalize.xsl#L156-L190) (I am here calculates the number of orthographical words for each language)
  - project description ???
  - number and date formatting

**Comment by TomazErjavec** [comment]
Nice ones; I'd call it parlamint4v3 :)
And I just found  #157, will look at it tomorow.

**Comment by TomazErjavec** [comment]
Here is my proposal for what parlamint-add-common-content should set or correct (both in root and component files, and taking into account number and date formatting, where applicable):
* release date (shoud be parameter, default is today)
* version number (parameter)
* handle (parameter)
* top level ID to be the same as filename
* ParlaMint stamp in main title
* speech and word extents 
* tag usages
* project description in English
* maybe langUsage, as you suggest, need to look into this

Anything else @matyaskopp? 
Any change of you implementing this, or shall I? I think parlamint2final does some of the above things better than add-common, so it might be worth comparint the templates.

**Comment by TomazErjavec** [comment]
> Any change of you implementing this, or shall I? 

As next week is pretty busy, and there is time pressure to finalise the distro scripts (it will take 3 weeks to reprocess all the corpora), I did this myself, with the final dev commit being https://github.com/clarin-eric/ParlaMint/commit/cc7addeed926e121e159135ac0e51a5bcc1df639.

I *think* add-common-content works fine (except for some doubts abut BE commission sessions), cf. https://github.com/clarin-eric/ParlaMint/blob/cc7addeed926e121e159135ac0e51a5bcc1df639/Scripts/parlamint-add-common-content.xsl#L687-L691

Also, [parlamint2release](https://github.com/clarin-eric/ParlaMint/blob/devel/Scripts/parlamint2release.xsl) might be ok too. The idea was also to leave the "fixing" of metadata (like removal GB "special" speakers) in add-common-content (even though it isn't really), but to move everything to do with annotated words into parlamint2release.xsl.

What *doesn't* work is factorisation, this might be my fault (and, to an extent probably is), but right now the parlamint2distro script has factorisation commented out: https://github.com/clarin-eric/ParlaMint/blob/cc7addeed926e121e159135ac0e51a5bcc1df639/Scripts/parlamint2distro.pl#L335-L337

The reason is, it produces a mess. Options:

- @matyaskopp tries to fix it
- I use the factorisation script already on the submitted corpora, and then run the distro script
- I reimplement factorisation, as I can't seem to really understand the current code
- I modify parlamint2release.xsl to defactorise the corpora, and then it will be easier, as the script only has to deal with non-factorised files (problems are esp. with already factorised files)

Thoughts?

**Comment by matyaskopp** [comment]
> What _doesn't_ work is factorisation, this might be my fault (and, to an extent probably is), but right now the parlamint2distro script has factorisation commented out:

It never worked in a partially factorized corpus, because it checks whether any of the types _listOrg_, _listPerson_, _taxonomy_ is factorized:
https://github.com/clarin-eric/ParlaMint/blob/cc7addeed926e121e159135ac0e51a5bcc1df639/Scripts/parlamint2distro.pl#L324-L329
If any of these types is factorized, then factorization is skipped:
https://github.com/clarin-eric/ParlaMint/blob/cc7addeed926e121e159135ac0e51a5bcc1df639/Scripts/parlamint2distro.pl#L331-L338

I believe the factorization script is working on partially factorized files, but it does not copy files in `xi:include`...
Should I add it there?

**Comment by TomazErjavec** [comment]
>  because it checks whether any of the types listOrg, listPerson, taxonomy is factorized
...
>  believe the factorization script is working on partially factorized files

So maybe the fix here would be to check if all the above are factorised?

> but it does not copy files in xi:include... Should I add it there?

Yes please!

**Comment by matyaskopp** [comment]
> > because it checks whether any of the types listOrg, listPerson, taxonomy is factorized
> > ...
> > believe the factorization script is working on partially factorized files
> 
> So maybe the fix here would be to check if all the above are factorised?

I changed the distro script to factorize every time - even if it is already factorized. **Not tested !!!**
https://github.com/clarin-eric/ParlaMint/blob/feba24b9c9e08c3bffedece408d9f0d9c6db55b6/Scripts/parlamint2distro.pl#L324-L342



> > but it does not copy files in xi:include... Should I add it there?
> 
> Yes please!

Done and tested (copy firstly parse xml - so indentation can change in the file)

**Comment by TomazErjavec** [comment]
This has all been now fixed, closing.
