### ISSUE TITLE
factorization before finalization distribution

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#681]
Prepare script for factorization data before finalization with distro script

**Comment by TomazErjavec** [comment]
Thank you @matyaskopp. On this basis I now made in [794d629](https://github.com/clarin-eric/ParlaMint/commit/794d6294c1af74b0453d3c001b9c24528feb67e4) parlamint-factorize-corpora.pl that factorised all the submitted corpora, which can then serve as input to the distribution script.
So, all done here, closing.
