### ISSUE TITLE
notes normalization and mt version

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#684]
`Scripts/mt-insert-notes.xsl` needs an update to work with normalized notes/incidents. Normalization function can be included from 
https://github.com/clarin-eric/ParlaMint/blob/5fd0a6055579ded5b2b0b77f0988246fea2c6e0e/Scripts/parlamint-lib.xsl#L558-L571
with `<xsl:import href="parlamint-lib.xsl"/>` to make safe future changes.

In the source language, only special cases of notes are normalized, but normalizing every note and matching them with the correct translation should work.

**Comment by TomazErjavec** [comment]
Done, closing.
