### ISSUE TITLE
MT: remove country specific annotations taxonomies

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#690]
this removes the inclusion of ParlaMint-taxonomy-UD-SYN.ana.xml
https://github.com/clarin-eric/ParlaMint/blob/0bc2a9c31322132b756bdcea3bd46f1a6a12235f/Scripts/mt-prepare4mt.xsl#L163-L180

But there are country-specific annotations, such as:
- `Data/ParlaMint-BE/ParlaMint-BE-taxonomy-chn_pos_tagging.ana.xml`
- `Data/ParlaMint-CZ/ParlaMint-CZ-taxonomy-NER.cnec2.0.ana.xml`
- `Data/ParlaMint-NL/ParlaMint-NL-taxonomy-chn.ana.xml`

I think all `.ana.xml` suffixed taxonomies except `ParlaMint-taxonomy-NER.ana.xml` can be removed.

**Comment by TomazErjavec** [comment]
Well spotted @matyaskopp, changed now.
