### ISSUE TITLE
XML entities not decoded in vert format

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#699]
@AnnaParla reported this for UA corpus:
`Фракція політичної партії Всеукраїнське об'єднання &#34;Батьківщина&#34;` (and many other parliamentary groups)
https://www.clarin.si/ske-beta/#text-type-analysis?corpname=parlamint30_ua&wlminfreq=1&wlicase=1&include_nonwords=1&showresults=1&wlnums=frq&wlattr=speech.speaker_party_name
I also saw it in PT corpus:
`Grupo Parlamentar do Partido Ecologista &#34;Os Verdes&#34;`
https://www.clarin.si/ske-beta/#text-type-analysis?corpname=parlamint30_pt&wlminfreq=1&wlicase=1&include_nonwords=1&showresults=1&wlnums=frq&wlattr=speech.speaker_party_name

@TomazErjavec, I remember we were discussing this maybe two years back. I don't remember if there was anything you could do... Perhaps a new nosketch solved this???
```XML
<speech id="ParlaMint-UA_2023-02-07-m0.u2" 
    ...  
    speaker_party="фЄС" 
    speaker_party_name="Фракція політичної партії &#34;Європейська солідарність&#34;" 
    ...>
<!-- -->
</speech>
```

Other possible solutions:
We can recommend avoiding `"` character or replacing it with a different one in conversion to vert

**Comment by TomazErjavec** [comment]
Well spotted. I do in fact change XML entities to chars in the vertical files, but forgot we can have not only `&quot;` but also character entities. Fixed not in [85ed583](https://github.com/clarin-eric/ParlaMint/commit/85ed58378f455769475a01ceed64068a7846cc9d), as well as the corpus on the concordancers.
But, of course, I found other bugs now, sigh...
