### ISSUE TITLE
UA: lower cased languages

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#700]
In English, the names of languages should be in upper case, but UA has them in lower case: https://github.com/clarin-eric/ParlaMint/blob/c68b7fe2bc4f27a85e8e8dbe08545035d0dc179e/Data/ParlaMint-UA/ParlaMint-UA.xml#L135-L142.

This should be fixed to English, Ukrainian, Russian both in plain text and .ana roots.

**Comment by matyaskopp** [comment]
this is already fixed in ParlaMint-UA-finalize script: https://github.com/ufal/ParlaMint-UA/commit/74db5ef0602b8ef9419feca889306cf5772f8de0
it should be ok in the next release - but leaving this opened

**Comment by AnnaParla** [comment]
I have fixed it there as well.

**Comment by TomazErjavec** [comment]
Note that this is now fixed in parlamint2release.xsl as well.
Given that this is now fixed also in source, can we close this issue?

**Comment by matyaskopp** [comment]
ok, closing
