### ISSUE TITLE
ParlaMint2release breaks CZ named entities

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#702]
This tries to fix invalid named entities, but it breaks nested entities:
https://github.com/clarin-eric/ParlaMint/blob/c68b7fe2bc4f27a85e8e8dbe08545035d0dc179e/Scripts/parlamint2release.xsl#L433-L439

should be:
```XML
  <!-- Bug where a name contains no words, but only a transcriber comment: remove <name> tag -->
  <xsl:template mode="comp" match="tei:body//tei:name[not(.//tei:w)]">
    <xsl:message select="concat('WARN ', /tei:TEI/@xml:id, 
                         ': removing name tag as name ', normalize-space(.), 
			 ' contains no words for ', ancestor-or-self::tei:*[@xml:id][1]/@xml:id)"/>
    <xsl:apply-templates mode="comp"/>
  </xsl:template>
```
`tei:w` changed to `.//tei:w` (looking for all descendants)

**Comment by TomazErjavec** [comment]
Thanks for noticing, fixed now. As discussed it might be a good idea to remove special CZ NEs anyway.
