### ISSUE TITLE
Parliamentary body - unexpected values

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#705]
possibly related to #584 

![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/efb473d3-4dca-42a7-992d-11573d536aee)

**Comment by matyaskopp** [comment]
Another view on the same issue: 
https://www.clarin.si/ske-beta/#text-type-analysis?corpname=parlamint30_xx_en&tab=basic&filter=containing&onecolumn=1&wlattr=speech.body&wlminfreq=1&include_nonwords=1&itemsPerPage=50&showresults=1&cols=%5B%22frq%22%5D&wlsort=frq

![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/ac3ed7a1-ced3-4410-a40b-33b645b3c698)

**Comment by TomazErjavec** [comment]
The text.body attrbute is a multivalued one, so "National parliament|Lower house|Legislative session|Sitting" then also decomposes into its consituent values. This comes from the [3.0 FR corpus](https://www.clarin.si/ske/#text-type-analysis?corpname=parlamint30_fr&wlminfreq=1&wlicase=1&include_nonwords=1&showresults=1&wlnums=frq&wlattr=speech.body), who has references to these categories in the meeting element.  

The value of this attribute is now ([9129867](https://github.com/clarin-eric/ParlaMint/commit/9129867f4e48e302ee6adeb2e1c6aaa0b719c809)) explicitly limited to one of the values we expect. 
Unfortunatelly the legislature taxonomy doesn't really allow for a more sensible approach.

The "unicameral" comes from [GR 3.0](https://www.clarin.si/ske/#text-type-analysis?corpname=parlamint30_gr&wlminfreq=1&wlicase=1&include_nonwords=1&showresults=1&wlnums=frq&wlattr=speech.body): https://github.com/clarin-eric/ParlaMint/blob/535dae3f802d20ea053e76899ddcf6ab805049c0/Data/ParlaMint-GR/ParlaMint-taxonomy-parla.legislature.xml#L46

The term should of course be "Unicameralism". This issue will crop up again once we make the common taxonomies, and we can address it then. For now, I fixed it in my local copy.

**Comment by TomazErjavec** [comment]
Local copies fixed, issues to indicate problems posted, oridinal corpora re-compiled, en recompiled, verts re-joined and re-installed. Phew! But I think it is ok now:
![image](https://github.com/clarin-eric/ParlaMint/assets/5927714/98fc7d78-2edb-4771-aa8b-f9e1dedf5971)
