### ISSUE TITLE
corpora sizes confusion

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#706]
I expected these statistics should show the total number of tokens in the corpora:

**multilingual version:**
https://www.clarin.si/ske-beta/#text-type-analysis?corpname=parlamint30_xx&tab=basic&filter=containing&onecolumn=1&wlattr=speech.corpus&wlminfreq=1&include_nonwords=1&itemsPerPage=50&showresults=1&chartitems=20&cols=%5B%22frq%22%5D&wlsort=token%3Al

**English version:**
https://www.clarin.si/ske-beta/#text-type-analysis?corpname=parlamint30_xx_en&tab=basic&filter=containing&onecolumn=1&wlattr=speech.corpus&wlminfreq=1&include_nonwords=1&itemsPerPage=50&showresults=1&chartitems=20&cols=%5B%22frq%22%5D&wlsort=token%3Al

**CZ standalone**
in both CZ corpus is one of the smallest ones, which is not true because it contains > 33M tokens.
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/e0680f3f-4475-4cc7-ad6f-3d76b95512e8)
https://www.clarin.si/ske-beta/#concordance?corpname=parlamint30_cz&tab=advanced&queryselector=cql&attrs=word&viewmode=kwic&attr_allpos=all&refs_up=0&shorten_refs=1&glue=1&gdexcnt=300&show_gdex_scores=0&itemsPerPage=20&structs=s%2Cg&refs=%3Dspeech.speaker_id%2C%3Dspeech.date&default_attr=lemma&cql=%5B%5D&showresults=1&showTBL=0&tbl_template=&gdexconf=&f_tab=advanced&f_showrelfrq=1&f_showperc=0&f_showreldens=0&f_showreltt=0&c_customrange=0&operations=%5B%7B%22name%22%3A%22cql%22%2C%22arg%22%3A%22%5B%5D%22%2C%22query%22%3A%7B%22queryselector%22%3A%22cqlrow%22%2C%22cql%22%3A%22%5B%5D%22%2C%22default_attr%22%3A%22lemma%22%7D%2C%22id%22%3A4889%7D%5D

**CZ in multilingual**
But when I query this in the multilingual version, I get only 9.4 M tokens
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/2c8b96f2-c8d9-44ad-b353-9accc314814a)
https://www.clarin.si/ske-beta/#concordance?corpname=parlamint30_xx&tab=advanced&queryselector=cql&attrs=word&viewmode=kwic&attr_allpos=all&refs_up=0&shorten_refs=1&glue=1&gdexcnt=300&show_gdex_scores=0&itemsPerPage=20&structs=s%2Cg&refs=%3Dspeech.speaker_id%2C%3Dspeech.date&default_attr=lemma&cql=%5B%5D&showresults=1&tts=%7B%22speech.corpus%22%3A%5B%22CZ%22%5D%7D&showTBL=0&tbl_template=&gdexconf=&f_tab=basic&f_showrelfrq=1&f_showperc=0&f_showreldens=0&f_showreltt=0&c_customrange=0&operations=%5B%7B%22name%22%3A%22cql%22%2C%22arg%22%3A%22%5B%5D%22%2C%22query%22%3A%7B%22queryselector%22%3A%22cqlrow%22%2C%22cql%22%3A%22%5B%5D%22%2C%22default_attr%22%3A%22lemma%22%2C%22sca_speech.corpus%22%3A%5B%22CZ%22%5D%7D%2C%22id%22%3A5066%7D%5D

**Comment by matyaskopp** [comment]
it seems that some data has not been loaded to noske:
Zelenskyj speech is in CZ corpus: https://www.clarin.si/ske-beta/#concordance?corpname=parlamint30_cz&tab=advanced&queryselector=cql&default_attr=word&cql=%3Cspeech%20speaker_name%3D%3D%22Zelenskyj%2C%20Volodymyr%22%3E%5B%5D&showresults=1

but it is missing in multilingual (ParlaMint30_xx)
https://www.clarin.si/ske-beta/#concordance?corpname=parlamint30_xx&tab=advanced&queryselector=cql&default_attr=word&cql=%3Cspeech%20speaker_name%3D%3D%22Zelenskyj%2C%20Volodymyr%22%3E%5B%5D&showresults=1

and in the ParlaMint30_xx_en:
https://www.clarin.si/ske-beta/#concordance?corpname=parlamint30_xx_en&tab=advanced&queryselector=cql&default_attr=word&cql=%3Cspeech%20speaker_name%3D%3D%22Zelenskyj%2C%20Volodymyr%22%3E%5B%5D&showresults=1

but it is in the "release":
```XML
            <note type="speaker" xml:lang="en">President of Ukraine Volodymyr Zelesky</note>
            <u who="#VolodymyrZelenskyj" ana="#guest" xml:id="ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5" source="https://www.psp.cz/eknih/2021ps/stenprot/220615/s901003.htm#r2" xml:lang="en" corresp="mt-src:ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5">
               <note type="comment" xml:lang="en">Speaks Ukrainian, simultaneous translation.</note>
               <seg xml:id="ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1" xml:lang="en" corresp="mt-src:ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1">
                  <s xml:id="ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1.s1" n="79" corresp="mt-src:ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1.s1">
<w xml:id="ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1.s1.t1" pos="VBP" msd="UPosTag=VERB|Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin" lemma="thank">Thank</w>
<w xml:id="ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1.s1.t2" pos="PRP" msd="UPosTag=PRON|Case=Acc|Person=2|PronType=Prs" lemma="you" join="right">you</w>
<pc xml:id="ParlaMint-CZ_2022-06-15-ps2021-000-01-000-999.u5.p1.s1.t3" pos="Z" msd="UPosTag=PUNCT">.</pc>
                  </s>
<!-- .... -->
             </u>
```

**Comment by TomazErjavec** [comment]
Thanks, this was a stupid mistake where only 1 file per date was inserted into the common XX vert.
Fixed now in script, should be ok when I make the new vert and mount it.
Leaving open for now, so we can make sure the mistake is gone once new XX corpus is avialable on the concordancer.

**Comment by TomazErjavec** [comment]
Fixed now, closing.
