### ISSUE TITLE
IS: missing lang attribute in language

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#708]
https://github.com/clarin-eric/ParlaMint/blob/535dae3f802d20ea053e76899ddcf6ab805049c0/Data/ParlaMint-IS/ParlaMint-IS.xml#L124-L127

should be:
```XML
 <langUsage> 
    <language xml:lang="en" ident="en">English</language> 
    <language xml:lang="en" ident="is">Icelandic</language>
 </langUsage> 
```

Or even better is to add an Icelandic translation...

See other corpora, e.g. AT:
https://github.com/clarin-eric/ParlaMint/blob/535dae3f802d20ea053e76899ddcf6ab805049c0/Data/ParlaMint-AT/ParlaMint-AT.xml#L157-L162

**Comment by TomazErjavec** [comment]
Yes, this should be fixed for 3.1, as it causes all segments in IS not to be marked with language in the concordancers. Not such a problem for monolingual corpora, but is a problem for the multilingual one.

**Comment by starkadur** [comment]
I'm sorry for how late I reacted to this. I somehow thought I had received an email telling me I did not have to do anything but just bear this in mind the next time I would compile the data. But I don't find any such email. If I am not wrong there are only two places that I would need to change this, in the root file of  TEI and TEI.ana. Should I just change those files and send them to you?

**Comment by TomazErjavec** [comment]
> If I am not wrong there are only two places that I would need to change this, in the root file of TEI and TEI.ana.

Yes, exactly.

> Should I just change those files and send them to you?

Yes please!

**Comment by TomazErjavec** [comment]
Files sent, closing.
