### ISSUE TITLE
GR: lower cased languages

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#709]
The same issue is in UA: #700 

In English, the names of languages should be in upper case, but GR has them in lower case:
https://github.com/clarin-eric/ParlaMint/blob/535dae3f802d20ea053e76899ddcf6ab805049c0/Data/ParlaMint-GR/ParlaMint-GR.xml#L129-L134

**Comment by TomazErjavec** [comment]
Note that this is now fixed in parlamint2release.xsl. Of course, It would still be good to fix it in the source.

**Comment by TomazErjavec** [comment]
Fixed, closing.
