### ISSUE TITLE
different number of notes in joint and single corpora

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#717]
I have discovered an inconsistency in notes between ParlaMint-XX and ParlaMint-ES-GA:
- (I was not able to filter only ES-GA, you have to jump to the correct page) https://www.clarin.si/ske-beta/#concordance?corpname=parlamint30_xx&tab=advanced&queryselector=cql&attrs=word&viewmode=kwic&attr_allpos=all&refs_up=0&shorten_refs=1&glue=1&gdexcnt=300&show_gdex_scores=0&itemsPerPage=20&structs=s%2Cg&refs=%3Dspeech.speaker_id%2C%3Dspeech.date&cql=%3Cspeech%3E&showresults=1&results_screen=frequency&showTBL=0&tbl_template=&gdexconf=&f_freqml=%5B%7B%22attr%22%3A%22speech.corpus%22%2C%22context%22%3A%220%22%2C%22base%22%3A%22kwic%22%7D%2C%7B%22ctx%22%3A0%2C%22base%22%3A%22kwic%22%2C%22attr%22%3A%22note.type%22%7D%5D&f_tab=advanced&f_showrelfrq=1&f_group=1&f_showperc=0&f_showreldens=0&f_showreltt=0&c_customrange=0&operations=%5B%7B%22name%22%3A%22cql%22%2C%22arg%22%3A%22%3Cspeech%3E%22%2C%22query%22%3A%7B%22queryselector%22%3A%22cqlrow%22%2C%22cql%22%3A%22%3Cspeech%3E%22%2C%22default_attr%22%3A%22%22%7D%2C%22id%22%3A4578%7D%5D 
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/ace3d3ab-c72d-4397-8af8-50742f992195)

- https://www.clarin.si/ske/#text-type-analysis?corpname=parlamint30_es_ga&tab=basic&filter=containing&onecolumn=1&wlattr=note.type&wlminfreq=1&include_nonwords=1&itemsPerPage=50&showresults=1&cols=%5B%22frq%22%5D&wlsort=frq
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/a9ca7f9e-1fa5-490b-aad5-239a28ed887a)

Many notes are missing in the "joint corpora" (ParlaMint-XX)

**Comment by TomazErjavec** [comment]
The missing notes etc. are ok in TEI, but it seems I lose them here: https://github.com/clarin-eric/ParlaMint/blob/a726ea51017fe5d00d797fe82099a3da88c88e07/Scripts/parlamint2xmlvert.xsl#L127-L133. 
Will look into it once ParlaMint-en 3.0 is released.

**Comment by TomazErjavec** [comment]
Hm, the [parlamint2xmlvert.xsl](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/parlamint2xmlvert.xsl) has changed a lot in the meantime, and I think I also addressed this issue. However, note (sic!) that it doesn't really matter, as the concordancer looses a lot of notes anyway, as they are empty elements, and if more than one follows a token, only one is retained.

So I will close this, but if @matyaskopp you feel it is an issue, please reopen in Future.
