### ISSUE TITLE
ParlaMint "root" files

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#72]
There are now two overall ParlaMint corpus "root" files, one for the [unannotated](https://github.com/clarin-eric/ParlaMint/blob/main/ParlaMint.xml) and the other for the [.ana](https://github.com/clarin-eric/ParlaMint/blob/main/ParlaMint.ana.xml) corpus. Both are automatically generated from the root files in the sample directories with the [parlamint2root.xsl](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/parlamint2root.xsl) script.

The reason "root" is in quotes is that the files are not actually meant to be used as a proper root (we would get ID clashes, also, a huge XML document), but rather as another aid to validation, or, rather, harmonisation: here you can see one after the other the same elements from the teiHeaders of the corpora for each country (for those that are currently available), so if anybody is different (in a bad way) from the others, you could fix your corpus. 

Of coruse, if anybody has suggestion for improving these two files, pls. post them here.

**Comment by matyaskopp** [comment]
### Namespaces
Your script copies namespaces definitions from `teiCorpus`, I have defined there a `xi:include`. And it looks quite strange:
https://github.com/clarin-eric/ParlaMint/blob/fa851dfa5c02b7b9f2047e47ab412a12b1e9a0ac/ParlaMint.ana.xml#L37-L44
Should we move extra namespaces to subelements?

### Date format
What is recommended format for the text version of date interval? We used SI version:
https://github.com/clarin-eric/ParlaMint/blob/fa851dfa5c02b7b9f2047e47ab412a12b1e9a0ac/ParlaMint.ana.xml#L211
But some others used a similar format as in attributes is used:
https://github.com/clarin-eric/ParlaMint/blob/fa851dfa5c02b7b9f2047e47ab412a12b1e9a0ac/ParlaMint.ana.xml#L128

**Comment by TomazErjavec** [comment]
> Should we move extra namespaces to subelements?

Yes, that would be nice (so, directly to the xi:include elements), so they don't pop up in weird places. 

> What is recommended format for the text version of date interval?

There isn't one, I didn't want to complicate people's with this as well because language/country specific rules (which I would prefer there) can be rather difficult to implement. So, just leave yours as it is, the others, well, if you can change to whatever your country uses, great, if not, not to worry. For the root file I guess I could just change so that the values from the attributes are displayed.

**Comment by TomazErjavec** [comment]
There doesn't seem to be further comments here, so closing this issue.
