### ISSUE TITLE
Speaker role when unknown speaker

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#725]
This situation
```XML
<u xml:id="ParlaMint-ES_2015-01-20-CD150120.u1" ana="#chair">
  <!-- SKIPPING -->
</u>
```
is not in the Chairman slice in a pie chart but in an unknown role. See charts from ParlaMint ES:
**roles**
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/7dd4889e-4d7d-48da-a124-41bb0ba16df5)

**speaker names**
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/913d5d49-6be0-4eaa-88c0-c29a51dffb2c)

**Comment by TomazErjavec** [comment]
Thanks for noticing, silly bug. Fixed now.
![image](https://github.com/clarin-eric/ParlaMint/assets/5927714/3b54dd37-1c54-488c-8831-89a9da6b9a72)
