### ISSUE TITLE
UA: wrong English name of grVU?

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#726]
I noticed the following English name:
https://github.com/clarin-eric/ParlaMint/blob/7d358e298dc1b39a0f9ed5fc9dc28e67340f1150/Data/ParlaMint-UA/ParlaMint-UA-listOrg.xml#L1001-L1002

Is this the same as https://en.wikipedia.org/wiki/Restoration_of_Ukraine? Because, if so, it would be better to give it the same name as is on English Wikipedia (ditto for any others). If this is in fact some other party, just close the issue pls.!

**Comment by matyaskopp** [comment]
Yes, this is the very same parliamentary group, the source for our data was this message: https://lb.ua/news/2022/05/22/517619_radi_stvorili_novu_deputatsku.html

@AnnaParla please confirm and change it in our spreadsheet
