### ISSUE TITLE
Political orientation taxonomy

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#729]
Note also that [ParlaMint-taxonomy-politicalOrientation.xml](https://github.com/clarin-eric/ParlaMint/blob/main/Corpora/Taxonomies/ParlaMint-taxonomy-politicalOrientation.xml) is not in fact yet finished (explanations for the more bizzare orientations are missing).

_Originally posted by @TomazErjavec in https://github.com/clarin-eric/ParlaMint/issues/728#issuecomment-1691569932_

**Comment by TomazErjavec** [comment]
I added explanations to the [taxonomy](https://github.com/clarin-eric/ParlaMint/blob/devel/Corpora/Taxonomies/ParlaMint-taxonomy-politicalOrientation.template.xml), @katjameden, could you have a look pls. and let us know if you find any errors?

**Comment by katjameden** [comment]
I looked at the taxonomy, and the terms and explanations seem to be fine, except for "Far left" and "Far right", which should probably have a "-" between them (i.e. "Far-left" and "Far-right"), as Jure mentioned earlier in the email.

And just one tiny editing problem: there's an extra space at the end of the explanation of "Single Issue Politics" that should be deleted.

**Comment by matyaskopp** [comment]
> I looked at the taxonomy, and the terms and explanations seem to be fine, except for "Far left" and "Far right", which should probably have a "-" between them (i.e. "Far-left" and "Far-right"), as Jure mentioned earlier in the email.
> 
> And just one tiny editing problem: there's an extra space at the end of the explanation of "Single Issue Politics" that should be deleted.

Okay, I have implemented changes in 6b2d2cf

**Comment by matyaskopp** [comment]
I believe we can close this issue. If @katjameden or @jureskubic disagree, please reopen.
