### ISSUE TITLE
GR: affiliation "to" less than "from"

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#738]
In GR listPerson there are two cases where the `affiliation/@to' attribute is less than `affiliation/@from', cf. `from="2019-07-17" to="2019-07-15"` in:
https://github.com/clarin-eric/ParlaMint/blob/0dfbeb729f258a114e29b82faca9e847ed4c51b6/Samples/ParlaMint-GR/ParlaMint-GR-listPerson.xml#L2876-L2881

**Comment by DimitrisGk-iel** [comment]
Thanks for spotting this out. The correct start date is 2019-07-07. We will make the appropriate corrections.

**Comment by TomazErjavec** [comment]
Thank you! Please could you do it soon, so that we can start wrapping up the corpora.
Just to keep things tidy, this error is first mentioned in #715.

**Comment by DimitrisGk-iel** [comment]
I have rerun the code to output the root xmls (ParlaMint-GR.xml , ParlaMint-GR.ana.xml) but i am getting the following error. Did something change at version 3 because until 2.1 we didn't have this issue?
![image](https://github.com/clarin-eric/ParlaMint/assets/30075838/d77d3bd4-0482-46ec-a3e9-e759e959249d)

**Comment by TomazErjavec** [comment]
> Did something change at version 3 because until 2.1 we didn't have this issue?

Sorry for not alerting you about this, because a) indeed, it did change, and b) I changed your corpus myself in one detail exactly so this would work but forgot to let you know. Namely, you have:
https://github.com/clarin-eric/ParlaMint/blob/0dfbeb729f258a114e29b82faca9e847ed4c51b6/Samples/ParlaMint-GR/ParlaMint-taxonomy-parla.legislature.xml#L41-L48
but the correct term is:
https://github.com/clarin-eric/ParlaMint/blob/0dfbeb729f258a114e29b82faca9e847ed4c51b6/Corpora/Taxonomies/ParlaMint-taxonomy-parla.legislature.xml#L572-L574

So, if you could just change "unicameral" to "Unicameralism" and hopefully it will work.

**Comment by DimitrisGk-iel** [comment]
I have issued a PR that should address the 3 issues (#738 #735 #709).
Please, let me know if you spot anything out of order.
Also, should i send the 2 root files ( ParlaMint-GR.xml, ParlaMint-GR.ana.xml ) with all the xi:include elements in an email?

**Comment by TomazErjavec** [comment]
Thanks, will do it soon. Yes, pls. email the files.

**Comment by TomazErjavec** [comment]
Fixed, closing.
