### ISSUE TITLE
SE: affiliation "to" less than "from"

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#742]
As noticed in https://github.com/clarin-eric/ParlaMint/issues/715, SE has a case where the value of the to attribute has a date that comes before the value of from:
```
ERROR : attribute to=2019-01-19 is before from=2019-01-21
```
This is the error:
https://github.com/clarin-eric/ParlaMint/blob/0dfbeb729f258a114e29b82faca9e847ed4c51b6/Samples/ParlaMint-SE/ParlaMint-SE-listPerson.xml#L2213-L2215

It would be great if you could fix this and re-send the listPerson. However, it needs to be done soon, so we can wrap up the corpora.

**Comment by ninpnin** [comment]
Is this an isolated case or multiple things?

**Comment by TomazErjavec** [comment]
Just this 1 case.

**Comment by ninpnin** [comment]
This should be correct

```xml
 <affiliation role="minister" ref="#GOV" from="2019-01-21" to="2021-11-30"> 
    <roleName xml:lang="sv">minister för högre utbildning och forskning</roleName> 
 </affiliation> 
```

**Comment by TomazErjavec** [comment]
Thanks, will fix it so at our end.
