### ISSUE TITLE
Wrong IOB format for nested named entities

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#75]
Source data:
https://github.com/clarin-eric/ParlaMint/blob/99f6b182f407287352957969e9d61fccc2c41002/ParlaMint-CZ/ParlaMint-CZ_2016-04-13-ps2013-044-02-006-162.ana.xml#L322-L336

Conll format:
https://github.com/clarin-eric/ParlaMint/blob/99f6b182f407287352957969e9d61fccc2c41002/ParlaMint-CZ/ParlaMint-CZ_2016-04-13-ps2013-044-02-006-162.conllu#L47-L48

Correct (simplified) format (ignoring nested `<name>` elements):
```
5	Milana     	....	_	NER=B-PER
6	Chovance	....	_	NER=I-PER|SpaceAfter=No
```
NER value for `Chovanec` should be `I-PER`

related #73

**Comment by TomazErjavec** [comment]
Well spotted! I think I fixed it now in the script (9b20bfc) and files (0c19666).
