### ISSUE TITLE
NoSketch - no or invalid pie chart

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#751]
I came to this when I was answering #750 

@TomazErjavec, this looks like a bug in NoSketch. 
When you want a **pie chart of a feature with no values in the corpus**, you get no pie chart instead of a single color chart with an empty label. It is confusing because if you have already printed some different chart, the chart is not removed, but the old chart remains.

1. Try this link: https://www.clarin.si/ske/#text-type-analysis?corpname=parlamint30_dk&tab=basic&filter=containing&onecolumn=1&wlattr=speech.term&wlminfreq=1&include_nonwords=1&itemsPerPage=50&showresults=1&cols=%5B%22frq%22%5D&wlsort=frq
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/71f11bc9-bfc5-4cd5-b3e1-db6c5ad10404)

2. click on different feature:
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/a6176a76-b8cb-413c-a822-be1ada95856f)

3. click back to the term 
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/1dbfcc85-0320-4b66-ad85-d0f7988d2d07)

**Comment by TomazErjavec** [comment]
OK, the good news is that DK now [has terms](https://www.clarin.si/ske/#text-type-analysis?corpname=parlamint40_dk&tab=basic&filter=containing&onecolumn=1&wlattr=speech.agenda&wlminfreq=1&include_nonwords=1&itemsPerPage=50&showresults=1&cols=%5B%22frq%22%5D&wlsort=frq), so the first specific bug won't crop up at least here. 
And then, nothing we can do about this (except if somebody were to report it to Lexical Computing), so I will close this issue.
