### ISSUE TITLE
government opposition TEI representation

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#76]
I'm not sure that the current(NL) TEI representation of opposition political parties/groups is correctly encoded. 
https://github.com/clarin-eric/ParlaMint/blob/ff310bb92decb5de9c0b26ec5482a3298296f502/ParlaMint-NL/ParlaMint-NL.xml#L500-L504

The parties are not mutually in opposition. They are in opposition to government (`#GOV`) or current government political parties/groups (`#party.VVD #party.PvdA`). So I guess, a correct TEI encoding (according to guidelines: [`<relation>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-relation.html)) is:

```
<relation name="opposition"
          active="#party.PVV #party.SP #party.CDA #party.D66 #party.ChristenUnie #party.GroenLinks #party.SGP #party.PvdD #party.50PLUS"
          passive="#GOV"
          from="2012-11-05"
          to="2017-03-14"
          ana="#GOV.28"/>
```
or
```
<relation name="opposition"
          active="#party.PVV #party.SP #party.CDA #party.D66 #party.ChristenUnie #party.GroenLinks #party.SGP #party.PvdD #party.50PLUS"
          passive="#party.VVD #party.PvdA"
          from="2012-11-05"
          to="2017-03-14"
          ana="#GOV.28"/>
```

Parla-CLARIN recommendations don't mention how to represent it.

**Comment by TomazErjavec** [comment]
I agree with the above proposal, and it was so implemented in cd103d7. However, as mentioned in #77, there is the problem that not all corpora include `org[@role = 'government']`, e.g. https://github.com/clarin-eric/ParlaMint/blob/cd103d76452018390f4c63296892295952174a36/Parties/ParlaMint-relations.xml#L9-L15

 So, if we won't be able to have this inserted, then we will have to stick to "mutual", even though I agree that it is semantically ill-formed.

**Comment by matyaskopp** [comment]
I see... 
What if we define an opposition differently - it is not an opposition to the government, but it is an opposition with the respect to a given chamber (I would prefer the term, but we decide to define the term as the `<event>` instead of `<org>`).

Suggested solution:
```
 <relation n="BE" 
           name="opposition" 
           active="#Ecolo #cdH #DéFi #Vuye_Wouters #sp.a #PP #PS #PTB #FDF #VB #PVDA-PTB #Groen" 
           passive="#parliament" 
           from="2014-10-11" 
           to="2018-12-09" 
           ana="#period_54"/>
```

The relation should be definitely between some subject and object. So `pasive="#"` doesn't seem to be a good solution...

**Comment by TomazErjavec** [comment]
> So pasive="#" doesn't seem to be a good solution...

Of course not, this is just # followed by the non-existent government ID..

> passive="#parliament" 

I find this rather ugly, i.e. wrong, as they are not in opposition ot the parliament, as they are members of the parliament.

What occurs to me now is that we can ask people to put in the goverment org, but, if they don't, I have this finalization script anyway, and it wouldn't be too hard to add - for those that don't already have it - at the start of listOrg an new organisation, a la
```
<org role="government" xml:id="government.XX" >
   <orgName xml:lang="en" full="yes">Government of Xland</orgName>
</org>
```
I can probably sniff out what "Xland" should in fact stand for. It is not perfect, as the official name of the gov't is most likely different, and we are lacking its name in the county language and possible other info, but maybe it is still the best option?

And now that I look at who has this info missing from my last export, there are not so many: BE, HR, PL, TR. The second two are the V1 folks, could be persuaded to add this info, maybe BE and TR as well, what do your say @JessedeDoes and @coltekin?

**Comment by matyaskopp** [comment]
> What occurs to me now is that we can ask people to put in the goverment org... 

Adding a "fictive" government organization makes sense to me. Even if no person will be affiliated with it.

**Comment by coltekin** [comment]
Adding a government org sounds good to me. I can happily add this (easy for TR corpus).

I do not know if this is in line with the idea above, but some frequent speakers (e.g., ministers) who are not members of the parliament (or even maybe one of the parties) but part of the government may also be indicates as the member of it.

**Comment by TomazErjavec** [comment]
> Adding a government org sounds good to me. I can happily add this (easy for TR corpus).

Great, thanks. You can just send me the org element, or, if you want, the 2 roots with this added.

> I do not know if this is in line with the idea above, but some frequent speakers (e.g., ministers) who are not members of the parliament (or even maybe one of the parties) but part of the government may also be indicates as the member of it.

I guess it is in line with this idea, but so far nobody has done this - except FR (although, interestingly, they don't have the government as such), e.g.
https://github.com/clarin-eric/ParlaMint/blob/d40e5b7a0cf7e2ae51af3bf8dc30fcf56a8f9af6/ParlaMint-FR/ParlaMint-FR.xml#L470-L476
and then https://github.com/clarin-eric/ParlaMint/blob/d40e5b7a0cf7e2ae51af3bf8dc30fcf56a8f9af6/ParlaMint-FR/ParlaMint-FR.xml#L2996-L2999
(although it seems strange to me that the role of prime minister is time delimited, I would leave it without the existence event)

If you wish, you can of course add such info.

**Comment by TomazErjavec** [comment]
The encoding of oppostions (and insertion of the governemt organisations) has been done, so, closing.
