### ISSUE TITLE
Translating taxonomies - HOW TO

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#764]
Where can I find detailed information about the translation of taxonomies?

In the slide from the last meeting, it said "Taxonomies without translations are prepared in folders in data branch".  In Data/ParlaMint-IS there are no taxonomy files.

I am also a bit confused since I had all the taxonomy files in my data folder on my local repository, with Icelandic translations, before I pulled from the remote to my local this morning. Now they are all gone.

**Comment by matyaskopp** [comment]
The `Data` folder has been renamed to `Sample`  https://github.com/clarin-eric/ParlaMint/commit/faf9a27f0348ebbef45483b1a8ed150c3d05e546

Prepared taxonomies are here: https://github.com/clarin-eric/ParlaMint/tree/data/Samples/ParlaMint-IS
