### ISSUE TITLE
ES-GA: Update data

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#767]
We just added a missing team member in the .ana file and completed the roleName for ministers in the listPerson file. No other changes on our part for the next release. 
Here is the [link](https://drive.google.com/file/d/1jBWjpNKoLpJ53UJq2h7-oQsWMhLh7i9S/view?usp=drive_link) for you and @TomazErjavec to a .zip file containing the final version of the .ana and listPerson files, downloadable with 
```bash
wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1jBWjpNKoLpJ53UJq2h7-oQsWMhLh7i9S' -O new-final-ES-GA.zip
```

_Originally posted by @adina-v in https://github.com/clarin-eric/ParlaMint/issues/763#issuecomment-1721319060_

**Comment by TomazErjavec** [comment]
OK, received and processed, closing.
