### ISSUE TITLE
IS: update(fix) data

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#783]
https://github.com/clarin-eric/ParlaMint/pull/781

Replace `#parla.meeting.unregistered` with `#parla.meeting` in component files

**Comment by TomazErjavec** [comment]
Hopefilly fixed in 6199c88. If problems, next build will report, so, closing.

**Comment by TomazErjavec** [comment]
Nope, my fix didn't work, still getting `"#parla.meeting.unregistered` in final corpus. Must fix.

**Comment by TomazErjavec** [comment]
Truly fixed now, closing.
