### ISSUE TITLE
UA: remaining problem(s)

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#785]
The latest build of UA shows only 1 error:
`ERROR: multiple party statuses for ВікторВасильовичБондар.1975 on 2015-02-05: Coalition Opposition`
So, it seems that one of the parties the speaker belongs to is on the given date both in Coalition and Opposition. This should be fixed, and a new listPerson submitted.

If anybody wants to look at the warnings as well (and there are some funny ones, but mostly to do with the linguistic analysis), the logs are, as always, at https://nl.ijs.si/et/tmp/ParlaMint/Logs/?C=M;O=D

For further checks, the corpus is also available at https://www.clarin.si/ske-beta/#dashboard?corpname=parlamint31_ua
Note that the metadata is now in local langauge.
You can see the formatting of the person names and political orientation there too. The latter is as suggested first in #775, so Wiki followed by enco. This can be changed of course.

**Comment by matyaskopp** [comment]
@AnnaParla I have updated all fraction affiliations:
- removed affiliations from data.rada.gov.ua
- added affiliations from `Faction-group_membership` sheet

**Comment by matyaskopp** [comment]
@TomazErjavec, sorry for our Ukrainian mess. We have used multiple official sources which were in conflict.
Now, it should be fixed:
- in data branch https://raw.githubusercontent.com/clarin-eric/ParlaMint/437c87f41a9880c4a5f3b43922d10b12bbe7a9e8/Samples/ParlaMint-UA/ParlaMint-UA-listPerson.xml
- in my tantra home ParlaMint-UA-3.1

you can close it, once you update your copy.

**Comment by TomazErjavec** [comment]
Thanks, processed with the new listPerson, no errors now, so, closing.
