### ISSUE TITLE
Reapperance of Data/

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#788]
In the data branch we now again have the obsolete [Data/](https://github.com/clarin-eric/ParlaMint/tree/data/Data/) directory, maybe because @hpreki's push/pull request with obsolete repo. @hpreki, @matyaskopp, can this be deleted?

**Comment by matyaskopp** [comment]
oh, I haven't noticed that during the merge, sorry. Now fixed (removed whole Data folder)

**Comment by TomazErjavec** [comment]
Thanks, but I now noticed that it still persists in the Main branch, so pls. delete there too.
Maybe it would be a good idea to merge data and esp. devel into Main as well, latter 67 commits ahead!

**Comment by matyaskopp** [comment]
solved, branches are synced now
