### ISSUE TITLE
Rename V3.1 to V4?

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#793]
I can't get it out of my head that it would be good to have the next version named 4.0, rather than 3.1:

- there have been so many changes since 3.0 that this is not a minor revision of the data but a major one
- minor revisions are also supposed to retain backward compatibility, but this one won't as some encoding decisions have changed, and the vertical file / concordancer attributes as well, and for ParlaMint-en the CoNLL-U files
- it's kind of neat that ParlaMint I had version 1 and 2, and ParlaMint II would have 3 and 4
- last, but not least, V4 rolls of the tongue better than 3.1

I would do the work, this is more asking for confirmation or good reasons why this is stupid.

**Comment by matyaskopp** [comment]
I like the idea, also for two more reasons:
- We want to refer both to the corpus and to the schema(and requirements), so it is easier to refer to v4 to avoid conclusion. We can e.g. release a ParlaMint-UA 4.0.1 (as a standalone corpus) with more data which will clearly refer to the ParlaMint 4 schema and requirements.
- one Czechocentric reason is that then ParlaMint and ParCzech versioning will be aligned with the versions :-)
