### ISSUE TITLE
vert file do not correspond to meta.tsv

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#798]
vert sample
```XML
<speech id="ParlaMint-ES-CT_2017-10-27-4402.1.0" text_id="ParlaMint-ES-CT_2017-10-27-4402" subcorpus="Corpus de referència" lang="Català" body="Unicameralisme" term="XII Legislatura" session="-" meeting="44" sitting="2" agenda="-" date="2017-10-27" title="Corpus Parlamentari en català ParlaMint-ES-CT, 2017-10-27 4402.ana" speaker_role="Presidència" speaker_id="ForcadellCarme" speaker_name="Forcadell Lluís, Carme" speaker_mp="MP" speaker_minister="notMinister" speaker_party="GP-JxSi;GP-REP" speaker_party_name="Grup Parlamentari de Junts pel Sí;Grup Parlamentari Republicà" party_status="-" party_orientation="Partit arreplegador" speaker_gender="F" speaker_birth="1955">
```

corresponding tsv lines
```tsv
ID      Title   Date    Body    Term    Session Meeting Sitting Agenda  Subcorpus       Speaker_role    Speaker_MP      Speaker_Minister        Speaker_party        Speaker_party_name      Party_status    Speaker_ID      Speaker_name    Speaker_gender  Speaker_birth
ParlaMint-ES-CT_2017-10-27-4402.1.0     Corpus Parlamentari en català ParlaMint-ES-CT, 2017-10-27 4402.ana      2017-10-27      Unicameralisme  XII Legislatura      -       44      2       -       Corpus de referència    Presidència     MP      notMinister     GP-JxSi;GP-REP  Grup Parlamentari de Junts pel Sí;Grup Parlamentari Republicà        -       ForcadellCarme  Forcadell Lluís, Carme  F       1955
```

| tsv key            | tsv value                                                          | vert key           | vert value                                                         |
|--------------------|--------------------------------------------------------------------|--------------------|--------------------------------------------------------------------|
| ID                 | ParlaMint-ES-CT_2017-10-27-4402.1.0                                | id                 | ParlaMint-ES-CT_2017-10-27-4402.1.0                                |
| Title              | Corpus Parlamentari en català ParlaMint-ES-CT, 2017-10-27 4402.ana | title              | Corpus Parlamentari en català ParlaMint-ES-CT, 2017-10-27 4402.ana |
| Date               | 2017-10-27                                                         | date               | 2017-10-27                                                         |
| Body               | Unicameralisme                                                     | body               | Unicameralisme                                                     |
| Term               | XII Legislatura                                                    | term               | XII Legislatura                                                    |
| Session            | -                                                                  | session            | -                                                                  |
| Meeting            | 44                                                                 | meeting            | 44                                                                 |
| Sitting            | 2                                                                  | sitting            | 2                                                                  |
| Agenda             | -                                                                  | agenda             | -                                                                  |
| Subcorpus          | Corpus de referència                                               | subcorpus          | Corpus de referència                                               |
| Speaker_role       | Presidència                                                        | speaker_role       | Presidència                                                        |
| Speaker_MP         | MP                                                                 | speaker_mp         | MP                                                                 |
| Speaker_Minister   | notMinister                                                        | speaker_minister   | notMinister                                                        |
| Speaker_party      | GP-JxSi;GP-REP                                                     | speaker_party      | GP-JxSi;GP-REP                                                     |
| Speaker_party_name | Grup Parlamentari de Junts pel Sí;Grup Parlamentari Republicà      | speaker_party_name | Grup Parlamentari de Junts pel Sí;Grup Parlamentari Republicà      |
| Party_status       | -                                                                  | party_status       | -                                                                  |
| Speaker_ID         | ForcadellCarme                                                     | speaker_id         | ForcadellCarme                                                     |
| Speaker_name       | Forcadell Lluís, Carme                                             | speaker_name       | Forcadell Lluís, Carme                                             |
| Speaker_gender     | F                                                                  | speaker_gender     | F                                                                  |
| Speaker_birth      | 1955                                                               | speaker_birth      | 1955                                                               |
|                    |                                                                    | text_id            | ParlaMint-ES-CT_2017-10-27-4402                                    |
|                    |                                                                    | lang               | Català                                                             |
|                    |                                                                    | party_orientation  | Partit arreplegador                                                |

`text_id`, `lang`,`party_orientation` are missing in tsv files. I am not sure what `lang` means, because language can change within utterance.

(@maartenpt please follow this issue because it will influence conversion to TEITOK format)

**Comment by TomazErjavec** [comment]
Thanks @matyaskopp for noticing this, and giving a stunningly clear analysis! My bad... Fixed now, I hope, but lets wait until ES-CT is built again before closing.

**Comment by TomazErjavec** [comment]
> I am not sure what lang means, because language can change within utterance.

About this: if it does then "Multilingual" is output. Yes, always in English...

**Comment by TomazErjavec** [comment]
This has been fixed as far as I can tell, so, closing.
