### ISSUE TITLE
links to search services for text version of corpora don't make sense

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#81]
I am a bit confused about links to search services on **plain text** version:

> Erjavec, Tomaž; et al., 2021, _Multilingual comparable corpora of parliamentary debates ParlaMint 2.0_, Slovenian language resource repository CLARIN.SI, [http://hdl.handle.net/11356/1388](http://hdl.handle.net/11356/1388)

![image](https://user-images.githubusercontent.com/5867995/118233726-969c9080-b492-11eb-883e-999294d99eb9.png)

They don't make sense to me because search services work with **annotated** data.

**Comment by TomazErjavec** [comment]
Well, this was meant as a feature, but I guess it is arguable. The idea was that it makes it easier for folks to see that they can search via the concordancers, regardless of which entry they land on. But, yes, the unannotated corpus is not the one mounted on the concordancers. So, do we prefer utility or truth? Your call, this info is not difficult to delete.

One more change: we now have for noSkE also per-corpus search in the menu. If you click on "ParlaMint", you are in the parlamint.cgi, and can search only among our corpora. If you click on a particular country corpus, your are in run.cgi, and can then search also in any other of the mounted corpora. Feature or bug? I think the first, but it might be confusing. But you can then compare a parlamint corpus to some other avialable there.

**Comment by matyaskopp** [comment]
> Well, this was meant as a feature, but I guess it is arguable. The idea was that it makes it easier for folks to see that they can search via the concordancers, regardless of which entry they land on. But, yes, the unannotated corpus is not the one mounted on the concordancers. So, do we prefer utility or truth? Your call, this info is not difficult to delete.

I prefer truth...

I have discussed it with @kosarko and it seems that for the current version of DSpace, the fastest solution is
to define repository as a service (CLARIN.SI repository / repository / related data /... - I am not sure about the correct label) and add a link to annotated data:
![image](https://user-images.githubusercontent.com/5867995/118675556-f7153000-b7fa-11eb-9404-3e477dcbc80c.png)
If we say that the plain text data are in the repository service - we say the truth because annotated data are derived from plain text data. I am not saying that it is an ideal solution but it is closer to the truth at least.
(https://github.com/ufal/clarin-dspace/wiki/Refbox-services-integration)

@kosarko is planning to visualize relations `dc.relation.ispartof` and `dc.relation.haspart`  but currently, it is in the state of planning.

> One more change: we now have for noSkE also per-corpus search in the menu.

I am not absolutely sure about the label "ParlaMint". Probably we can use "ParlaMint corpora" to pin the difference of other items in the list.

**Comment by TomazErjavec** [comment]
> I prefer truth...

So be it: deleted from http://hdl.handle.net/11356/1388.

> I am not absolutely sure about the label "ParlaMint". Probably we can use "ParlaMint corpora"

So changed on http://hdl.handle.net/11356/1405.

> the fastest solution is to define repository as a service

Inventive, but I find it, well, weird to have the repository as a "related service" of the repository. So, far (and here as well) I simply mention in the description that there are related entries. Then again, simply using the name "Related entries" for the service would do the trick here. Still not ideal though, as you would need to put in the titles of the related entries by hand, while they are in fact already avalialble in the repository. Will think about if this would make sense, in which case we would also have to update old entries, not to be undertaken lightly in any case.

> @kosarko is planning to visualize relations dc.relation.ispartof and dc.relation.haspart but currently, it is in the state of planning.

OK, good to know. Although what we would also need is dc.relation.relatedto (or whatever the correct relation is), as we often have this case, as is in fact the case with ParlaMint (you can't really comfortably state that the TEI is "a part" of TEI.ana, well, I couldn't anyway).

**Comment by kosarko** [comment]
@TomazErjavec there are plenty of "predefined" relations
![image](https://user-images.githubusercontent.com/1842385/119004896-3eccc080-b98f-11eb-8ca1-9a6112464791.png)
so maybe one of them fits better, you can also define fields with your own semantics.

The tricky part is the visualization - if you want something fancier than just showing the link (if that's enough just edit the items; it will appear in full item view; or if you modify item-view.xsl you can get it into the simple one too).

Do you have any particular ideas for the visualisation? I do have some notes somewhere on what we need to achieve with the ispart/haspart, but I'm not sure it'll fit in a dropdown as the versions do (there were some debates on what  the versions should look like, see ufal/DSpace#412)
the result is described in
https://github.com/ufal/clarin-dspace/blob/39e44860b18aff81b7bf819ce9576c9ddab4476c/dspace-rest/src/main/java/org/dspace/rest/ItemsResource.java#L1075-L1086

or maybe something along the lines of https://github.com/ufal/clarin-dspace/issues/864 would be better?
