### ISSUE TITLE
FI: README.md contents not included in ParlaMint 4.0

### ISSUE THREAD

**Issue by yoge1** [clarin-eric/ParlaMint#813]
https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-FI.tgz
- file ParlaMint-FI/README-FI.md - documentation is missing (just headings in the file)

https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-FI.ana.tgz
- file ParlaMint-FI.ana/README-FI.ana.md - documentation is missing (just headings in the file)

The documentation is in the GitHub repo: https://github.com/clarin-eric/ParlaMint/blob/main/Samples/ParlaMint-FI/README.md

**Comment by TomazErjavec** [comment]
Hopefully sorted now, cf. https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-FI.ana.tgz or https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-FI.tgz
