### ISSUE TITLE
Houses

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#82]
I've discovered something a bit embarassing about our corpora, largely my fault:
1. there is no machine readable way to determine if a certain corpus has a uni- or bicameral parliament
2. not all bicameral corpora have their corpus root and components marked with whether the corpus/component pertains to the lower or upper house, incl. SI and ES, much to my embarassment. 

Below is the list of countries, with what Wikipedia tells me are the number of their houses, and if they have the upper/lower distinction marked up:
- BE: Bicameralism, lower only, marked on root, *NOT* marked on components
- BG: Unicameralism
- CZ: Bicameralism, lower only, marked on root, marked on components
- DK: Unicameralism
- ES: Bicameralism, lower only, *NOT* marked on root, *NOT* marked on components
- FR: Bicameralism, lower only, marked on root, marked on components
- GB: Bicameralism, contains both, *NOT* marked on root, *NOT* marked on components
- HR: Unicameralism
- HU: Unicameralism
- IS: Unicameralism
- IT: Bicameralism, upper only, *NOT* marked on root, marked on components
- LT: Unicameralism
- LV: Unicameralism
- NL: Bicameralism, contains both, marked on root, *NOT* marked on components
- PL: Bicameralism, contains both, marked on root, marked on components
- SI: Bicameralism, lower only, *NOT* marked on root, *NOT* marked on components
- TR: Unicameralism

Could you pls.:
- let me know in case the Bi/Unicameralism and which hous is included for your country is marked above _incorrectly_
- for BE, GB, IT, NL let me know if you can fix this yourself, or I should do it?

Essentially, all the meeting elements of the corpus root and of each component should have in their `@ana` attribute added the pointer to the appropriate house, so (assuming you did not change the taxonomy IDs) either `#parla.upper` or `#parla.lower`, e.g. for SI root it would be:
```
<meeting n="7" ana="#parla.lower #parla.term #DZ.7">7. mandat</meeting>
<meeting n="8" ana="#parla.lower #parla.term #DZ.8">8. mandat</meeting>
``` 
and for a SI component:
```
<meeting n="59" ana="#parla.lower #parla.meeting.extraordinary">Izredna</meeting>
<meeting n="7" ana="#parla.lower #parla.term #DZ.7">7. mandat</meeting>
```
Technically this should be simple because, as far as I see, for each component the house is always in one way or another present in the file name and main title.

As for 1): I propose to insert into each corpus TEI header the textClass element, which would specify if the country has one or two houses, and, somewhat redundantly, if two, also which is included in the corpus. E.g. for BG it would be:
```
<textClass>
  <catRef scheme="#parla.legislature" target="#parla.uni"/>
</textClass>
```
And for GB:
```
<textClass>
  <catRef scheme="#parla.legislature" target="#parla.bi #parla.upper #parla.lower"/>
</textClass>
```
Except if somebody (like Matjaš) has a better suggestion!

Again, I can do this, or you can, but if you will, pls. let me know.

**Comment by calzada** [comment]
Dear Tomaz,

The Spanish Congress (Cortes) has two houses: The Lower House (Congreso de los Diputados) and the Upper House (Senado). ParlaMint-ES only contains plenary speeches from the Lower House. I can see, the -ana.xml does not include this information in the meeting tags. What we can see is in the root is:
<meeting n="10" corresp="#CD" ana="#parla.term #CD.10">Term 10</meeting>
And in each document, for example:
<meeting n="10" corresp="#CD" ana="#parla.term #CD.10">Legislatura X</meeting>
Shall I do anything?
Best
mc

**Comment by TomazErjavec** [comment]
> Shall I do anything?
No, I will fix this for ES, my fault anyway!

**Comment by calzada** [comment]
Thanks, Tomaz.
And actually, I think it is mu fault as well, I should have realised before. 
Best for now,
mc

**Comment by matyaskopp** [comment]
> Except if somebody (like Matjaš) has a better suggestion!

[`<textClass>`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-textClass.html) sounds good - I like it. We can probably use it in component files besides (in the future). Probably for categorizing subcorpora or topics that are common for the whole component file.

**Comment by vaidasmo** [comment]
Dear Tomaz,

Lithuanian parliament is unicameral, so it is the lower house.

We included info about lower/upper house into the root files:
   <particDesc>
            <listOrg>
                <org ana="#parla.national #parla.lower" role="parliament" xml:id="S">

Should we add info about unicameralism?

Best,
Vaidas

**Comment by TomazErjavec** [comment]
> Lithuanian parliament is unicameral, so it is the lower house.

This is quite a surprise to me - I thought if it is unicameral, it does not have houses, cf. [Wikipedia](https://en.wikipedia.org/wiki/Lower_house): "A lower house is one of two chambers of a bicameral legislature". Also in our Legislature taxonomies, the lower house is under "Bicameralism", so the classification is then contradictory.

I didn't check any of the unicameral corpora, as this problem didn't actually occur to me. Options:
- just leave everything as it is, as, even if wrong, it doesn't have much practical consequence
- remove "#parla.lower" from wherever it appears in unicameral corpora 

Thoughts?

**Comment by atomm** [comment]
For IT the information reported above is correct and we can do the fix in the roots. 
I will just wait to see an example correctly encoded or the schema. 
` insert into each corpus TEI header the textClass element` I guess means as a sibling of "fileDesc", "encodingDesc", "profileDesc". Any particular order?

**Comment by TomazErjavec** [comment]
> For IT the information reported above is correct and we can do the fix in the roots.

OK, great & thanks. 

> I will just wait to see an example correctly encoded or the schema.

I extended the schema in 7b2e224 to include `<textClass>`.

> I guess means as a sibling of "fileDesc", "encodingDesc", "profileDesc". Any particular order?

Actually, no, it comes under profileDesc. TEI allows any order, but for ParlaMint I constrained this to come immediatelly after `<settingDesc>`.  For IT this would be:
```
<textClass>
  <catRef scheme="#parla.legislature" target="#parla.bi #parla.upper"/>
</textClass>
```
So, you would need to insert this into root, as well as mark with `#parla.upper` the meeting elements there.

**Comment by vaidasmo** [comment]
> 
> 
> > Lithuanian parliament is unicameral, so it is the lower house.
> 
> This is quite a surprise to me - I thought if it is unicameral, it does not have houses, cf. [Wikipedia](https://en.wikipedia.org/wiki/Lower_house): "A lower house is one of two chambers of a bicameral legislature". Also in our Legislature taxonomies, the lower house is under "Bicameralism", so the classification is then contradictory.

In general, if a parliament is unicameral, then it only has a lower house. So unicameralism and lower house is not contradictory in principle. However, it may be confusing for users. So we could remove "#parla.lower". But since it doesn't have much practical consequence, we will leave corpora unchanged.

Vaidas

**Comment by TomazErjavec** [comment]
> So we could remove "#parla.lower". But since it doesn't have much practical consequence, we will leave corpora unchanged.

OK. But given that I am running my Scripts/parlamint2final.xsl script over the corpora anyway, do you (and the other Unicamerals) mind if I automatically remove "#parla.lower" from the meeting elements (where they appear, of course)?

**Comment by vaidasmo** [comment]
> do you (and the other Unicamerals) mind if I automatically remove "#parla.lower" from the meeting elements (where they appear, of course)?

Sure, no problem.

Vaidas

**Comment by TomazErjavec** [comment]
This is now fixed, i.e. the appropriate house is inserted in the parlamint2final.xs script, via the variable giving all the houses, cf. https://github.com/clarin-eric/ParlaMint/blob/6cc455ffb8dfb4ab206fcf9f68c936761508ac73/Scripts/parlamint2final.xsl#L52-L143

For parliaments that have both houses, further rules are used, cf. https://github.com/clarin-eric/ParlaMint/blob/6cc455ffb8dfb4ab206fcf9f68c936761508ac73/Scripts/parlamint2final.xsl#L637-L711
