### ISSUE TITLE
Failing Parla-CLARIN schema validation

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#822]
not sure what happened, only countries with CHES fail

**Comment by TomazErjavec** [comment]
Was dev merged into data / main? Because there were changes to the schema to accommodate CHES in devel.

**Comment by matyaskopp** [comment]
> Was dev merged into data / main? Because there were changes to the schema to accommodate CHES in devel.

yes, devel is both in the main and data branches: https://github.com/clarin-eric/ParlaMint/commits/data
- merge to main: a529d34cbf087fec74e8e0672846627454a50221
- merge to data: 35273da21953f337992d56155df0ebafde8b4f1c

**Comment by matyaskopp** [comment]
Mixture of `state` and `label` is not allowed in TEI:
```XML
<content>
	<sequence>
		<elementRef key="precision" minOccurs="0" maxOccurs="unbounded"/>
		<alternate>
			<elementRef key="state" minOccurs="1" maxOccurs="unbounded"/>
			<sequence>
				<classRef key="model.headLike" minOccurs="0" maxOccurs="unbounded"/>
				<classRef key="model.pLike" minOccurs="1" maxOccurs="unbounded"/>
				<alternate minOccurs="0" maxOccurs="unbounded">
					<classRef key="model.noteLike"/>
					<classRef key="model.biblLike"/>
				</alternate>
			</sequence>
			<alternate minOccurs="0" maxOccurs="unbounded">
				<classRef key="model.labelLike"/>
				<classRef key="model.noteLike"/>
				<classRef key="model.biblLike"/>
			</alternate>
		</alternate>
	</sequence>
</content>
```

**Comment by TomazErjavec** [comment]
Drat, missed that one. It doesn't show up in the build, as I only validate against ParlaMint RNG schemas. The worst is that we could manage without label, as it only encoded the CHES name of the party.

I can't fix this now, as it would mean recompiling all the corpora from scratch (CHES/Wiki/ministers get inserted firs, then all the rest of the build). I guess this means we will have to live with failing samples and non-TEI conformant corpora for 4.0. 
Sorry about this.

**Comment by TomazErjavec** [comment]
OK, this has now been fixed, as evidenced by new conversion log files. I also removed all Samples (as they are failing with the new schema) and started adding new samples as they become available. So, closing.
