### ISSUE TITLE
Corpus configuration file contain wrong timespan

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#824]
https://github.com/clarin-eric/ParlaMint/blob/7b52ae5a0cc57c2464b0372d6275f3135de59dac/Samples/ParlaMint-CZ/parlamint40_cz.regi#L3
The end year is 2022, but the CZ corpus also contains 2023 data.

I don't know how the regi file is created if it is a bug in some script(fix needed) or a human error(will be fixed in the next release) due to manual modifications.

**Comment by TomazErjavec** [comment]
> a human error

Yes, my error, sorry. Fixed now, also in concordancders.
