### ISSUE TITLE
Different vert files for 2.1

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#83]
In the current version of the corpora on the [concordancer](https://www.clarin.si/noske/parlamint.cgi/) there turns out to be problems with folks understanding how the corpus is encoded, i.e. I wanted to put too much information into the vert files.

There are two problems:
1. The vert files have two structural elements, `<text>` and `<speech>`, each one with various attributes. But even though structural elements look a lot like XML elements, the concordancer has no concept of nesting, i.e. it doesn't know if a speech is inside text, or maybe the other way around, in fact, they could both even be on the same level. So people wanting to [make a subcorpus](https://www.clarin.si/noske/parlamint.cgi/subcorp_form?corpname=parlamint20_si) get unintuitive (wrong, from their point of view) results. E.g. if you make a subcorpus of texts that belong to the covid corpus (so: TEXT.SUBCORPUS=COVID), and you also specify that you want speeches made by women (SPEECH.SPEAKER_GENDER=F), you won't get a subcorpus of speeches by women in the covid part of the corpus, but you will get the covid part of the corpus that also contains speeches by women, so, in practice, the whole COVID part of the corpus.
2. I encoded the transcriber comments with the structural element `<note>` but encoded what the comment actually is as one token. Which is nice, as you see the comments in the corpus, but it means that the corpus has more tokens than it really should, as well as leading to some other problems that would take too long to explan.

So, what I would do for V2.1 in the vertical files for the concordancers is:

1. Get rid of the `<text>` element, and migrate all its attributes onto the `<speech>` element. As structural elements are mostly used only for their attributes, the only damage this will do, as far as I can see, is not being able to see in the concordancer how many texts there are in the corpus - and, as this is pretty arbitrary anyway, I don't see this as a problem.
2. Encode transcriber comments as empty elements, where I might put their content in a new attribute called e.g. "content".

If anywone finds this problematic, or has a better idea, pls. shout soon!

**Comment by calzada** [comment]
It seems pretty sensible!!

Best

mc

**Comment by TomazErjavec** [comment]
As no comments, implemented in a64b276440199b3ac6582dbd9bf75e6ce0ccb840 and closing
