### ISSUE TITLE
Political orientations - leftover values

### ISSUE THREAD

**Issue by katjameden** [clarin-eric/ParlaMint#831]
In the tsv files of Wiki and CHES there are parties that have no `pm_id`s, but for which `lr` values are still available - see [example ](https://github.com/clarin-eric/ParlaMint/blob/main/Corpora/Orientations/Orientation-BG.Wiki.tsv). These values probably date back to when we split the once merged file to separate the Wiki and CHES files - I am pretty sure these values just need to be removed, but I am just posting this here to check.

**Comment by TomazErjavec** [comment]
Indeed, these line do not hurt, but they are useless. Removed now, closing.
