### ISSUE TITLE
Make sample to have same folder structure as release

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#832]
Refactorize samples to have the same structure as a release. Reasons:
- it avoids confusion about the structure
- easier using and debugging scripts (eg release script can be used on sample data while it is developed)

**Comment by TomazErjavec** [comment]
This has been done now, @matyaskopp, pls. have a look at [Samples](https://github.com/clarin-eric/ParlaMint/tree/devel/Samples/) and, if you are happy with the result, pls. close.
Note that the logs of sample generation are now also included.
