### ISSUE TITLE
HU: wrong setting day in v4.0

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#833]
setting (WRONG)
https://github.com/clarin-eric/ParlaMint/blob/7b52ae5a0cc57c2464b0372d6275f3135de59dac/Samples/ParlaMint-HU/ParlaMint-HU.xml#L119

vs 

bibl (CORRECT)
https://github.com/clarin-eric/ParlaMint/blob/7b52ae5a0cc57c2464b0372d6275f3135de59dac/Samples/ParlaMint-HU/ParlaMint-HU.xml#L64

**Comment by TomazErjavec** [comment]
Fixed in source. When the corpus is recompiled it should be ok.
Leaving open untill the build is actually done.

**Comment by TomazErjavec** [comment]
Fixed now, cf. https://github.com/clarin-eric/ParlaMint/commit/1ad81f91b8fd3462711cbf308d66dc35e36c778b#r140411999
