### ISSUE TITLE
add citation file

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#834]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by TomazErjavec** [comment]
Nice one! And you can [set it to dataset](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#citing-something-other-than-software) as well.

It is not quite clear to me if the citation to ParlaMint should GitHub, latest ParlaMint.ana repo entry or LREV paper though.

**Comment by matyaskopp** [comment]
Started implementing: [![CITATION.cff](https://github.com/clarin-eric/ParlaMint/actions/workflows/validateCITATION.yml/badge.svg)](https://github.com/clarin-eric/ParlaMint/actions/workflows/validateCITATION.yml)

this action nicely produces a summary of validation: https://github.com/clarin-eric/ParlaMint/actions/runs/8637031866/attempts/1#summary-23678302673

**Comment by matyaskopp** [comment]
and now valid: https://github.com/clarin-eric/ParlaMint/actions/runs/8637159767/attempts/1#summary-23678726898

**Comment by matyaskopp** [comment]
@TomazErjavec I believe it is now ok, not all cff features are supported by GitHub... 
GitHub parses [f875f26](https://github.com/clarin-eric/ParlaMint/commit/f875f26d7a4151be6a3236ffb4809bea9500c159) as follows:

- APA
> Erjavec, T., Kopp, M., Ljubešić, N., Kuzman, T., Rayson, P., Osenova, P., Ogrodniczuk, M., Çöltekin, Ç., Koržinek, D., Meden, K., Skubic, J., Rupnik, P., Agnoloni, T., Aires, J., Barkarson, S., Bartolini, R., Bel, N., Calzada Pérez, M., Darģis, R., Diwersy, S., Gavriilidou, M., van Heusden, R., Iruskieta, M., Kahusk, N., Kryvenko, A., Ligeti-Nagy, N., Magariños, C., Mölder, M., Navarretta, C., Simov, K., Tungland, L. M., Tuominen, J., Vidler, J., Vladu, A. I., Wissik, T., Yrjänäinen, V., & Fišer, D. (2024). ParlaMint II: Advancing Comparable Parliamentary Corpora Across Europe (Version 1 - PREPRINT). https://doi.org/10.21203/rs.3.rs-4176128/v1

- BibTeX
```
@unpublished{Erjavec_ParlaMint_II_Advancing_2024,
author = {Erjavec, Tomaž and Kopp, Matyáš and Ljubešić, Nikola and Kuzman, Taja and Rayson, Paul and Osenova, Petya and Ogrodniczuk, Maciej and Çöltekin, Çağrı and Koržinek, Danijel and Meden, Katja and Skubic, Jure and Rupnik, Peter and Agnoloni, Tommaso and Aires, José and Barkarson, Starkaður and Bartolini, Roberto and Bel, Núria and Calzada Pérez, María and Darģis, Roberts and Diwersy, Sascha and Gavriilidou, Maria and van Heusden, Ruben and Iruskieta, Mikel and Kahusk, Neeme and Kryvenko, Anna and Ligeti-Nagy, Noémi and Magariños, Carmen and Mölder, Martin and Navarretta, Costanza and Simov, Kiril and Tungland, Lars Magne and Tuominen, Jouni and Vidler, John and Vladu, Adina Ioana and Wissik, Tanja and Yrjänäinen, Väinö and Fišer, Darja},
doi = {10.21203/rs.3.rs-4176128/v1},
month = apr,
title = {{ParlaMint II: Advancing Comparable Parliamentary Corpora Across Europe}},
year = {2024}
}
```

If you are ok with it, feel free to close the issue.

**Comment by TomazErjavec** [comment]
I'm not sure if this can be changed, but clicking "Cite this repository" on gives you 
"If you use this software in your work, please cite it using the following metadata. "

Not sure "software" is appropriate here, but this might be a canned message.

Also not sure if we should also change the main README where we make reference to the previous LREV paper? 

Apart from these two details, nice!

**Comment by matyaskopp** [comment]
> Not sure "software" is appropriate here, but this might be a canned message.

this cannot be changed, see: https://github.com/citation-file-format/ruby-cff/issues/121



> Also not sure if we should also change the main README where we make reference to the previous LREV paper?

not sure too, we can have both: preprint and paper in readme. If the preprint is accepted, then we can remove the old paper...

**Comment by TomazErjavec** [comment]
OK, added preprint to README & closing.
