### ISSUE TITLE
Add source to UD-SYN taxonomy 

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#835]
This https://github.com/clarin-eric/ParlaMint/blob/ab841183536cdda20e89d454f324b81cbdbb818c/Data/Taxonomies/ParlaMint-taxonomy-UD-SYN.ana.xml corresponds to this commit: https://github.com/UniversalDependencies/docs/tree/0749864b5048bb8995fe68aedc37f721bc1338ee

There are two possibilities for how to link the source to this taxonomy:
1. allow `taxonomy/@source`
2. add the original source commit to the description 

@TomazErjavec Option 2. does not require schema modification, so it is easier to implement. Should I do it that way?

**Comment by TomazErjavec** [comment]
Yes, option 2 sounds better, pls. do!

**Comment by matyaskopp** [comment]
done, no other change of taxonomy
