### ISSUE TITLE
get rid of absolute paths

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#839]
related to #838 
currently, absolute paths are used for Saxon, Jing,... ???

Parametrize it or use environment variables.

**Comment by TomazErjavec** [comment]
I have, I think, a better idea than to start messing with env: we need just 3 programs which are not standar unix, namely jing, saxon and the conll validation. What about simply having all three installed locally, i.e. inside the ParlaMint directory and then just use relative paths to call them? 
We already do that for the conll validation, we'd just do it for jing and saxon as well - and these are just .jar files, so we could just put them in Scripts (or maybe all thee in Scripts/bin). 
What do you thing @matyaskopp ?

**Comment by matyaskopp** [comment]
@TomazErjavec , it is a nice solution.
- everyone who has a system installation can just put a symlink to `Scripts/bin`
- the rest will install the prerequisites to `Scripts/bin`

**Comment by TomazErjavec** [comment]
Glad you like it! Will start implementing it then.

**Comment by TomazErjavec** [comment]
OK, done (not manin Makefile, but all the rest). Hope it works, testing now on UA.
(sorry forgot to include this issue in commits)

**Comment by TomazErjavec** [comment]
When placing saxon in the new Scripts/bin directory I took the latest version of Saxon, rather than the many-years old one that I used before. It seems that in the meantime the functioning of `document-uri(/)` has [changed](https://www.saxonica.com/html/documentation12/functions/fn/document-uri.html), i.e. you can no longer use it to get the name of the input file. However, `base-uri()` seems to do the trick, so I substituted it in all (also your) files. Maybe a good idea to test anyway.
These are yours in Scripts:
```
list-affiliation-org-role-pairs.xsl:  <xsl:variable name="country" select="replace(replace(document-uri(/),
list-element-attribute.xsl:  <xsl:variable name="country" select="replace(replace(document-uri(/), '.+/([^/]+)\.xml', '$1'), 'ParlaMint-([^._]+).*', '$1')"/>
list-links.xsl:  <xsl:variable name="country" select="replace(replace(document-uri(/)
```

**Comment by TomazErjavec** [comment]
@matyaskopp, I now changed old sys paths to new local ones everywhere (I think), incl. in README files.
Not that I moved the description of prerequisite installation to Scripts/bin/README.md (and I also found a newer version of Jing/Trang, I hope they work!)

The only bit that I didn't want to touch are .github/actions - I leave this to you. These two files have (several) paths to saxon:
* ./.github/actions/ParlaMintValidate/validate.sh
* ./.github/actions/ParlaMintEnvSetup/action.yml

I now also occurs to me that we could put the basic prerequisites into Scripts/bin ourselves, i.e. just have them as part of git. What do you think?

**Comment by matyaskopp** [comment]
I have implemented absolute paths into GitHub actions. 

> I now also occurs to me that we could put the basic prerequisites into Scripts/bin ourselves, i.e. just have them as part of git. What do you think?

I am not sure if it is a good solution, but I think we can leave it as it is.

**Comment by TomazErjavec** [comment]
Greatm so it seems everything is done, closing. If any bugs crop up, we can open a new one to address them.
