### ISSUE TITLE
UA: scant description of "acting"

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#840]
UA has an additional taxonomy for speaker roles, i.e. [ParlaMint-UA-taxonomy-affiliation.roles.xml](https://github.com/clarin-eric/ParlaMint/blob/devel/Samples/ParlaMint-UA/ParlaMint-UA-taxonomy-affiliation.roles.xml). But the category description is lacking an explanation, i.e. it looks strange to have the term, followed by a colon, but nothing after. Can this be fixed by explaining what "acting" is?

**Comment by matyaskopp** [comment]
@AnnaParla can you take a look at this, please edit this file: https://github.com/ufal/ParlaMint-UA/blob/main/Taxonomies/ParlaMint-UA-taxonomy-affiliation.roles.xml

**Comment by AnnaParla** [comment]
Done, committed to the main branch.

**Comment by TomazErjavec** [comment]
Got it, thanks!
