### ISSUE TITLE
EE: how to solve affiliation collision?

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#851]
With the new to/from fix, those errors are gone from EE. However, it still doesn't [validate](https://github.com/clarin-eric/ParlaMint/actions/runs/8155828210) which is a pain.

@matyaskopp, and idea what to do about this?
* change the ERROR into WARN?
* somehow fix directly by hand in the source corpus? 

Btw. the error messages don't tell you the person, because they can't? Right now it is a bit difficult to find where the errros actually are. I guess there are two, so 4 lines, 2 for TEI, 2 for ana:
```
ERROR[01] ParlaMint-EE-listPerson affiliation collision: (2014-11-03 --- 2015-04-08) has multiple days overlap with (2014-11-04 --- 2015-04-09) affiliation member-#government.Valitsus
ERROR[01] ParlaMint-EE-listPerson affiliation collision: (2014-11-03 --- 2015-04-08) has multiple days overlap with (2014-11-04 --- 2015-04-09) affiliation member-#government.Valitsus
ERROR[01] ParlaMint-EE-listPerson affiliation collision: (2014-11-03 --- 2015-04-08) has multiple days overlap with (2014-11-04 --- 2015-04-09) affiliation member-#government.Valitsus
ERROR[01] ParlaMint-EE-listPerson affiliation collision: (2014-11-03 --- 2015-04-08) has multiple days overlap with (2014-11-04 --- 2015-04-09) affiliation member-#government.Valitsus
```

**Comment by matyaskopp** [comment]
this is the collision:
```XML
      <affiliation ref="#government.Valitsus" role="member" from="2014-11-03" to="2015-04-08">
         <roleName xml:lang="et">Liige</roleName>
         <roleName xml:lang="en">Member</roleName>
      </affiliation>
      <affiliation role="member" ref="#government.Valitsus" from="2014-11-04" to="2015-04-09"/>
```

The merging script also looks into the `affiliation/roleName` element and if they are different, then they are not merged. but probably in the `member`-role case, they can be merged

There can also be problems with `affiliation/@source` and `affiliation/orgName` that I am ignoring in the affiliation comparison:
https://github.com/clarin-eric/ParlaMint/blob/58c4042802ed77843d1f1e535addbb6909bf9d2a/Scripts/parlamint-lib.xsl#L729-L748

**Comment by matyaskopp** [comment]
> Yes, I think so. So, will you do this? Then EE ERROR should go away.

done
