### ISSUE TITLE
use perl from environment

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#855]
currently, in most scripts, the hash-bank line contains the system Perl:
```
#!/usr/bin/perl
```
but it should be replaced with 
```
#!/usr/bin/env perl
```

it is safer because both commands `perl script.pl` and `./script.pl` use the same Perl 
and you can use custom Perl with perlbrew.

**Comment by TomazErjavec** [comment]
> @TomazErjavec changed in all '*.pl' scripts, there should be no change for you and Tantra, because you are using the system perl
Thanks @matyaskopp, indeed, it seems just fine.
