### ISSUE TITLE
HU: problem with taxonomies and syntactic relations

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#857]
I've just tried to process HU.ana with the somewhat improved pipe-line for 4.1, and two problems appeared, which were already present in 4.0, but nobody noticed:

The first is that the linguistic taxonomies are defied and XIncluded in the corpus root twice:
```
<classDecl>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-subcorpus.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-speaker_types.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-parla.legislature.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-NER.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-UD-SYN.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-CHES.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-politicalOrientation.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-NER.ana.xml"/>
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="ParlaMint-taxonomy-UD-SYN.ana.xml"/>
</classDecl>
```

This is, of course, wrong, and the ones without .ana should not be there. I removed then myself from the corpus but then I get 157,405 errors like:
```
ERROR ParlaMint-HU_2016-12-07.ana: ERROR: Can't find local id for link/@ana="ud-syn:nmod_obl"
...
ERROR ParlaMint-HU_2023-07-31.ana: ERROR: Can't find local id for link/@ana="ud-syn:nmod_obl"
```

I had a look and [nmod:obl](https://universaldependencies.org/docsv1/hu/dep/nmod-obl.html) seems to be a hu-specific relation from UD V1, which now no longer exists.

The question is what to do now. I see two options:
* the simplest is to change `nmod_obl` to `nmod` (or some other valid relation); we get rid of errors, but also potentially useful info
* introduce a HU specific UD taxonomy `ParlaMint-HU-taxonomy-UD-SYN.ana.xml` which contains only the definition of `nmod_obl`, and include it along with the standard one.

 I would appreciate advice which route to take.

**Comment by matyaskopp** [comment]
it is still in UD12 data: http://hdl.handle.net/11346/PMLTQ-MZGC , but it is not documented on web pages: https://universaldependencies.org/hu/index.html#relations-overview

but It has been already added on github:
https://github.com/UniversalDependencies/docs/blob/5a573316b93dc8d08bec5c159fd549242219c00c/_hu/dep/nmod-obl.md

I have tried to regenerate UD-SYN taxonomy, but it is not included in taxonomy, because the documentation contains bug (already reported: https://github.com/UniversalDependencies/docs/issues/898), script report:
```
ERROR: title 'nmod' does not match filename _hu/dep/nmod-obl.md
```

So the easiest/cleanest solution is probably to fix UD documentation and then regenerate our taxonomy.

**Comment by TomazErjavec** [comment]
> So the easiest/cleanest solution is probably to fix UD documentation and then regenerate our taxonomy.

Thanks for investigating this further - this solution is certainly the cleanest, but not the easiest, in fact, it's the most complicated, as it involves then also changing the taxonomies for all other corpora, and we are dependent on UD fixes.

So, for now, I will go with my solution 2 above, i.e. "introduce a HU specific UD taxonomy ParlaMint-HU-taxonomy-UD-SYN.ana.xml which contains only the definition of nmod_obl, and include it along with the standard one." 

When/if we get the fixed main ParlaMint UD taxonomy, this extra HU taxonomy can be removed.

**Comment by matyaskopp** [comment]
@TomazErjavec , @lnnoemi I have fixed UD documentation: https://github.com/UniversalDependencies/docs/pull/1020 and update out UD-SYN taxonomy.

Only new IDs were introduced 
(except `parataxis_coord` used in [Beja language](https://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=bej&SearchType=ALL)  : https://github.com/clarin-eric/ParlaMint/commit/90fd082d111e81960ebf0849032812c504605fa8#diff-21d0540a03f6f73e674e5181241bb42b2a8eb19de1ee245e9b63616dce188c88L1283-L1285)
 so no breaking of other corpora!!!

**Comment by TomazErjavec** [comment]
Thanks @matyaskopp, I now fixed HU so it uses the new common UD taxonomy, and it all seems to work, so, closing.
