### ISSUE TITLE
Allow running functions for getting speaker features out of TEI context

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#858]
Currently, it is not possible to run functions like this:
https://github.com/clarin-eric/ParlaMint/blob/4fd7df8eb1f58701650ac41f134a5f4f26387f5e/Scripts/parlamint-lib.xsl#L452-L464

outside `/tei:TEI` context because they use variable `$at-date` defined outside the function's scope. Only a small change can fix this and allow getting person status at any timepoint:
```XML
  <!-- Output appropriate label if the speaker is (not) a Minister when speaking -->
  <xsl:function name="et:speaker-minister" as="xs:string">
    <xsl:param name="speaker" as="element(tei:person)"/>
    <xsl:value-of select="et:speaker-minister($speaker,$at-date)"/> <!-- calling 2-param function with default date -->
  </xsl:function>

  <xsl:function name="et:speaker-minister" as="xs:string">
    <xsl:param name="speaker" as="element(tei:person)"/>
    <xsl:param name="when" as="xs:string"/> <!-- date of returned info -->
    <xsl:choose>
      <xsl:when test="$speaker/tei:affiliation[@role = 'minister']
                      [et:between-dates($when, @from, @to)]">
        <xsl:value-of select="$minister-label"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$nonminister-label"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:function>
```

@TomazErjavec I need this change for other conversion scripts, now for ParCzech, in future for ParlaMint2teitok (so I can get rid of the dependency on metadata file)

**Comment by TomazErjavec** [comment]
> variable $at-date [is] defined outside the function's scope

Horrible, this was an oversight; of course it should get the date as a parameter.

>  Only a small change can fix this and allow getting person status at any timepoint:

OK, this is a possibility but I think it would be cleaner to just change et:speaker-minister to require 2 arguments and then change all the calls to the function so that they give the 2 parameters.

**Comment by TomazErjavec** [comment]
I had a look now through other similar functions and I see this a more prevasive problem, in particular, et:speaker-affiliations-refs doesn't have the data parameter, and then many function call this function. Still, it might be worth fixing all of them. Shall I do it?
If you prefer, you can of course also implement your minimalist solution.

**Comment by matyaskopp** [comment]
I have implemented the minimalist solution, you can always remove single-param functions, when no other script calls it
