### ISSUE TITLE
ES: Conflicting dates of party affiliations

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#86]
In ParlaMint-ES five persons are members of more than one political party at certain times:
1.     GarcíaJosé
2.     GonzálezMaría
3.     MartínezMaría
4.     MartínMaría
5.     RodríguezMaría

This might be fixed in the future, for new we leave it as it is, as it would not be simple to fix, cf. also https://github.com/calzada/PARLAMINT-ES-MC/issues/19.

**Comment by calzada** [comment]
Yes! That sounds right. When you want me to correct it, just let me know. 
Best for now,
mc

**Comment by TomazErjavec** [comment]
This has been presumably fixed in < 3.0, so, closing.
