### ISSUE TITLE
Add Metadata/ to repo release

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#864]
In the folder [Build/Metadata](https://github.com/clarin-eric/ParlaMint/tree/devel/Build/Metadata) we now have TSV files giving various ParlaMint-wide metadata which might be immediatelly useful for people wanting an overview of the corpus or just the lists of persons and organisations in TSV. So, it would make sense to include this directory as a separate file in the ParlaMint release.
This issue is to track the development of this idea.

**Comment by TomazErjavec** [comment]
Added the following sentence into the item description for the TEI and TEI.ana versions:

> An overview of the statistics of the corpora is avaialable on GitHub in the folder Build/Metadata, in particular for the release 4.1 at https://github.com/clarin-eric/ParlaMint/tree/0892bb956685a2b864479a0c0b3f18007ad254f5/Build/Metadata.

**Comment by matyaskopp** [comment]
@TomazErjavec, I think  it is much better to point to the release commit, so the URL looks like this: https://github.com/clarin-eric/ParlaMint/tree/v4.1/Build/Metadata

**Comment by TomazErjavec** [comment]
You are of course right. Changed it in the repo description. Of course, it will work only once we make the release (or is it tag:)
Will leave the issue opended till then.

**Comment by TomazErjavec** [comment]
https://github.com/clarin-eric/ParlaMint/tree/v4.1/Build/Metadata works now, closing.
