### ISSUE TITLE
ParlaMint to distro - enqueueing slurm job

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#866]
Implement make target that enqueues [slurm](https://slurm.schedmd.com/sbatch.html) job
- sets a correct paths
- determine memory needed (5x annotated version, minimum 16GB)
- determine the number of CPU cores to be allocated
  - less than 60GB memory -> 15 cores
  - more or equal 60GB memory -> 30 cores
      - currently GB needs 240GB (if larger amount is needed, then core inducements needs to be done to allow running on _iridium_ machine which has more memory)
  - this is because a lot of ufal machines have 30 cores and 128Gb memory - two jobs(corpora) per node
- place additional common log for all runs to `Build/Logs/ParlaMint.slurm.log` with columns:
  - datetime
  - commit of current scripts
  - parliament code
  - status:
    - `STARTED`
    - `FINISHED`
    - `FAILED-<FAILCODE>`
  - slurm job id irrational log can be explored in `pmXX-distro.<job id>.log`, where XX is parliament code
  - name of node where computation has been done
  - `-` or `<time program output>`

The script should run `make all CORPORA=XX` in `Build` directory and only running single parliament should be allowed with single run of script.

calling:
```
make distro-make-all-XX
```

**Comment by matyaskopp** [comment]
@TomazErjavec I am struggling a bit with memory because I don't want the script to be too greedy (looking for the correct balance between corpus size and RAM usage). 
Is there a reason why some fatal errors do not lead to dying script?
https://github.com/clarin-eric/ParlaMint/blob/f2918caa0858f7b986723c12a562ad79a506ed92/Scripts/parlamint2distro.pl#L266
https://github.com/clarin-eric/ParlaMint/blob/f2918caa0858f7b986723c12a562ad79a506ed92/Scripts/parlamint2distro.pl#L270
https://github.com/clarin-eric/ParlaMint/blob/f2918caa0858f7b986723c12a562ad79a506ed92/Scripts/parlamint2distro.pl#L297
https://github.com/clarin-eric/ParlaMint/blob/f2918caa0858f7b986723c12a562ad79a506ed92/Scripts/parlamint2distro.pl#L301

I believe the script should die in these cases, but I rather ask...

**Comment by TomazErjavec** [comment]
> Is there a reason why some fatal errors do not lead to dying script?

I can't recal that there is and I hope that there isn't...
I fixed it now so that the script in fact dies. Sorry about this!

**Comment by TomazErjavec** [comment]
Sorry, didn't mean to close.

**Comment by matyaskopp** [comment]
Final setup:
- memory allocation: `50GB + 3 * corpusSize`
- CPU allocation:
  - MEM > 250GB: 14 cores (ufal specific - not happen)
  - MEM > 120GB: 30 cores
  - 24 cores otherwise 

# memory
successful runs (pink is current safe setup)
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/58257c0d-518b-4a66-93c1-effc09180a62)

# corpus sizes and speed:
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/1a60d5e5-9f04-4d19-bcb9-ceb894b5b4b1)
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/3cbc3eca-3704-45f8-b074-aa6aa979a73a)
![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/ddfe771c-41d4-4b78-acff-1300804e2828)
