### ISSUE TITLE
Non-valid symlinks in distribution

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#869]
Some time ago symlinks were introduced into the [Schema/](Schema/) directory for [ParlaMint.odd.rng](https://github.com/clarin-eric/ParlaMint/blob/main/Schema/ParlaMint.odd.rng) and [ParlaMint.odd.rnc](https://github.com/clarin-eric/ParlaMint/blob/main/Schema/ParlaMint.odd.rnc), which makes sense.
However, when making the distribution the parlamint2distro.pl script does a dircopy of the Schema directory into the ParlaMint-XX.TEI(.ana) distribution directory: 
https://github.com/clarin-eric/ParlaMint/blob/f2918caa0858f7b986723c12a562ad79a506ed92/Scripts/parlamint2distro.pl#L254
https://github.com/clarin-eric/ParlaMint/blob/f2918caa0858f7b986723c12a562ad79a506ed92/Scripts/parlamint2distro.pl#L286
which means that the two files are copied as symlinks - but their target is broken the distribution folder.

This needs to be fixed by copying over the actual files, not the symlinks. However, I cannot find an elegant way to do this in Perl.
@matyaskopp, would you have any idea how to do this?

**Comment by matyaskopp** [comment]
This seems to fix it:
```
$File::Copy::Recursive::CopyLink=0;
```
https://metacpan.org/pod/File::Copy::Recursive#SymLinks

**Comment by TomazErjavec** [comment]
Indeed, this works, thank you. Sorry for not finding the solution myself!
