### ISSUE TITLE
CZ: double title[@type="sub"] causes problems during import to parlameter

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#87]
We have two subtitles and parlameter takes the first during import

https://github.com/clarin-eric/ParlaMint/blob/e2cbca2fe9b6344b3e40e064a9abbc9cf8fed722/ParlaMint-CZ/ParlaMint-CZ_2013-11-25-ps2013-001-01-001-001.ana.xml#L11-L13

@TomazErjavec, Should be the first subtitle removed from the data? And keep just **agenda item title**...

**Comment by matyaskopp** [comment]
![image](https://user-images.githubusercontent.com/5867995/119660517-a4a5c600-be2f-11eb-8e7d-b229c3595e76.png)

**Comment by TomazErjavec** [comment]
> We have two subtitles.

Ah, I wasn't aware of that, I guess it should've been a part of the schema to prevent this, as I was assuming that each TEI has only one subtitle in a language.

> parlameter takes the first during import

And so does noSketch if you look at the metadata of a concordance:
```
Token number | 31
Document number | 0
Text ID | ParlaMint-CZ_2019-05-09-ps2017-028-07-001-217.ana
text.title | Parliament of the Czech Republic, Chamber of Deputies
text.from | 2019-05-09
text.to | 2019-05-09
```

> Should be the first subtitle removed from the data? 

Yes, this would be a good idea.

> And keep just agenda item title...

Or concatenate the two.

So, I expect an updated corpus from you?

**Comment by matyaskopp** [comment]
I prefer to change your finalizing script https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/parlamint2final.xsl
I think it will be safer. 

suggested value, that replaces all subtitles
```
concat(/TEI/teiHeader/fileDesc/titleStmt/title[@type='sub', @xml:lang='cs'][1],
            ', ',
            /TEI/teiHeader/fileDesc/sourceDesc/bibl/date/@when
            ', ',
             /TEI/teiHeader/fileDesc/titleStmt/title[@type='sub', @xml:lang='cs'][2]
)
```
to be almost sure that it is unique.


Is it ok? I can change the script and make a pull request...

**Comment by matyaskopp** [comment]
Or another solution:
one CZ file does not correspond to a session but it corresponds to the agenda item.
I can use 
```
<title xml:lang="cs" type="desc">Parlament České republiky, Poslanecká sněmovna, 2013-11-25</title>
``` 
value for subtitle to join sitting day together.


And for agenda item title use:
```
<title xml:lang="cs" type="desc">1. Slib předsedajícího ustavující schůze Poslanecké sněmovny</title>
```

If it would work for nosketch and parlameter it would make more sense in the interface (session ~ sitting day)

**Comment by TomazErjavec** [comment]
I'd prefer not to introduce a new title type at this stage, so would go for your first solution - we do wan't to keep the corpora encoded in the same way (as much as possible). If you agree, I can implement the change in the finalize script.

**Comment by matyaskopp** [comment]
ok, I agree. 
thanks!

**Comment by TomazErjavec** [comment]
This should now be fixed in  e2cbca2. 
Before:
```
<title type="sub" xml:lang="cs">Parlament České republiky, Poslanecká sněmovna</title>
<title type="sub" xml:lang="en">Parliament of the Czech Republic, Chamber of Deputies</title>
<title xml:lang="cs" type="sub">Začátek schůze Poslanecké sněmovny 25. listopadu 2013 ve 14.05 hodin Přítomno: 199 poslanců</title>
```
now:
```
<title type="sub" xml:lang="cs">Parlament České republiky, Poslanecká sněmovna, 2013-11-25, Začátek schůze Poslanecké sněmovny 25. listopadu 2013 ve 14.05 hodin Přítomno: 199 poslanců</title>
<title type="sub" xml:lang="en">Parliament of the Czech Republic, Chamber of Deputies</title>
```

I am not entirely happy with this solution as:

1. the cs subtitle gives the date twice, so the "2013-11-25" is a bit redundant
2. the en subtitle is not the same as the cs one, worse, it is not unique in the corpus (and, in fact, never was).

what about:
```
<title type="sub" xml:lang="cs">Parlament České republiky, Poslanecká sněmovna; Začátek schůze Poslanecké sněmovny 25. listopadu 2013 ve 14.05 hodin Přítomno: 199 poslanců</title>
<title type="sub" xml:lang="en">Parliament of the Czech Republic, Chamber of Deputies, 2013-11-25</title>
```

The en title will still not be unique, but at least uniquer...

**Comment by matyaskopp** [comment]
a redundant date is only at the beginning of sitting - so it does not irritate me.

If we really want a unique id we can use a value from the main title: `2013-11-25 ps2013-001-01-001-001`
commonly with the date, so the result would be:
```
<title type="sub" xml:lang="cs">Parlament České republiky, Poslanecká sněmovna, 2013-11-25 ps2013-001-01-001-001; Začátek schůze Poslanecké sněmovny 25. listopadu 2013 ve 14.05 hodin Přítomno: 199 poslanců</title>
<title type="sub" xml:lang="en">Parliament of the Czech Republic, Chamber of Deputies, 2013-11-25 ps2013-001-01-001-001</title>
```
I know that it is a bit cryptic, but it contains a piece of full structured information: 

- Czech parliament
- chamber
- date
- term beginning
- meeting number
- sitting number
- topic counter
- agenda item number
- agenda item title (for cs version)

I know that it is quite complicated, but it will allow following a single topic during legislative procedure.

**Comment by TomazErjavec** [comment]
> a redundant date is only at the beginning of sitting - so it does not irritate me.

OK, fair enough.

> I know that it is quite complicated

Yes, it is! I don't think anybody would really understand it, and, also, it would be a bit too much dangerous work fixing it right now, when the script is running for the other languages. 
But, as my program died on CZ anyway (it turns out you sometimes have 3 subheadings!) I took the opportunity to add the date to the English subtitle.

So, a title now looks like this:
```
<titleStmt>
   <title type="main" xml:lang="cs">Český parlamentní korpus ParlaMint-CZ, 2013-11-25 ps2013-001-01-000-000 [ParlaMint.ana]</title>
   <title type="main" xml:lang="en">Czech parliamentary corpus ParlaMint-CZ, 2013-11-25 ps2013-001-01-000-000 [ParlaMint.ana]</title>
   <title type="sub" xml:lang="cs">Parlament České republiky, Poslanecká sněmovna, 2013-11-25, Začátek schůze Poslanecké sněmovny 25. listopadu 2013 ve 14.05 hodin Přítomno: 199 poslanců</title>
   <title type="sub" xml:lang="en">Parliament of the Czech Republic, Chamber of Deputies, 2013-11-25</title>
```

I don't dare fiddle anymore now, so you can either close this or set it for the "next" milestone.

**Comment by matyaskopp** [comment]
ok, I am closing it. I will solve it in our ParCzech project. The next ParlaMint-CZ release will be derived from ParCzech - so if our project will be correct ParlaMint wouldn't inherit its mess...
