### ISSUE TITLE
BG: missing respStmt/persName

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#89]
Missing `persName`:
https://github.com/clarin-eric/ParlaMint/blob/61308e517e857bf65d806fe3aa091cd82c7f6302/ParlaMint.ana.xml#L37-L39

Name from `ParlaMint-BG.ana.xml` is filtered out because it has `xml:lang="bg"`
https://github.com/clarin-eric/ParlaMint/blob/61308e517e857bf65d806fe3aa091cd82c7f6302/ParlaMint-BG/ParlaMint-BG.ana.xml#L32-L35

**Comment by TomazErjavec** [comment]
Thanks, fixed in 5bf8471b.
