### ISSUE TITLE
DK,IT: Strange bibliography item

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#90]
This `<bibl>` item has been probably propagated from the very first samples of ParlaMint 1.0:

https://github.com/clarin-eric/ParlaMint/blob/61308e517e857bf65d806fe3aa091cd82c7f6302/ParlaMint-DK/ParlaMint-DK.ana.xml#L79-L82

**Comment by matyaskopp** [comment]
another one:
https://github.com/clarin-eric/ParlaMint/blob/61308e517e857bf65d806fe3aa091cd82c7f6302/ParlaMint.ana.xml#L316-L320

It makes sense to refer from annotated version to the raw TEI version but this handler points to self

**Comment by TomazErjavec** [comment]
Thanks, fixed in 5bf8471b.
