### ISSUE TITLE
Fix guidelines for new corpora

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#92]
Use proper date for splitting to `covid` and `reference` subcorpora. It would avoid overlapping interval confusion:
![image](https://user-images.githubusercontent.com/5867995/121818386-2e0a2480-cc87-11eb-94d2-a9f774ca037b.png)

The splitting date is 1st November:

- everything after this date(including) is `covid`

- everything before this date(excluding) is `reference`

**Comment by TomazErjavec** [comment]
The subcorpora are now changed anyway, so am closing this issue.
