### ISSUE TITLE
HU error in language definitions

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#95]
Each corpus should have the definition of languages it uses in the teiHeader//langUsage both in their langage and in English, but HU doesn't, it also mis-labels the name "Hungarian" as being written in Hungarian:
```
         <langUsage>
            <language ident="en" xml:lang="en">English</language>
            <language ident="hu" xml:lang="hu">Hungarian</language>
         </langUsage>
```

**Comment by matyaskopp** [comment]
now fixed
