### ISSUE TITLE
TR bug in setting dates

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#99]
The settingDesc/setting/desc should have a date with from and to attributes whose values denote the start and end dates that the transcriptions in the corpus cover. TR, however, does not have the correct dates `<date from="2009-04-01" to="2021-02-11"/>` but has some strange ones:
```
            <setting>
               <name type="city">Ankara</name>
               <name type="country" key="TR">Turkey</name>
               <date from="1996-11-28" to="2000-10-27"/>
            </setting>
```

**Comment by coltekin** [comment]
I fixed this in my scripts to set it to the correct range. It will be correct in the next release.

**Comment by matyaskopp** [comment]
ok, keeping it open.
@coltekin,  please close the issue when new samples are uploaded to GitHub.

**Comment by TomazErjavec** [comment]
@coltekin, as you are working on your corpus, is this fixed? If yes, pls. close.

**Comment by coltekin** [comment]
This issue can also be closed (it seems I am not allowed to close the issues).
